### ISSUE TITLE
avocado removes whole context of /tmp directory when running first time on machine

### ISSUE THREAD

**Issue by jscotka** [avocado-framework/avocado#1023]
Hi,
I've found, that if I run avocado test for fist time with parametr --avocado-log-dir /some/path/somewhere
probably causes something like:
rm -rf /tmp/*
for second time it does not cause that, because probably there is created some dir structure.
I'm not able to pinpoint exactly whats wrong.
It is doing when you are running avocado run on some machine for fist time and causes very bad things.

avocado-0.29.0-2.el7.centos.noarch

**Comment by jscotka** [comment]
I forgot to mention, that I'm running avocado under root user, thats why it is very harmful

**Comment by clebergnu** [comment]
@jscotka I'll try to reproduce it

**Comment by clebergnu** [comment]
I was not able to reproduce this.  The closer I could get to it is the cleanups we have on the Makefile targets.

**Comment by jscotka** [comment]
Hi,
I've did not met it for long time and also I did not met it with easy reproducer. I'll close this issue until I'll met it again
