### ISSUE TITLE
Avocado crashed unexpectedly: 'module' object has no attribute 'term_support'

### ISSUE THREAD

**Issue by sathnaga** [avocado-framework/avocado#1093]
# avocado list --vt-type libvirt --vt-list-guests
Searched /usr/share/avocado/data/avocado-vt/images for guest images

Available guests in config:

Avocado crashed unexpectedly: 'module' object has no attribute 'term_support'
You can find details in /var/tmp/avocado-traceback-2016-03-25_20:30:49-p2TbDH.log

Found the fix, will send a PR soon

**Comment by ldoktor** [comment]
Hello Satheesh, in deed I forgot to change this one. The `term_support` was renamed to `TERM_SUPPORT` to match pep8 recommendations. Let me send a fix for that, for not please use `avocado run --dry-run` instead.
