### ISSUE TITLE
libvirt bootstrap problem (at least on ppc64le)

### ISSUE THREAD

**Issue by svirt** [avocado-framework/avocado#1137]
Hello,

seems there is an an issue with bootstrapping Avocado in libvirt mode on ppc64le, I tried both local Avocado installation and systemwide one. I guess I did everything like before for the case when it was working. I use the upstream Avocado/Avocado-vt from git.

The command for bootstrapping **(local)**/systemwide Avocado is

**(./scripts/)**avocado vt-bootstrap --vt-guest-os RHEL.7.devel --vt-no-downloads --yes-to-all --vt-selinux-setup --vt-update-config --vt-update-providers --vt-type libvirt

The plugins output is:
```
Plugins that add new commands (avocado.plugins.cli.cmd):
exec-path    Returns path to avocado bash libraries and exits.
run          Run one or more tests (native test, test alias, binary or script)
sysinfo      Collect system information
list         List available tests
multiplex    Generate a list of dictionaries with params from a multiplex file
plugins      Displays plugin information
config       Shows avocado config keys
distro       Shows detected Linux distribution
**vt-bootstrap Avocado VT - implements the 'vt-bootstrap' subcommand**
Plugins that add new options to commands (avocado.plugins.cli):
remote  Remote machine options for 'run' subcommand
journal Journal options for the 'run' subcommand
json    JSON output options for 'run' command
html    HTML job report options for 'run' subcommand
wrapper Implements the '--wrapper' flag for the 'run' subcommand
vm      Virtual Machine options for 'run' subcommand
gdb     GDB options for the 'run' subcommand
replay  Replay options for 'run' subcommand
xunit   xUnit output options
**vt-list Avocado-VT/virt-test support for 'list' command**
**vt      Avocado VT/virt-test support to 'run' command** 
```

The output for test list command   **(./scripts/)**avocado list --vt-type libvirt --verbose is
```
ACCESS_DENIED: 0
BROKEN_SYMLINK: 0
EXTERNAL: 0
FILTERED: 0
INSTRUMENTED: 53
MISSING: 0
NOT_A_TEST: 25
SIMPLE: 0
VT: 0
```

The similar result is when I try to install/list qemu tests...

**Comment by ldoktor** [comment]
OK, so the problem is really minor. When `avocado list` is used without the `--vt-guest-os`, it uses default, which is `JeOS`. But there is no `pseries` variant of `JeOS`, so it correctly reports empty set.

Please use `--vt-guest-os xxx` (eg`avocado list --vt-guest-os RHEL.7.devel`) to see the supported tests for this os.

**Comment by svirt** [comment]
It works now Thanks! I will close the issue
