### ISSUE TITLE
Multiplexing Variants when using more than yaml file

### ISSUE THREAD

**Issue by narasimhan-v** [avocado-framework/avocado#1155]
Hi,

I tried to run 2 tests, each having its own multiplexing (.yaml) file.
The way I did it was:

# avocado run sleeptenmin.py env_variables.sh --multiplex sleeptenmin.py.data/sleeptenmin.yaml env_variables.sh.data/env_variables.yaml

Is this a currently supported approach ?

If yes, I see the variants generated are not expected.
For this example, the first file should run with 8 variants, and second file with 3 variants.

But what happens when we run both together is, it runs for 9 variants, as shown below:

# avocado multiplex sleeptenmin.py.data/sleeptenmin.yaml
Variants generated:
Variant 1:    /run/sleeptenmin/builtin, /run/variants/one_cycle
Variant 2:    /run/sleeptenmin/builtin, /run/variants/six_cycles
Variant 3:    /run/sleeptenmin/builtin, /run/variants/one_hundred_cycles
Variant 4:    /run/sleeptenmin/builtin, /run/variants/six_hundred_cycles
Variant 5:    /run/sleeptenmin/shell, /run/variants/one_cycle
Variant 6:    /run/sleeptenmin/shell, /run/variants/six_cycles
Variant 7:    /run/sleeptenmin/shell, /run/variants/one_hundred_cycles
Variant 8:    /run/sleeptenmin/shell, /run/variants/six_hundred_cycles

# avocado multiplex env_variables.sh.data/env_variables.yaml 
Variants generated:
Variant 1:    /run/short
Variant 2:    /run/medium
Variant 3:    /run/long

# avocado multiplex sleeptenmin.py.data/sleeptenmin.yaml env_variables.sh.data/env_variables.yaml Variants generated:
Variant 1:    /run/sleeptenmin/builtin
Variant 2:    /run/sleeptenmin/shell
Variant 3:    /run/variants/one_cycle
Variant 4:    /run/variants/six_cycles
Variant 5:    /run/variants/one_hundred_cycles
Variant 6:    /run/variants/six_hundred_cycles
Variant 7:    /run/short
Variant 8:    /run/medium
Variant 9:    /run/long

**Comment by ldoktor** [comment]
Dear @narasimhan-v,

assignment tests to multiplex files is currently not supported. You can specify multiple files, but they will be combined together to create one big tree, which would yield all the possible combinations of the each multiplexed section. Let me demonstrate it using `avocado multiplex --tree` commands

```
avocado multiplex -t examples/tests/sleeptenmin.py.data/sleeptenmin.yaml 
 ┗━━ run
      ┣━━ sleeptenmin
      ┃    ╠══ builtin
      ┃    ╚══ shell
      ┗━━ variants
           ╠══ one_cycle
           ╠══ six_cycles
           ╠══ one_hundred_cycles
           ╚══ six_hundred_cycles
```
`+`
```
avocado multiplex -t examples/tests/env_variables.sh.data/env_variables.yaml 
 ┗━━ run
      ╠══ short
      ╠══ medium
      ╚══ long

```
`=`
```
avocado multiplex -t examples/tests/sleeptenmin.py.data/sleeptenmin.yaml examples/tests/env_variables.sh.data/env_variables.yaml
 ┗━━ run
      ╠══ sleeptenmin
      ║    ╠══ builtin
      ║    ╚══ shell
      ╠══ variants
      ║    ╠══ one_cycle
      ║    ╠══ six_cycles
      ║    ╠══ one_hundred_cycles
      ║    ╚══ six_hundred_cycles
      ╠══ short
      ╠══ medium
      ╚══ long
```
where the double lines `═` signals that the variant will be multiplexed (therefor it yields one sibling at a time)

Assigning multiplex files to specific tests is still under discussion, one way could be the `Job API RFC`: https://www.redhat.com/archives/avocado-devel/2016-April/msg00014.html but that is in an early stage right now so the only option currently available is to break your setup into multiple `avocado run` executions.

Additionally we'd gladly welcome any real-world use case, should you have one, either in the `Job API RFC` or as a separate thread on avocado-devel@redhat.com.

**Comment by ldoktor** [comment]
Actually let me explain the variants a bit. The problem is that the `env_variables` tags the `/run` as `!mux`, which means yield only one sibling at a time. The `--multiplex` optionally supports adding prefix to each file by `$prefix:$file` (prefix is an absolute or relative path which will be prefixed to the resulting tree). By separating the two files into a different path, you probably get the expected result:

```
avocado multiplex --tree sleep:examples/tests/sleeptenmin.py.data/sleeptenmin.yaml env_variables:examples/tests/env_variables.sh.data/env_variables.yaml
 ┗━━ run
      ┣━━ sleep
      ┃    ┣━━ sleeptenmin
      ┃    ┃    ╠══ builtin
      ┃    ┃    ╚══ shell
      ┃    ┗━━ variants
      ┃         ╠══ one_cycle
      ┃         ╠══ six_cycles
      ┃         ╠══ one_hundred_cycles
      ┃         ╚══ six_hundred_cycles
      ┗━━ env_variables
           ╠══ short
           ╠══ medium
           ╚══ long
```
Where the `═` signals `!mux` relation and `━` non-`!mux` relation. The difference is, that `non-!mux` relation joins the results, yielding one of each siblings, while `!mux` relation yields only one of the siblings:
```
avocado multiplex sleep:examples/tests/sleeptenmin.py.data/sleeptenmin.yaml env_variables:examples/tests/env_variables.sh.data/env_variables.yaml
Variants generated:
Variant 1:    /run/sleep/sleeptenmin/builtin, /run/sleep/variants/one_cycle, /run/env_variables/short
Variant 2:    /run/sleep/sleeptenmin/builtin, /run/sleep/variants/one_cycle, /run/env_variables/medium
Variant 3:    /run/sleep/sleeptenmin/builtin, /run/sleep/variants/one_cycle, /run/env_variables/long
Variant 4:    /run/sleep/sleeptenmin/builtin, /run/sleep/variants/six_cycles, /run/env_variables/short
Variant 5:    /run/sleep/sleeptenmin/builtin, /run/sleep/variants/six_cycles, /run/env_variables/medium
Variant 6:    /run/sleep/sleeptenmin/builtin, /run/sleep/variants/six_cycles, /run/env_variables/long
Variant 7:    /run/sleep/sleeptenmin/builtin, /run/sleep/variants/one_hundred_cycles, /run/env_variables/short
Variant 8:    /run/sleep/sleeptenmin/builtin, /run/sleep/variants/one_hundred_cycles, /run/env_variables/medium
Variant 9:    /run/sleep/sleeptenmin/builtin, /run/sleep/variants/one_hundred_cycles, /run/env_variables/long
Variant 10:    /run/sleep/sleeptenmin/builtin, /run/sleep/variants/six_hundred_cycles, /run/env_variables/short
Variant 11:    /run/sleep/sleeptenmin/builtin, /run/sleep/variants/six_hundred_cycles, /run/env_variables/medium
Variant 12:    /run/sleep/sleeptenmin/builtin, /run/sleep/variants/six_hundred_cycles, /run/env_variables/long
Variant 13:    /run/sleep/sleeptenmin/shell, /run/sleep/variants/one_cycle, /run/env_variables/short
Variant 14:    /run/sleep/sleeptenmin/shell, /run/sleep/variants/one_cycle, /run/env_variables/medium
Variant 15:    /run/sleep/sleeptenmin/shell, /run/sleep/variants/one_cycle, /run/env_variables/long
Variant 16:    /run/sleep/sleeptenmin/shell, /run/sleep/variants/six_cycles, /run/env_variables/short
Variant 17:    /run/sleep/sleeptenmin/shell, /run/sleep/variants/six_cycles, /run/env_variables/medium
Variant 18:    /run/sleep/sleeptenmin/shell, /run/sleep/variants/six_cycles, /run/env_variables/long
Variant 19:    /run/sleep/sleeptenmin/shell, /run/sleep/variants/one_hundred_cycles, /run/env_variables/short
Variant 20:    /run/sleep/sleeptenmin/shell, /run/sleep/variants/one_hundred_cycles, /run/env_variables/medium
Variant 21:    /run/sleep/sleeptenmin/shell, /run/sleep/variants/one_hundred_cycles, /run/env_variables/long
Variant 22:    /run/sleep/sleeptenmin/shell, /run/sleep/variants/six_hundred_cycles, /run/env_variables/short
Variant 23:    /run/sleep/sleeptenmin/shell, /run/sleep/variants/six_hundred_cycles, /run/env_variables/medium
Variant 24:    /run/sleep/sleeptenmin/shell, /run/sleep/variants/six_hundred_cycles, /run/env_variables/long
```
You can find other example in documentation: http://avocado-framework.readthedocs.org/en/latest/MultiplexConfig.html

**Comment by narasimhan-v** [comment]
Thanks @ldoktor for the `$prefix:$file` explanation.
And yes, we can still do it with multiple runs, and no real use case for having all such cases in a single run :)

**Comment by ldoktor** [comment]
I'm glad I could help. We do have use cases for the above, there are just more pressing matters to do first.
