### ISSUE TITLE
Invalid multiplex file

### ISSUE THREAD

**Issue by kanssty** [avocado-framework/avocado#1190]
Dear,

I just followed the avocado guide to learn and try use a multiplex file.
http://avocado-framework.readthedocs.io/en/latest/WritingTests.html

But I found it not workable as example on guild book.
Is my installation problem or need to config something? These example file was provide by default, but can not be workable?

This is my execution result.

[root@zs95kv2 avocado]# avocado run examples/tests/sleeptest.py
JOB ID     : f0973076b06dde31cf7921a8bc1d58ae0b68118c
JOB LOG    : /root/avocado/job-results/job-2016-05-04T23.46-f097307/job.log
TESTS      : 1
 (1/1) examples/tests/sleeptest.py:SleepTest.test: PASS
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0
JOB HTML   : /root/avocado/job-results/job-2016-05-04T23.46-f097307/html/results.html
TIME       : 1.00 s
[root@zs95kv2 avocado]# avocado run examples/tests/sleeptest.py --multiplex examples/tests/sleeptest.py.data/sleeptest.yaml

[Errno 2] Invalid multiplex file 'examples/tests/sleeptest.py.data/sleeptest.yaml': unacceptable character #x0000: control characters are not allowed
  in "examples/tests/sleeptest.py.data/sleeptest.yaml", position 118: 'examples/tests/sleeptest.py.data/sleeptest.yaml'
[root@zs95kv2 avocado]# avocado multiplex -t examples/tests/sleeptest.py.data/sleeptest.yaml
Invalid multiplex file 'examples/tests/sleeptest.py.data/sleeptest.yaml': unacceptable character #x0000: control characters are not allowed
  in "examples/tests/sleeptest.py.data/sleeptest.yaml", position 118
[root@zs95kv2 avocado]# cat examples/tests/sleeptest.py.data/sleeptest.yaml
!mux
short:
    sleep_length: 0.5
medium:
    sleep_length: 1
long:
    sleep_length: 5
longest:
    sleep_length: 10
[root@zs95kv2 avocado]#

**Comment by kanssty** [comment]
position 118 is the last character on yaml file,  I am sure there is no invisible symbol in it.

[root@zs95kv2 avocado]# cat -vet examples/tests/sleeptest.py.data/sleeptest.yaml
!mux$
short:$
    sleep_length: 0.5$
medium:$
    sleep_length: 1$
long:$
    sleep_length: 5$
longest:$
    sleep_length: 10$

**Comment by clebergnu** [comment]
I tried, but could not reproduce:

```
$ ./scripts/avocado run examples/tests/sleeptest.py --multiplex examples/tests/sleeptest.py.data/sleeptest.yaml
JOB ID     : 3ac0a4eaa924e2bee4440d25e977ec089176cdce
JOB LOG    : /home/cleber/avocado/job-results/job-2016-05-05T23.21-3ac0a4e/job.log
TESTS      : 4
 (1/4) examples/tests/sleeptest.py:SleepTest.test;1: PASS
 (2/4) examples/tests/sleeptest.py:SleepTest.test;2: PASS
 (3/4) examples/tests/sleeptest.py:SleepTest.test;3: PASS
 (4/4) examples/tests/sleeptest.py:SleepTest.test;4: PASS
RESULTS    : PASS 4 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0
JOB HTML   : /home/cleber/avocado/job-results/job-2016-05-05T23.21-3ac0a4e/html/results.html
TIME       : 16.52 s
```

Can you check that we have the same file with:

```
$ sha1sum examples/tests/sleeptest.py.data/sleeptest.yamlfdeb7bcedc79228d9179842cd0dfa669a4fd4e83  examples/tests/sleeptest.py.data/sleeptest.yaml
```

And can you also check your current locale settings?

```
$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

This should, I hope, give us some hints.

**Comment by kanssty** [comment]
Thanks for your information. It looks very strange. The setting is same as yours but not workable.

[root@zs95kv2 avocado]# sha1sum examples/tests/sleeptest.py.data/sleeptest.yaml
fdeb7bcedc79228d9179842cd0dfa669a4fd4e83  examples/tests/sleeptest.py.data/sleeptest.yaml
[root@zs95kv2 avocado]# locale
LANG=en_US.utf8
LC_CTYPE="en_US.utf8"
LC_NUMERIC="en_US.utf8"
LC_TIME="en_US.utf8"
LC_COLLATE="en_US.utf8"
LC_MONETARY="en_US.utf8"
LC_MESSAGES="en_US.utf8"
LC_PAPER="en_US.utf8"
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=
[root@zs95kv2 avocado]#

Maybe, it's a problem of libyaml?

**Comment by clebergnu** [comment]
Could be. @ldoktor does this ring any bell?

**Comment by kanssty** [comment]
I did a little test about yaml load function. 

Created a normal python scripts.
`
[root@zs95kv2 avocado]# cat test.py
import yaml
f = open('test.yaml')
x = yaml.load(f)
print x
f.close()
`
And remove the  tag  of '!mux' from yaml file

`
[root@zs95kv2 avocado]# cat test.yaml
short:
    sleep_length: 0.5
medium:
    sleep_length: 1
long:
    sleep_length: 5
longest:
    sleep_length: 10
[root@zs95kv2 avocado]#
`
The result it, normal python yaml.load is workable, but avocado multiplex -t still can not read file.

`
[root@zs95kv2 avocado]# python test.py
{'medium': {'sleep_length': 1}, 'longest': {'sleep_length': 10}, 'long': {'sleep_length': 5}, 'short': {'sleep_length': 0.5}}
[root@zs95kv2 avocado]#
[root@zs95kv2 avocado]# avocado multiplex -t test.yaml
Invalid multiplex file 'test.yaml': unacceptable character #x0000: control characters are not allowed
  in "test.yaml", position 113
`

**Comment by kanssty** [comment]
I did a little test for libyaml and python function.

Created a basic yaml load function.

[root@zs95kv2 avocado]# cat test.py
import yaml
f = open('test.yaml')
x = yaml.load(f)
print x
f.close()

Because of this error, I remove the tag of '!mux'  from the test.yaml
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!mux'

[root@zs95kv2 avocado]# cat test.yaml
short:
    sleep_length: 0.5
medium:
    sleep_length: 1
long:
    sleep_length: 5
longest:
    sleep_length: 10

The result is that, basic python function is work, but avocado multiplex -t still run into this problem.

[root@zs95kv2 avocado]# python test.py
{'medium': {'sleep_length': 1}, 'longest': {'sleep_length': 10}, 'long': {'sleep_length': 5}, 'short': {'sleep_length': 0.5}}
[root@zs95kv2 avocado]#

[root@zs95kv2 avocado]# avocado multiplex -t test.yaml
Invalid multiplex file 'test.yaml': unacceptable character #x0000: control characters are not allowed
  in "test.yaml", position 113
[root@zs95kv2 avocado]#

**Comment by kanssty** [comment]
Is there any way to debug it or trace the python code?

**Comment by ldoktor** [comment]
Hello @kanssty this looks like https://www.redhat.com/archives/avocado-devel/2015-November/msg00009.html issue. Might I ask about the platform and python version? It looks like the bug in CYaml.

(There are few recommendations how to disable CYaml to workaround this issue)

**Comment by kanssty** [comment]
I did not use official Linux and libyaml, I am testing zKVM (KVM on IBM Z mainframe version). 
But this environment is very like as Fedora, we want to enable avocado on our test environment.

[root@zs95kv2 ~]# uname -a
Linux zs95kv2 3.10.0-229.7.2.el7_1.kvmibm1_1_1.20.s390x #1 SMP Thu Mar 31 19:19:09 EDT 2016 s390x s390x s390x GNU/Linux
[root@zs95kv2 ~]#

[root@zs95kv2 ~]# python -V
Python 2.7.5
[root@zs95kv2 ~]#

root@zs95kv2 ~]# yum list installed | grep yaml
libyaml.s390x                    0.1.4-11.el7_1.ibm.1                 @frobisher
libyaml-devel.s390x              0.1.4-11.el7_1.ibm.1                 @sdk
[root@zs95kv2 ~]#

**Comment by ldoktor** [comment]
Well that's most probably the CYaml problem as Olav used

```
$ uname -a
Linux ultraseven 3.10.82-2042.1.pkvm2_1_1.71.ppc64 #1 SMP Fri Jul 31 09:52:38 CDT 2015 ppc64 ppc64 ppc64 GNU/Linux
$ rpm -q python
python-2.7.5-15.1.pkvm2_1_1.1.ppc64
```

Could you please try removing/renaming the `/usr/lib64/python2.7/site-packages/yaml/cyaml.py*` file?

If you don't want to mess with your system, you can also modify avocado: 

```diff
diff --git a/avocado/core/tree.py b/avocado/core/tree.py
index c39ea07..0f689bc 100644
--- a/avocado/core/tree.py
+++ b/avocado/core/tree.py
@@ -45,10 +45,7 @@ except ImportError:
     MULTIPLEX_CAPABLE = False
 else:
     MULTIPLEX_CAPABLE = True
-    try:
-        from yaml import CLoader as Loader
-    except ImportError:
-        from yaml import Loader
+    from yaml import Loader
 
 from . import output
```

This seems to be quite frequent, perhaps we should add a settings to disable CYaml.

**Comment by kanssty** [comment]
I tried to modify the avocado, but got the same result. Did I make some mistake?

1) edited /avocado/avocado/avocado/core/tree.py
try:
    import yaml
except ImportError:
    MULTIPLEX_CAPABLE = False
else:
    MULTIPLEX_CAPABLE = True
    from yaml import Loader

from . import output

2) Diff result.
[root@zs95kv2 core]# diff  /avocado/avocado/avocado/core/tree.py /root/tree.py
48c48,51
<     from yaml import Loader
---
>     try:
>         from yaml import CLoader as Loader
>     except ImportError:
>         from yaml import Loader
[root@zs95kv2 core]#

3) Remove tree.pyc
-rw-r--r--. 1 root root 26816 May  9 01:27 tree.py
[root@zs95kv2 core]#


[root@zs95kv2 avocado]# avocado multiplex -t test.yaml
Invalid multiplex file 'test.yaml': unacceptable character #x0000: control characters are not allowed
  in "test.yaml", position 113
[root@zs95kv2 avocado]#

And I tried to 2nd workaroud about remove cyaml.py*, it works fine.
But as you said, I don't really want to mess my environment here.

**Comment by ldoktor** [comment]
This is weird, can you add a `logging.getLogger("avocado.app").error("Importing Loader, not CLoader")` message to your modified tree to see whether it's really being used? Because the fix above should work without the need for removing the `cyaml` files.

**Comment by kanssty** [comment]
Added 2 area for debug.

import collections
import itertools
import locale
import os
import re

logging.getLogger("avocado.app").error("Importing Loader, not CLoader")

try:
    import yaml
    logging.getLogger("avocado.app").error("Importing Loader, not CLoader")
except ImportError:
    MULTIPLEX_CAPABLE = False
else:
    MULTIPLEX_CAPABLE = True
    from yaml import Loader

Same result.

[root@zs95kv2 avocado]# avocado multiplex -t test.yaml
Invalid multiplex file 'test.yaml': unacceptable character #x0000: control characters are not allowed
  in "test.yaml", position 113
[root@zs95kv2 avocado]#

Seem like not been execute this script.


Yes, previously we have 2 allcation which have avocado source.
I installed avocado again on / (root) dir, and rename the old one to avocado_bk.

And I deleted tree.py on old folder as below.

[root@zs95kv2 core]# pwd;ll tree*
/avocado/avocado/avocado/core
-rw-r--r--. 1 root root 26965 May  9 22:28 tree.py
[root@zs95kv2 core]#

[root@zs95kv2 core]# pwd; ll tre*
/root/avocado/env2/avocado_bk/avocado/core
ls: cannot access tre*: No such file or directory
[root@zs95kv2 core]#

Any idea about how can we specific which python source had been executed?

**Comment by kanssty** [comment]
There is an other little question, how can I uninstall avocado of source base from Linux like environment. I can't find any uninstallation information on avocado guide.

**Comment by ldoktor** [comment]
Well it looks like the non-modified one is used. Let's move the discussion regarding uninstall here: https://github.com/avocado-framework/avocado/issues/1197 and with a clean environment we can resume this problem.

**Comment by kanssty** [comment]
I removed all of avocado and reinstalled a new avocado again. And then I modify tree.py again, got the same result. I found there is not new pyc file was created again, so I think it should not be used.

[root@zs95kv2 core]# ll tree*
-rw-r--r--. 1 root root 26889 May 10 20:34 tree.py
[root@zs95kv2 core]#

Is there some pyc in others dir or something need to be deleted or clean up? No pyc file means tree.py was been compiled?
Oh... After I modified python source, should I recompile avocado? which is the command for this?

**Comment by ldoktor** [comment]
This is odd, there are probably some left-overs. Python should produce the `pyc` files on each invocation, so that means it uses a different folder.

Can you please describe the steps? Mine would be:

1. remove previous avocado (most importantly from /usr/lib)
2. clone avocado; cd avocado
3. modify the `avocado/core/tree.py`
4. run `make link`
5. run `./scripts/avocado run passtest.py -m examples/tests/sleeptest.py.data/sleeptest.yaml`

or alternatively:

1. remove previous avocado (most importantly from /usr/lib)
2. clone avocado; cd avocado
3. modify the `avocado/core/tree.py`
4. run `sudo make install`
5. run `avocado run passtest.py -m examples/tests/sleeptest.py.data/sleeptest.yaml`

If none of this helps, try the first approach but in step 5 try running `PYTHONPATH=".:$PYTHONPATH" ./scripts/avocado run passtest.py -m examples/tests/sleeptest.py.data/sleeptest.yaml`, which forces python to first try looking for libraries in the current directory.

**Comment by kanssty** [comment]
Thank you very much! Done, we can close this issue.
