### ISSUE TITLE
After avocado-vt installation, avocado bacome not workable.

### ISSUE THREAD

**Issue by kanssty** [avocado-framework/avocado#1202]
I opened an issue on avocado-vt  and copied it to here.
Hi,
Followed the guide of
http://avocado-framework.readthedocs.io/en/latest/ContributionGuide.html#hacking-and-using-avocado
I have installed avocado-vt on source base avocado as below.
Are there any conflict with avocado-vt

[root@zs95kv2 avocado]# cd /avocado/
[root@zs95kv2 avocado]# git clone https://github.com/avocado-framework/avocado-vt.git
Cloning into 'avocado-vt'...
remote: Counting objects: 38364, done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 38364 (delta 9), reused 0 (delta 0), pack-reused 38337
Receiving objects: 100% (38364/38364), 18.89 MiB | 7.02 MiB/s, done.
Resolving deltas: 100% (27198/27198), done.
[root@zs95kv2 avocado]# ll
total 12
drwxr-xr-x. 15 root root 4096 May 10 20:21 avocado
drwxr-xr-x. 14 root root 4096 May 10 20:57 avocado-vt
-rw-r--r--. 1 root root 118 May 10 20:32 sleeptest.yaml
[root@zs95kv2 avocado]# cd avocado
[root@zs95kv2 avocado]# avocado -v
Avocado 35.0
[root@zs95kv2 avocado]#

[root@zs95kv2 avocado]# make link
/usr/bin/python setup.py develop --user
running develop
running egg_info
writing avocado.egg-info/PKG-INFO
writing top-level names to avocado.egg-info/top_level.txt
writing dependency_links to avocado.egg-info/dependency_links.txt
writing entry points to avocado.egg-info/entry_points.txt
reading manifest file 'avocado.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'avocado.egg-info/SOURCES.txt'
running build_ext
Creating /root/.local/lib/python2.7/site-packages/avocado.egg-link (link to .)
Adding avocado 35.0 to easy-install.pth file
Installing avocado script to /root/.local/bin
Installing avocado-rest-client script to /root/.local/bin

Installed /avocado/avocado
Processing dependencies for avocado==35.0
Finished processing dependencies for avocado==35.0
for MAKEFILE in ../sleeptest.yaml ../avocado-vt;\
do AVOCADO_DIRNAME=avocado make -C $MAKEFILE link &>/dev/null && echo ">> LINK $MAKEFILE" || echo ">> SKIP $MAKEFILE";\
done

        SKIP ../sleeptest.yaml
        LINK ../avocado-vt
        [root@zs95kv2 avocado]#

But after installation. Avocado became not workable as below.

[root@zs95kv2 avocado]# avocado
Traceback (most recent call last):
File "/usr/bin/avocado", line 5, in
pkg_resources.run_script('avocado==35.0', 'avocado')
File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
self.require(requires)[0].run_script(script_name, ns)
File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1449, in run_script
raise ResolutionError("No script named %r" % script_name)
pkg_resources.ResolutionError: No script named 'avocado'
[root@zs95kv2 avocado]#

Why command of avocado became not workable.

**Comment by kanssty** [comment]
I have successfully installed avocado-vt and command of avocado became not workable.
Need to specify full path to execute.

[root@zs95kv2 avocado]# avocado
Traceback (most recent call last):
  File "/usr/bin/avocado", line 5, in <module>
    pkg_resources.run_script('avocado==35.0', 'avocado')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1449, in run_script
    raise ResolutionError("No script named %r" % script_name)
pkg_resources.ResolutionError: No script named 'avocado'
[root@zs95kv2 avocado]#
[root@zs95kv2 avocado]#
[root@zs95kv2 avocado]# ./scripts/avocado
usage: avocado [-h] [-v] [--config [CONFIG_FILE]] [--show [STREAM[:LVL]]] [-s]

               {exec-path,run,config,list,multiplex,plugins,sysinfo,distro,vt-bootstrap}
               ...

Avocado Test Runner

optional arguments:
  -h, --help            show this help message and exit
  -v, --version         show program's version number and exit
  --config [CONFIG_FILE]
                        Use custom configuration from a file
  --show [STREAM[:LVL]]
                        List of comma separated builtin logs, or logging
                        streams optionally followed by LEVEL (DEBUG,INFO,...).
                        Builtin streams are: "test": test output; "debug":
                        tracebacks and other debugging info; "app":
                        application output; "early": early logging of other
                        streams, including test (very verbose); "remote":
                        fabric/paramiko debug; "all": all builtin streams;
                        "none": disables regular output (leaving only errors
                        enabled). By default: 'app'
  -s, --silent          disables regular output (leaving only errors enabled)

subcommands:
  valid subcommands

  {exec-path,run,config,list,multiplex,plugins,sysinfo,distro,vt-bootstrap}
                        subcommand help
    exec-path           Returns path to avocado bash libraries and exits.
    run                 Run one or more tests (native test, test alias, binary
                        or script)
    config              Shows avocado config keys
    list                List available tests
    multiplex           Generate a list of dictionaries with params from a
                        multiplex file
    plugins             Displays plugin information
    sysinfo             Collect system information
    distro              Shows detected Linux distribution
    vt-bootstrap        Avocado VT - implements the 'vt-bootstrap' subcommand

avocado: error: too few arguments
[root@zs95kv2 avocado]#

**Comment by ldoktor** [comment]
Hello @kanssty, I guess this issue was resolved in https://github.com/avocado-framework/avocado-vt/issues/498 right?

**Comment by liwbj** [comment]
I hope so, but I have to specify the full path to run avocado command here.
I'm not sure why?

[root@zs95kv2 ~]# avocado
Traceback (most recent call last):
  File "/usr/bin/avocado", line 5, in <module>
    pkg_resources.run_script('avocado==35.0', 'avocado')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1449, in run_script
    raise ResolutionError("No script named %r" % script_name)
pkg_resources.ResolutionError: No script named 'avocado'
[root@zs95kv2 ~]#

**Comment by ldoktor** [comment]
I remember hitting this issue, basically python verifies you're using the correct version, but I don't remember the details. @clebergnu any ideas?

(basically I usually install avocado by `make install`, then I erase `/usr/lib/python2.7/site-packages/avocado*`, keeping just the `/etc/` and `/usr/bin/avocado*` files. Then I use `make link` in avocado directory, which takes care of the egg and symlinks and I don't have any problems with this)

**Comment by sathnaga** [comment]
deleting the ~/.local/bin and ~/.local/lib folders which created by make link and installing avocado again fixes this issue.

**Comment by ldoktor** [comment]
Great, thank you for the report.
