### ISSUE TITLE
RFC: Runner for avocado-misc-tests

### ISSUE THREAD

**Issue by sathnaga** [avocado-framework/avocado#1219]
How about having a config files which has details of list of testcases to run, point me if any such possibility is already available, This would be very much useful for running them in defined groups.

The same can be achieved through tagging the testcases, a single testcase can have 
multiple tags and referencing the tag will result in a group of testcases, **but** giving the defined multiplexer combination  or other filters for each testcase would be a probelm.

#avocado run --config sanity.cfg

#cat sanity.cfg 
#Make sure these are relative to avocado tests folder
#testcase path   --   yaml file if needed
cpu/ebizzy.py	cpu/ebizzy.py.data/ebizzy.yaml
io/disk/dbench.py
io/net/infiniband/dapl.sh

Expected output would be consolidated results of all three above scripts

**Comment by sathnaga** [comment]
@lmr @ldoktor @clebergnu @adereis @apahim Comments and suggestion please.

**Comment by clebergnu** [comment]
@sathnaga does this card:

https://trello.com/c/TILd7HIp/593-rfc-introduce-the-concept-of-test-suites-test-groups

Looks like something you may be thinking about?

**Comment by adereis** [comment]
On Tue, May 17, 2016 at 02:22:36AM -0700, Satheesh Rajendran wrote:
> @lmr @ldoktor @clebergnu @adereis @apahim Comments and suggestion please.
> 

With the exception of using --multiplex, which right now is not
supported on a per-test basis, what you describe can be
accomplished with bash:

$ avocado run $(cat tests.cfg | grep -v '^#')

-- 
Ademar Reis
Red Hat

^[:wq!

**Comment by sathnaga** [comment]
@clebergnu : Have gone through that card, basic idea matches and partly that addresses, I see it more for avocado-vt usecase. It might not address providing per test multiplex option or test specific filters.

@adereis That would be quick hack without multiplex option, the expectation is to have per test multiplex option and test specific filters if any.

**Comment by clebergnu** [comment]
@sathnaga other possibility would be to create a job and add your tests to it, either from the same Python code that creates the `Job`, or from a file.  We envision something like this being possible with the "Job API":

```python
  #!/usr/bin/env python
  from avocado import Job
  from avocado.resolver import resolve

  job = Job()
  tests = [resolve(line) for line in open('sanity.cfg').readlines()]
  job.run_tests(tests)
```

Please refer to http://www.redhat.com/archives/avocado-devel/2016-April/msg00014.html for the initial discussions about the Job API.

I'm closing this so we can discuss this in the context of Job API discussion on the mailing list.
