### ISSUE TITLE
docker Test to avocado 

### ISSUE THREAD

**Issue by PraveenPenguin** [avocado-framework/avocado#1269]
Hi 
  I want to port docker test to avocado as well try to add some new Test case , is this is possible can i add it in avocado-misc-tests git or we are going to use to other git .

Thanks

**Comment by ldoktor** [comment]
Are you talking about the https://github.com/autotest/autotest-docker ? If so than a new repo would IMO make sense.

**Comment by PraveenPenguin** [comment]
@ldoktor  yes i am talking something like same . ok ,  can you please create a git repo for same than will port test from autotest-docker  to newly created git .

Thanks
Praveen

**Comment by ldoktor** [comment]
Wow, you are taking quite a big task for yourself. Let's also notify @cevich as he might have some opinions about that.

From my side I'd like to know if you intend to simply keep it intact and only create a wrapper to execute it, or if you want to replace the `autotest` libraries and rework it as fully instrumented avocado test? (The later would be preferred, but it does not necessarily means you have to do it yourself, nor that it has to be perfect conversion at first. It'd be an iterative process and I think guys from autotest-docer would be able to help, right @cevich?)

**Comment by cevich** [comment]
Yes, I would highly encourage participating in https://github.com/autotest/autotest-docker and https://github.com/cevich/autotest-docker-enabled-product-testing.   I investigated using Avacado for testing Docker, however the dependency-cost is too high - it won't run natively on Atomic Host like regular, boring, old Autotest will.

The only sensible way to do (that I could find) is to run the Avacado tests on a "slave" or "controller" machine, and do all the actual testing remotely through ssh (which brings a huge number of problems an challenges along for the ride).   Whereas Docker Autotest is already written, working, actively maintained and being used for QA purposes.  Autotest itself is in 'maintenance' mode, so there's no fear of any API's changing and little risk of unknown bugs being found.

The ADEPT project (linked above) stands in place for an Autotest server, and allows Docker Autotest orchestration from Jenkins.  However, the **devel** branch I'm actively working on,  will be 100% cloud and tooling agnostic.  It has the right hooks to run on any cloud, including locally with just libvirt.  It uses (mostly) Ansible 2.1 for all the orchestration.  Currently only OpenStack clouds are supported but I want to expand that.

Both of these projects are being actively developed, specificity for our internal testing of RHEL/RHEL Atomic, CentOS, and Fedora plus Atomic variants.  We even have a public trello board where all the QE and Docker planning is happening:  https://trello.com/b/xMCopwZm/containers  Take a look, and you're welcome to join our small band in either or both github projects.  There's never any shortage of work to do :grinning:

**Comment by PraveenPenguin** [comment]
@ldoktor @cevich thanks
