### ISSUE TITLE
Can avocado  job log preserve log for every run?

### ISSUE THREAD

**Issue by nainav** [avocado-framework/avocado#1288]
Can avocado  job log preserve log for every run?

There is a use case : I want to preserve every log of my test run and am using avocado framework.How to do it .

**Comment by clebergnu** [comment]
Avocado already saves every job inside it's own directory.  In a regular system, you'll find multiple job result directories at the user's `~/avocado/job-results` directory.  Each one of them should have a `job.log` file.

**Comment by clebergnu** [comment]
@nainav I'm closing this issue, if you need further help, please let us know.

**Comment by nainav** [comment]
@clebergnu ,

Thanks for your quick response ,

I have tried this solution but , `~/avocado/job-results ` directory contains only the results of latest run in `job.log` and previous runs test-results were empty.

**Comment by clebergnu** [comment]
@nainav there's something really wrong with your setup.  Can you please run:

```sh
$ avocado config
$ avocado --version
```

And send us the result?

Just for a simple comparison, my job results directory has the result of the latest 853 jobs:

```sh
$ ls -1 ~/avocado/job-results/*/job.log | wc -l 
853
```

**Comment by nainav** [comment]
[naina@dhcp35-1 job-results]$  avocado config
Failed to load plugin from module "avocado.plugins.html": ImportError('No module named html',)
Config files read (in order):
    /etc/avocado/avocado.conf
    /etc/avocado/conf.d/gdb.conf
    /home/naina/.config/avocado/avocado.conf

    Section.Key                             Value
    datadir.paths.base_dir                  /home/naina/PycharmProjects/abcdk
    datadir.paths.test_dir                  /home/naina/PycharmProjects/abcdk/tests
    datadir.paths.data_dir                  /home/naina/PycharmProjects/abcdk/libraries
    datadir.paths.logs_dir                  ~/avocado/job-results
    sysinfo.collect.enabled                 True
    sysinfo.collect.installed_packages      False
    sysinfo.collect.profiler                False
    sysinfo.collectibles.commands           /etc/avocado/sysinfo/commands
    sysinfo.collectibles.files              /etc/avocado/sysinfo/files
    sysinfo.collectibles.profilers          /etc/avocado/sysinfo/profilers
    runner.output.colored                   True
    runner.output.utf8                      
    runner.behavior.keep_tmp_files          False
    remoter.behavior.reject_unknown_hosts   False
    remoter.behavior.disable_known_hosts    False
    job.output.loglevel                     debug
    restclient.connection.hostname          localhost
    restclient.connection.port              9405
    restclient.connection.username          
    restclient.connection.password          
    plugins.skip_broken_plugin_notification []
    plugins.loaders                         ['file', '@DEFAULT']
    gdb.paths.gdb                           /usr/bin/gdb
    gdb.paths.gdbserver                     /usr/bin/gdbserver
[naina@dhcp35-1 job-results]$ avocado --version
Avocado 35.0
Failed to load plugin from module "avocado.plugins.html": ImportError('No module named html',)
[naina@dhcp35-1 job-results]$ ls -1 ~/avocado/job-results/*/job.log | wc -l 
186

**Comment by clebergnu** [comment]
@nainav there you go, you have 186 of the job logs saved.  Isn't that what you want?

**Comment by nainav** [comment]
@clebergnu , Thanks :)
