### ISSUE TITLE
avocado use broken lzma,tarfile implemntation from python 2.7

### ISSUE THREAD

**Issue by dmonakhov** [avocado-framework/avocado#1290]
lzma  library is known to being broken for python 2.7 (at least python 3.4 is OK)
tarfile implementation is also broken http://stackoverflow.com/questions/30302204/tar-extractall-does-not-recognize-unexpected-eof

Let's temproraly switch to '/bin/xzcat' helpers as we do it in 'autotest'
Example: 
## Usage: python2.7 ./extract.py

import lzma
import tarfile
## so uncompressed tar stream will be also corrupted

lz = lzma.LZMAFile('linux-4.0.tar.xz')
t = tarfile.open(fileobj=lz)
## Silently ignores corrupted tarstream and extract incomplete archive ('fs','net' directories will absent)

t.extractall('.')

**Comment by ldoktor** [comment]
It seems like the `silent` part had been fixed:

```
>>> import lzma
>>> import tarfile
>>> lz = lzma.LZMAFile('linux-4.0.tar.xz')
>>> t = tarfile.open(fileobj=lz)
>>> t.extractall('.')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/tarfile.py", line 2078, in extractall
    self.extract(tarinfo, path)
  File "/usr/lib64/python2.7/tarfile.py", line 2115, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "/usr/lib64/python2.7/tarfile.py", line 2191, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/usr/lib64/python2.7/tarfile.py", line 2232, in makefile
    copyfileobj(source, target)
  File "/usr/lib64/python2.7/tarfile.py", line 266, in copyfileobj
    shutil.copyfileobj(src, dst)
  File "/usr/lib64/python2.7/shutil.py", line 49, in copyfileobj
    buf = fsrc.read(length)
  File "/usr/lib64/python2.7/tarfile.py", line 831, in read
    buf += self.fileobj.read(size - len(buf))
  File "/usr/lib64/python2.7/tarfile.py", line 743, in read
    return self.readnormal(size)
  File "/usr/lib64/python2.7/tarfile.py", line 758, in readnormal
    return self.__read(size)
  File "/usr/lib64/python2.7/tarfile.py", line 750, in __read
    raise ReadError("unexpected end of data")
tarfile.ReadError: unexpected end of data

$ pip list |grep lzma
pyliblzma (0.5.3)
```

Anyway I see your point and having `archive` library which is only able to uncompress small files is not really useful. I think we should keep the code there and add optional dependency on tar. When it's available we should use it, but when it's not available we should attempt to extract the file using python library and re-raise the possible exceptions along with information that they should install `tar` for advanced features.

There is a similar problem with `zip` as well, currently we handle symlinks/file permissions manually. So we could re-use this code and first try using `unzip` utility and when not available fall-back to standard library.

I'll mention this on the avocado meeting and get back to you. Thank you for this notice!

**Comment by ldoktor** [comment]
This card has been described in https://trello.com/c/X3Qnsz4I/760-redesign-the-utils-archive and we are going to plan it accordingly to the priorities. In the meantime please hardcode the `tar` command manually.

**Comment by adereis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Redesign the `utils.archive`](https://trello.com/c/X3Qnsz4I/760-redesign-the-utils-archive)

**Comment by ldoktor** [comment]
I believe all the info is described in the card, let's close this issue and we'll plan the card accordingly to priorities (unless someone from community picks it earlier as currently it's not really high priority for us)
