### ISSUE TITLE
function that return online cpu number {map}

### ISSUE THREAD

**Issue by PraveenPenguin** [avocado-framework/avocado#1364]
Not able to find any function in avocado that return online cpu number in system if that functionality not available if yes can i add that 
i need this to one of my test which use cpu hot plug 

Regards
praveen

**Comment by ldoktor** [comment]
Hello @PraveenPenguin, dou you need the total count, or the bitmap? For total number of cpus you can use `multiprocessing.cpu_count()`. For online bitmap you can probably use the https://github.com/avocado-framework/avocado/pull/1363/commits/7d7f292d2fcefb8a2ad9dff8b93cf77a91e81da7 (with some cleanups)

**Comment by PraveenPenguin** [comment]
@ldoktor for test i need  bitmap of online cpu's , will do all required clean up and raise new pull request .

**Comment by PraveenPenguin** [comment]
@ldoktor thanks for merge  of code 

will close this issue
