### ISSUE TITLE
Unable to read values from yaml file in Avocado 39.0

### ISSUE THREAD

**Issue by vrbagalkote** [avocado-framework/avocado#1380]
I have a script which is working perfectly fine in Avocado 38.0 and I see values reflected from the yaml, but where as the same script on Avocado 39.0 is failing to take the values from yaml file.

**Comment by ldoktor** [comment]
Hello @vrbagalkote, can you please provide more details? What values are you talking about? Is your script part of a test, or does it parses the results, or is it some kind of a plugin to integrate avocado with your tools?

**Comment by vrbagalkote** [comment]
Hi @ldoktor , My script is a test case. And it gets input values from yaml file(disk name, raid level). Please refer below patch.

https://github.com/avocado-framework/avocado-misc-tests/pull/135

**Comment by apahim** [comment]
@ldoktor indeed multiplexer is not working after b6cbe7340ae16543665603a8bab8aa49d68bf9e2.

**Comment by lmr** [comment]
I had this problem a while ago, but thought it was some backwards incompatible changes to the multiplexer. Without time to investigate, I started to use the 36 LTS version.

**Comment by ldoktor** [comment]
I'm sorry about this issue. I forgot to inject the mux-path into the params in the cleanup commit, which broke the params. The `--dry-run` worked well, which made me think it works fine. I'll send a v2 with the fixes and a selftest to avoid such problems (currently we check params in simple test, which works similarly to dry-run)
