### ISSUE TITLE
regression: jobscripts plugin called before jsonresult

### ISSUE THREAD

**Issue by dmonakhov** [avocado-framework/avocado#1403]
Before 40.0 jobscripts plugin was the very last plugin which called on job completion.
I use that fact to prepare job report email. This script parsed result.json and create
test list status.
But this behaviour changed and now jobscripts result hook called before json, so results.json is not generated yet.

BTW: It would be nice to have generic email report plugin.

**Comment by dmonakhov** [comment]
broken by this commit d60991ff01e79006748798698115c4a2196f7d12

**Comment by clebergnu** [comment]
Hi @dmonakhov, thanks for reporting this.  I understand that this change broke your expectation, but what happened with that change is that the generation of job results were taken out of of the job.  Honestly, I didn't give enough though if the post job plugins (including jobscripts) should run before or after the generation of results.  Initially, it'd seem that post job scripts should be the first thing to run after the job is completed, but I can totally understand your use case and I'll look at generating the results first.

**Comment by dmonakhov** [comment]
Proposed patch:
diff --git a/avocado/core/job.py b/avocado/core/job.py
index eaae5e3..93ab801 100644
--- a/avocado/core/job.py
+++ b/avocado/core/job.py
@@ -564,7 +564,6 @@ class Job(object):
             self.exitcode |= exit_codes.AVOCADO_FAIL
             return self.exitcode
         finally:
-            self.job_pre_post_dispatcher.map_methods('post', self)
             if not settings.get_value('runner.behavior', 'keep_tmp_files',
                                       key_type=bool, default=False):
                 data_dir.clean_tmp_files()
diff --git a/avocado/plugins/run.py b/avocado/plugins/run.py
index 298f983..4c899d4 100644
--- a/avocado/plugins/run.py
+++ b/avocado/plugins/run.py
@@ -196,4 +196,6 @@ class Run(CLICmd):
             if len(job_instance.result_proxy.output_plugins) > 0:
                 result = job_instance.result_proxy.output_plugins[0]
                 result_dispatcher.map_method('render', result, job_instance)
+
+        job_instance.job_pre_post_dispatcher.map_methods('post', job_instance)
         return job_run

**Comment by dmonakhov** [comment]
`diff --git a/avocado/core/job.py b/avocado/core/job.py
index eaae5e3..93ab801 100644
--- a/avocado/core/job.py
+++ b/avocado/core/job.py
@@ -564,7 +564,6 @@ class Job(object):
             self.exitcode |= exit_codes.AVOCADO_FAIL
             return self.exitcode
         finally:
-            self.job_pre_post_dispatcher.map_methods('post', self)
             if not settings.get_value('runner.behavior', 'keep_tmp_files',
                                       key_type=bool, default=False):
                 data_dir.clean_tmp_files()
diff --git a/avocado/plugins/run.py b/avocado/plugins/run.py
index 298f983..4c899d4 100644
--- a/avocado/plugins/run.py
+++ b/avocado/plugins/run.py
@@ -196,4 +196,6 @@ class Run(CLICmd):
             if len(job_instance.result_proxy.output_plugins) > 0:
                 result = job_instance.result_proxy.output_plugins[0]
                 result_dispatcher.map_method('render', result, job_instance)
+
+        job_instance.job_pre_post_dispatcher.map_methods('post', job_instance)
         return job_run`

**Comment by clebergnu** [comment]
@dmonakhov btw, we have an example post-job plugin to send emails:

https://github.com/avocado-framework/avocado/tree/master/examples/plugins/job-pre-post/mail

It's simple (on purpose) but should serve as a starting point for a more robust implementation.

**Comment by clebergnu** [comment]
The change you propose seems straighforward indeed.  Can you send that as a PR? Explaining *why* the change is highly desirable in the commit message, as it will help to keep the history sound.

**Comment by dmonakhov** [comment]
Ok

**Comment by dmonakhov** [comment]
OOPs. There are more important changes untroduced by this commit.
job archivation ( which can be enabled by --archive|-z)  is now called before results plugins. So we will have results-dir w/o results.json which is very very bad.

**Comment by clebergnu** [comment]
Closing as this is dealt with the plugin ordering support proposal.
