### ISSUE TITLE
ImportError('cannot import name TestResult',)

### ISSUE THREAD

**Issue by sathnaga** [avocado-framework/avocado#1439]
$avocado --version
Avocado 40.0
Failed to load plugin from module "avocado.plugins.jsonresult": ImportError('cannot import name TestResult',)
Failed to load plugin from module "avocado.plugins.replay": ImportError('cannot import name TestResult',)
Failed to load plugin from module "avocado.plugins.distro": ImportError('cannot import name TestResult',)

**Comment by apahim** [comment]
`make clean` will fix that.

**Comment by sathnaga** [comment]
@apahim Done! Tnx
