### ISSUE TITLE
How to run all testcases of one directory?

### ISSUE THREAD

**Issue by linfenghuaster** [avocado-framework/avocado#1451]
The command like:

avocado run test_directory --show-job-log

My solution is: 

rewrite the run.py as plugin, if it is directory, run the testcase one by one using avocado, 

it seems not a good solution.

**Comment by apahim** [comment]
Isn't `avocado run test_directory/*` enough?

**Comment by ldoktor** [comment]
Could you please elaborate a bit? Avocado by default discovers directories recursively, so if you provide path to a directory, it identifies all avocado-like tests (executable binaries, executable python scripts, python scripts inherited from `avocado.Test`) and executes them one by one.

If you don't want to descend the directories, you could use the wildcards as @apahim recommended, or even complex structures involving bash like `avocado run $(find foo/bar -iname '*.py' --... | grep ...)`.

**Comment by linfenghuaster** [comment]
Hello, I find the problem :
If a test directory includes many subdirectories, which each has a test.py and test.yaml , the test.py looks like:
```python
#!/usr/bin/env python

from avocado import main
from avocado import Test


class MyTest(Test):
    """add the other method"""
    pass


class PassTest(MyTest):
    """
    Example test that passes.
    """

    def test(self):
        """
        A test simply doesn't have to fail in order to pass
        """
        pass


if __name__ == "__main__":
    main()
```
Sometimes  the avocado treat the test.yaml as a test, so it will run test.py and test.yaml both,

so avocado run test_directory/* will fail, I have not find the reason, so I use the plugin mentioned above.

**Comment by ldoktor** [comment]
Not sure which plugin you talk about, but let's use this example:

```
$ ls -al
celkem 20
drwxrwxr-x.  3 medic medic 4096  9. zář 18.59 .
drwxrwxr-x. 18 medic medic 4096  9. zář 18.56 ..
-rw-rw-r--.  1 medic medic    0  9. zář 18.57 empty.py
-rw-rw-r--.  1 medic medic    0  9. zář 18.57 my.yaml
-rwxrwxr-x.  1 medic medic  302  9. zář 14.34 passtest.py
-rwxrwxr-x.  1 medic medic   16  9. zář 14.34 passtest.sh
drwxrwxr-x.  2 medic medic 4096  9. zář 18.59 subdir

# empty.py is empty, nonexecutable file
# my.yaml is empty yaml file
# passtest* are copied from `examples/tests`
# subdir is a directory containing `passtest.py` copied from `examples/tests`

$ avocado run *

Unable to discover url(s) 'empty.py', 'my.yaml' with loader plugins(s) 'file', 'external', try running 'avocado list -V empty.py my.yaml' to see the details.

# This fails because the `empty.py` and `my.yaml` are not tests
# and you especially asked to run them

$ avocado run .
JOB ID     : b9b5e456c0b2fa88b71496045b20360609c15eb0
JOB LOG    : /home/medic/avocado/job-results/job-2016-09-09T19.01-b9b5e45/job.log
TESTS      : 3
 (1/3) ./passtest.py:PassTest.test: PASS (0.00 s)
 (2/3) ./passtest.sh: PASS (0.01 s)
 (3/3) ./subdir/passtest.py:PassTest.test: PASS (0.00 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0
TESTS TIME : 0.01 s

# This executes everything test-like in this directory and all subdirectories
# as you can see it ignores the `empty.py` because it's not inherited from
# avocado.Test, nor is it executable. The same story with `my.yaml`.

$ avocado run *.py

Unable to discover url(s) 'empty.py' with loader plugins(s) 'file', 'external', try running 'avocado list -V empty.py' to see the details.

# Won't run, because `empty.py` is not executable, nor is it avocado test

$ avocado run *.sh
JOB ID     : 87b4176bf23fa18d81369e3ef3aadd7035e8f7f5
JOB LOG    : /home/medic/avocado/job-results/job-2016-09-09T19.03-87b4176/job.log
TESTS      : 1
 (1/1) passtest.sh: PASS (0.01 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0
TESTS TIME : 0.01 s

# Runs all matching tests

$ avocado run $(find . -iname 'pass*.py')
JOB ID     : 15c5c056c4294324b83a50826f6309241b7315fb
JOB LOG    : /home/medic/avocado/job-results/job-2016-09-09T19.04-15c5c05/job.log
TESTS      : 2
 (1/2) ./passtest.py:PassTest.test: PASS (0.00 s)
 (2/2) ./subdir/passtest.py:PassTest.test: PASS (0.00 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0
TESTS TIME : 0.00 s

# the find recursively finds all matching patterns and hands it over as arguments to avocado

$ avocado run $(find . -maxdepth 1 -iname 'pass*.py')
JOB ID     : d88a82da51b87d46e1c8e1c5e21aa9c861607f2b
JOB LOG    : /home/medic/avocado/job-results/job-2016-09-09T19.05-d88a82d/job.log
TESTS      : 1
 (1/1) ./passtest.py:PassTest.test: PASS (0.00 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0
TESTS TIME : 0.00 s

# Similar to previous only limit the query to this directory
```

Also note that it's easier to analyze the issue by running `avocado list` where avocado lists the detected test type or reason why it's not a test.

**Comment by linfenghuaster** [comment]
The plugin is the modified run.py in my project.

I run the testcases of examples by the command: avocado run test_directory/*,  there is no problem too.
But in my project, all the test.py is inherited from the VirtTest Class , which is inherited from avocado/Test class as the avocado-virt,  when running the command: avocado list,  show nothing.

The test diretory looks like:

$ tree mytest/
mytest/
├── test1
│   ├── test.py
│   └── test.yaml
├── test2
│   ├── test.py
│   └── test.yaml
└── test3
    ├── test.py
    └── test.yaml

In my project, treating the test.yaml as a test should be resolved firstly.

Thank you very much.

**Comment by apahim** [comment]
@linfenghuaster you can say to avocado that your derived class is in fact an avocado test class. To do so, use the docstring tag `:avocado: enable`.
Reference: http://avocado-framework.readthedocs.io/en/latest/WritingTests.html?highlight=docstring#test-tags

**Comment by ldoktor** [comment]
Everything what you specify on cmdline is taken as test, which means running `avocado run test.yaml` results into a failure, because `test.yaml` is not a test, nor can it be executed (unless it's executable, then it probably fails).

When you use `avocado run *` it results into the same, because avocado won't receive `*` as argument, but `bash` converts it into `test1 test2 test3 test.py test.yaml`. Now when you look at the way avocado parses each argument:

```
test1 => is directory, try to recursively find all tests and ignore non-tests
    - test.py - probably test (requires the `:avocado: enable` or `avocado.Test` in it)
    - test.yaml - not a test (unless executable)
test2 => is a directory, try to recursively find all tests and ignore non-tests
    - test.py - probably test (requires the `:avocado: enable` or `avocado.Test` in it)
    - test.yaml - not a test (unless executable)
test3 => is a directory, try to recursively find all tests and ignore non-tests
    - no tests found, raise exception
test.py - probably test (requires the `:avocado: enable` or `avocado.Test` in it)
test.yaml - not a test (unless executable); raise exception
```
Therefor the result should be `Unable to discover urls(s) 'test3, test.yaml' with ...`.

I'd recommend using the `:avocado: enable` in your tests (or double inheritance with `avocado.Test` in it) and `avocado run .` to run all tests in that directory and it's children. For advanced things like different yaml file per each test please wait for the `Job API` (ideally share your suggestions in the RFC upstream). Also note that there is another RFC regarding test filtering based on tags https://github.com/avocado-framework/avocado/issues/1368, which could be useful to filter out unwanted tests.

**Comment by linfenghuaster** [comment]
OK, Thank you, I will try.  Add '.yaml'  as  the member of ignore_suffix

```python
       ignore_suffix = ('.data', '.pyc', '.pyo', '__init__.py',
                         '__main__.py')
```
 ?

**Comment by ldoktor** [comment]
Adding `.yaml` to `ignore_suffix` won't help if you specified the file directly on the cmdline (`avocado run foo.pyc` is going to fail as well), on the other hand avocado automatically skips every non-test file when discovering a directory (`avocado run .` is going to skip `foo.pyc` as it's not a test, unless it's executable (`chmod +x`)).

Therefor your options are either to create bash script to find all your tests or to rely on avocado's dictionary discovery (which might require the `:avocado: enable` tag if you use multiple test class inheritance).

**Comment by clebergnu** [comment]
@linfenghuaster I believe @ldoktor adressed your concerns here, right?  If you need to keep discussing this, please reopen this issue.  Thanks.
