### ISSUE TITLE
issue while installation avocado:40 in ubuntu 

### ISSUE THREAD

**Issue by PraveenPenguin** [avocado-framework/avocado#1464]
Hi 
 facing a issue while installation avocado latest version in ubuntu 
1- did a clone avocado git 
2- install dependencies 
3- run python setup.py 

root@ubuntu:~/test1/avocado# python setup.py 
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied
root@ubuntu:~/test1/avocado# 

Regards
Praveen

**Comment by apahim** [comment]
You have to inform the command `install`:
`python setup.py install`
Reference: http://avocado-framework.readthedocs.io/en/latest/GetStartedGuide.html#generic-installation-from-a-git-repository

**Comment by PraveenPenguin** [comment]
@apahim  my mistake . thanks
