### ISSUE TITLE
html reports not generated by default with version 41.0

### ISSUE THREAD

**Issue by narasimhan-v** [avocado-framework/avocado#1477]
I see that avocado does not generate html reports by default in version 41.0
It generated html in version 40.0

Are there any changes related to this ?

**Comment by apahim** [comment]
Yes, html is now a real plugin. Meaning you have to run `$ make link` for it to work in your development workstation or install the `avocado-plugins-output-html` rpm.

**Comment by narasimhan-v** [comment]
@apahim thanks for the clarification.
Just saw those commits as well.

Think it is better to have tthis mentioned in the [Documentation](http://avocado-framework.readthedocs.io/en/latest/ResultFormats.html)

**Comment by apahim** [comment]
Agreed. Are you going to send a pull request for it? Otherwise, I can create a card.

**Comment by sathnaga** [comment]
@narasimhan-v @apahim 
$cd avocado/optional_plugins/html
$python setup.py install

**Comment by narasimhan-v** [comment]
@apahim Sure, I will send a PR.

Is it enough if I mention it only in HTML results exlanation (ResultFormats.rst) or should I mention also in installation guide (GetStartedGuide.rst) ?

**Comment by apahim** [comment]
@narasimhan-v, both. You should mention in GetStartedGuide.rst that html plugin is an optional package. Also, for those installing from source, it requires the aditional `make link` command. And in ResultFormats.rst, you can mention in `HTML report` section that it depends on the plugin to be installed.

**Comment by clebergnu** [comment]
@narasimhan-v @apahim this PR should deal with this, now that in-tree optional plugins are also activated by `make develop`:

https://github.com/avocado-framework/avocado/pull/1531

**Comment by clebergnu** [comment]
Closing as #1531 has been merged.
