### ISSUE TITLE
git helper writes to stdout, making comparisons impossible

### ISSUE THREAD

**Issue by imphil** [avocado-framework/avocado#1505]
I have the following code in my test:

```python
def setUp(self):
    ...
    git.get_repo('https://github.com/xxx/xxx', branch = 'master', lbranch = 'master', destination_dir = self.somedir)
```

git_repo uses the process module to call git, which in turn writes to the test stdout. 

~~~
Initialized empty Git repository in /var/tmp/avocado_y5uSzm/xxx/src/xxx/.git/
ce1f159659b78707ad4exxx0c736505998be8b63
~~~

As the tempdir is different on every run, this makes comparing the output using `--output-check-record` impossible.

I wasn't able to quickly get avocado to build in development mode, but probably something like this should fix it:

```diff
diff --git a/avocado/utils/git.py b/avocado/utils/git.py
index 0bffd2c..15dea15 100644
--- a/avocado/utils/git.py
+++ b/avocado/utils/git.py
@@ -103,7 +103,8 @@ class GitRepoHelper(object):
         """
         os.chdir(self.destination_dir)
         return process.run(r"%s %s" % (self.cmd, astring.shell_escape(cmd)),
-                           ignore_status=ignore_status)
+                           ignore_status=ignore_status,
+                           allow_output_check = 'none')
 
     def fetch(self, uri):
         """
```

**Comment by ldoktor** [comment]
Well, this is unexpected. The question is whether someone might depend on this as it has been here for a long time. Your proposed fix works well, let me send PR for you and we can discuss the possible issues there.

**Comment by ldoktor** [comment]
Btw do you have any particular problem setting the avocado in development mode? Is there anything with regards to documentation we could change to make it easier?

**Comment by clebergnu** [comment]
Closing as pull requested as merged.

**Comment by imphil** [comment]
@ldoktor Thanks for creating the PR!

Regarding the documentation: I've used the documentation at http://avocado-framework.readthedocs.io/en/latest/ContributionGuide.html#hacking-and-using-avocado

Especially the paragraph after `make develop` is a bit confusing to me (just as python package managers are in general). What I think happened on my system that I've ran the avocado command from `~/.local/bin/avocado`, but it picked up the modules from the distro-installed version. I didn't confirm that in detail, so my guess might be wrong.

What IMHO could be done to the documentation:
- what should people do to run avocado after running "make develop"?
- How much of this symlink/egg stuff requires action to get things running, and what is just explaining the background details?

**Comment by ldoktor** [comment]
One should not need to configure anything extra. Take a look at the `.travis.yml` file, which set's avocado in develop mode in the CI. All the needed steps are:

```
$ make requirements
$ make develop
$ ./scripts/avocado ...
```

To simplify things I don't use the `./scripts/avocado`, but I simply copy&paste `scripts/avocado` to `/usr/local/bin` and use it all the times. There are not many changes so it works with most of the versions and when there is a bigger change I can always update it. If you use `make develop` it should always use the develop version and not the installed one. To check that you can simply break avocado and give it a try.

Also note that you only need to run `make develop` once, then you can update the code and the latest version is always used. (unless you add/remove some targets like adding a new plugin, then you need to develop after update/cleanup before remove)
