### ISSUE TITLE
Wrong behaviour with filtering keys in multiplex

### ISSUE THREAD

**Issue by ligurio** [avocado-framework/avocado#1509]
I have a simple multiplex file:

```
[root@supermicro1 tests]# cat test.yaml 
tests: !mux
 test1:
   timeout: 1
   db: 'dffd'
 test2:
   timeout: 1000
[root@supermicro1 tests]# 
```

avocado generate two combinations from this file:

```
[root@supermicro1 tests]# avocado multiplex test.yaml 
Variants generated:
Variant 1:    /run/tests/test1
Variant 2:    /run/tests/test2
```

But in test.py I want to get keys for _test1_ key only:

```
[root@supermicro1 tests]# cat test.py
#!/usr/bin/env python

from avocado import Test
from avocado import main

class Test(Test):

    def setUp(self):

        db = self.params.get('timeout', '*/test1*')
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    def test(self):
        pass

if __name__ == "__main__":
    main()
```

and when I run test.py using avocado it runs with second parameter combination too:

```
[root@supermicro1 tests]# avocado run test.py -m test.yaml --tap -
1..2
# debug.log of test.py:Test.test;1:
#   17:59:35 DEBUG| PARAMS (key=timeout, path=*/test1*, default=None) => 1
#   17:59:35 INFO | PASS 1-test.py:Test.test;1
#   17:59:35 INFO | 
ok 1 test.py:Test.test;1
# debug.log of test.py:Test.test;2:
#   17:59:35 DEBUG| PARAMS (key=timeout, path=*/test1*, default=None) => None
#   17:59:35 INFO | PASS 2-test.py:Test.test;2
#   17:59:35 INFO | 
ok 2 test.py:Test.test;2
[root@supermicro1 tests]# 
```
According to [Avocado documentation](http://avocado-framework.readthedocs.io/en/latest/MultiplexConfig.html) it's wrong behavior.

**Comment by ligurio** [comment]
So my scenario is quite simple - I want to keep all test parameters in a set of YAML files and run test set with these parameters. Test should take all required parameters from test variants generated by Avocado.

**Comment by ldoktor** [comment]
Hello @ligurio, before going into details, let's adjust your example. The usage of `timeout` is restricted only to test timeout and this value is in use by the runner itself (you can access this value, but you must not specify multiple occurrences). For demonstration purposes let's change this value to `db_timeout`:

```yaml
tests: !mux
 test1:
   db_timeout: 1
   db: 'dffd'
 test2:
   db_timeout: 1000
```
```python
    print self.params.get("db_timeout", "*/test1*")
```

Now to the problem. The idea behind `!mux` is to produce all combinations of the child nodes. This basically means by using `!mux` you're saying split the params database into several variants and run each test with the values specified by each variant (only).

To see all params that are available to test you can use `avocado run test.py -m test.yaml --dry-run --show-job-log`:

```
...
Variant 1:    /run/tests/test1
Variant 2:    /run/tests/test2
...
START 1-passtest.py:PassTest.test;1
Test params:
/run/tests/test1:db ==> dffd
/run/tests/test1:timeout ==> 1
...
START 2-passtest.py:PassTest.test;2
Test params:
/run/tests/test2:timeout ==> 1000
...
```

From this you can see that only `/run/tests/test1` params are handed over to first variant, and `/run/tests/test2` params are handed over to the second variant.

The option you're probably looking for is to join the branches, which is the default relation. Let's try the same but remove the first `!mux`:

```yaml
tests:
 test1:
   db_timeout: 1
   db: 'dffd'
 test2:
   db_timeout: 1000
```

```
Variant 1:    /run/tests/test1, /run/tests/test2
...
START 1-passtest.py:PassTest.test
Test params:
/run/tests/test1:db_timeout ==> 1
/run/tests/test1:db ==> dffd
/run/tests/test2:db_timeout ==> 1000
```

Which contains both options. Anyway I guess this is still not what you had in mind (at least what I think you had in mind). If I understand the motivation correctly, you have 2 tests and they share some of the values, eg. db, db_timeout, db_password, ... while defining some of their own, correct? I'd do something like this:

```yaml
database:
    db_timeout: 1
    db: 'dffd'
tests: !mux
    test1:
        foo: test1_value
    test2:
        foo: test2_value
```

which produces:

```
Variant 1:    /run/database, /run/tests/test1
Variant 2:    /run/database, /run/tests/test2
...
START 1-passtest.py:PassTest.test;1
Test params:
/run/database:db_timeout ==> 1
/run/database:db ==> dffd
/run/tests/test1:foo ==> test1_value
...
START 2-passtest.py:PassTest.test;2
Test params:
/run/database:db_timeout ==> 1
/run/database:db ==> dffd
/run/tests/test2:foo ==> test2_value
```

as you can see both tests contains the `database` values and each contains it's own set of params from `tests/*`. Does this fit your requirement?

**Comment by ldoktor** [comment]
Actually after reading your question again I realized you are basically interested in answer1, which means just remove the `!mux` and use different than `timeout` keyword as the `timeout` keyword would make the mux-file fail.

**Comment by ligurio** [comment]
@ldoktor Thanks for detailed explanation! Now this mechanism is more clear for me.

My main idea was having single and common YAML config for all my tests. But avocado runs tests with all available variants and it's seems there is only one ability to don't run test with parameters for other tests is an option "--exclude" with all excluded variants. But it is a complicated way when you have a big number of tests and parameters for them.

**Comment by ldoktor** [comment]
Yep, that is the cost for not having test-url as part of the multiplexer (compare to avocado-vt). So far we discussed several options, like default multiplex files located in test's data dir (eg. `avocado run sleeptest.py --mux-default` would according to the idea look for `default.yaml` in the data dir). Other was to include the test url (optionaly) so instead of `avocado run test -m file.yaml` one would include the `test` in the yaml file and only run `avocado run -m my_tests.yaml` which would define both, variants and tests (like in avocado-vt)

Anyway none those made it upstream. Currently the closest thing is the Job API, which is in progress. That should allow defining free-form jobs including the possibility to assign various different yaml files to each test. We all are looking forward to that feature...

For now I can only recommend using a big yaml file and use `--filter-only` and `--filter-out` to filter the current test (eg `avocado run --filter-only /test1 -- test1.py` `avocado run --filter-only /test2 -- test2.py`, ...)

I guess your question is covered, so let's close this issue and feel free to reopen or raise a new one if needed.

**Comment by ligurio** [comment]
@ldoktor, thanks again for explanation! :)
