### ISSUE TITLE
return object of process.run() can also have pid as a attribute  

### ISSUE THREAD

**Issue by PraveenPenguin** [avocado-framework/avocado#1514]
Hi 
I need  pid of  running command which run through process.run() that i  can use in my one  test  is there any way i get pid from  return object of process.run()  ?
Regards
Praveen

**Comment by apahim** [comment]
That's quite easy to add, since `process.Popen` returns the pid, we just have to fill `CmdResult` with that information. Working on that.

**Comment by PraveenPenguin** [comment]
@apahim thanks
