### ISSUE TITLE
Analyzing dmesg for tagging a test as PASS or FAIL

### ISSUE THREAD

**Issue by narasimhan-v** [avocado-framework/avocado#1545]
Since each test collects dmesg, can we analyze it for errors, and tag a test as `FAIL` in that case ?

To start with, we can just look for some common errors in dmesg logs, or just grep for the word `error`

**Comment by lmr** [comment]
IMO, the test itself must explicitly check dmesg and if a particular error message pattern was found during test execution, then it could mark itself as FAIL. Sometimes a dmesg failure might be unrelated to the test itself, that's why the checks should be explicit in the test.

**Comment by adereis** [comment]
I agree with Lucas. Avocado itself can't tell if a message in dmesg should imply in a test failure or not.  There are many things happening with the machine during a test (includding running multiple avocado jobs), not to mention a test might even be interested in some error (imagine a test that causes an error to validate some error handling, for example).

Besides, dmesg/journal collection is done via sysinfo, which is a subsystem completely unrelated to test statuses.

If you want to do it, I recommend using the python syslog/journal routines. But keep in mind your test may be fragile if it just checks for error messages in dmesg.

**Comment by narasimhan-v** [comment]
@lmr @adereis Agreed. Thanks

**Comment by sathnaga** [comment]
@lmr @narasimhan-v @adereis @ldoktor How about having dmesg check as a plugin and that monitors for the list of known failures(call trace, BUGON, etc and this list can be improved), a given test can subscribe to that service/plugin and get error-ed out when such issues are thrown out, we can make the dmesg_check on/off during test preprocess/postprocess or config

**Comment by PraveenPenguin** [comment]
@sathnaga looks me good

**Comment by ldoktor** [comment]
I'd rather implement a `avocado.utils` for that, which could be initialized during `setUp` and checked during `tearDown` of the test and each test could get finer control over what it should expect. This utility should report the error/panic/bug/... records as instances and the test could decide whether it wants to report it or not.

If one wants this as a plugin (pre/post job or pre/post test?) they would have this utils in hand to enable it for jobs/tests. Would that work for you, @narasimhan-v, @adereis, @lmr?

**Comment by narasimhan-v** [comment]
@ldoktor @sathnaga It would be good to have this in `avocado.utils`, if not as an optional plugin that can be enabled/disabled by a test case.

**Comment by ldoktor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [dmesg check utility](https://trello.com/c/lN5ATg4N/858-dmesg-check-utility)

**Comment by sathnaga** [comment]
@ldoktor not able find the above card in trello?

There are few more usecases which requires this plugin, from avocado-vt we mostly not worry about the dmesg outputs for any test assertions right now, but
there are situations host kernel warnings, errors are thrown while test execution which might of our interest.

How a

**Comment by sathnaga** [comment]
I would feel we can introduce avocado command line param to enable/disable the dmesg check which inturn would check during the postporocess of test, and that can be generic for avocado-vt and avocado-misc tests?

we can already use the dmesg output present in the pre,post folder of sysinfo collection?

**Comment by sathnaga** [comment]
@adereis @lmr @narasimhan-v ^^

**Comment by sathnaga** [comment]
@narasimhan-v can you reopen this issue to get our discussion keep going

**Comment by narasimhan-v** [comment]
@sathnaga I am not able to re-open

**Comment by lmr** [comment]
@sathnaga If you guys want to revisit this discussion, I'll reopen it. My views on the subject have gone unchanged, athough for a large test suite based on avocado such as avocado-vt you could add default post processing routines that detect problems in dmesg.

**Comment by sathnaga** [comment]
@lmr agree, but it would be good to have the routines generic because there are times we hit at different kernel warning altogether than the test, so we can have a generic way of alerting the user with different(custom) error messages.

**Comment by sathnaga** [comment]
virttest/env_process.py
```
if params.get("verify_host_dmesg", "yes") == "yes":
        dmesg_log_file = params.get("host_dmesg_logfile", "host_dmesg.log")
        dmesg_log_file = utils_misc.get_path(test.debugdir, dmesg_log_file)
        utils_misc.verify_host_dmesg(dmesg_log_file=dmesg_log_file)


```
@lmr  I see this in avocado-vt already, will check what it is up to.

**Comment by sathnaga** [comment]
This can be the starting place, and we can improve the error string list,check and try making it generic across avocado?

```
def verify_host_dmesg(dmesg_log_file=None, trace_re=None):
    """
    Find host call trace in dmesg log.

    :param dmesg_log_file: The file used to save host dmesg. If None, will save
                           host dmesg to logging.debug.
    :param trace_re: re string used to filter call trace.
    """
    panic_re = [r"BUG:.*---\[ end trace .* \]---"]
    panic_re.append(r"----------\[ cut here.* BUG .*\[ end trace .* \]---")
    panic_re.append(r"general protection fault:.* RSP.*>")
    panic_re.append(r"Out of memory: Kill process .*Call Trace:")
    panic_re = "|".join(panic_re)
    dmesg = process.system_output("dmesg", timeout=30, ignore_status=True,
                                  verbose=False)
    if dmesg:
        match = re.search(panic_re, dmesg, re.DOTALL | re.MULTILINE | re.I)
        if match is not None:
            err = "Found call trace in host dmesg."
            d_log = "Host dmesg log:\n%s" % dmesg
            if dmesg_log_file:
                file(dmesg_log_file, "w+").write(d_log)
                err += " Please check host dmesg log %s." % dmesg_log_file
            else:
                err += " Please check host dmesg log in debug log."
                logging.debug(d_log)
            process.system("dmesg -C", ignore_status=True)
            raise exceptions.TestError(err)

```

**Comment by adereis** [comment]
My view on this stays the same:

> [...] Avocado itself can't tell if a message in dmesg should imply in a test failure or not. There are many things happening with the machine during a test (includding running multiple avocado jobs), not to mention a test might even be interested in some error (imagine a test that causes an error to validate some error handling, for example).

So I don't think this belongs to Avocado, as it doesn't match the architecture or the base requirement that Avocado should be multi-user and multi-job capable.

With that said, the code you wrote seems to be fine be used in your test, or maybe even as the base for something to be added to `utils`. Another idea would be to do these checks pre/post (job or test) so users get a warning somewhere.

Again, I recommend closing this issue.

**Comment by ldoktor** [comment]
OK, going in circles, I also keep the same opinion as during previous round. Such feature could be useful, I'd split it into several levels:

1. generic failures detection, useful for most tests, can be disabled by config/test metadata
2. specific failures detection, should be an avocado utility which would be called from `tearDown` of the test (eg. userspace crashes and so on)

The first can use `dmesg` or some better heuristic. A while ago we had an example code by @jfilak  https://github.com/jfilak/avocado/commit/e3258706bdfffb8ddddb2f1bc51328af2958617d which was using ABRT to report kernel crashes, but he claimed that the same mechanism can be used to detect any process failures like userspace program crashes.

In examples, the (1) would be usually ON in testing farms, probably enabled on devels systems. It'd be disabled only for executions where call traces are expected either by setting, or by test metadata (currently only available as `default_params`). I can see this implemented as pre/post test plugin (which IIRC does not exists yet)

The (2) would be called from test, for example:

```python
crash.register(pid)
crash.register(pid, flags)
crash.collect()  # => Checks whether registered pids produced crashes
crash.dmesg.oom()  # Looks for out of memory messages
crash.dmesg.soft_lockup()  # looks for soft lockups
...
```

**Comment by jfilak** [comment]
You don't need to reimplement the logic to detect kernel oops in dmesg - ABRT already doest that pretty well. However, if you really want to implement your own dmesg parser, here you can see the list of strings matched recognized by ABRT:
https://github.com/abrt/abrt/blob/master/src/lib/kernel.c#L84

**Comment by jfilak** [comment]
@clebergnu  Hmm, I was under the impression that this is the ABRT integration proposal:
https://www.redhat.com/archives/avocado-devel/2016-November/msg00013.html

**Comment by clebergnu** [comment]
@jfilak I guess the intention was to have a PR of sorts sent, but you're right, your patch is a valid starting point.  I'm reopening this issue, but I don't think Avocado should by default attempt to fail tests based on possible system wide failures.

So, I'm going to attempt to turn your patch into a utility function that test writers can use.  On top of that, we can later think of having a plugin.

**Comment by narasimhan-v** [comment]
@clebergnu Where do we stand on this now, and how do you suggest we proceed here ? I can see some avocado-misc-tests are having their own dmesg implementations.

@PraveenPenguin Your thoughts please ?

**Comment by PraveenPenguin** [comment]
@narasimhan-v I started to rework on this `https://github.com/avocado-framework/avocado/pull/2642` may try to send PR as soon as possible

**Comment by narasimhan-v** [comment]
@clebergnu I see that dmesg collection is removed from framework from avocado/core/sysinfo. So we are going against framework using dmesg for anything ?

**Comment by willianrampazzo** [comment]
Hi @narasimhan-v, I went thru the discussion, and I have the same opinion as others here that it is not Avocado's responsibility to fail a test based on dmesg output, but the responsibility of the test itself. 

So, I also agree that something implemented as a utility should be considered instead of adding this kind of checks to the Avocado core. If we add this kind of feature to the core, we may expect other requests to different files that testers may think are relevant to their tests checked into the Avocado core.

**Comment by narasimhan-v** [comment]
Sure @willianrampazzo I get your point.

**Comment by willianrampazzo** [comment]
Closing this issue as there have not been activities for more than one year. Please, reopen it if needed, or open a new issue with a specific request from this issue.
