### ISSUE TITLE
Package for Fedora?

### ISSUE THREAD

**Issue by ralphbean** [avocado-framework/avocado#1558]
I see you have a repo for Fedora systems.  Would you be open to submitting avocado for package review to be in Fedora officially?

We're considering avocado as one of a number of frameworks for testing in the Fedora Modularity effort, but we don't think we'd be able to use it if it wasn't in the official Fedora repos.

**Comment by clebergnu** [comment]
Most definetely! I'm the Fedora packager for autotest, Avocado's previous incarnation.  For Avocado we've designed it from day one to not have the same packaging problems we had with autotest, so it should be a pretty simple process.

I'm adding a card to our planning board to track this task!

**Comment by clebergnu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Propose Avocado packages to Fedora](https://trello.com/c/idiQ3z8M/861-propose-avocado-packages-to-fedora)

**Comment by mmathesius** [comment]
Fedora packaging is in progress.
https://bugzilla.redhat.com/show_bug.cgi?id=1394952

**Comment by clebergnu** [comment]
Latest updates on the BZ for Fedora 24:

```
python-aexpect-1.2.0-3.20161110gitaca459d.fc24, python-avocado-43.0-6.fc24 has been pushed to the Fedora 24 stable repository. If problems still persist, please make note of it in this bug report.
```

and F25:

```
python-aexpect-1.2.0-3.20161110gitaca459d.fc25, python-avocado-43.0-6.fc25 has been pushed to the Fedora 25 stable repository. If problems still persist, please make note of it in this bug report.
```

This is awesome! Thanks to everyone involved. I'm closing this issue. now.
