### ISSUE TITLE
IPMI support for avocado

### ISSUE THREAD

**Issue by sathnaga** [avocado-framework/avocado#1560]
How about adding IPMI library support to avocado.

IPMI being industry standard protocol for system management, it will make it a common library across
different platforms and we can achieve console access to host etc..

Any comments and thoughts?

**Comment by ldoktor** [comment]
The only thing I can say is yes, that could be useful. You can start simple and add some advanced stuff later.

**Comment by sathnaga** [comment]
@ldoktor Sure

**Comment by ldoktor** [comment]
I guess we're all set here. Feel free to re-open this issue, should you require assistance.
