### ISSUE TITLE
is there a way to control a remote docker container which installed avocado?

### ISSUE THREAD

**Issue by michael84** [avocado-framework/avocado#1561]
Hi guys,

As I am testing a target host with python 2.6 installed, and there is a running docker container with avocado installed already. Is there a way to control the container running on remote host?? thanks a lot.

**Comment by ldoktor** [comment]
Hello @michael84, if your container also has `sshd` enabled, you can use `--remote-hostname $ipaddr` to run a job inside of that container. (there are several options like `--remote-port`, `--remote-username` , ..., please check `avocado run -h` for details.

**Comment by michael84** [comment]
Thanks a lot @ldoktor ! yeah, it works to run a job inside of that container.

Actually, I installed avocado 39 on a host with python 2.7 installed, and the target machine installed python 2.6. I am trying to run a job to target machine remotely...the log shows:
==========
...
2016-10-26 23:05:51,970 stacktrace       L0041 ERROR| Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado-39.0-py2.7.egg/avocado/core/remote/runner.py:241
2016-10-26 23:05:51,970 stacktrace       L0044 ERROR| JobError: Remote machine does not seem to have avocado installed
2016-10-26 23:05:51,970 stacktrace       L0045 ERROR| 
==========

So I think this is due to the runner didn't find "/usr/lib/python2.7/site-packages/avocado-39.0-py2.7.egg/avocado/core/remote/runner.py" on remote host.

And then I installed avocado in a container which has python 2.7 and had it running on remote machine...hope it can run avocado as an app on remote machine. It is not working absolutely...

**Comment by ldoktor** [comment]
Hello @michael84, avocado should work fine with python 2.6, the message you put here is only a note that the `avocado --version` command failed on the remote machine, you could find more details in `remote.log` in the job results.

Anyway first things first. Did you try running the container interactively and running avocado? Does something like this work?

```
[medic@w541 ~ ]$ sudo docker run -t -i --rm  $image bash
[root@job-2016-10-27T09 /]# avocado run /bin/true 
JOB ID     : dc41d9f0ae5e28105a555df5401cee085ad14714
JOB LOG    : /root/avocado/job-results/job-2016-10-27T09.39-dc41d9f/job.log
TESTS      : 1
 (1/1) /bin/true: PASS (0.00 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0
JOB HTML   : /root/avocado/job-results/job-2016-10-27T09.39-dc41d9f/html/results.html
TESTS TIME : 0.00 s
[root@job-2016-10-27T09 /]# exit
[medic@w541 ~ ]$ 
```

If not than you need to focus on why the in-container avocado does not work. You can also try:

```
AVOCADO_LOG_DEBUG=yes avocado run /bin/true
```
or even
```
avocado --show all run /bin/true
```

to see all streams and debug information in order to find the root cause.

**Comment by ldoktor** [comment]
Hello @michael84, did the interactive execution work? Or did you get the in-docker testing running or is there a way to help you with that?

**Comment by ldoktor** [comment]
@michael84 there are no updates so I guess the interactive execution helped and your setup is now solid. Feel free to re-open this with additional info if necessary.
