### ISSUE TITLE
The installation document is incomplete.

### ISSUE THREAD

**Issue by tntC4stl3** [avocado-framework/avocado#1568]
Actually if you install avocado via pip and install all requirements for all plugins, you still need to download the source code and install the HTML report plugin manually.

But the document doesn't mention that in `Installing from standard Python tools` section.

Also I think it should be mentioned in chapter `Result Format` that we need the HTML plugin install before using `--open-browser` option.

**Comment by ldoktor** [comment]
Hello @tntC4stl3, this issue was addressed by https://github.com/avocado-framework/avocado/pull/1609 Feel free to re-open this request if you believe we should do more.
