### ISSUE TITLE
python 2.6 require stevedore>=1.8.0,<=1.10.0

### ISSUE THREAD

**Issue by yanan-fu** [avocado-framework/avocado#1613]
Currently, for python 2.6,  run "avocado vt-bootstrap --vt-type qemu" , it failed as:

> Avocado crashed:
Traceback (most recent call last):
  File "/usr/bin/avocado", line 5, in <module>
    pkg_resources.run_script('avocado-framework==43.0', 'avocado')
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 461, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1194, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib/python2.6/site-packages/avocado_framework-43.0-py2.6.egg/EGG-INFO/scripts/avocado", line 71, in <module>
    from avocado.core.app import AvocadoApp
  File "/usr/lib/python2.6/site-packages/avocado_framework-43.0-py2.6.egg/avocado/__init__.py", line 19, in <module>
    from avocado.core.job import main
  File "/usr/lib/python2.6/site-packages/avocado_framework-43.0-py2.6.egg/avocado/core/job.py", line 32, in <module>
    from . import dispatcher
  File "/usr/lib/python2.6/site-packages/avocado_framework-43.0-py2.6.egg/avocado/core/dispatcher.py", line 20, in <module>
    from stevedore import EnabledExtensionManager
  File "/usr/lib/python2.6/site-packages/stevedore-1.18.0-py2.6.egg/stevedore/__init__.py", line 23, in <module>
    LOG.addHandler(logging.NullHandler())
> AttributeError: 'module' object has no attribute 'NullHandler'

Checked, python2.6 require stevedore>=1.8.0,<=1.10.0. 
In requirements.txt, it is defined, but in setup.py:

>    172           python_requires='>=2.6',
>    173           install_requires=['stevedore'])

Then after "python setup.py install",  stevedore-1.18.0-py2.6.egg  will be installed.

Modify steup.py as following and test again, it is ok.

>     172           python_requires='>=2.6',
>     173           install_requires=['stevedore>=1.8.0,<=1.10.0'])

The test is base on python-setuptools-0.6.10-3.el6.noarch which is included  in rhel6.9 repo.

**Comment by ldoktor** [comment]
Good catch, can you please send a PR as you did all the investigation?

**Comment by clebergnu** [comment]
2016-11-09 2:30 GMT-03:00 Yanan Fu <notifications@github.com>:

> Currently, for python 2.6, run "avocado vt-bootstrap --vt-type qemu" , it
> failed as:
>
> Avocado crashed:
> Traceback (most recent call last):
> File "/usr/bin/avocado", line 5, in <module>
> pkg_resources.run_script('avocado-framework==43.0', 'avocado')
> File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 461, in
> run_script
> self.require(requires)[0].run_script(script_name, ns)
> File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1194, in
> run_script
> execfile(script_filename, namespace, namespace)
> File "/usr/lib/python2.6/site-packages/avocado_framework-43.
> 0-py2.6.egg/EGG-INFO/scripts/avocado", line 71, in <module>
> from avocado.core.app import AvocadoApp
> File "/usr/lib/python2.6/site-packages/avocado_framework-43.
> 0-py2.6.egg/avocado/*init*.py", line 19, in <module>
> from avocado.core.job import main
> File "/usr/lib/python2.6/site-packages/avocado_framework-43.
> 0-py2.6.egg/avocado/core/job.py", line 32, in <module>
> from . import dispatcher
> File "/usr/lib/python2.6/site-packages/avocado_framework-43.
> 0-py2.6.egg/avocado/core/dispatcher.py", line 20, in <module>
> from stevedore import EnabledExtensionManager
> File "/usr/lib/python2.6/site-packages/stevedore-1.18.0-py2.
> 6.egg/stevedore/*init*.py", line 23, in <module>
> LOG.addHandler(logging.NullHandler())
> AttributeError: 'module' object has no attribute 'NullHandler'
>
> Checked, python2.6 require stevedore>=1.8.0,<=1.10.0.
> In requirements.txt, it is defined, but in setup.py:
>
> 172 python_requires='>=2.6',
> 173 install_requires=['stevedore'])
>
> Then after "python setup.py install", stevedore-1.18.0-py2.6.egg will be
> installed.
>
> Modify steup.py as following and test again, it is ok.
>
> 172           python_requires='>=2.6',
> 173           install_requires=['stevedore>=1.8.0,<=1.10.0'])
>
>
The problem with such a line is that it will apply those version
restrictions for *all* Python versions.  It seems that we may have to
choose between a single range of stevedore versions for all Python
versions, or a different setup sequence for Python 2.6.  This difference
setup sequence would be:

1) pip install -r requirements.txt
2) python setup.py install

**Comment by ldoktor** [comment]
Well the `setup.py` is a script, therefor we can define the `install_requires` conditionally on the current python version, cant we? :wink:

**Comment by ldoktor** [comment]
(But I guess the conditional lines should be also supported by the install script)

**Comment by clebergnu** [comment]
2016-11-09 11:01 GMT-03:00 Lukáš Doktor <notifications@github.com>:

> Well the setup.py is a script, therefor we can define the install_requires
> conditionally on the current python version, cant we? 😉
>

Yes, it should be possible.

**Comment by clebergnu** [comment]
Closing on #1622 merge.
