### ISSUE TITLE
[Report] No handlers could be found for logger

### ISSUE THREAD

**Issue by PandaWei** [avocado-framework/avocado#1638]
[root@hw3 avocado]# scripts/avocado --show all vt-bootstrap --vt-type qemu
stevedore.extension: found extension EntryPoint.parse('zip_archive = avocado.plugins.archive:ArchiveCLI')
stevedore.extension: found extension EntryPoint.parse('remote = avocado.plugins.remote:Remote')
stevedore.extension: found extension EntryPoint.parse('journal = avocado.plugins.journal:Journal')
stevedore.extension: found extension EntryPoint.parse('yaml_to_mux = avocado.plugins.yaml_to_mux:YamlToMux')
stevedore.extension: found extension EntryPoint.parse('gdb = avocado.plugins.gdb:GDB')
stevedore.extension: found extension EntryPoint.parse('wrapper = avocado.plugins.wrapper:Wrapper')
stevedore.extension: found extension EntryPoint.parse('vm = avocado.plugins.vm:VM')
stevedore.extension: found extension EntryPoint.parse('json = avocado.plugins.jsonresult:JSONCLI')
stevedore.extension: found extension EntryPoint.parse('replay = avocado.plugins.replay:Replay')
stevedore.extension: found extension EntryPoint.parse('xunit = avocado.plugins.xunit:XUnitCLI')
stevedore.extension: found extension EntryPoint.parse('tap = avocado.plugins.tap:TAP')
stevedore.extension: found extension EntryPoint.parse('docker = avocado.plugins.docker:Docker')
stevedore.extension: found extension EntryPoint.parse('envkeep = avocado.plugins.envkeep:EnvKeep')
stevedore.extension: found extension EntryPoint.parse('html = avocado_result_html:HTML')
stevedore.extension: found extension EntryPoint.parse('vt-list = avocado_vt.plugins.vt_list:VTLister')
root: No python imaging library installed. Windows guest BSOD detection disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
root: No python imaging library installed. PPM image conversion to JPEG disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
stevedore.extension: found extension EntryPoint.parse('vt = avocado_vt.plugins.vt:VTRun')
stevedore.extension: found extension EntryPoint.parse('exec-path = avocado.plugins.exec_path:ExecPath')
stevedore.extension: found extension EntryPoint.parse('run = avocado.plugins.run:Run')
stevedore.extension: found extension EntryPoint.parse('sysinfo = avocado.plugins.sysinfo:SysInfo')
stevedore.extension: found extension EntryPoint.parse('list = avocado.plugins.list:List')
stevedore.extension: found extension EntryPoint.parse('multiplex = avocado.plugins.multiplex:Multiplex')
stevedore.extension: found extension EntryPoint.parse('plugins = avocado.plugins.plugins:Plugins')
stevedore.extension: found extension EntryPoint.parse('diff = avocado.plugins.diff:Diff')
stevedore.extension: found extension EntryPoint.parse('config = avocado.plugins.config:Config')
stevedore.extension: found extension EntryPoint.parse('distro = avocado.plugins.distro:Distro')
stevedore.extension: found extension EntryPoint.parse('vt-bootstrap = avocado_vt.plugins.vt_bootstrap:VTBootstrap')
17:44:08 INFO | qemu test config helper
17:44:08 INFO | 
17:44:08 INFO | 1 - Checking the mandatory programs and headers
17:44:08 INFO | /bin/7za OK
17:44:08 INFO | /sbin/tcpdump OK
17:44:08 INFO | /bin/nc OK
17:44:08 INFO | /sbin/ip OK
17:44:08 INFO | /sbin/arping OK
17:44:08 INFO | /bin/gcc OK
17:44:08 INFO | /usr/include/sys/types.h OK
17:44:08 INFO | /usr/include/sys/socket.h OK
17:44:08 INFO | /usr/include/sys/unistd.h OK
17:44:08 INFO | /usr/include/python2.7/Python.h OK
17:44:08 INFO | 
17:44:08 INFO | 2 - Checking the recommended programs
17:44:08 INFO | /bin/qemu-kvm OK
17:44:08 INFO | /bin/qemu-img OK
17:44:08 INFO | /bin/qemu-io OK
17:44:08 INFO | 
17:44:08 INFO | 3 - Updating all test providers
avocado.test: Running 'git log -1'
avocado.test: [stdout] commit c704a6bab3c4a0b0c533030e97ca4db449f05487
**No handlers could be found for logger "avocado.test.stdout"**
avocado.test: Command 'git log -1' finished with 0 after 0.0304291248322s
avocado.test: [stdout] Merge: 671a2e3 162069f
avocado.test: [stdout] Author: Wayne Sun <ericbreeze@gmail.com>
avocado.test: [stdout] Date:   Wed Oct 19 00:13:32 2016 -0500
avocado.test: [stdout] 
avocado.test: [stdout]     Merge pull request #895 from sudeeshjohn/dac_start_destroy
avocado.test: [stdout]     
avocado.test: [stdout]     dac_start_destroy: libvirt version check added
avocado.test: Running 'git log -1'
avocado.test: [stdout] commit aa4e4b0772afb40d1edafab872319b92b4d057d4
avocado.test: [stdout] Author: Andrei Stepanov <astepano@redhat.com>
avocado.test: Command 'git log -1' finished with 0 after 0.024386882782s
avocado.test: [stdout] Date:   Thu Oct 20 17:18:21 2016 +0200
avocado.test: [stdout] 
avocado.test: [stdout]     Fix vm_shutdown test.
avocado.test: [stdout]     
avocado.test: [stdout]     Signed-off-by: Andrei Stepanov <astepano@redhat.com>
avocado.test: Running 'git log -1'
avocado.test: [stdout] commit a0adf8dd53a5d968a326e9f9810986e9d548588a
avocado.test: Command 'git log -1' finished with 0 after 0.00979018211365s
avocado.test: [stdout] Merge: d335dff 9c93182
avocado.test: [stdout] Author: Xu Tian <xutian@redhat.com>
avocado.test: [stdout] Date:   Wed Nov 23 16:59:47 2016 +0800
avocado.test: [stdout] 
avocado.test: [stdout]     Merge pull request #829 from PandaWei/balloon_stress
avocado.test: [stdout]     
avocado.test: [stdout]     Two commits about balloon stress test
17:44:08 INFO | 
17:44:08 INFO | 4 - Verifying directories
..............

**Comment by ldoktor** [comment]
Well this is the problem with leftovers from `run`. The `bootstrap.py` uses `LoggingConfig` to reset and re-configure logging, which does not suit avocado.

```
virttest/bootstrap.py:755

        log_cfg = utils_misc.VirtLoggingConfig()
        log_cfg.configure_logging(verbose=True)

```
When we added vt-bootstrap we needed to keep compatibility with autotest, so the question is whether we still want to keep it. If not we could use the proper `avocado.app` logger instead of root logger and remove the custom log handling. Alternatively we could conditionally skip this step when running from avocado and enable the root logger (which is used by `virttest.bootstrap`) directly in `avocado_vt.plugins.vt_bootstrap`.

**Comment by PandaWei** [comment]
No final conclusion has yet been reached on this matter, right?

we can avoid the no handler error by the following,
```
--- a/virttest/asset.py
+++ b/virttest/asset.py
@@ -326,7 +326,7 @@ def download_test_provider(provider, update=False):
         # sanity check to ensure the git repository is OK:
         try:
             os.chdir(download_dst)
-            process.system('git log -1')
+            process.system('git log -1', verbose=False)
         except process.CmdError:
             logging.error('Something is unexpectedly wrong with the git repository at %s',
                           download_dst)
```
 "git log -1" throws an exception or not should be concerned about.

**Comment by ldoktor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [issue: vt-bootstrap warns about no logging handler](https://trello.com/c/wPMZ8bHg/877-issue-vt-bootstrap-warns-about-no-logging-handler)

**Comment by ldoktor** [comment]
Thank you for reporting this issue, it was addressed by https://github.com/avocado-framework/avocado-vt/issues/905
