### ISSUE TITLE
Support to access console for different architecutres. 

### ISSUE THREAD

**Issue by harihare** [avocado-framework/avocado#1663]
Avocado framework will be used by all architectures, Is there any future plans to include support to  access console for different architectures like conmux in autotest.

**Comment by kvaneesh** [comment]
It would nice if we can have a health check thread with remote/vm runner. This health check can then see if the remote/vm crashed  and also capture console.log

**Comment by ldoktor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ISSUE: Support to access console for different architectures](https://trello.com/c/AiuUdABw/883-issue-support-to-access-console-for-different-architectures)

**Comment by lmr** [comment]
@harihare I made some comments in the linked Trello card. While in principle this is a goal that would make avocado much more interesting for platform level test development, in practice the core development team may not have enough time to work on this.

**Comment by lmr** [comment]
@kvaneesh About the health check, it's something that would be better off on a separate issue/trello card. We have extensive experience with checking VM health from previous projects, such as virt-test, so the criteria can be borrowed from these projects.

**Comment by ldoktor** [comment]
Hello @harihare and @kvaneesh. We talked about this RFE and it looks tempting. There are some updates on the associated card https://trello.com/c/AiuUdABw/883-issue-support-to-access-console-for-different-architectures

Anyway we do plan to improve the remote execution (health check, per-test responses, ...) as a side effect of the Job API and multi-stream tests (maybe in a second stage as the primary goal is to get the basic support, but remote will definitely benefit from this). For now the remote execution is considered more-like a feature for developers to transparently execute their tests on remote machines and for CI one should use the remote execution of Jenkins (or whatever tools you are using).

As for the provisioning and controlling machines, that would also be nice, but it's definitely not the main aim at this point. It's similar to previous, in CI environment one usually has access to it from Jenkins and for local execution (at least our) developers usually prefer custom setup. We see the benefit in this, though, so if you have the resources and use cases, we'd be happy to review your official RFC and eventually patches. I'd suggest starting simple and ideally re-use existing projects.

Feel free to re-open this for additional details, but if you plan to work on this I'd suggest sending an RFC to avocado-devel mailing list.
