### ISSUE TITLE
runner_queue exit func call doesn't work

### ISSUE THREAD

**Issue by kvaneesh** [avocado-framework/avocado#1665]
Hi,

Usage of runner_queue as below

      self.runner_queue.put({"func_at_exit": cleanup,
                              "args": (self.path,),
                              "once": True})

Doesn't work unless the test case are in python path. We get an exception during test execution. 

Simple test:
```
#!/usr/bin/env python

import os
from avocado import main
from avocado import Test


def cleanup(path):
    if os.path.exists(path):
        os.unlink(path)

class MyTest(Test):
    """
    test
    """

    path = "/tmp/aab"

    def setUp(self):
        if os.path.exists(self.path):
            # Already initialized
            return
        self.runner_queue.put({"func_at_exit": cleanup,
                              "args": (self.path,),
                              "once": True})
        print "INITIALIZING"
        open(self.path, "w")

    def test_1(self):
        pass

    def test_2(self):
        pass

    def test_3(self):
        pass

if __name__ == "__main__":
    main()
```

For the above test to work the script should be PYTHONPATH.

-aneesh

**Comment by ldoktor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ISSUE: Allow `func_at_exit` calls from modules not in avocado's `PYTHONPATH`](https://trello.com/c/5JtoH2qW/882-issue-allow-func-at-exit-calls-from-modules-not-in-avocado-s-pythonpath)

**Comment by ldoktor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Revise the `func_at_exit`](https://trello.com/c/6KKuwEUh/932-revise-the-func-at-exit)

**Comment by clebergnu** [comment]
The card that tracks this has been closed with `WONT FIX`, so let's sync and close this issue too.

**Comment by ldoktor** [comment]
Well actually the later card is still valid and it should address this issue as well... So for updates please follow the https://trello.com/c/6KKuwEUh/932-revise-the-func-at-exit
