### ISSUE TITLE
The print statement cause the avocado to be crashed(the avocado version: 36lts)

### ISSUE THREAD

**Issue by linfenghuaster** [avocado-framework/avocado#1670]
The  testcase looks like, for example test.py :

 ```
import time

from avocado import Test

print Test

class SleepTest(Test):

    def test(self):
        sleep_length = self.params.get('sleep_length', default=1)
        self.log.debug("Sleeping for %.2f seconds", sleep_length)
        time.sleep(sleep_length)

```

when execute the command: 

avocado run test.py --show-job-log

then the avocado is crashed.

**Comment by ldoktor** [comment]
Hello @linfenghuaster, can you please provide more details about the versions and frequency? I'm not able to reproduce this on Fedora 25 with the latest master 1c88846f48680d173dad23534bb57165badccc07

**Comment by linfenghuaster** [comment]
My system is suse 11 sp3, which default python is 2.6.8. And i find: python 2.6.6(Centos 6.8 default) and 2.7 are ok , but 2.6.8 and 2.6.9 crashed.

**Comment by ldoktor** [comment]
Well I don't have such system around, can you share an output of `avocado --show all run test.py`? And if the crash is even sooner, you can try `AVOCADO_LOG_EARLY=y AVOCADO_LOG_DEBUG=y avocado --show all run test.py`.

**Comment by ldoktor** [comment]
I tried opensuse11.3, but the python version there is 2.6.5 and it works well: http://pastebin.com/GRrm3QgN Without more details I'm really unable to do anything about it. Are there isos for suse 11 without the need to register?

**Comment by ldoktor** [comment]
Oh, I know what probably happened, are you using the released avocado? If so there was a fix recently for logging infinite recursion, which is already fixed on master and 36lts branches, but it has not been released yet. So if you see a lot of messages like "No handlers could be found for logger", then it's this bug and please use the latest 36 or master till the new packages are built.

Also please next time include all logs, which would help identifying this issue earlier. For details about this issue you can see https://github.com/avocado-framework/avocado/issues/1551 and https://github.com/avocado-framework/avocado/pull/1644#discussion_r89829228

**Comment by linfenghuaster** [comment]
Yes, I use the 36lts release version. The 36lts branche fixes my problem. Sorry, My personal compute's OS is OS X, which can not reproduce the problem too. Any way, I'll pay attention next time.

**Comment by ldoktor** [comment]
Sure, no problem. I'm glad we have a fix already. Next time just make sure to include as much information as possible including all tracebacks.

**Comment by ldoktor** [comment]
The 36.3 was tagged https://github.com/avocado-framework/avocado/tree/36.3 and built. I'm not sure whether it's built automatically for SuSE, but at least the latest Fedora should not contain this issue.
