### ISSUE TITLE
Avocado-framework 44 doesn't work on CentOS 7

### ISSUE THREAD

**Issue by mateush** [avocado-framework/avocado#1683]
Latest version of the framework(44) installed with yum from packages gives no results of a test.
The error message:
> Error running method "post_tests" of plugin "journal": 'JournalResult' object has no attribute 'journal'

Executing:
`pip uninstall avocado_framework`
`pip install avocado_framework`
which downgrades it to 42, solves the issue.

Regards.

**Comment by ldoktor** [comment]
Hello @mateush, I'm sorry to hear that. I tried it on fresh Fedora and the RPM works well. Can you please include the full output of `AVOCADO_LOG_EARLY=y AVOCADO_LOG_DEBUG=y avocado --show all run /bin/true` and `AVOCADO_LOG_EARLY=y AVOCADO_LOG_DEBUG=y avocado plugins`? I'm wondering whether this issue is connected with already fixed https://github.com/avocado-framework/avocado/issues/1551

**Comment by clebergnu** [comment]
Hi @mateush, I tried to reproduce, but I did not hit the same issue you did:

```
# avocado run passtest.py --journal
JOB ID     : fc2917d5685f4033fafdc2f6fa864ea7066498ed
JOB LOG    : /root/avocado/job-results/job-2017-01-02T06.10-fc2917d/job.log
TESTS      : 1
 (1/1) passtest.py:PassTest.test: PASS (0.00 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0
TESTS TIME : 0.00 s
JOB HTML   : /root/avocado/job-results/job-2017-01-02T06.10-fc2917d/html/results.html
[root@localhost ~]# uname -a
Linux localhost.localdomain 3.10.0-327.22.2.el7.x86_64 #1 SMP Thu Jun 23 17:05:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
[root@localhost ~]# cat /etc/centos-release
CentOS Linux release 7.2.1511 (Core)
 avocado --version
Avocado 44.0
[root@localhost ~]# rpm -q avocado
avocado-44.0-0.el7.centos.noarch
```

Please add the information @ldoktor requested so we can try to pin down the error on your environment.

**Comment by mateush** [comment]
Hi @ldoktor and @clebergnu .

Thank you for your help. Tests suggested by you produced valid results.

Therefore, I investigated my scripts and it turned out that in version 44 files containing test cases must be transferred manually to a remote machine before execution. I must have overlooked this change and framework's update has caused this problem.

It might be deduced from [that section](http://avocado-framework.readthedocs.io/en/44.0/RunningTestsRemotely.html#known-issues) but maybe it would be worth highlighting this change?

Regards, Mateusz.
