### ISSUE TITLE
bad NFS mount causes that avocado run freezes

### ISSUE THREAD

**Issue by jscotka** [avocado-framework/avocado#1714]
I've runned commad: `avocado run /bin/true /bin/false --show-job-log`
result: https://paste.fedoraproject.org/535072/14851720/

it wait forever after line: 
Job ID: 67a9efaf24f8f1cd17596381a881c4df3552664f
 
Not logging /proc/pci (file does not exist)
-----------------------

after strace of command I've found that it is caused by bad NFS. It tries to catch state of dir
...
[pid  7099] stat("/home", {st_mode=S_IFDIR|0755, st_size=18, ...}) = 0
[pid  7099] stat("/boot", {st_mode=S_IFDIR|0555, st_size=4096, ...}) = 0
[pid  7099] stat("/mnt/engineeringX",
There is mounted NFS server () this server is bad.

avocado should not freeze here, and should call these commands with some timeouts and write as unresponsive call, because this stats are not important for running avocado anyway.

   Regards
   Honza

**Comment by ldoktor** [comment]
Hello Jan,

actually the hang is correct and there is not much to do about it apart from setting some timeouts on sysinfo collection. Now let's have a look at your issue in detail:

1. you execute avocado
2. avocado starts collecting sysinfo information
  - avocado tries to get output of `mount` or `df` or other command which gets information from all mounted devices which hangs till the nfs responses.

The timeout is only a partial help as any command might cause a hang later in the code. Anyway if you insist something like 60s deadline per sysinfo collection would be fine by me (less could be dangerous as on some machines it takes seconds to respond).

**Comment by jscotka** [comment]
Hi,
yes, I agree with your solution, 60s deadline is better than this situation. And there could be also second solution, be able to disable sysinfo from cmd line, it could also work, at least in these cases when you know that something is bad.
Probably it would be nice to add both fix - timeouts + disabling sysinfo from cmd line

**Comment by ldoktor** [comment]
The sysinfo can be disabled from cmdline by using `avocado run --sysinfo off`. Please take a look at the pull request #1715 whether it is sufficient for your situation.

**Comment by ldoktor** [comment]
The support for configurable timeout for sysinfo command gathering was merged. @jscotka feel free to re-open this if it doesn't suit your workflow.

**Comment by ldoktor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [sysinfo: Introduce timeout for command gathering](https://trello.com/c/40RKSXK6/916-sysinfo-introduce-timeout-for-command-gathering)
