### ISSUE TITLE
Display more friendly error tips

### ISSUE THREAD

**Issue by mengalong** [avocado-framework/avocado#1721]
when we use avocado execute some actually not existing testcase the error tips is very simple like this:

```
# avocado run not_existing_test_case.py --mux-yaml not_existing_yaml_file.yml
No such file or directory
```
from the error tips we cannot identify which file is not exist.
Is there any future plans to  make the error tips more friendly.

for example:
```
# avocado run not_existing_test_case.py --mux-yaml not_existing_yaml_file.yml
cannot access not_existing_test_case.py: No such file or directory
cannot access not_existing_yaml_file.yml: No such file or directory
```

**Comment by apahim** [comment]
Ok, first of all, let me say I agree. Let's improve the error tips.
About this specific message, for the tests files, Avocado calls them "test references". So, if you provide a test reference for a missing file, the message will be very distinctive:
~~~
$ avocado run not_existing_test_case.py

Unable to resolve reference(s) 'not_existing_test_case.py' with plugins(s) 'file', 'external', try running 'avocado list -V not_existing_test_case.py' to see the details.
~~~
The message you're seeing is coming from the yaml_to_mux plugin, which tries to parse the yaml file before the test reference resolver takes place. So, let's improve the yaml_to_mux messages.

**Comment by apahim** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve yaml_to_mux error messages](https://trello.com/c/hYCrS1oI/900-improve-yaml-to-mux-error-messages)

**Comment by mengalong** [comment]
Thanks very much.
Today is my first time to use avocado,
I have debug the code I think I can fix the problem.
The Chinese New Year is coming, I will have a week holiday, when I come back I can submit a patch.

**Comment by apahim** [comment]
Ok, looking forward to see your contribution. Thank you.

**Comment by mengalong** [comment]
HI，@apahim

when I execute: make check I got some error messages like this:

```
/home/mengalong/code/avocado/selftests/doc/test_doc_build.py:39:5: E722 do not use bare except'
Style check fail: /home/mengalong/code/avocado/selftests/doc/test_doc_build.py
/home/mengalong/code/avocado/selftests/functional/test_utils.py:188:9: E722 do not use bare except'
Style check fail: /home/mengalong/code/avocado/selftests/functional/test_utils.py
PEP8 compliance FAIL
style FAILED
make: *** [check] error 1
```
These are some code style errors and not introduced by my change.
Do I need fix it ?

**Comment by mengalong** [comment]
Here is the PR, please review it:
https://github.com/avocado-framework/avocado/pull/1728

**Comment by apahim** [comment]
@mengalong, checking.

**Comment by apahim** [comment]
Ok, last Jan 30, new version of pep8 included this E722 check for bare `except` clause:
https://pypi.python.org/pypi/pycodestyle
I will take care of it.
