### ISSUE TITLE
avocado supported achitectures, missing epel dependencies

### ISSUE THREAD

**Issue by jscotka** [avocado-framework/avocado#1723]
Hi,
I had to move testing from intel arch to all supported like: s390x, ppc64le, arm, ...
with avocado. I used avocado RPM repositories before and I had enabled EPEL for installing on RHEL.
http://avocado-framework.readthedocs.io/en/45.0/GetStartedGuide.html#enterprise-linux

But problem is that epel is not for all arches, so that, I'm unable to use RPM based avocado at all.
I've solved it by using pip install avocado-framework, to isntall it to all possible architectures, but there are some errors and it is bad solution at all to use pip instead of signed packages.
there are two solutions:
1. add also all dependencies of avocado to you repo (fabric, etc.)
2. remove dependencies of avocado on EPEL
     Regards
     Honza

**Comment by jscotka** [comment]
Hi,
as we discussed. I'm looking forward that avocado will be splitted to more modules, and base "avocado run" will not be dependent on fabric and similar tools what are not in base RHEL.
This fix will work for me.

**Comment by clebergnu** [comment]
Hi, I actually have a WIP version.  I should post a final version in a day
or two.

**Comment by clebergnu** [comment]
@jscotka the first version of the mentioned PR is out:

https://github.com/avocado-framework/avocado/pull/1744

**Comment by clebergnu** [comment]
@jscotka 46.0 included this change.  I'm closing this issue.  If you feel there's still something else to do here, please reopen it.
