### ISSUE TITLE
Fix RPM packaging paths

### ISSUE THREAD

**Issue by Andrei-Stepanov** [avocado-framework/avocado#1754]
According to: https://www.redhat.com/archives/avocado-devel/2017-February/msg00021.html

After installation avocado should work with: /var/lib/<smth>  Currently it works with:

avocado bootstrap command:
/usr/share/avocado/data/avocado-vt/test-providers.d/downloads/io-github-spiceqa-spice/spice/cfg/run.cfg   -- fetched from git

avocado run command:
/usr/share/avocado/data/avocado-vt/backends/spice/cfg/run.cfg

Please look at: https://fedoraproject.org/wiki/Archive:PackagingDrafts/RPMMacros_sharedstatedir_optflags_and_admonitions

Avocado should use for dynamic data:  %{_sharedstatedir}    /var/lib
Files inside /usr/share should be known to RPM.

**Comment by ldoktor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix RPM packaging paths](https://trello.com/c/KU1DvSAz/918-fix-rpm-packaging-paths)

**Comment by ldoktor** [comment]
Thank you for reporting this issue, it was fixed by https://github.com/avocado-framework/avocado/issues/1934
