### ISSUE TITLE
Fix RPM dependency for avocado-vt plugin to python-netaddr

### ISSUE THREAD

**Issue by Andrei-Stepanov** [avocado-framework/avocado#1755]
Fresh RHEL7.3 + EPEL + RPM packages from: https://repos-avocadoproject.rhcloud.com/static/avocado-el.repo

repoquery --location 'avocado*'
https://repos-avocadoproject.rhcloud.com/static/epel-7Server-noarch/avocado-45.0-0.el7.centos.noarch.rpm
https://repos-avocadoproject.rhcloud.com/static/epel-7Server-noarch/avocado-examples-45.0-0.el7.centos.noarch.rpm
https://repos-avocadoproject.rhcloud.com/static/epel-7Server-noarch/avocado-plugins-output-html-45.0-0.el7.centos.noarch.rpm
https://repos-avocadoproject.rhcloud.com/static/epel-7Server-noarch/avocado-plugins-vt-45.0-0.el7.centos.noarch.rpm

# avocado list
Failed to load plugin from module "avocado_vt.plugins.vt_list": ImportError('No module named netaddr',)
Failed to load plugin from module "avocado_vt.plugins.vt": ImportError('No module named netaddr',)

So, there is some lack of dependency on python-netaddr.

**Comment by ldoktor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [avocado-vt: Fix RPM packaging paths](https://trello.com/c/vp4swvdV/919-avocado-vt-fix-rpm-packaging-paths)

**Comment by ldoktor** [comment]
Thanks, we added it to `requirements` but forgot to update the RPM spec file... Working on it...

**Comment by ldoktor** [comment]
Thank you, Andrei, for the detailed report. The fix should be applied on master.
