### ISSUE TITLE
inherit test methods from parent

### ISSUE THREAD

**Issue by jscotka** [avocado-framework/avocado#1793]
I have code like:
```python
from avocado import Test
class a(Test):
    """
    :avocado: disable
    """
    def testA(self):
        print "a"

class b(a):
    """
    :avocado: enable
    """
    def testB(self):
        print "b"
```

when I call `avocado run ./b.py` It would be nice to see testA and testB there, not only testB.

**Comment by ldoktor** [comment]
OK, I like this one better 😄. I think it should be doable to expand the introspection of `:avocado: enable` tests (or even provide a different tag to say this needs to be introspected thoroughly) to look for the origin of that class and find all `test*` methods. Obviously it won't allow dynamic loading, but it should gather all existing `test*` methods of that class and I think the cost is worth it.

Note I'd not support doing this by default for all tests, only for those which are marked by a docstring (either `enable` or new one).

**Comment by ldoktor** [comment]
Btw the (incorrect) usage of this feature was also in our tree some time ago. The commit d312badcce7f69e3cd5eeb19b983ffe3e6edc4c3 rearranges our unittests to avoid double-execution of inherited class. In this example it was actually not intended to execute the test methods defined in parent class, but sometimes it is necessary and useful to allow this. Before the commit d312badcce7f69e3cd5eeb19b983ffe3e6edc4c3 if you executed the `selftests/functional/test_basic.py` as unittest, it executed more tests, than when you executed it as `avocado run`.

**Comment by ldoktor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Inherit `test*` methods from parents](https://trello.com/c/GtFlhcOj/1011-inherit-test-methods-from-parents)

**Comment by ldoktor** [comment]
Please follow the card on trello to get updates https://trello.com/c/GtFlhcOj/1011-inherit-test-methods-from-parents
