### ISSUE TITLE
--job-results-dir defaults to previous known value

### ISSUE THREAD

**Issue by narasimhan-v** [avocado-framework/avocado#1794]
When run a test with `--job-results-dir` option, and if next test is run without `--job-results-dir` option, the results dir defaults to the previous given directory.

**Comment by ldoktor** [comment]
Hello @narasimhan-v, can you please elaborate a bit? I am not able to reproduce this issue, I only saw a little inconsistency in the output which is addressed here: https://github.com/avocado-framework/avocado/pull/1795

**Comment by narasimhan-v** [comment]
@ldoktor Sorry, my mistake. It was one of my configuration.
Closing this.

**Comment by ldoktor** [comment]
No problem, at least it brought the attention which might improve the test logs 😄
