### ISSUE TITLE
[RFE] make avocado run file.py:test_Something not "grep" for the method names by default

### ISSUE THREAD

**Issue by jsynacek** [avocado-framework/avocado#1796]
I have several tests with the same prefix in the method name:
```
$ avocado list test-manager.py
...
INSTRUMENTED test-manager.py:TestManager.test_GetUnitByPID
INSTRUMENTED test-manager.py:TestManager.test_GetUnitFileState
INSTRUMENTED test-manager.py:TestManager.test_GetUnit
...
```
Now, I would like to run only `test_GetUnit` because I'm working on it right now.
```
$ avocado run test-manager.py:TestManager.test_GetUnit
...
TESTS      : 3
 (1/3) test-manager.py:TestManager.test_GetUnitByPID: PASS (1.32 s)
 (2/3) test-manager.py:TestManager.test_GetUnitFileState: PASS (0.38 s)
 (3/3) test-manager.py:TestManager.test_GetUnit: PASS (0.22 s)
...
```
Well, in this case it doesn't matter too much, because the tests with the same prefix run for a short time, but it's still annoying and it would matter if they were long. I could use tags or comment out the rest of the tests, but that's not user friendly.

I propose to make the run syntax look for the exact name instead of "grepping" for the method name. If one would want to "grep", I propose implementing a simple globbing syntax like `test-manager.py:test_GetUnit*` or maybe even `test-manager.py:test_*Unit*`. I mean use the glob at least on the right, maybe even on the left or both sides.

**Comment by ldoktor** [comment]
I agree with you. Not sure whether we wont break other people's setups, but I'd rather see the use of `fnmatch` to filter the test methods than the `grep`-like interface.

@apahim, @clebergnu any opinions?

**Comment by apahim** [comment]
Ok, I was taking a look at the current code and the way it works is: we get the string after the `:` and use it as a regex to perform a `re.search()` in the test name. Example:

```
$ avocado run passtest.py:test
JOB ID     : 8c2beec431932be45d3f906cb6b0a4adf37fda77
JOB LOG    : /home/apahim/avocado/job-results/job-2017-02-17T14.14-8c2beec/job.log
 (1/1) passtest.py:PassTest.test: PASS (0.01 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0
TESTS TIME : 0.01 s
JOB HTML   : /home/apahim/avocado/job-results/job-2017-02-17T14.14-8c2beec/html/results.html

```

In the command above, we are getting the `test` string and making the `re.search()` in the resulting test name (`passtest.py:PassTest.test`).

So, as we are using the string as a regex, you could add a end-of-string marker to the regex. That should suffice for the usage requested in this RFE:

```
$ avocado list ~/avocado/tests/test_demo.py
INSTRUMENTED /home/apahim/avocado/tests/test_demo.py:MyTest.test
INSTRUMENTED /home/apahim/avocado/tests/test_demo.py:MyTest.test1
INSTRUMENTED /home/apahim/avocado/tests/test_demo.py:MyTest.test2
INSTRUMENTED /home/apahim/avocado/tests/test_demo.py:MyTest.test3

$ avocado run ~/avocado/tests/test_demo.py:test$
JOB ID     : 6285a4f1346cf9688a6d0e8e2b4bf41fb6066929
JOB LOG    : /home/apahim/avocado/job-results/job-2017-02-17T14.13-6285a4f/job.log
 (1/1) /home/apahim/avocado/tests/test_demo.py:MyTest.test: PASS (0.02 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0
TESTS TIME : 0.02 s
JOB HTML   : /home/apahim/avocado/job-results/job-2017-02-17T14.13-6285a4f/html/results.html
``` 
@jsynacek, do you think this is good enough for you?

Anyway, to change the current behavior and make a direct string comparison between the reference after the `:` and the test method name will require us to also deal with the case where the test class is provided (like `avocado run ~/avocado/tests/test_demo.py:MyTest.test1`). I'm not against it... just wanted to point this out.

**Comment by ldoktor** [comment]
Actually you are right. I forgot that I actually used the `re.compile` to make the filter really powerful. (next time I should first look and not think...). I think we should include this in our documentation...

**Comment by jsynacek** [comment]
Yep, that definitely works. I still find it a bit counterintuitive to use regexps in this case by default, though. But that's just my opinion. In case you decided to not change the current behaviour, I would definitely mention it in the documentation.

**Comment by apahim** [comment]
https://trello.com/c/iJlNcBaf/930-improve-the-docs-regarding-the-test-references

**Comment by ldoktor** [comment]
OK let's track this issue only in trello: https://trello.com/c/iJlNcBaf/930-improve-the-docs-regarding-the-test-references
