### ISSUE TITLE
redefining self.name should not be fatal.

### ISSUE THREAD

**Issue by jscotka** [avocado-framework/avocado#1800]
Hi,
with @ldoktor we've found the issue, that I've still seen message:
```
Error running method "end_test" of plugin "tap": 'str' object has no attribute 'name'
```

He found that I redefined `self.name` inside my test class by another value, becuase of name is very nice a common option. Although I've redefined it, avocado uses things like: `self.name, self.log, self.outputdir` internally, so using this more less general names leads to very strange errors.
I understand that in case I'll redefine self.log by some my variable, or method, I'll not be able to use logging possibiliti in test, but it also should not be fatal.
And also in case I'll redefine self.name to some value, it should not have side effects. like this strange errors.

     Regads
     Honza

**Comment by clebergnu** [comment]
Hi @jscotka,

An Avocado (INSTRUMENTED) test is intended to give a user some ready to use features, and this requires some internal state.  We are trying hard to limit the number of public (and private) attributes of a `avocado.Test` class instance, but with this approach there's no way to avoid having at least some of those.

If we were to support other types of tests, say a user defined function without any "container" class, then we probably wouldn't be able to provide as many utilities to the test writer.

Still, one thing we should fix *right now* is to include ``name`` in the documentation of the test API:

http://avocado-framework.readthedocs.io/en/46.0/api/test/avocado.html#avocado.Test

**Comment by ldoktor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Protect `avocado.Test.*` variables](https://trello.com/c/rbJ8AKtp/931-rfc-protect-avocado-test-variables)

**Comment by ldoktor** [comment]
Should be addressed by the https://github.com/avocado-framework/avocado/pull/1824
