### ISSUE TITLE
RFE: using TAGS also for method

### ISSUE THREAD

**Issue by jscotka** [avocado-framework/avocado#1837]
Hi,
I like the idea of  `:avocado: tags=slow`
it works well. There is one trouble: it works just for whole class. it would be very nice to have it also for method like:

```python
class hello(Test):
    def test(self):
        """
        :avocado: tags=abc
        """
        pass
```

It allows to fiter test, and be test specific, not only class.

otherwise probably next issue is, that it would be like to allow complex syntax on commad line for filtering, like:

```
avocado run --filter-by-tags "not (tag1 and tag2) or tier*"
```
so pelase add full logic parser with __*__ notation, it could help to write more complex filtering based on tags

      Regards
     Honza

**Comment by clebergnu** [comment]
Test-level tags is indeed something we should support.  Since it looks like the general  idea of tags was well received, we should indeed make it more flexible.

About the "complex syntax", I think we should be able to cover all use cases you describe *but* the glob-like one (*"tier*"*).   The "not (tag1 and tag2)" could be written as:

```
--filter-by-tags=-tag1,-tag2
```

And you could use that with the same command line with, say, `tier1`, `tier2`, etc:

```
--filter-by-tags=-tag1,-tag2  --filter-by-tags=tier1  --filter-by-tags=tier2
```

**Comment by jscotka** [comment]
Hi,
yes, that suits me.
These globs are nice to have, but not so important.
    Regards
    Honza

**Comment by clebergnu** [comment]
OK, so let's restrict this issue to the test-level (as opposed to class-level) support for tags.

**Comment by jscotka** [comment]
Yep, it makes sense.
so and I suggest also option to specify which tags to filter, like: 
--filter-by-tags=tag -- any tag anywhere
--filter-by-tags=class:tag -- just tag mathich class
--filter-by-tags=method:tag -- just tag mathich method

I don't know the usescase now, but I can imagine that it sounds like good idea, to be able to differenciate that :-)

**Comment by juju812** [comment]
Hi, here's another TAGS related issue.

Currently syntax listed as below is not supported:
```
:avocado: enable,tags=abc,defg
``` 

```
:avocado: enable
:avocado: tags=abc,defg
```

So it's not convenient to set `enable` flag and `tags` at the same time. Minor modification in `core.safeloader` needed to support this scenario.

**Comment by apahim** [comment]
@jscotka, you can track the request here: https://trello.com/c/DYRJOIkO/957-rfe-support-tags-in-test-methods
Anyway, we will update this issue when it's ready.

**Comment by apahim** [comment]
@juju812 , you can track the request here: https://trello.com/c/6FpySXuC/958-rfe-support-defining-enable-and-tags-in-the-same-docstring-line

**Comment by ldoktor** [comment]
Let me close this issue as we have a tracker here https://trello.com/c/DYRJOIkO/957-rfe-support-tags-in-test-methods
