### ISSUE TITLE
Tests under avocado-misc-tests/io/net fail with "TestSkipError: None interface is not available" error.

### ISSUE THREAD

**Issue by hathyaga** [avocado-framework/avocado#1839]
Issue is with yaml file for the network tests under io directory as the script fails to read the "interface" parameter for the tests.

**Comment by PraveenPenguin** [comment]
I think this is not the issue only with only io test case issue seems me on avocado 46 as yaml parameter is not read it when test tried to run using yaml param 

avocado 44 log

[root@localhost ~]# avocado run avocado-misc-tests/fs/xfstests.py -m avocado-misc-tests/fs/xfstests.py.data/xfstests.yaml --show-job-log
found extension EntryPoint.parse('jobscripts = avocado.plugins.jobscripts:JobScripts')
Commands configured by file: /etc/avocado/sysinfo/commands
Files configured by file: /etc/avocado/sysinfo/files
Profilers configured by file: /etc/avocado/sysinfo/profilers
Profiler disabled
Command line: /usr/bin/avocado run avocado-misc-tests/fs/xfstests.py -m avocado-misc-tests/fs/xfstests.py.data/xfstests.yaml --show-job-log

**Avocado version: 44.0**

Config files read (in order):
/etc/avocado/avocado.conf
/etc/avocado/conf.d/gdb.conf
/root/.config/avocado/avocado.conf

Avocado config:
Section.Key                             Value
datadir.paths.base_dir                  /usr/share/avocado
datadir.paths.test_dir                  /usr/share/avocado/tests
datadir.paths.data_dir                  /usr/share/avocado/data
datadir.paths.logs_dir                  ~/avocado/job-results
sysinfo.collect.enabled                 True
sysinfo.collect.installed_packages      False
sysinfo.collect.profiler                False
sysinfo.collect.locale                  C
sysinfo.collectibles.commands           /etc/avocado/sysinfo/commands
sysinfo.collectibles.files              /etc/avocado/sysinfo/files
sysinfo.collectibles.profilers          /etc/avocado/sysinfo/profilers
runner.output.colored                   True
runner.output.utf8                      
remoter.behavior.reject_unknown_hosts   False
remoter.behavior.disable_known_hosts    False
job.output.loglevel                     debug
restclient.connection.hostname          localhost
restclient.connection.port              9405
restclient.connection.username          
restclient.connection.password          
plugins.disable                         []
plugins.skip_broken_plugin_notification []
plugins.loaders                         ['file', '@DEFAULT']
gdb.paths.gdb                           /usr/bin/gdb
gdb.paths.gdbserver                     /usr/bin/gdbserver

Avocado Data Directories:

Avocado replaces config dirs that can't be accessed
with sensible defaults. Please edit your local config
file to customize values

base     /usr/share/avocado
tests    /usr/share/avocado/tests
data     /usr/share/avocado/data
logs     /root/avocado/job-results

Multiplex tree representation:
 \-- run
      \-- setup
           \-- runargs
                  -> test_range: 2,12,34-87,91,99-112
                  -> skip_dangerous: True

Temporary dir: /var/tmp/avocado_T8JopX

Variant 1:    /run/setup/runargs

Job ID: 23f65d2bf5de165d281bc7181230a99ee935fa03

**avocado 46:**

[root@localhost ~]# avocado run avocado-misc-tests/fs/xfstests.py -m avocado-misc-tests/fs/xfstests.py.data/xfstests.yaml --show-job-log
Commands configured by file: /etc/avocado/sysinfo/commands
Files configured by file: /etc/avocado/sysinfo/files
Profilers configured by file: /etc/avocado/sysinfo/profilers
Profiler disabled
Command line: /usr/bin/avocado run avocado-misc-tests/fs/xfstests.py -m avocado-misc-tests/fs/xfstests.py.data/xfstests.yaml --show-job-log

Avocado version: 46.0

Config files read (in order):
/etc/avocado/avocado.conf
/etc/avocado/conf.d/gdb.conf
/root/.config/avocado/avocado.conf

Avocado config:
Section.Key                             Value
datadir.paths.base_dir                  /usr/share/avocado
datadir.paths.test_dir                  /usr/share/avocado/tests
datadir.paths.data_dir                  /usr/share/avocado/data
datadir.paths.logs_dir                  ~/avocado/job-results
sysinfo.collect.enabled                 True
sysinfo.collect.commands_timeout        -1
sysinfo.collect.installed_packages      False
sysinfo.collect.profiler                False
sysinfo.collect.locale                  C
sysinfo.collectibles.commands           /etc/avocado/sysinfo/commands
sysinfo.collectibles.files              /etc/avocado/sysinfo/files
sysinfo.collectibles.profilers          /etc/avocado/sysinfo/profilers
runner.output.colored                   True
runner.output.utf8                      
remoter.behavior.reject_unknown_hosts   False
remoter.behavior.disable_known_hosts    False
job.output.loglevel                     debug
restclient.connection.hostname          localhost
restclient.connection.port              9405
restclient.connection.username          
restclient.connection.password          
plugins.disable                         []
plugins.skip_broken_plugin_notification []
plugins.loaders                         ['file', '@DEFAULT']
gdb.paths.gdb                           /usr/bin/gdb
gdb.paths.gdbserver                     /usr/bin/gdbserver

Avocado Data Directories:

base     /usr/share/avocado
tests    /usr/share/avocado/tests
data     /usr/share/avocado/data
logs     /root/avocado/job-results/job-2017-03-07T14.06-56119b3

Multiplex tree representation:
 \-- run
      \-- setup
           \-- runargs
Multiplex variants:
Variant 1:    /run/setup/runargs
Temporary dir: /var/tmp/avocado_GgmPKo

Job ID: 56119b335dbcaf79dc18243245d42baefd18505a

Not logging /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor (file does not exist)

**Comment by apahim** [comment]
Looking into it.

**Comment by hathyaga** [comment]
verified with 1840 and it solves the issue.
