### ISSUE TITLE
Query about method to overwrite standard Avocado plugins in version 0.45

### ISSUE THREAD

**Issue by juju812** [avocado-framework/avocado#1844]
We were used to overwrite Avocado plugin "run" and "list", added some customized option, and finally register them to entry point `avocado.plugins.cli.cmd` by the code below.

>       entry_points={
>           'avocado.plugins.cli.cmd': [
>                 'run = uvp_virt.plugins.run:Run',
>                 'list = uvp_virt.plugins.list:List'
>           ]
>       }

In avocado version 0.31 this works fine, when we execute `avocado run`, code in `uvp_virt.plugins.run` executed as expected. But after we update avocado version to 0.45, things goes wrong, standard plugin executed instead of our own.

By viewing the code we found that one `self.extensions.sort` method added in `Dispatcher._init_plugins` and this is probably the reason why plugin loading order changed.

So there are two queries:

1. Is this an advised way to overwrite plugins like what we've done in 0.31? Just because our plugin loaded later it's selected to execute. In my personal view it's some kind of ugly and not stable. We should directly overwrite code in `avocado.plugins.run`, for we are modifying, not adding a new plugin, meanwhile we can avoid to load unused plugins while running test.

2. If it's actually advised, how could we still select our plugin instead of standard one? I've noticed that there're section in avocado.conf as below:

> [plugins.cli.cmd]
>     order = ['myrun', 'run']

But I have no idea of the behavior when the plugin name is the same...

Sorry for bother and looking forward your kindly reply.

**Comment by clebergnu** [comment]
Hi @juju812.

I don't really know how much different your own `run` and `list` commands are, but it looks like, if the standard commands can not be customized by an `avocado.plugins.cli` type of plugin (http://avocado-framework.readthedocs.io/en/47.0/api/core/avocado.core.html#avocado.core.plugin_interfaces.CLI), I'd go with new commands.

By having command such as `uvp-virt-run` and `uvp-virt-list`, there'd be no need to replace the original commands.  Also, if you're loading new types of tests from either `run` or `list`, the complete (or partial) solution would be to write a new test type and loader.  Unfortunately, these have not been moved to the "new plugin architecture" yet.

Still, having said all that, the only place where we decide what to run as an avocado sub command is what was given on the command line + the definition of the setuptools entry points.  This specific plugin class, does not respect ordering because only one command will ever be executed for each Avocado execution.  The dispatcher is never involved.  The relevant code that proves this is here:

https://github.com/avocado-framework/avocado/blob/master/avocado/core/app.py#L86

So, I'd say that a new installation of an updated avocado has replaced the setuptools entrypoints on your environment, and causing the standard commands to be executed.  You can double check that with:

```python
import pkg_resources
print pkg_resources.get_entry_info('avocado_framework', 'avocado.plugins.cli.cmd', 'run')
```

**Comment by juju812** [comment]
Hi, @clebergnu,

Thanks for your quick response.
But actually it's not a installation issue. After new installation of avocado 0.45, I re-installed our own code then entry points registered either. 

In my view this issue caused by unpredictable plugin loading order when the plugin name is the same.To make things clear I'll list subcommand output of command `avocado -h` in version 0.31 and 0.45 as below.

v0.31:

>  subcommands:
>   valid subcommands
> 
>   {exec-path,run,config,list,valgrind,multiplex,plugins,sysinfo,distro}
>                         subcommand help
>     exec-path           Returns path to avocado bash libraries and exits.
>     run                 Run one or more tests (native test, test alias, binary
>                         or script)
>     sysinfo             Collect system information
>     list                List available tests
>     multiplex           Generate a list of dictionaries with params from a
>                         multiplex file
>     plugins             Displays plugin information
>     config              Shows avocado config keys
>     distro              Shows detected Linux distribution
>     **run                 Run one or more tests (native test, test alias, binary
>                         or script)**
>     **list                List available tests**
>     **valgrind            UTS valgrind subcommand**
> 

v0.45:

> subcommands:
>   valid subcommands
> 
>   {exec-path,run,sysinfo,list,valgrind,multiplex,plugins,diff,config,distro}
>                         subcommand help
>     config              Shows avocado config keys
>     diff                Shows the difference between 2 jobs.
>     distro              Shows detected Linux distribution
>     exec-path           Returns path to avocado bash libraries and exits.
>     **list                List available tests(UTS CUSTOMIZED)**
>     list                List available tests
>     multiplex           Tool to analyze and visualize test variants and params
>     plugins             Displays plugin information
>     **run                 Runs one or more tests (native test, test alias,
>                         binary or script)(UTS CUSTOMIZED)**
>     run                 Runs one or more tests (native test, test alias,
>                         binary or script)
>     sysinfo             Collect system information
>     **valgrind            UTS valgrind subcommand**

In my view, later loaded plugins will take effect. In v0.31, customized plugins loaded in the end so we can use our `run` and `list`. But things changed in v0.45, probably by the `self.extensions.sort` method, loading order of our customized plugins moved up so we got standard ones instead. : (

Of course we can use new command name as `uvp-virt-run` and `uvp-virt-list`, ether we can directly overwrite the `run` and `list` code in `avocado.plugins` to avoid this issue. But we're trying to find another beautiful way, so the query comes out again, is there a compact way to change the plugin loading order when the plugin name is the same? Or you can point out that same plugin name is not supported and advised so we'll change our mind. : )

**Comment by juju812** [comment]
BTW, we modified the `run` command in order to run multiple tests with different yaml configuration files, as mentioned in issue #1451.

> linux-gAJiGG:/mnt/git/v2r3/testcase # tree test_tc/
> test_tc/
> |-- test_tc1
> |   |-- test.py
> |   |-- test.pyc
> |  \`-- test.yaml
> |-- test_tc2
> |   |-- test.py
> |   |-- test.pyc
> |   \`-- test.yaml
> \`-- test_tc3
>     |-- test.py
>     \`-- test.pyc
> 
> 3 directories, 8 files

In standard Avocado, the yaml file load only once before the command `run` start. So all test files have to share one yaml file. And only one `Job` instance created for multiple tests files. So I changed the code to create multiple `Job`s in one `run` command, each `Job` for single test file, and load yaml configuration before `Job` created. Example code pasted as below:

```python
    def run(self, args):
        """
        Run test modules or simple tests.

        :param args: Command line args received from the run subparser.
        """
        log = logging.getLogger("avocado.app")
        # add by hejun31@huawei.com
        references_backup = copy.deepcopy(args.reference)
        timeout_backup = args.job_timeout
        debug = getattr(args, "mux_debug", False)
        exit_code = exit_codes.AVOCADO_ALL_OK
        exit_code_list = []
        for reference in references_backup:
            for _ in range(args.repeat):
                if not os.path.isdir(reference):  # Single file
                    args.job_timeout = timeout_backup
                    exit_code_list.append(self._run(args, log))
                else:
                    ignore_suffix = ('.data', '.pyc', '.pyo', '__init__.py', '.yaml',
                                     '__main__.py', 'env.py')
                    for dirpath, _, filenames in os.walk(reference):
                        for file_name in filenames:
                            if not file_name.startswith('.'):
                                for suffix in ignore_suffix:
                                    if file_name.endswith(suffix):
                                        break
                                else:
                                    pth = os.path.join(dirpath, file_name)
                                    yaml_pth = os.path.join(dirpath, file_name.replace('.py', '.yaml'))
                                    args.reference = [pth]  # reference is a list
                                    avocado_variants_backup = copy.deepcopy(args.avocado_variants)
                                    if os.path.exists(yaml_pth):
                                        from_yaml = create_from_yaml([yaml_pth], debug)
                                        args.avocado_variants.data.merge(from_yaml)
                                    args.job_timeout = timeout_backup
                                    exit_code_list.append(self._run(args, log, is_dir=True))
                                    # Recover the avocado variants after test run
                                    args.avocado_variants = avocado_variants_backup
        for i in exit_code_list:
            exit_code |= i

        return exit_code
        # end by hejun31@huawei.com

    def _run(self, args, log, is_dir=False):
        if args.unique_job_id is not None:
            try:
                int(args.unique_job_id, 16)
                if len(args.unique_job_id) != 40:
                    raise ValueError
            except ValueError:
                log.error('Unique Job ID needs to be a 40 digit hex number')
                sys.exit(exit_codes.AVOCADO_FAIL)
        try:
            args.job_timeout = time_to_seconds(args.job_timeout)
        except ValueError as e:
            log.error(e.message)
            sys.exit(exit_codes.AVOCADO_FAIL)
        job_instance = job.Job(args)
        job_run = job_instance.run(is_dir)
        result_dispatcher = ResultDispatcher()
        if result_dispatcher.extensions:
            result_dispatcher.map_method('render',
                                         job_instance.result,
                                         job_instance)
        # add by wangshengfang@huawei.com
        if args.profile_path is not None:
            return self._profile(job_instance.run, args.profile_path)
        # end by wangshengfang@huawei.com

        return job_run
```

This solution is imperfect and dedicated to our own test setup, but hope this thinking is useful for Avocado design, or you can help to improve the solution in Avocado designer's PoV.

Thanks again.BTW, we modified the `run` command in order to run multiple tests with different yaml configuration files, as mentioned in issue #1451.

> linux-gAJiGG:/mnt/git/v2r3/testcase # tree test_tc/
> test_tc/
> |-- test_tc1
> |   |-- test.py
> |   |-- test.pyc
> |  \`-- test.yaml
> |-- test_tc2
> |   |-- test.py
> |   |-- test.pyc
> |   \`-- test.yaml
> \`-- test_tc3
>     |-- test.py
>     \`-- test.pyc
> 
> 3 directories, 8 files

In standard Avocado, the yaml file load only once before the command `run` start. So all test files have to share one yaml file. And only one `Job` instance created for multiple tests files. So I changed the code to create multiple `Job`s in one `run` command, each `Job` for single test file, and load yaml configuration before `Job` created. Example code pasted as below:

```python
    def run(self, args):
        """
        Run test modules or simple tests.

        :param args: Command line args received from the run subparser.
        """
        log = logging.getLogger("avocado.app")
        # add by hejun31@huawei.com
        references_backup = copy.deepcopy(args.reference)
        timeout_backup = args.job_timeout
        debug = getattr(args, "mux_debug", False)
        exit_code = exit_codes.AVOCADO_ALL_OK
        exit_code_list = []
        for reference in references_backup:
            for _ in range(args.repeat):
                if not os.path.isdir(reference):  # Single file
                    args.job_timeout = timeout_backup
                    exit_code_list.append(self._run(args, log))
                else:
                    ignore_suffix = ('.data', '.pyc', '.pyo', '__init__.py', '.yaml',
                                     '__main__.py', 'env.py')
                    for dirpath, _, filenames in os.walk(reference):
                        for file_name in filenames:
                            if not file_name.startswith('.'):
                                for suffix in ignore_suffix:
                                    if file_name.endswith(suffix):
                                        break
                                else:
                                    pth = os.path.join(dirpath, file_name)
                                    yaml_pth = os.path.join(dirpath, file_name.replace('.py', '.yaml'))
                                    args.reference = [pth]  # reference is a list
                                    avocado_variants_backup = copy.deepcopy(args.avocado_variants)
                                    if os.path.exists(yaml_pth):
                                        from_yaml = create_from_yaml([yaml_pth], debug)
                                        args.avocado_variants.data.merge(from_yaml)
                                    args.job_timeout = timeout_backup
                                    exit_code_list.append(self._run(args, log, is_dir=True))
                                    # Recover the avocado variants after test run
                                    args.avocado_variants = avocado_variants_backup
        for i in exit_code_list:
            exit_code |= i

        return exit_code
        # end by hejun31@huawei.com

    def _run(self, args, log, is_dir=False):
        if args.unique_job_id is not None:
            try:
                int(args.unique_job_id, 16)
                if len(args.unique_job_id) != 40:
                    raise ValueError
            except ValueError:
                log.error('Unique Job ID needs to be a 40 digit hex number')
                sys.exit(exit_codes.AVOCADO_FAIL)
        try:
            args.job_timeout = time_to_seconds(args.job_timeout)
        except ValueError as e:
            log.error(e.message)
            sys.exit(exit_codes.AVOCADO_FAIL)
        job_instance = job.Job(args)
        job_run = job_instance.run(is_dir)
        result_dispatcher = ResultDispatcher()
        if result_dispatcher.extensions:
            result_dispatcher.map_method('render',
                                         job_instance.result,
                                         job_instance)
        # add by wangshengfang@huawei.com
        if args.profile_path is not None:
            return self._profile(job_instance.run, args.profile_path)
        # end by wangshengfang@huawei.com

        return job_run
```

This solution is imperfect and dedicated to our own test setup, but hope this thinking is useful for Avocado design, or you can help to improve the solution in Avocado designer's PoV.

Thanks again.

**Comment by apahim** [comment]
@juju812, why don't you avoid clashes and just change the name of your plugin? Like this:

```python
...
from avocado.plugins.run import Run
...

class Run(Run):
    name = 'myrun'
    def run(self, args):
        ...
```

With the proper entrypoint:
```python
entry_points={'avocado.plugins.cli.cmd': [ 'myrun = uvp_virt.plugins.run:Run']}
```

And use it like this:
```
$ avocado myrun ...
```

Anyway, an Avocado execution is a one-job-run by concept. To do what you want, I'd rather use something like this:
```bash
#!/bin/bash

# Find the test files
tests=$(ls $1/*.py)

# Execute avocado once per test file with the corresponding yaml
for test in $tests
do  
    avocado run $test -m ${test%.py}.yaml
done
```

To use with:
```
$ ./run.sh  ~/avocado/tests/
```

**Comment by apahim** [comment]
Btw, as a test, I created an *optional plugin* with the same `run` name:
https://github.com/apahim/avocado/commit/d86afba72e72170b1cf33ca46c5ccbe272fe440c

And I can use it without issues. Here it's showing up in the `list`:
```
$ avocado plugins
Plugins that add new commands (cli.cmd):
config    Shows avocado config keys
diff      Shows the difference between 2 jobs.
distro    Shows detected Linux distribution
exec-path Returns path to avocado bash libraries and exits.
list      List available tests
multiplex Tool to analyze and visualize test variants and params
plugins   Displays plugin information
run       Runs one or more tests (native test, test alias, binary or script)
run       Hackish run   <===============
sysinfo   Collect system information
Plugins that add new options to commands (cli):
docker      Run tests inside docker container
envkeep     Keep variables in remote environment
gdb         GDB options for the 'run' subcommand
html        HTML job report options for 'run' subcommand
journal     Journal options for the 'run' subcommand
json        JSON output options for 'run' command
remote      Remote machine options for 'run' subcommand
replay      Replay options for 'run' subcommand
tap         TAP - Test Anything Protocol results
vm          Virtual Machine options for 'run' subcommand
wrapper     Implements the '--wrapper' flag for the 'run' subcommand
xunit       xUnit output options
yaml_to_mux YamlToMux options for the 'run' subcommand
zip_archive Result archive (ZIP) support to run command
Plugins that run before/after the execution of jobs (job.prepost):
jobscripts  Runs scripts before/after the job is run
teststmpdir Creates a temporary directory for tests consumption
Plugins that generate job result in different formats (result):
html        HTML result support
json        JSON result support
xunit       XUnit result support
zip_archive Result archive (ZIP) support
Plugins that generate job result based on job/test events (result_events):
human   Human Interface UI
journal Journal event based results implementation
tap     TAP - Test Anything Protocol results
```

And here the proof it's being used (https://github.com/apahim/avocado/commit/d86afba72e72170b1cf33ca46c5ccbe272fe440c#diff-b1b85ecd025dae2a7081dabd2a4c01abR38):
```
$ avocado run passtest.py
xxx hacking arround xxx
JOB ID     : c6d58a83fdbcadc35776428dfa3ffab088cf269b
JOB LOG    : /home/apahim/avocado/job-results/job-2017-03-09T13.08-c6d58a8/job.log
 (1/1) passtest.py:PassTest.test: PASS (0.02 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0
TESTS TIME : 0.02 s
JOB HTML   : /home/apahim/avocado/job-results/job-2017-03-09T13.08-c6d58a8/html/results.html
```

**Comment by clebergnu** [comment]
@juju812 can you please paste the outcome of this from your system:

```python
import pkg_resources
print pkg_resources.get_entry_info('avocado_framework', 'avocado.plugins.cli.cmd', 'run')
```

**Comment by juju812** [comment]
Hi, @apahim,

Thanks for your comments. 
For plugin name issue, yes, we'll consider to change plugin name to avoid this conflict. This is the simplest way.
And for multi-job-in-one-run issue, solution of shell script seems not accepted by our users. They think an autotest framework should handle this scenario instead of creating extra scripts. So we have to continue using this implementation. : (

And @clebergnu, here's the output of `get_entry_info` and `avocado plugins`:

> linux-gAJiGG:~ # python
> Python 2.6.9 (unknown, Dec 12 2016, 11:39:40) 
> [GCC 4.3.4 [gcc-4_3-branch revision 152973]] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> \>\>\> import pkg_resources
> \>\>\> print pkg_resources.get_entry_info('avocado', 'avocado.plugins.cli.cmd', 'run')
> run = avocado.plugins.run:Run
> \>\>\> exit()


> linux-gAJiGG:~ # avocado plugins | more
> Plugins that add new commands (cli.cmd):
> config    Shows avocado config keys
> diff      Shows the difference between 2 jobs.
> distro    Shows detected Linux distribution
> exec-path Returns path to avocado bash libraries and exits.
> list      List available tests(UTS CUSTOMIZED)
> list      List available tests
> multiplex Tool to analyze and visualize test variants and params
> plugins   Displays plugin information
> run       Runs one or more tests (native test, test alias, binary or script)(UTS CUSTOMIZED)  **<==== loaded before standard plugin**
> run       Runs one or more tests (native test, test alias, binary or script)
> sysinfo   Collect system information
> valgrind  UTS valgrind subcommand
> Plugins that add new options to commands (cli):
> docker      Run tests inside docker container
> envkeep     Keep variables in remote environment
> gdb         GDB options for the 'run' subcommand
> journal     Journal options for the 'run' subcommand
> json        JSON output options for 'run' command
> remote      Remote machine options for 'run' subcommand
> replay      Replay options for 'run' subcommand
> tap         TAP - Test Anything Protocol results
> vm          Virtual Machine options for 'run' subcommand
> wrapper     Implements the '--wrapper' flag for the 'run' subcommand
> xunit       xUnit output options
> yaml_to_mux YamlToMux options for the 'run' subcommand
> zip_archive Result archive (ZIP) support to run command
> Plugins that run before/after the execution of jobs (job.prepost):
> jobscripts  Runs scripts before/after the job is run
> teststmpdir Creates a temporary directory for tests consumption
> Plugins that generate job result in different formats (result):
> json        JSON result support
> xunit       XUnit result support
> zip_archive Result archive (ZIP) support
> Plugins that generate job result based on job/test events (result_events):
> human   Human Interface UI
> journal Journal event based results implementation
> tap     TAP - Test Anything Protocol results

You can see that only one plugin named "run" is loaded, and I still insist this difference cause by different plugin loading order and later loaded plugins will take effect.

**Comment by apahim** [comment]
@juju812, did you try to create it as an optional plugin, as in my comment https://github.com/avocado-framework/avocado/issues/1844#issuecomment-285335489?

**Comment by juju812** [comment]
Here's one section of the setup.py we're using, in my view this is exact optional plugin you refered...

```python
setup(name='uvp-virt',
      version=VERSION,
      description='UVP Virtualization Testing Plugin',
      author='Lin Fenghua',
      author_email='linfenghua@huawei.com',
      url='http://github.com/uvp-virt',
      packages=find_packages(),
      data_files=get_data_files(),
      entry_points={
          'avocado.plugins.cli.cmd': [
                'valgrind = uvp_virt.plugins.valgrind:Valgrind',
                'run = uvp_virt.plugins.run:Run',
                'list = uvp_virt.plugins.list:List'
          ]
      },
      zip_safe=False
      )
```

**Comment by ldoktor** [comment]
Hello @juju812, I'm wondering whether the `pre/post` job plugin won't serve you actually better than the custom `run` plugin. Unless you need to influence the loading (I mean download the tests etc) it should suffice and is the recommended way of doing things before/after job execution.

**Comment by juju812** [comment]
Hi, all, after discussion we decide to rename our plugin to avoid this name conflict.
Thank you all and in my view this issue can be closed.

**Comment by ldoktor** [comment]
I'm glad you worked it out
