### ISSUE TITLE
backport patch to 36lts branch?

### ISSUE THREAD

**Issue by will-Do** [avocado-framework/avocado#1870]
Hi,
We are using 36lts for daily work, and suffering a bug that the terminal stty is messed up when run help of some some commands(paginator=on), and turned out it was fixed by 55efdca9f00, could we get this fix to 36lts?
And is there any strategies or rules that we can back port patches like this?

**Comment by clebergnu** [comment]
@will-Do if a bug is preventing you from using Avocado LTS, then yes, it should be fixed (in LTS).

Every bug fix request for LTS will be considered, and unless there's something major preventing us from fixing it, it will make into the 36lts branch.

Another matter is how often we do releases out of that branch, but we're also really flexible at this point.

**Comment by clebergnu** [comment]
@will-Do btw, if you feel like it, you could go as far as sending a pull request for the LTS branch (a cherry-pick/backport of that patch, for instance).

**Comment by will-Do** [comment]
@clebergnu 
Got it, thanks, I will do that

**Comment by lmr** [comment]
I'm closing this due to the merge of #1871.
