### ISSUE TITLE
Directive parsing only works for a single directive

### ISSUE THREAD

**Issue by benzea** [avocado-framework/avocado#1886]
Currently the directive parser only searches for the first occurrence of `:avocado: XXX`. This means that if one does for example:

    :avocado: enable
    :avocado: tags=a,b,c

Then the tags will not be found. Avocado should either find all occurrences or allow specifying all options together.

**Comment by apahim** [comment]
Yep, we have a card for that and it's marked as a bug (meaning it will be worked in the coming sprint for sure):
https://trello.com/c/6FpySXuC/958-bug-make-it-possible-to-define-enable-and-tags-docstring

**Comment by clebergnu** [comment]
Fixed by #1915
