### ISSUE TITLE
Ideal usage of self.srcdir

### ISSUE THREAD

**Issue by narasimhan-v** [avocado-framework/avocado#1924]
What is the ideal usage of self.srcdir ?
I can see that one directory per run(variant ) is getting created, but not getting cleared/removed after the test runs.

Right now, we use it to download the tar-balls needed for test runs.
Ex: https://github.com/avocado-framework-tests/avocado-misc-tests/blob/master/io/disk/ltp_fs.py

**Comment by ldoktor** [comment]
The way I understand `src` dir is to store sources used in test so they can be re-used to verify possible failures. For git-based sources this is probably not necessary as sha can be stored instead, but for arbitrary downloads it might be the only way to see what version was actually used.

Anyway let's ask the guys who introduced it @clebergnu @lmr @adereis

**Comment by narasimhan-v** [comment]
Sure, lets wait for their replies.

Example:

```
# du -sh /var/tmp/avocado_WCjpa4/*
1.9G	 /var/tmp/avocado_WCjpa4/03-avocado-misc-tests_io_disk_ltp_fs.py_Ltp_Fs.test_fs_run_3
1.9G	 /var/tmp/avocado_WCjpa4/04-avocado-misc-tests_io_disk_ltp_fs.py_Ltp_Fs.test_fs_run_4
812M     /var/tmp/avocado_WCjpa4/05-avocado-misc-tests_io_disk_ltp_fs.py_Ltp_Fs.test_fs_run_5

```

For one `ltp_fs` test run, one dir `/var/tmp/avocado_WCjpa4` gets created.
Then, one sub folder per variant gets created.
So, the downloaded files by variant 1 can not be accessed by variant 2.

Is this the way it is expected to work ?

**Comment by ldoktor** [comment]
Absolutely, because the other variant is a different test and could use a different sources. If you want to share the build, you can use `teststmpdir`. Note that `teststmpdir` is not persistent and it's shared among all tests in the job.

Basically if you know which version are you going to use and you are not interested in the downloaded content after the test execution (eg. when you can log the version/hash), I'd suggest using `workdir`. For (small) sources where you might want to be interested in having the sources stored in results, I'd use `srcdir` and for shared resources among multiple tests I'd use `teststmpdir` (with manual backup if necessary).

**Comment by harish-24** [comment]
`workdir` and `srcdir` are working similarly i.e. extracting asset for each variant and building it.
When using `teststmpdir` there is no issues w.r.t tar file. But for zip file, the following issue seems to occur, as 'src' contains the file contents on `os.symlink`
```
Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado_framework-48.0-py2.7.egg/avocado/core/test.py:578
2017-04-18 17:36:02,846 stacktrace       L0044 ERROR| Traceback (most recent call last):
2017-04-18 17:36:02,846 stacktrace       L0044 ERROR|   File "/var/lib/libvirt/images/workspace/runAvocadoFVTTest/avocado-fvt-wrapper/tests/avocado-misc-tests/generic/ltp.py", line 50, in setUp
2017-04-18 17:36:02,846 stacktrace       L0044 ERROR|     archive.extract(tarball, self.teststmpdir)
2017-04-18 17:36:02,846 stacktrace       L0044 ERROR|   File "/usr/lib/python2.7/site-packages/avocado_framework-48.0-py2.7.egg/avocado/utils/archive.py", line 242, in uncompress
2017-04-18 17:36:02,847 stacktrace       L0044 ERROR|     x.extract(path)
2017-04-18 17:36:02,847 stacktrace       L0044 ERROR|   File "/usr/lib/python2.7/site-packages/avocado_framework-48.0-py2.7.egg/avocado/utils/archive.py", line 168, in extract
2017-04-18 17:36:02,847 stacktrace       L0044 ERROR|     self._update_zip_extra_attrs(path)
2017-04-18 17:36:02,847 stacktrace       L0044 ERROR|   File "/usr/lib/python2.7/site-packages/avocado_framework-48.0-py2.7.egg/avocado/utils/archive.py", line 192, in _update_zip_extra_attrs
2017-04-18 17:36:02,847 stacktrace       L0044 ERROR|     os.symlink(src, dst)
2017-04-18 17:36:02,847 stacktrace       L0044 ERROR| OSError: [Errno 36] File name too long
```
@ldoktor Can you help on this?

**Comment by ldoktor** [comment]
@harish-24 would you please report the `zip` issue in a separate issue and provide more details? (especially dir names) It looks unrelated to this thread, but is definitely a valid issue.

**Comment by ldoktor** [comment]
@clebergnu @lmr @adereis guys, can you please provide the details about the original `srcdir` purpose and whether we actually need it?

**Comment by ldoktor** [comment]
Guys, could you please comment on this? @clebergnu @lmr @adereis

**Comment by lmr** [comment]
Indeed, self.srcdir was intended to store test sources, and self.workdir is used for artifacts created as a result of, for example, stuff in self.srcdir being built.

**Comment by lmr** [comment]
I suppose for multiple variants, if the same code base is used among them, the same code base could be copied over, but that seems wasteful. Maybe a simple symlink can be placed in case the source code is the same among all variants.

**Comment by clebergnu** [comment]
IMO, looking at the use cases, `srcdir` is just our attempt to set a policy on what some temporary (work) files mean.  There's no extra value in `srcdir` when compared to `workdir`.  Actually, it seems to cause recurring confusion (myself included).

About `workdir`, there's of course value in it.  Tests frequently need a temporary writable location.  Naming-wise though (a hard task), it could even be seen purely as a temporary dir.  But, I'm not advocating a name change to `tmpdir` or something like it (at least not right now).

**Comment by ldoktor** [comment]
I'd also prefer to keep the `workdir` name, people are used to it. The question is whether `srcdir` is necessary as people can use their `workdir` directly or `teststmpdir` to share the location.

**Comment by clebergnu** [comment]
Yes, I also think `srcdir` provides little to no value.  And with that being flagged and agreed upon, I'd say we can start the deprecation process for it.

**Comment by ldoktor** [comment]
OK, so the answer to this issue would be `srcdir` is not really useful, use `teststmpdir` in case you want to share the files across all tests, or `tmpdir` to work with this test's data only.

**Comment by narasimhan-v** [comment]
Thanks @ldoktor @clebergnu @lmr
