### ISSUE TITLE
avocado throws error while running with local user.

### ISSUE THREAD

**Issue by omps** [avocado-framework/avocado#1925]
```
$ avocado run output_check.sh --output-check-record all
Traceback (most recent call last):
  File "/usr/bin/avocado", line 5, in <module>
    pkg_resources.run_script('avocado-framework==48.0', 'avocado')
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 461, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1188, in run_script
    raise ResolutionError("No script named %r" % script_name)
pkg_resources.ResolutionError: No script named 'avocado'
```

Installed avocado using root user but not able to run it using normal user. Could you please suggest how to fix this.

**Comment by ldoktor** [comment]
Hello @omps, this depends on the method you used to install it. Can you please provide more details on your environment (distribution, pip and python versions) and the steps you used to install Avocado?

**Comment by clebergnu** [comment]
@omps I'm assuming you either fixed or is not able to provide further information on this issue.  If it reappears, please reopen this issue.
