### ISSUE TITLE
Backport CANCEL status to LTS version

### ISSUE THREAD

**Issue by will-Do** [avocado-framework/avocado#1946]
Hi folks,
Now some of tests in tp-libvirt are using the 'CANCEL' status, but as we are using 36lts avocado, backport it is in a high priority. 
But as there are lots of conflicts between these two branches, should I resolve them all manually? or maybe there's a new LTS version will be released soon?

**Comment by apahim** [comment]
Hi @will-Do. `CANCEL` status is a new feature and there's no backport of features to LTS, only bugfixes. The next LTS is **expected** to be the version 52 (no guarantees though). Considering we are about to release the version 49 and the release cycle takes 3-4 weeks, it will not take that long for the next LTS.
I'd recommend you to report the issue in `tp-spice`, so they can keep using alternative methods until you have a new LTS in place. The `self.skip()` is in deprecation process, but it will only be removed after the next LTS.

**Comment by will-Do** [comment]
Thanks @apahim 
I will find a way to deal with it from test provider side.

**Comment by ldoktor** [comment]
@will-Do basically for Avocado-vt tests the recommended way is to use:

```python
from autotest.client.shared import error

raise error.TestNAError("my skip")
```

and all of the `error` exceptions will work until Avocado-vt gets rid of `autotest` dependency and even then we'll have to probably support it in a similar fashion (probably via avocado-vt's module)

**Comment by will-Do** [comment]
@ldoktor 
Yes, that's the original way, but there're already lots of update about getting rid of ```autotest``` from the test provider side(used ```avocado.core.exceptions.SkipError```, then switch to ```test.skip/test.cancel```, so I don't think they want go back to the original way.
We can workaround the problem temporarily, and waiting for the new LTS relases.

**Comment by ldoktor** [comment]
Sure, for now I'd recommend using the `autotest` exceptions and once we release new LTS (which should be in ~2 releases) then you can replace it easily.

**Comment by ldoktor** [comment]
Btw not so long ago we made the `TestError` `TestFail` and `TestCancel` available in `avocado` public API so that would be the simplest replacement (easily automated)

**Comment by ldoktor** [comment]
^^ basically you can replace:

```python
from autotest.client.shared import error
error.TestNAError
```

with
```python
import avocado
avocado.TestCancel
```

**Comment by will-Do** [comment]
@ldoktor Thanks for your suggestion.
What we have to replace is for 36lts is: ```test.cancel(``` to ```test.skip(```.
