### ISSUE TITLE
html report: No data available in table

### ISSUE THREAD

**Issue by luckyh** [avocado-framework/avocado#1971]
There are some new features introduced by https://github.com/avocado-framework/avocado/pull/1967. However, avocado-vt didn't follow the change, as the result, test result items failed to be inserted into html content.

Does anyone have the plan to fix this?

**Comment by luckyh** [comment]
The following `result.tests` content was caught from my vt test.
```python
[{'basedir': None,
  'class_name': 'VirtTest',
  'fail_class': None,
  'fail_reason': None,
  'job_logdir': '...',
  'job_unique_id': '...',
  'logdir': '...',
  'logfile': '...',
  'name': '...',
  'params': None,
  'paused': False,
  'paused_msg': '',
  'running': False,
  'srcdir': '...',
  'status': 'PASS',
  'time_elapsed': 112.8275830745697,
  'time_end': 1493797267.258346,
  'time_start': 1493797154.430763,
  'timeout': '356400',
  'traceback': None,
  'whiteboard': "...",
  'workdir': '...'}]
```

**Comment by apahim** [comment]
@luckyh, checking.

**Comment by luckyh** [comment]
@apahim thanks!

**Comment by apahim** [comment]
@luckyh could you please review https://github.com/avocado-framework/avocado-vt/pull/1002 ?
