### ISSUE TITLE
Problems inheriting from avocado.Test

### ISSUE THREAD

**Issue by caleb-moniot** [avocado-framework/avocado#1978]
I've just started with Avocado and I'm attempting to create a class that inherits from avocado.Test.  Running the test produces an 'Unable to resolve reference(s)' error when attempting to run the test.  

```python
from avocado import Test
from avocado import main


class BaseTest(Test):
    def common_method(self, msg):
        self.log.info(msg)


class TestOne(BaseTest):
    def test(self):
        self.common_method('BaseTest:TestOne')
        value = 1
        self.assertEquals(value, 1)


if __name__ == "__main__":
    main()
```

Running this test through avocado produces the following error. 

*Unable to resolve reference(s) '/usr/share/avocado/tests/BaseTest-TestOne.py' with plugins(s) 'file', 'external', try running 'avocado list -V /usr/share/avocado/tests/BaseTest-TestOne.py' to see the details.*

Removing the BaseTest class and having TestOne inherit from Test seems to work.

```python
from avocado import Test
from avocado import main


class TestOne(Test):
    def test(self):
        self.log.info('Test:TestOne')
        value = 5
        self.assertEquals(value, 5)


if __name__ == "__main__":
    main()
```

*JOB ID     : 55577f67c72ae3bba1154e9eed8c37ea25987791
JOB LOG    : /home/user1/avocado/job-results/job-2017-05-03T18.19-55577f6/job.log
 (1/1) /usr/share/avocado/tests/TestOne.py:TestOne.test: PASS (0.01 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
TESTS TIME : 0.01 s
JOB HTML   : /home/user1/avocado/job-results/job-2017-05-03T18.19-55577f6/html/results.html*

Is there something that I'm overlooking or is this not a supported?

**Comment by apahim** [comment]
Hi @caleb-moniot,
The point is that Avocado does not load the test class before execution, so introspection is not possible. To discover the tests we make static analysis.

So, for those tests that are written in a class not directly inheriting from `avocado.Test`, you have to help Avocado a bit.

Please include the following docstring in your test class:

```python
from avocado import Test
from avocado import main


class BaseTest(Test):
    def common_method(self, msg):
        self.log.info(msg)


class TestOne(BaseTest):
    """
    :avocado: enable
    """
    def test(self):
        self.common_method('BaseTest:TestOne')
        value = 1
        self.assertEquals(value, 1)


if __name__ == "__main__":
    main()
```

--
apahim

**Comment by caleb-moniot** [comment]
Thanks for your quick response @apahim. That was exactly what was missing.
