### ISSUE TITLE
using static test method in Test class causes very cryptic output

### ISSUE THREAD

**Issue by jscotka** [avocado-framework/avocado#1985]
it seems that using static test method in Test class causes very strange error. 
```
14:16 $ cat ./test.py 
from avocado import Test
from avocado import main

class A(Test):

    def testA():
        self.log.info("A")
        pass

if __name__ == "__main__":
    main()

14:17 $ python ./test.py 
found extension EntryPoint.parse('journal = avocado.plugins.journal:JournalResult')
found extension EntryPoint.parse('tap = avocado.plugins.tap:TAPResult')
found extension EntryPoint.parse('human = avocado.plugins.human:Human')
found extension EntryPoint.parse('teststmpdir = avocado.plugins.teststmpdir:TestsTmpDir')
found extension EntryPoint.parse('jobscripts = avocado.plugins.jobscripts:JobScripts')
Command line: ./test.py

Avocado version: 46.0

Config files read (in order):
/etc/avocado/avocado.conf
/etc/avocado/conf.d/gdb.conf
/home/jscotka/.config/avocado/avocado.conf

Avocado config:
Section.Key                             Value
datadir.paths.base_dir                  /usr/share/avocado
datadir.paths.test_dir                  /usr/share/avocado/tests
datadir.paths.data_dir                  /usr/share/avocado/data
datadir.paths.logs_dir                  ~/avocado/job-results
sysinfo.collect.enabled                 True
sysinfo.collect.commands_timeout        -1
sysinfo.collect.installed_packages      False
sysinfo.collect.profiler                False
sysinfo.collect.locale                  C
sysinfo.collectibles.commands           /etc/avocado/sysinfo/commands
sysinfo.collectibles.files              /etc/avocado/sysinfo/files
sysinfo.collectibles.profilers          /etc/avocado/sysinfo/profilers
runner.output.colored                   True
runner.output.utf8                      
remoter.behavior.reject_unknown_hosts   False
remoter.behavior.disable_known_hosts    False
job.output.loglevel                     debug
restclient.connection.hostname          localhost
restclient.connection.port              9405
restclient.connection.username          
restclient.connection.password          
plugins.disable                         []
plugins.skip_broken_plugin_notification []
plugins.loaders                         ['file', '@DEFAULT']
gdb.paths.gdb                           /usr/bin/gdb
gdb.paths.gdbserver                     /usr/bin/gdbserver

Avocado Data Directories:

Avocado replaces config dirs that can't be accessed
with sensible defaults. Please edit your local config
file to customize values

base     /home/jscotka/avocado
tests    /usr/share/avocado/tests
data     /home/jscotka/avocado/data
logs     /home/jscotka/avocado/job-results

Temporary dir: /tmp/avocado_uQg0R6

Variant 1:    /

Job ID: 5a4d634bc8d96aa37bc3197729e14ac25d7a6d53

PARAMS (key=timeout, path=*, default=None) => None
START 1-./test.py:A.testA

Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado/core/test.py:488
TypeError: testA() takes no arguments (1 given)

Local variables:
Traceback (most recent call last):

  File "/usr/lib/python2.7/site-packages/avocado/core/test.py", line 494, in _run_avocado
    local_vars = inspect.trace()[1][0].f_locals

IndexError: list index out of range

ERROR 1-./test.py:A.testA -> IndexError: list index out of range

Test results available in /tmp/avocado_avocado.core.job2bTjxG
```

**Comment by lmr** [comment]
It seems like you forgot to add the `@staticmethod` decorator to the function. Also, how are you supposed use `self.log`on a static method?

**Comment by lmr** [comment]
So since you missed the staticmethod decorator, the class instance is being passed as the first argument of the method, causing the error. The bug description is misleading, when I read the summary my first thought was that a test with correct code was triggering the behavior, when it's not the case.

**Comment by lmr** [comment]
So the intended code would be

    from avocado import Test
    from avocado import main
    import logging

    class A(Test):

        @staticmethod
        def testA():
            log = logging.getLogger('avocado.tests')
            log.info("A")

    if __name__ == "__main__":
        main()

Which passes just fine:

    ...
    PARAMS (key=timeout, path=*, default=None) => None
    START 1-mytest.py:A.testA
    A
    PASS 1-mytest.py:A.testA

**Comment by clebergnu** [comment]
@jscotka I think you just missed the `self` parameter to `testA`, which is the most common way of writing Avocado tests.

**Comment by jscotka** [comment]
no, I l know that I've missed (self) inside test metdhond by mistake.
It also failed in case there was  print "A" instead of  self.log.info("A").

I'm just wondering that this is very cryptic bug, not about using some decorators like @staticmethod, at least in traceback probably there could be provided this help like please use decorator: ` @staticmethod`

**Comment by lmr** [comment]
The error message is actually very correct:

    TypeError: testA() takes no arguments (1 given)

And that's how python will error out. It does require a bit of python knowledge to understand the message, but it's 100% clear provided that you know how arguments are passed to methods in python classes.

I suppose we can add some extra help on top of what python provides, but that seems very error prone and hard to do right. I'd say it's not worth implementing the mentioned extra help.

**Comment by clebergnu** [comment]
IMO, this is pretty accurate:

```
Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado/core/test.py:488
TypeError: testA() takes no arguments (1 given)
```

It's the same Python error you'd get when running the same type of code outside of Avocado.  Anyway, our docs can be more explicit about the signature of the test functions here:

http://avocado-framework.readthedocs.io/en/49.0/WritingTests.html#what-is-an-avocado-test

**Comment by clebergnu** [comment]
I created a card to track this:

https://trello.com/c/1dGWBED5/1023-document-test-functions-signatures

@jscotka I'm closing this one and we'll track it on Trello.  Thanks for reporting it.

**Comment by jscotka** [comment]
I'm not sure. I've tested code and it works pretty well
```
class A(object):

    def testA(self):
        print ("A")
        pass

a=A()
a.testA()
```

**Comment by clebergnu** [comment]
@jscotka sure, you have a method **and** the `self` parameter there.  Your other option is to have a static method (and mark it as such), then you can drop the "self" parameter.

In the following example, `testA` and `testB` will **not** work:

```
class A(object):
   def testA():
      print("A")
      pass

   @staticmethod
   def testB(self):
      print("B")
      pass

a = A()
a.testA()
a.testB()
```

**Comment by clebergnu** [comment]
@jscotka the whole point is, you **original** example is broken:

```
class A(Test):

    def testA():
        self.log.info("A")
        pass
```

This won't work on a basic Python (object) class, nor unittest.TestCase or any other type of class.  `testA` here is a method, and **requires** the `self` parameter. Period.

Please address **this** comment, because I feel this simple point is being missed.
