### ISSUE TITLE
RFE: append results to previous job

### ISSUE THREAD

**Issue by jscotka** [avocado-framework/avocado#2003]
please provide option like --append to avocado what allows extend previous job result
Discussed with @ldoktor personally.

**Comment by ldoktor** [comment]
Basically the way I understood it is that you have several tests that are not necessary part of one job, but you'd like to report them together. There are two (basic) ways, we can either support merging results, or allow extending the job.

The first one would be really tricky as the tests are order-dependent (they have serial numbers) and such merge would either have to change them, or it could potentially generate clashes.

The second one could be quite simple and the way I imagine it in my head is that you'd execute a job:

```
avocado run sleeptest.py
JOB ID     : fd5d34c48758b6adb003a467c6c1a89e8320e922
JOB LOG    : /home/medic/avocado/job-results/job-2017-05-16T15.46-fd5d34c/job.log
 (1/1) sleeptest.py:SleepTest.test: PASS (1.02 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 1.23 s
JOB HTML   : /home/medic/avocado/job-results/job-2017-05-16T15.46-fd5d34c/html/results.html
```

and later (even on a different machine using different Avocado or whatever) you would run:

```
avocado run --extend fd5d3 passtest.py -m my.yaml
JOB ID     : 0e05ef134e4ae590ec4678b98e9953fd372a4ea8
SRC JOB ID : fd5d34c48758b6adb003a467c6c1a89e8320e922
JOB LOG    : /home/medic/avocado/job-results/job-2017-05-16T15.46-0e05ef1/job.log
 (1/3) sleeptest.py:Sleeptest.test: PASS (1.02s)
 (2/3) passtest.py:PassTest.test;foo-cff6: PASS (0.01 s)
 (3/3) passtest.py:PassTest.test;bar-e20f: PASS (0.01 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 1.57 s
JOB HTML   : /home/medic/avocado/job-results/job-2017-05-16T15.46-0e05ef1/html/results.html
```

Where the previously existing tests would not be executed, only reported and restuls would be copied over to the new results.

One remaining question is regarding sysinfo collection, I don't think it should be executed pre, but only post job.

Does this fit your needs, @jscotka?

**Comment by jscotka** [comment]
Hi,
sure that fits what I want. The solution that results are copied from mentioned job is perfect. 
I can imagine when when used this parameter for exteding results. just post sysinfo is scheduled, and pre is copied from previous job.

otherwise I would like to have option to use some relative adress like "--extend latest" than some ID, what I have to automatically parse from output. (yes I know I can also dereference symbolic link to latest but it is not so confortable as used some relative name like "latest")

**Comment by ldoktor** [comment]
Sure they should share the `replay` logic, so either full/partial id, latest or path_to_the_results should be acceptable. Also note that you can use `--force-job-id` to set job id (to avoid parsing the output).

Anyway I'll bring this to our next scrum meeting and we'll discuss whether this is acceptable.

**Comment by ldoktor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [RFC: Append results to previous job](https://trello.com/c/Dn5Z9eOi/1039-rfc-append-results-to-previous-job)

**Comment by ldoktor** [comment]
@jscotka there is a trello card so it will get implemented once the priority reaches the top (feel free to vote there).
