### ISSUE TITLE
reconsider which version lands in fedora

### ISSUE THREAD

**Issue by jscotka** [avocado-framework/avocado#2005]
Hi,
I've found issue, that in fedora 25 there is still old version (0.46) and as we've discussed with @ldoktor there could be LTS version, because fedora allows bug fixing.
I vote for rebasing until EOL of fedora but in case it is not allowed, the better solution is to have there LTS version
    Regards
    Honza

**Comment by ldoktor** [comment]
@mmathesius IIRC you were talking about rebasing the library per release, but it looks like only F27 is updated. Was it not possible to do? If so perhaps we should use the next LTS as a base and from time to time send bugfixes (perhaps we can even synchronize our LTS releases to - every other - Fedora release, but this is just a brainstorm).

@clebergnu @apahim this might be interesting to you as well...

**Comment by mmathesius** [comment]
I've been keeping Rawhide up to date just to keep the package current with the regular Avocado releases. There should be no reason the updates couldn't also be pushed to the other current versions of Fedora, there just didn't seem to be a demand for it. Apparently there is. Should I start the update process for 49.0--or wait for 50.0 at this point?

I've also given a small amount of consideration to packaging the upcoming LTS release for Fedora. But as far as I know, it would need to packaged under a different name to avoid conflicting with the regular releases. `python#-avocado-lts`, perhaps?

**Comment by clebergnu** [comment]
50.0 will be out later Today, so I'd suggest waiting for it.

As for multiple versions of a given package on Fedora, it will indeed require a different name.  I guess the naming format you're proposing (`python#-avocado-lts`) is pretty sane, so +1 on that.

**Comment by jscotka** [comment]
+1 for that solution, have in version fedora as last as possibe with same name of rpm and -lts for LTS version of avocado.
Thanks a lot

**Comment by mmathesius** [comment]
I just committed and built python-avocado-50.0-1 for F24, F25, F26, and Rawhide. I have also submitted it as an update for F24, F25, and F26--so expect to see it in the testing repos soon.

**Comment by clebergnu** [comment]
Awesome @mmathesius! Thanks! I guess we can close this issue since Merlin will (I assume) keep updating `python#-avocado` until the introduction of `python#-avocado-lts`.
