### ISSUE TITLE
RFE utils: append clever timeout/retry/delay decorators

### ISSUE THREAD

**Issue by jscotka** [avocado-framework/avocado#2006]
Would you be interested in adding https://github.com/cockpit-project/cockpit/blob/master/test/avocado/timeoutlib.py to your `avocado.utils`? It allows you to use decorators like: 

```python
    @Retry(attempts=5, timeout=5, error=IFailedError('Too many retries!'), delay=20)
```

**Comment by clebergnu** [comment]
@jscotka and another thanks for the PR on this.  I'm closing this issue so we can focus on the PR only.

**Comment by jscotka** [comment]
Thanks a lot @clebergnu
