### ISSUE TITLE
RFE utils: add network simulation library

### ISSUE THREAD

**Issue by jscotka** [avocado-framework/avocado#2007]
It would be nice to have there some library allows simulate ethernet devices and connect them together,
see my code in cockpit:
https://github.com/cockpit-project/cockpit/blob/master/test/avocado/libnetwork.py

**Comment by apahim** [comment]
@jscotka seems like you've done most of the work already. Could you please port the code to Avocado utils and propose as a Pull Request?

**Comment by jscotka** [comment]
Hi, yep, I'm done with that for cockpit and it works well. 
Unfortunatelly I do not have time now to improve it for avocado, or repair that via PR reviews to satisfy avocado coding style or guidelines.
 
I can do initial PR for you if you want, in case somebody will then take care about that and finish PR on top of my PR.

Otherwise I don't have time for next month or two, then, we'll see, maybe I'll do that.

**Comment by jscotka** [comment]
Hi,
I've created initial version of network simulation library:
https://github.com/avocado-framework/avocado/pull/2056

**Comment by clebergnu** [comment]
@jscotka thanks a lot for sending that PR.  I'll close this issue while we focus on the PR only.
