### ISSUE TITLE
RFE utils: add disc simulation library

### ISSUE THREAD

**Issue by jscotka** [avocado-framework/avocado#2008]
It would be nice to have there some library allows simulate disc devices,
see my code in cockpit:
https://github.com/cockpit-project/cockpit/blob/master/test/avocado/libdisc.py
It allows to use loopback devices as simple solution, or it uses iSCSI target/initiator for more realistic disc simulation.

**Comment by apahim** [comment]
@jscotka seems like you've done most of the work already. Could you please port the code to Avocado utils and propose as a Pull Request?

**Comment by ldoktor** [comment]
@jscotka there is a PR associated with this, it just needs some love. Do you use this library? Can you please take a look at it and respond with v3?

**Comment by willianrampazzo** [comment]
It has been some years since this issue does not have any activity. I'm closing it. If it is still needed, feel free to reopen.
