### ISSUE TITLE
pip installation of avocado does not work on CentOS6

### ISSUE THREAD

**Issue by jscotka** [avocado-framework/avocado#2027]
Avocado installation on CentOS6 does not work well, at least pip installation:
```
[root@qeos-158 ~]# yum  --enablerepo=epel install python-pip
...
Installed:
  python-pip.noarch 0:7.1.0-1.el6                                               

Complete!

[root@qeos-158 ~]# pip install avocaod-framework
...
  Downloading avocado-framework-50.0.tar.gz (648kB)
    100% |████████████████████████████████| 651kB 658kB/s 
Collecting stevedore>=1.8.0 (from avocado-framework)
  Downloading stevedore-1.21.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): six>=1.9.0 in /usr/lib/python2.6/site-packages (from stevedore>=1.8.0->avocado-framework)
Collecting pbr>=2.0.0 (from stevedore>=1.8.0->avocado-framework)
  Downloading pbr-3.0.1-py2.py3-none-any.whl (99kB)
    100% |████████████████████████████████| 102kB 2.3MB/s 
Installing collected packages: pbr, stevedore, avocado-framework
  Running setup.py install for avocado-framework
Successfully installed avocado-framework-50.0 pbr-3.0.1 stevedore-1.21.0

[root@qeos-158 ~]# avocado run /bin/true
Avocado crashed unexpectedly: 'module' object has no attribute 'NullHandler'
You can find details in /tmp/avocado-traceback-2017-05-23_02:39:42-Bhg_Bz.log

[root@qeos-158 ~]# cat /tmp/avocado-traceback-2017-05-23_02:39:42-Bhg_Bz.log
Avocado crashed:
Traceback (most recent call last):
  File "/usr/bin/avocado", line 71, in <module>
    from avocado.core.app import AvocadoApp
  File "/usr/lib/python2.6/site-packages/avocado/__init__.py", line 28, in <module>
    from avocado.core.job import main
  File "/usr/lib/python2.6/site-packages/avocado/core/job.py", line 32, in <module>
    from . import dispatcher
  File "/usr/lib/python2.6/site-packages/avocado/core/dispatcher.py", line 21, in <module>
    from stevedore import EnabledExtensionManager
  File "/usr/lib/python2.6/site-packages/stevedore/__init__.py", line 23, in <module>
    LOG.addHandler(logging.NullHandler())
AttributeError: 'module' object has no attribute 'NullHandler'

[root@qeos-158 ~]# cat /etc/redhat-release 
CentOS release 6.9 (Final)
```

**Comment by ldoktor** [comment]
Could you please specify which pytohn version are you using? I don't think there is python 2.7+ on Centos6 and Avocado 50 requires 2.7+. You should be a ble to use the 36lts (`avocado-framework<34.0`).

**Comment by jscotka** [comment]
yep, that is possible. 
Isn't that possible to somehow fix, that pip install avocado-framework will install older version when on system there is just python2.6?
This could cause compatibility troubles. when using pip and avocado. (I should not care which version of avocado is for my system. Pip could solve that for me)

**Comment by clebergnu** [comment]
@jscotka I've enabled the listing for the LTS version too:

https://pypi.python.org/pypi/avocado-framework

In our source code, we state that Python 2.7 is required for newer releases:

https://github.com/avocado-framework/avocado/blob/master/setup.py#L175

But it looks like pip can't be made aware of that.  Also, there's the possibility of marking one file as Python version dependent but it looks like this is for binary archives, and not for source files.  Do you know more than we do here?  We'd love for pip to auto select the *right* version for users.

**Comment by jscotka** [comment]
I have no idea how to do that. I just though that pip could know how to select proper version for proper version of system, based on python version :-)

I've found that because there were discussion to use python 3  for avocado and it was argued that there is support for RHEL6 and it does not contain proper python version.
So I'm not sure with conclusion. if support of RHEL6 will be removed in few years, or there will be still some version via pip epel able to install in RHEL/CentOS6

Probably should be supported for whole lifecycle of RHEL6 and fixing security issues if any.

**Comment by clebergnu** [comment]
That's the point of LTS, with longer support cycles.  For information on lifecycle:

http://avocado-framework.readthedocs.io/en/latest/rfcs/LongTermStability.html

Now, is using a version modifier on EL6 a blocker for you?  For me running this works pretty well:

```
$ pip install stevedore 
Collecting stevedore
  Using cached stevedore-1.21.0-py2.py3-none-any.whl
Collecting pbr>=2.0.0 (from stevedore)
  Downloading pbr-3.0.1-py2.py3-none-any.whl (99kB)
    100% |████████████████████████████████| 102kB 824kB/s 
Requirement already satisfied: six>=1.9.0 in ./lib/python2.7/site-packages (from stevedore)
Installing collected packages: pbr, stevedore
Successfully installed pbr-3.0.1 stevedore-1.21.0

$ pip install 'avocado-framework<=37.0' 
Collecting avocado-framework<=37.0
  Downloading avocado-framework-36.4.tar.gz (711kB)
    100% |████████████████████████████████| 716kB 7.2MB/s 
  Running setup.py (path:/tmp/pip-build-WIRkWa/avocado-framework/setup.py) egg_info for package avocado-framework produced metadata for project name avocado. Fix your #egg=avocado-framework fragments.
  Requirement already satisfied (use --upgrade to upgrade): avocado from https://pypi.python.org/packages/81/9c/e62566cab3975abed498affcebc8b2d29a4cb403ad55c70c571252c26f94/avocado-framework-36.4.tar.gz#md5=42eb6f057b9518f7d04ab74cc269fd21 in ./lib/python2.7/site-packages
```

Another example is @Andrei-Stepanov, he has installation scripts using pip in which he chooses either LTS or a regular release.

With regards to Python 3, that's where we want to go.  And it's pretty hard (or at the very least a misuse of resources) to try to support Python 2.6, 2.7 and 3.x on the same code base.

Let me know if this is understood and if you can install Avocado 36.X from pip using the version selector above.

**Comment by clebergnu** [comment]
@jscotka actually, on a EL6 box, I can reproduce your issue with `NullHandler`:

```
$ pip install 'avocado-framework<=37.0' 
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
Collecting avocado-framework<=37.0
  Using cached avocado-framework-36.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-aXYOf2/avocado-framework/setup.py", line 22, in <module>
        from avocado import VERSION
      File "avocado/__init__.py", line 19, in <module>
        from avocado.core.job import main
      File "avocado/core/job.py", line 33, in <module>
        from . import dispatcher
      File "avocado/core/dispatcher.py", line 19, in <module>
        from stevedore import ExtensionManager
      File "/tmp/lts/lib/python2.6/site-packages/stevedore/__init__.py", line 23, in <module>
        LOG.addHandler(logging.NullHandler())
    AttributeError: 'module' object has no attribute 'NullHandler'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-aXYOf2/avocado-framework/
```

Let me check what's going on here.

**Comment by clebergnu** [comment]
It was indeed a stevedore problem:

```
File "/tmp/lts/lib/python2.6/site-packages/stevedore/__init__.py", line 23, in <module>
        LOG.addHandler(logging.NullHandler())
    AttributeError: 'module' object has no attribute 'NullHandler'
```

You need to use a version also compatible with Python 2.6. I suggest:

```
$ pip install 'stevedore==0.14'
```

**Comment by ldoktor** [comment]
Basically those are all pip issues. Every since we dropped 2.6 compatibility our `setup.py` says that and in 36lts we use `stevedore>=1.8.0,<=1.10.0; python_version < '2.7'` to select the right stevedore version. One think you can try is using `pip install pip --upgrade` to see whether the issue was fixed in later versions.

Anyway please use `avocado-framework<37.0` to get the latest 36.4 version (at this time, others might follow) and if the stevedore issue won't improve by using the latest pip please install `stevedore<=1.10.0` before installing avocado. That should give you solid base to run your tests, perhaps not with all the latest features, but fully functional on python 2.6. (bug reports are treated as high priority for about 6 months after the next lts release).

Can you please confirm this solution works for you?

**Comment by jscotka** [comment]
it is not blocking me at all. I'm using version from your repositories for rhel6 and it works well.
I've just tested also installation avocado via pip on rhel6 and I've met this issue.

So yep as you mentioned there exist lots of workarounds what improves that and fix the issue, but as you mentioned probably it is not possible to fix this issue directly on pip. (install proper version of avocado and libraries dependent on python version or version of system)

BTW I've tried one of solution: 
pip install --upgrade "avocado-framework<=37.0" 
but it failed too :-) because of missing modules `logutils` and `unittest2`
```
ollecting avocado-framework<37.0
  Using cached avocado-framework-36.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-8E2BMK/avocado-framework/setup.py", line 22, in <module>
        from avocado import VERSION
      File "avocado/__init__.py", line 19, in <module>
        from avocado.core.job import main
      File "avocado/core/job.py", line 34, in <module>
        from . import runner
      File "avocado/core/runner.py", line 28, in <module>
        from . import test
      File "avocado/core/test.py", line 31, in <module>
        from . import multiplexer
      File "avocado/core/multiplexer.py", line 27, in <module>
        from . import tree
      File "avocado/core/tree.py", line 53, in <module>
        from . import output
      File "avocado/core/output.py", line 31, in <module>
        import logutils
    ImportError: No module named logutils
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-8E2BMK/avocado-framework
```

**Comment by ldoktor** [comment]
OK, downloading RHEL.6 to give it a try. When using from sources, one should use `requirements.txt` but IIRC they are not applied when using from pip. We added the basic requirements not that long ago to `setup.py`, but it was not reflected in 36lts so perhaps we can do better...

**Comment by ldoktor** [comment]
We decided not to backport this to 36lts as it's a new feature and the new 51lts already tackles this.
