### ISSUE TITLE
RFE: Make avocado plugins more readable

### ISSUE THREAD

**Issue by Andrei-Stepanov** [avocado-framework/avocado#2055]
avocado plugins lists all available plugins.

The output list is divided in subcategories:

Plugins that add new commands (cli.cmd):
xxx
Plugins that run before/after the execution of jobs (job.prepost):
yyy
Plugins that generate job result based on job/test events (result_events):
zzz
Plugins that generate test variants (varianter): 
aaa

I propose to make this sub-categories more easy for reading. (For example add an empty line between categories.)

Now all categories are one list. Not easy to navigate and find necessary module.

**Comment by clebergnu** [comment]
@Andrei-Stepanov I agree with your suggestion.  Please find implementation in #2064
