### ISSUE TITLE
I'm getting a wrong font weight from Sketch

### ISSUE THREAD

**Issue by whoiskjl** [avocado-framework/avocado#2081]
![screen shot 2017-06-20 at 2 30 22 pm](https://user-images.githubusercontent.com/1874874/27349484-6c512078-55c5-11e7-9244-965a1cf7db2d.png)

It should be 600 not 300. It even says demi

**Comment by clebergnu** [comment]
@whoiskjl this is not realted to this project (Avocado), right?

**Comment by lmr** [comment]
Wrong project, I'm closing this

**Comment by whoiskjl** [comment]
I'm sorry! wrong project!
