### ISSUE TITLE
Can no longer install avocado version 49.0

### ISSUE THREAD

**Issue by UnitasBrooks** [avocado-framework/avocado#2122]
For the past few months we have been installing avocado version 49 like so:
```
yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
curl https://repos-avocadoproject.rhcloud.com/static/avocado-el.repo -o /etc/yum.repos.d/avocado.repo
yum install -y python-avocado-49.0-0.el7.centos.noarch
yum install -y python-avocado-plugins-output-html-49.0-0.el7.centos.noarch
```

It used to work fine, now we are getting automatically upgraded to 52.0
```
Package python-avocado-plugins-output-html is obsoleted by python2-avocado-plugins-output-html, trying to install python2-avocado-plugins-output-html-52.0-1.el7.noarch instead
Resolving Dependencies
--> Running transaction check
---> Package python2-avocado-plugins-output-html.noarch 0:52.0-1.el7 will be installed
```

We can still download 47.0 which may work for us, but will that eventually be obsoleted as well? The big breaking change was the mux-to-yaml module being renamed/going away. 

*EDIT*

Looks like I was mistaken 47 gets redirected as well, this is a pretty breaking thing for us currently, I really appreciate your help in advance!

**Comment by clebergnu** [comment]
@UnitasBrooks can you please check if this is "redirection" or is just a package selection based on the enabled repos?

What has recently happened is that Avocado was added to EPEL7.  I have to check which version is active there, but in theory, you could have it insta

**Comment by clebergnu** [comment]
If you have all the deps (and some come from EPEL 7), you can still install Avocado 49.0 with:

```
# yum --disablerepo=* --enablerepo=avocado install python-avocado-49.0-0.el7.centos.noarch python-avocado-plugins-output-html-49.0-0.el7.centos.noarch
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
Resolving Dependencies
--> Running transaction check
---> Package python-avocado.noarch 0:49.0-0.el7.centos will be installed
---> Package python-avocado-plugins-output-html.noarch 0:49.0-0.el7.centos will be installed
--> Finished Dependency Resolution

Dependencies Resolved

=======================================================================================================================================
 Package                                           Arch                  Version                          Repository              Size
=======================================================================================================================================
Installing:
 python-avocado                                    noarch                49.0-0.el7.centos                avocado                423 k
 python-avocado-plugins-output-html                noarch                49.0-0.el7.centos                avocado                 95 k

Transaction Summary
=======================================================================================================================================
Install  2 Packages

Total download size: 519 k
Installed size: 1.9 M
Is this ok [y/d/N]:y
Downloading packages:
(1/2): python-avocado-plugins-output-html-49.0-0.el7.centos.noarch.rpm                                          |  95 kB  00:00:00     
(2/2): python-avocado-49.0-0.el7.centos.noarch.rpm                                                              | 423 kB  00:00:01     
---------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                  342 kB/s | 519 kB  00:00:01     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : python-avocado-49.0-0.el7.centos.noarch                                                                             1/2 
  Installing : python-avocado-plugins-output-html-49.0-0.el7.centos.noarch                                                         2/2 
  Verifying  : python-avocado-plugins-output-html-49.0-0.el7.centos.noarch                                                         1/2 
  Verifying  : python-avocado-49.0-0.el7.centos.noarch                                                                             2/2 

Installed:
  python-avocado.noarch 0:49.0-0.el7.centos                python-avocado-plugins-output-html.noarch 0:49.0-0.el7.centos               

Complete!
```

**Comment by clebergnu** [comment]
I can quickly answer the question about the installation method (and I'll defer the investigation of the jobdata/variants error).  In thoery, all releases within the 52.X major release should bring *no* breakage.  LTS will only contain critical bug fixes, so it should be safe (and desirable) to use:

```
avocado-framework<53.0
avocado-framework-plugin-result-html<53.0
avocado-framework-plugin-varianter-yaml-to-mux<53.0
```

More info here: http://avocado-framework.readthedocs.io/en/52.0/rfcs/LongTermStability.html#deployment-details

**Comment by UnitasBrooks** [comment]
Ok thanks for your help, would you like me to open a new ticket regarding the variants error? Or will someone else stop by on this ticket?

**Comment by clebergnu** [comment]
@UnitasBrooks Yes, please open another issue!

**Comment by UnitasBrooks** [comment]
I am now getting a 503 installing the way we previously discussed:

yum --disablerepo=* --enablerepo=avocado install python-avocado-49.0-0.el7.centos.noarch py

Loaded plugins: fastestmirror, ovl
https://repos-avocadoproject.rhcloud.com/static/epel-7-noarch/repodata/repomd.xml: [Errno 14] HTTPS Error 503 - Service Unavailable
Trying other mirror.
https://repos-avocadoproject.rhcloud.com/static/epel-7-noarch/repodata/repomd.xml: [Errno 14] HTTPS Error 503 - Service Unavailable
Trying other mirror.
https://repos-avocadoproject.rhcloud.com/static/epel-7-noarch/repodata/repomd.xml: [Errno 14] HTTPS Error 503 - Service Unavailable
Trying other mirror.
https://repos-avocadoproject.rhcloud.com/static/epel-7-noarch/repodata/repomd.xml: [Errno 14] HTTPS Error 503 - Service Unavailable
Trying other mirror.
https://repos-avocadoproject.rhcloud.com/static/epel-7-noarch/repodata/repomd.xml: [Errno 14] HTTPS Error 503 - Service Unavailable
Trying other mirror.
https://repos-avocadoproject.rhcloud.com/static/epel-7-noarch/repodata/repomd.xml: [Errno 14] HTTPS Error 503 - Service Unavailable
Trying other mirror.
https://repos-avocadoproject.rhcloud.com/static/epel-7-noarch/repodata/repomd.xml: [Errno 14] HTTPS Error 503 - Service Unavailable
Trying other mirror.
https://repos-avocadoproject.rhcloud.com/static/epel-7-noarch/repodata/repomd.xml: [Errno 14] HTTPS Error 503 - Service Unavailable
Trying other mirror.
https://repos-avocadoproject.rhcloud.com/static/epel-7-noarch/repodata/repomd.xml: [Errno 14] HTTPS Error 503 - Service Unavailable
Trying other mirror.
https://repos-avocadoproject.rhcloud.com/static/epel-7-noarch/repodata/repomd.xml: [Errno 14] HTTPS Error 503 - Service Unavailable
Trying other mirror.

Is this a known issue?

**Comment by clebergnu** [comment]
@UnitasBrooks yes, and we're dealing with it.  Sorry for the trouble it may be causing.

**Comment by UnitasBrooks** [comment]
Thanks @clebergnu.

**Comment by clebergnu** [comment]
@UnitasBrooks I've set up a temporary repo until we've the original one fixed:

http://18.222.0.242/avocado-el.repo
http://18.222.0.242/avocado-fedora.repo

**Comment by ldoktor** [comment]
I believe this was addressed. Note that there is a new server so let us know if anything goes wrong...
