### ISSUE TITLE
Respect ~/.ssh/config configuration when running tests on remote hosts

### ISSUE THREAD

**Issue by mopsfelder** [avocado-framework/avocado#2141]
That would be great if settings under `~/.ssh/config` were respected when running tests on remote hosts.

Some useful scenarios of this feature would be when:
- remote host needs a bastion host configured;
- remote host needs different ssh key;
- remote host needs any specific ssh option configured.

As an example, consider the following `~/.ssh/config` snippet:

```
Host myguest
    HostName 192.168.1.100
    ProxyCommand ssh -q -l root bastionhost.domain.tld nc %h %p 2> /dev/null
```

Then, to run tests against *myguest*, I'd execute:

    avocado run --remote-hostname myguest --remote-username root passtest.py

And avocado would be able to run remote tests on *myguest*, which is reachable when using ssh ProxyCommand option.

Thanks!

**Comment by apahim** [comment]
https://trello.com/c/MTwJGSFQ/1095-respect-ssh-config-configuration-when-running-tests-on-remote-hosts

**Comment by apahim** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Respect ~/.ssh/config configuration when running tests on remote hosts](https://trello.com/c/MTwJGSFQ/1095-respect-ssh-config-configuration-when-running-tests-on-remote-hosts)

**Comment by mopsfelder** [comment]
Awesome!  Thank you, @ldoktor!  :1st_place_medal:

**Comment by ldoktor** [comment]
You're welcome, but send the thanks to Fabric guys, I just enabled it...
