### ISSUE TITLE
Django

### ISSUE THREAD

**Issue by mbhagavathula** [avocado-framework/avocado#2185]
Is there any web support in django like auto test?

**Comment by clebergnu** [comment]
I don't think I understand your question.  Autotest has a server component written used Django.  Avocado actually has a results server (mostly experimental):

https://github.com/avocado-framework/avocado-server

Also written using Django.  Does this answer your question?

**Comment by mbhagavathula** [comment]
thanks for pointing me to avocado server.  Can it run on python 3.5 ?

**Comment by clebergnu** [comment]
I don't think it will run out of the box on Python 3.  You could try and
let us know (patches are welcome).

**Comment by clebergnu** [comment]
@mbhagavathula I think we've answered your question, so I'm closing this issue.  If you any other questions, please let us know.
