### ISSUE TITLE
Ubuntu

### ISSUE THREAD

**Issue by mbhagavathula** [avocado-framework/avocado#2186]
How to install  Avacodo on ubuntu 16.04

**Comment by clebergnu** [comment]
Have you tried following these instructions:

http://avocado-framework.readthedocs.io/en/53.0/GetStartedGuide.html#installing-from-standard-python-tools 

If you have any issues, please reopen this issue.

**Comment by mbhagavathula** [comment]
thanks i installed however I am getting an error
root@localhost:/opt/avocado# avocado list
Test discovery plugin <avocado.core.loader.FileLoader object at 0x7f10049a5630> failed: 'utf-8' codec can't decode byte 0xf2 in position 10: invalid continuation byte

**Comment by clebergnu** [comment]
This looks like a Python 3 issue.  Avocado still needs some extra work to
fully work under Python 3.  Is that a requirement for you? If not, you
could try installing it under Python 2.
