### ISSUE TITLE
Failed to load plugin from module "avocado_runner_remote"

### ISSUE THREAD

**Issue by kryptek** [avocado-framework/avocado#2199]
Seems like the commit from 23 days ago might have broken this plugin. I installed it and when I run `avocado plugins`, it spews the following error:

```bash
Failed to load plugin from module "avocado_runner_remote": ImportError('cannot import name TestID',)
```

**Comment by clebergnu** [comment]
@kryptek the same commit (a67b2fb4f1bc2ddbf85caec26e80e8aa81f1d387) also renamed the import on the avocado_runner_remote module: 

```diff
diff --git a/optional_plugins/runner_remote/avocado_runner_remote/__init__.py b/optional_plugins/runner_remote/avocado_runner_remote/__init__.py
index b77e8716..0979fd9e 100644
--- a/optional_plugins/runner_remote/avocado_runner_remote/__init__.py
+++ b/optional_plugins/runner_remote/avocado_runner_remote/__init__.py
@@ -37,7 +37,7 @@ from avocado.core.output import LOG_JOB, LOG_UI
 from avocado.core.plugin_interfaces import CLI
 from avocado.core.runner import TestRunner
 from avocado.core.settings import settings
-from avocado.core.test import TestName
+from avocado.core.test import TestID
 from avocado.utils import archive
 from avocado.utils import astring
 from avocado.utils import process
@@ -507,7 +507,7 @@ class RemoteTestRunner(TestRunner):
                 name = [name[0]] + name[1].split(';')
                 if len(name) == 3:
                     name[2] = {"variant_id": name[2]}
-                name = TestName(*name, no_digits=-1)
+                name = TestID(*name, no_digits=-1)
                 state = dict(name=name,
                              time_elapsed=tst['time'],
                              time_start=tst['start'],
```

Maybe you're running a different combination of "core" Avocado and "runner_remote" plugin?

**Comment by kryptek** [comment]
Good point; I was just pip installing the framework and then i cloned the repo at HEAD to install the plugin. Is there a more proper way of doing that?

**Comment by clebergnu** [comment]
Yes, there is:

https://pypi.python.org/pypi/avocado-framework-plugin-runner-remote/53.0

That reminds me that we should also list those plugins at:

http://avocado-framework.readthedocs.io/en/53.0/GetStartedGuide.html#installing-from-standard-python-tools

**Comment by clebergnu** [comment]
@kryptek PR #2200 takes care of this, hopefully eliminating further confusion.  Please let me know if we can be of more assistance.  If you don't consider this solved, please reopen this issue.  And thanks for reporting that issue.
