### ISSUE TITLE
why this is "<" not ">" ?

### ISSUE THREAD

**Issue by zhangliang4418** [avocado-framework/avocado#2275]
https://github.com/avocado-framework/avocado/blob/d1503a1dcfe684a1b6ab03fd79546eb0f2bfb511/optional_plugins/runner_remote/avocado_runner_remote/__init__.py#L107

**Comment by zhangliang4418** [comment]
if "<", only loop once times.

**Comment by apahim** [comment]
Yep, a bug. Are sending the fix?

**Comment by zhangliang4418** [comment]
OK，thx，I‘ll send bug fix lately。
