### ISSUE TITLE
how can i display my results on html or other result document?

### ISSUE THREAD

**Issue by wellfrogliu** [avocado-framework/avocado#2282]
hello, i am a newer, i want to display some results on the html. For example, i test a ssd with avocado, i want to put results such as speed of wr/rd, bad block. but i don't find the solution. thank u.

**Comment by lmr** [comment]
The HTML report wasn't designed to display such results in it. Just use the logs for that.

**Comment by apahim** [comment]
Hey, welcome!

Not sure I got you question. Are you intending to change the HTML report format? If yes, that's not supported. But any log you generate inside your test can be seen on HTML report.

For instance, take a look at this test::

```python
from avocado import Test

class MyClass(Test):

    def test(self):
        stats = 123123123
        self.log.info('Here are the SSD stats: %s' % stats)
```
Here's the logged line:

![output_hswtlp](https://user-images.githubusercontent.com/4717757/32433542-9dcb864c-c2db-11e7-8645-1df8f70dc2e7.gif)

**Comment by clebergnu** [comment]
The whiteboard is intended to hold test-specific information, and it's a "first class citizen" of the test class:

http://avocado-framework.readthedocs.io/en/55.0/api/core/avocado.core.html#avocado.core.test.Test.whiteboard

One possible improvement to the HTML report would be to display the whiteboard contents.  Adding one extra column may be too much at this point, but it'd be possible to show the whiteboard contents on "mouse over".

**Comment by apahim** [comment]
Yep, agreed. And whiteboard is specially useful if you want to isolate your messages and/or generate the output in a given format for further parsing.
As per HTML improvements, I'd create icons (i.e. ![111398-200 resized](https://user-images.githubusercontent.com/4717757/32434836-80b6d580-c2df-11e7-84d9-2d459a9ec789.png)![83827-200 resized](https://user-images.githubusercontent.com/4717757/32434829-7e8de53c-c2df-11e7-8f46-589b1ed6f5ed.png)), put both in the same column, renaming the column from "Debug Log" to "Debug".

**Comment by lmr** [comment]
@apahim the changes you mentioned sound fine to me, and should be easy to do, given that bootstrap has elegant support for icons.

**Comment by wellfrogliu** [comment]
@lmr @apahim @clebergnu  Thank you for for your reply.  I have got it. I think the  log is very complex for other person. I just want to display  the results for others, in other words I want a report. I think I must do the report only myself.  thank u very much.

**Comment by ldoktor** [comment]
That depends on what you mean by report. `tap` plugin simply reports `ok/not ok` and is available in `results.tap`.

As for the whiteboard, yes, it is especially designed to store user content so perhaps you can use it that way.

Another thing you might consider is to create a special logger and mention your messages in it. Then display it and report the output, which might look like this:

```
avocado --show app,details run mytest1 mytest2
JOB ID     : 897cadac1fac7d9b0e5f932d4088517fe65b574a
JOB LOG    : /home/medic/avocado/job-results/job-2017-11-06T14.14-897cada/job.log
 (1/2) mytest1: checked devices /dev/sda /dev/sdb
ratio 1.15 0.85PASS (0.02 s)
 (2/2) mytest2: no available devices to check
FAIL (0.05 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 0.38 s
JOB HTML   : /home/medic/avocado/job-results/job-2017-11-06T14.14-897cada/results.html
```

Anyway it's hard to answer your question when one does not know your exact usage. Can you provide us a sample output? Doesn't have to be real-life, just a sketch of what would work for you so we know which way to point you (or how to improve Avocado so everyone can benefit from it).

**Comment by wellfrogliu** [comment]
glad to get your reply.  This is the report i like. But i think the whiteboard also can be ok for me . Thank you very much.
![avocado](https://user-images.githubusercontent.com/21235456/32444384-69e7b262-c33d-11e7-829c-49de148a293a.png)

**Comment by clebergnu** [comment]
@wellfrogliu your mock up seems to suggest that this custom data (ssd read/write speed) is *job* related, that is, not limited the scope of *one* test.  Is that a requirement?  Or would it make sense to have that date under the test description?

**Comment by wellfrogliu** [comment]
That is just my  thought.  Do you have some good ideas.  Thank you!

**Comment by apahim** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add link to the test whiteboard in HTML results](https://trello.com/c/9tGhBicJ/1170-add-link-to-the-test-whiteboard-in-html-results)

**Comment by ldoktor** [comment]
There is a trello card associated so let's just wait when it's prioritized and developed. Feel free to vote to increase it's priority.

**Comment by clebergnu** [comment]
Hi @apahim this issue is being handled in PR https://github.com/avocado-framework/avocado/pull/3196, and we're reusing the images you provided here.  Would you remember where those images (bug, whiteboard) came from?

**Comment by apahim** [comment]
I don't, sorry. But for sure it came from a google search and we should not use them. I'd suggest to make our own versions in SVG. I can help with that, if needed... just let me know.
