### ISSUE TITLE
Built-in test TrinityTest.test does not terminate

### ISSUE THREAD

**Issue by fkromer** [avocado-framework/avocado#2285]
If the `TrinityTest.test` (located in `/usr/share/avocado/tests/trinity.py`) is executed when running all built-in tests with `avocado run /usr/share/avocado/tests` (I use [v55.0 from PyPi](https://pypi.python.org/pypi/avocado-framework/55.0)) the test doesn't terminate (it was running for 35 minutes before I aborted it).

**Comment by apahim** [comment]
Any logs that could provide a clue? I see that trinity version is quite outdated... Current is 1.8 and we keep the 1.5 in our repository. That alone deserves a PR already, but if we can find/fix your issue in the process, it would be ever better.

**Comment by fkromer** [comment]
I could provide a log file that is quite long (about 15 MB). Even the output starting at `2017-11-08 14:15:37,716 test             L0381 INFO | START 55-/usr/share/avocado/tests/trinity.py:TrinityTest.test
` wouldn't fit into here I guess. Can I provide it to you somehow else?

**Comment by fkromer** [comment]
Can I skip this test from the test suite execution for now by adding an option to `avocado run /usr/share/avocado/tests`?

**Comment by apahim** [comment]
Can you paste the 'interesting' lines to fpaste.org?

**Comment by apahim** [comment]
I was going to tell you to use a 'negative lookbehind' regex in the test reference filter. Something like:

`avocado run /usr/share/avocado/tests:'^(?!.*Trinity)'`

But guess what? The filter is not working for directories, only for files. I will open a bug. Anyway, the alternative would be create the list of files externally, filter out the files you don't want and then provide the filtered list to the `avocado run`. Something like:

```
avocado run $(avocado list /usr/share/avocado/tests | awk '{print $2}' | awk -F':' '{print $1}' | sort | uniq | grep -v trinity.py)
```

**Comment by apahim** [comment]
Well, you can send the full job.log file to my dropbox: https://www.dropbox.com/request/oxEYNVwCWf224rdkpqZb

**Comment by fkromer** [comment]
Thanks for the hint for blacklisting tests. I pasted the interesting part of the log file already [here](https://paste.fedoraproject.org/paste/y0UaOiviPTGF1GD-ZgpJyA).

**Comment by apahim** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[BUG] Test Reference filter not working for directories](https://trello.com/c/7VQ3syLt/1167-bug-test-reference-filter-not-working-for-directories)

**Comment by apahim** [comment]
From the logs, there's nothing wrong. Seems like the test should indeed take a long time to finish, given the number of directories/files created by the `data_factory.make_dir_and_populate()` call.

**Comment by fkromer** [comment]
Do you know how long the execution takes roughly?

**Comment by apahim** [comment]
I tell you when it finishes here :)

**Comment by fkromer** [comment]
Great, thanks :)

**Comment by apahim** [comment]
@lmr, trinity test is running for almost 2h now in on system. I think we should just drop it or move it to the avocado-misc-tests repository. Thoughts?

**Comment by lmr** [comment]
@apahim I think that trinity by default runs on a loop. It was a test that I used for its usefulness, and also it helped me to test my Ctrl+C avocado patches at the time. We need to confirm the first statement, but moving to avocado-misc-tests seems a good idea.

**Comment by PraveenPenguin** [comment]
@apahim @lmr in `avocado-misc-tests` already has trinity test , you can find this in below path 

`https://github.com/avocado-framework-tests/avocado-misc-tests/blob/master/fuzz/trinity.py` you are looking any tweak on this as it can be run as avocado self test

**Comment by apahim** [comment]
Oh, great, so let's just drop that test from our examples.

**Comment by apahim** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update "trinity" example test](https://trello.com/c/uCcng8dN/1168-update-trinity-example-test)

**Comment by ldoktor** [comment]
It looks like all related PRs were merged and seem to address the original description. Closing.
