### ISSUE TITLE
Avocado ppa is invalid, and way out of date

### ISSUE THREAD

**Issue by twirrim** [avocado-framework/avocado#2328]
If you install the PPA in Ubuntu, it fails on update because:

```
E: The repository 'http://ppa.launchpad.net/lmr/avocado/ubuntu xenial Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

It's also about two years out of date (109 weeks, version 0.30.0 being the latest release) but linked to from http://avocado-framework.github.io/download.html as where to "Get yourself some fresh Avocado"

**Comment by apahim** [comment]
Yep, not that fresh. @lmr, do you intend to update that repo? Otherwise, we should remove it from our docs.

**Comment by ldoktor** [comment]
@lmr any updates on this?

**Comment by ldoktor** [comment]
Unfortunately there is nothing we can do about that as we don't own that repo. Feel free to create your own and if so please update our documentation to point to the new updated one.
