### ISSUE TITLE
Comparing results.

### ISSUE THREAD

**Issue by omps** [avocado-framework/avocado#2348]
Well, a quick question regarding comparison of result. In autotest there is this result database TKO which can be used to compare result, how the same can be done with Avocado. In general, would like to compare the result of a particular test on 2 different arch, which can help us identify any performance gain/loss if any, I see resultdb is there to collect the result but its documentation looks incomplete and I am not able to figure out how the same can be used to plot graphs for comparative analysis. I am happy to work on such system if there is none at present. 

Please advise.

**Comment by apahim** [comment]
The only comparison tool we have is the `avocado diff`, which compares some aspects of two given jobs, identified by Job ID or Job Results Directory, generating a unified diff report.
A contribution with such comparative tool which plots graphs and so on would be very welcomed.

**Comment by omps** [comment]
@apahim thanks for replying, any guidance in this direction would be a lot helpful.

**Comment by clebergnu** [comment]
@omps resurrecting avocado-server may also be something worth investigating.  Specially this:

http://avocado-server.readthedocs.io/en/latest/RestAPI.html#jobs-job-id-tests-test-id-data

Seems suitable for holding performance data.  And then the HTML UI could be extended to diff and plot performance data.  Just a thought.

**Comment by omps** [comment]
@omps

TODO
1.  Implement compare result using diff.
2. Put to HTML UI
3. Plot the graph.

**Comment by ldoktor** [comment]
@omps also you might want to improve the `diff` to support custom performance data. Originally we wanted to advocate `whiteboard` as arbitrary-data storage, but feel free to send other RFC with real-world examples. It might slow-down a bit your development, but you might as well get good ideas and have a better implementation as we are as well interested in such features.

**Comment by ldoktor** [comment]
@omps there are few requests in this issue, but nothing really specific. Diffing results quite heavily depends on the result format so please provide real-world examples ideally with expected results or directly send PRs with `diff` improvements.

Note `diff` received some improvements already, I'm using it to compare qemu-iotests on different machines and it works like a charm. Still there is https://trello.com/c/vDNFZF5h/1340-add-support-to-format-jobdata-results-into-various-formats that might help (it's inspired by diffs I'm using and should allow even cooler magic) but it is currently in long-term backlog so not likely to be implemented any time soon (unless my CI started to require it, forcing me to increase the priority myself).
