### ISSUE TITLE
Result DB setup

### ISSUE THREAD

**Issue by omps** [avocado-framework/avocado#2352]
Cannot find any document for setting up resultdb?

the closest i can get from avocado docs is http://avocado-framework.readthedocs.io/en/latest/optional_plugins/results.html?highlight=resultdb

Could you please suggest how this has to be setup.?

**Comment by omps** [comment]
got it.

http://avocado-server.readthedocs.io/en/latest/Introduction.html


Thanks.

**Comment by apahim** [comment]
Please don't confuse ResultsDB[1] with Avocado Server[2]. Despite the fact that they have many overlapping features and goals, they are not the same.

[1] - https://fedoraproject.org/wiki/ResultsDB
[2] - http://avocado-server.readthedocs.io/en/latest/
