### ISSUE TITLE
Add "awesome-avocado-framework" repo reference to "awesome" repo

### ISSUE THREAD

**Issue by fkromer** [avocado-framework/avocado#2386]
I created a repository [awesome-avocado-framework](https://github.com/fkromer/awesome-avocado-framework) which summarizes helpful references about Avocado. I would like to add the list to [awesome](https://github.com/sindresorhus/awesome). For having a PR accepted the list should have at least some stars (the more the better). Would be great if you could star the repo.

**Comment by ldoktor** [comment]
Hello @fkromer, nice collection, how about simply including those in the main documentation? I think it'd make sense (we do actually have some references already and we meant to add links to existing test repos to simplify collaboration) and your commits would be warmly welcomed.

**Comment by ldoktor** [comment]
(note that the official documentation is available on http://avocado-framework.readthedocs.io/en/latest/ and linked from http://avocado-framework.github.io/ as well as available within the source code, therefor easily accessible. That's why I'd prefer that to some other location)

**Comment by lmr** [comment]
@ldoktor, apparently the awesome repo requires that the list repo is named awesome-[name-of-the-project], and that is why he created it like that. Of course replicating that info into the official avocado docs would be very helpful as well.

So @fkromer if you have some time, please send a PR adding that info to the official avocado repo. Thanks!

**Comment by fkromer** [comment]
@ldoktor @lmr Right, I consider the list more as promotion than actual documentation. And the awesome-list seems to be a way better place for promotion than the documentation does. However I try to find some time to add it to the docs as well. What would you consider a reasonable location for it (w.r.t. other sections, e.g. after section "xyz")?

**Comment by ldoktor** [comment]
Personally I'm very conservative, I don't collect badges, don't follow cool social things etc. so I don't really want to join. Anyway @avocado-framework/maintainers if you want to, I'm not against. In the mean-time I improved our documentation to list some of the content I find useful (and some extra) https://github.com/avocado-framework/avocado/pull/2702
