### ISSUE TITLE
Question: Benefits of remote execution of tests

### ISSUE THREAD

**Issue by fkromer** [avocado-framework/avocado#2390]
If I understand it correctly to beeing able to execute tests on a remote machine it is required to install `avocado`, test dependencies like `gcc` etc. ([Running Tests Remotely - Remote setup](http://avocado-framework.readthedocs.io/en/latest/RunningTestsRemotely.html#remote-setup)) and repositories including tests like e.g. `avocado-misc-tests` on the remote machine.

That means I need to ensure these prerequisites e.g. via remote execution to get `avocado` etc. onto the remote machine. The only benefit of remote execution I am aware of is that I do not have to copy the job log files from the remote to the "test triggering" machine. Or are there other benefits I am not aware of? One thing I didn't try out yet is if "usual" test dependencies which can be setup easily with a manual remote connection (e.g. on Ubuntu with `sudo apt-get install ...`) are resolved if the tests are executed via remote execution as well. Or do they have to be setup manually like mentioned in the docs (`gcc, make and others if you want to compile a 3rd party test suite written in C`) as well?

**Comment by apahim** [comment]
The only benefit is indeed being able to trigger the test from a different machine, while collecting the logs from the remote execution. Tests dependencies are not resolved, nor tests files are copied over.
FYI, we have plans to include a way more powerful remote mechanism:
https://www.redhat.com/archives/avocado-devel/2017-April/msg00002.html 
But that is still under development.

**Comment by fkromer** [comment]
@apahim Ah, ok. I read the thread you hyperlinked. However I was not sure if there is already something which can be used in the meanwhile as workaround.

**Comment by ldoktor** [comment]
Basically the `remote` plugin is here only as simplification to (test) developers, who want to trigger something on a different machine/container eg. to have results on a different OS. For QA/CI there are usually different ways to provision machines (jenkins/beaker/...) as well as to fetch and provide results.

It's similar to html results plugin. The usage for CI is minimal, but for developers it's sometimes better.

As for multi-stream tests, that's a bit different story, it's more about being able to write tests that spawn across multiple workers (either on the same or a different machine).

Anyway people are creative and you're free to abuse anything if it suits your needs 😉

**Comment by fkromer** [comment]
@ldoktor You probably already know there is this prioritization issue :smile: However if it gets really relevant for me I will think about it for sure...
