### ISSUE TITLE
Request to add the attribute 'whiteboard' back

### ISSUE THREAD

**Issue by pingl2016** [avocado-framework/avocado#2399]
Hi Cleber,
In the pr #2355, you stopped to select the attribute 'whiteboard'. However i find avocado-vt(avocado-vt/virttest/env_process.py) still grab the value for the variable witheboard, and avocado(avocado/avocado/core/test.py) continue to write it to the json result(avocado/avocado/plugins/jsonresult.py). If we really don't need it, I think we should clean comprehensive.
If the whiteboard is no harmless, Is it ok for you to add it back. We check the version of qemu from it, it always show unknown now(such as "whiteboard": "<unknown>") Thanks.

**Comment by pingl2016** [comment]
@clebergnu Could you help to take a look on this issue? Thanks.

**Comment by clebergnu** [comment]
This has been resolved by #2431
