### ISSUE TITLE
Support for Other Platforms

### ISSUE THREAD

**Issue by dpquigl** [avocado-framework/avocado#2408]
I would love to use avocado to rewrite the tests for a project I'm involved in however there is a requirement that we also be able to run them on illumOS, BSD, and MacOSX. Is there any intention on expanding the support of avocado to other platforms besides Linux?

**Comment by ldoktor** [comment]
Dear @dpquigl, currently we only actively test Avocado on Linux (primarily Fedora/RHEL), but ~a year ago we got many fixes for MacOSX and without plugins @clebergnu successfully used Avocado on Haiku.

So basically we're trying to write code in a portable way, but we don't have maintainers for other OSs. Anyway contributions towards this goal are welcome.

**Comment by clebergnu** [comment]
@dpquigl have you had any success running Avocado on those platforms?  With the Python 3 port progressing, I'd imagine we're improving our portability too.

**Comment by ldoktor** [comment]
@dpquigl we most certainly want to support other platforms, depending on the complexity, but without a clear aim we can't add anything.

If you want to add support, ideally send a PR fixing issues for a given platform and if available add it to `.travis.yml` test matrix. If you need help with it, please send us information about which version you tried and how it misbehaved. Ideally a docker image or just a log mentioning distribution and what commands failed how. We don't promise anything but adding more posix-compatible systems should be fairly simple.
