### ISSUE TITLE
Memory utility has static values after import 

### ISSUE THREAD

**Issue by harish-24** [avocado-framework/avocado#2524]
With the recent introduction of Datasize patch in `avocado/utils/memory.py`, once it has been imported in a test, the values throughout the tests are persistent. This is probably due to object initialized when import and usage in test does not reflect new values and persists to values when initialized.

With the change, thp swap test https://github.com/avocado-framework-tests/avocado-misc-tests/blob/master/memory/transparent_hugepages_swapping.py has following issue.

Ex: Assuming we have a `memory.meminfo.SwapFree.m=2047` .
After some operations actual SwapFree is 1127

But with the latest changes in the utility, the value persists to old one
`memory.meminfo.SwapFree.m=2047`

My understanding is that this should be fixed in utility, as initializing `MemInfo` object from test does not justify proper usage of the utility. If not, please let know if tests has to adapt to these changes.

**Comment by apahim** [comment]
Yes, it should be fixed indeed. Working on that.

**Comment by harish-24** [comment]
@apahim Thanks :+1:

**Comment by harish-24** [comment]
Closing this as #2525 fixes this.
