### ISSUE TITLE
Copy files to VM by sftp before executing test insider VM

### ISSUE THREAD

**Issue by amoskong** [avocado-framework/avocado#2556]
I write some subtests in main_test.py, and it imports another module (usage_module.py), and I have problem to copy usage_module.py to VM. We might also share usage_module.py for other test file.

My current cmdline:
```
avocado --show all run main_test.py \
--vm-domain centos7 --vm-cleanup --vm-username root --vm-hostname 192.168.122.xx --vm-password xxx
```

Result:
Only main_test.py and main_test.py.data/ will be copied to VM before executing.

I tried to append 'usage_module.py' to avocado cmdline, but it reported that the usage_module.py doesn't contain valid subtest.

Then I add an empty subtest in usage_module.py, the file will be copied to VM, tests in main_test.py will be executed successfully, but the empty test will also be executed.

I found a workaround:
```
avocado --show all run main_test.py usage_module.py \
--vm-domain centos7 --vm-cleanup --vm-username root --vm-hostname 192.168.122.xx --vm-password xxx
```

empty subtest in usage_module.py:
```
class EmptyTest(Test):
    """
    Workaround:
      We want Avocado to copy this module to VM, it will be used by main_test.py
      But Avocado will raise error if the module doesn't contain valid subtest.
      So we add this empty test.

    :avocado: enable
    """
    def test_empty(self):
        pass
```

**Comment by amoskong** [comment]
@lmr @clebergnu do you have some suggestion on it?  Thanks.

**Comment by ldoktor** [comment]
Hello Amos, if the `main_test.py` is copied you have to be using really old Avocado. We removed the support to copy files a long time ago as it was not reliable (basically the issue you are describing here). There was a long discussion about that with several proposals, but given the circumstances (not enough development power) we decided to remove it to not give false hopes and we advised users to use `rsync` before avocado command.

Anyway if you want to bring the support back it'd have to be a generic concept based on test type (SIMPLE, Avocado-vt, ...). For INSTRUMENTED tests we'd need a generic way to specify extra files and ideally also tree of imports to copy them over automatically (but that is not mandatory)

**Comment by ldoktor** [comment]
Btw we usually just ship libraries via pip or rpm (depending on which team). Good about it is that we had to clean the libraries up and created them as a proper modules, which uncovered some hidden issues.

**Comment by ldoktor** [comment]
We are not going to develop anything like this in foreseeable future. If you want to contribute this as plugin, please send an RFC.
