### ISSUE TITLE
runner_remote and runner_vm plugins are not loadable after installation. 

### ISSUE THREAD

**Issue by Vincinator** [avocado-framework/avocado#2624]
**Context:**
Installation of runner_remote and runner_vm completes  without errors. I tried installing avocado and the plugins with pip and with the setup.py from the sources. 

**The Problem:**
runner_remote and runner_vm are not loadable after installation. Calling ```avocado plugins``` will result in 
```Failed to load plugin from module "avocado_runner_remote": ImportError('No module named api',)```

Thanks for your time!

**Comment by clebergnu** [comment]
@Vincinator can you please describe your installation method? The missing `api` module is probably `fabric.api`, so I'm guessing fabric failed to install on your system.

**Comment by Vincinator** [comment]
@clebergnu i could successfully install avocado with the optional remote and vm plugins on a different machine.
I used this method for the failing and the working environment.  
```bash
git clone https://github.com/avocado-framework/avocado
cd avocado
sudo python setup.py install
cd optional_plugins
cd runner_remote
sudo python setup.py install
``` 
Fails on my ubuntu server, works on my arch laptop. 

On the ubuntu server, where the setup fails for me, i also tried to install it in an virtual env via pip. 
```
python -m virtualenv /my/virtualenv/path
. /my/virtualenv/path/bin/activate
pip install avocado-framework
pip install avocado-framework
pip install avocado-framework-plugin-runner-remote
```

Executing ```pip list``` shows that some fabric version is installed
```bash
/usr/lib/python2.7/dist-packages/pip/_vendor/__init__.py:36: UserWarning: Module six was already imported from /usr/share/python-wheels/six-1.10.0-py2.py3-none-any.whl/six.py, but /usr/local/lib/python2.7/dist-packages/six-1.11.0-py2.7.egg is being added to sys.path
  __import__(modulename, globals(), locals(), level=0)
asn1crypto (0.24.0)
avocado-framework (61.0)
avocado-framework-plugin-runner-remote (61.0)
bcrypt (3.1.4)
cffi (1.11.5)
cryptography (2.2.2)
enum34 (1.1.6)
fabric (2.0.0)
idna (2.6)
invoke (1.0.0)
ipaddress (1.0.22)
paramiko (2.4.1)
pbr (4.0.2)
pip (8.1.1)
pyasn1 (0.4.2)
pycparser (2.18)
PyNaCl (1.2.1)
setuptools (39.1.0)
six (1.11.0)
stevedore (1.28.0)
wheel (0.29.0)
```

I will further investigate on that issue

Thanks!

**Comment by Vincinator** [comment]
I installed Fabric3  with ```pip install Fabric3 ```  now it works also on my Ubuntu server. Thanks!
