### ISSUE TITLE
Bad performance on flushing the tap result

### ISSUE THREAD

**Issue by luckyh** [avocado-framework/avocado#2647]
If a test produces a large amount of logs, it would wait for more than few hours to get all the logs flushed into the tap result file. (can run vt test `io-github-autotest-qemu.pxe_boot.with_query_cpus` to reproduce this)

I've checked the code and found that:

1. currently, avocado will write all the test logs into the tap result file (just for vt tests?)
2. after wrote each single line, avocado will sync the data on disk

My suggestion is, if we do need the test logs written into the tap result file, we'd better reduce the frequency on doing the sync.

**Comment by ldoktor** [comment]
Should be addressed by https://github.com/avocado-framework/avocado/pull/2688

**Comment by luckyh** [comment]
@ldoktor thank you!

**Comment by ldoktor** [comment]
you're welcome, it was partially selfish because I hate the huge `results.tap` files (in my CI they can be around 200-600MB and I don't see a point in storing redundant messages by default).
