### ISSUE TITLE
Remote tests failing

### ISSUE THREAD

**Issue by omps** [avocado-framework/avocado#2699]
Hi,

I am trying to run remote execution on one of the host. Avocado is installed on the remote server using `pip install avocado-framework`. The test path is for local machine. Not sure why this is failing any insight would be a lot helpful.

```
bin/avocado run --remote-hostname hostname --remote-username root avocado/examples/tests/sleeptest.py
JOB ID     : f2aaadb31f28c6541ed788ea376d00e56769afb0
JOB LOG    : /home/autotest/avocado/job-results/job-2018-07-05T12.47-f2aaadb/job.log
LOGIN      : root@hostname:22 (TIMEOUT: 60 seconds)

Avocado job failed: JobError: Remote execution failed with: Unable to resolve reference(s) 'avocado/examples/tests/sleeptest.py' with plugins(s) 'file', 'external', try running 'avocado list -V avocado/examples/tests/sleeptest.py' to see the details.
JOB HTML   : /home/autotest/avocado/job-results/job-2018-07-05T12.47-f2aaadb/results.html
```

**Comment by PraveenPenguin** [comment]
@omps have your system hostname is `hostname` as below line is says it failed to login 
```root@hostname:22 (TIMEOUT: 60 seconds)```  if not i think you need to provide right hostname

**Comment by ldoktor** [comment]
@omps the remote runner does not copy any tests. Do you have the `avocado/examples/tests/sleeptest.py` files available on the remote machine? (try ssh-ing into the machine and execute the suggested `avocado list -V avocado/examples/tests/sleeptest.py`).

**Comment by clebergnu** [comment]
@omps I think the explanations given by @ldoktor and @PraveenPenguin were sufficient.  We do understand the shortcomings of the remote runners, and we'll probably revisit them in the next 2nd or 3rd release. Stay tuned.  For now, I'm closing this issue, but feel free to reopen if you have any other concerns.
