### ISSUE TITLE
runner_docker plugin generates invalid long hostnames for a docker container

### ISSUE THREAD

**Issue by fj-sanchez** [avocado-framework/avocado#2904]
Every time that a container is launched a temporary hostname is generated, if the local machine hostname is long, for example has many labels part of a network domain, it will generate a very long hostname producing an error when calling the `docker` command. Apparently the max. hostname lengh supported by Docker is 64 characters to make it compatible with Windows...

[avocado-framework/avocado/blob/master/optional_plugins/runner_docker/avocado_runner_docker/__init__.py#L48](https://github.com/avocado-framework/avocado/blob/master/optional_plugins/runner_docker/avocado_runner_docker/__init__.py#L48)
```python
        if name is not None:
            options += " --name %s --hostname %s" % \
                       (name, name + '.' + socket.gethostname())
```

`name` is generated according to the current job logdir:
[avocado-framework/avocado/blob/master/optional_plugins/runner_docker/avocado_runner_docker/__init__.py#L125](https://github.com/avocado-framework/avocado/blob/master/optional_plugins/runner_docker/avocado_runner_docker/__init__.py#L125)

```
 dkr_name = os.path.basename(self.job.logdir) + '.' + 'avocado'
```

Not sure what should be the change here... Maybe just truncating the name so in total the hostname is not more than 64 characters?

**Comment by clebergnu** [comment]
Hi @fj-sanchez, we've decided to deprecate the docker runners, and consequently will not fix this and related issues.  See #3799.

As a heads up, a preliminary experimental container (podman) support exists in the `nrun` command via `--podman-spawner` option, and it's expected that it will evolve a lot in the upcoming releases.
