### ISSUE TITLE
--ignore-missing-references doesn't work properly with --docker

### ISSUE THREAD

**Issue by fj-sanchez** [avocado-framework/avocado#2905]
Hi,

I have a docker image where I copy all the tests to the /tests folder and set this folder as WORKDIR.

```
FROM python:alpine

RUN apk update && apk add --no-cache bash

WORKDIR /test

COPY requirements.txt /tmp/avocado-packets.txt
COPY xunit_mod_property /usr/bin/xunit_mod_property
COPY test /test
COPY config /config
```
I am trying to run avocado like this `avocado run --ignore-missing-references=on --mux-inject sleep_length:5 arg1:11 arg2:22 --docker alpine-avocado -- sleeptest.py test.sh` and this is the results if I run it from the `test` folder:
```
(avocado27) francisco@fran-laptop:~/src/avocado_tests/alpine-avocado/test$ avocado run --ignore-missing-references=on --mux-inject sleep_length:5 arg1:11 arg2:22 --docker alpine-avocado -- sleeptest.py test.sh
JOB ID     : 63e79cedb7a58f3d67cbd6a0c13d66a5b690bbff
JOB LOG    : /home/francisco/avocado/job-results/job-2018-11-08T13.46-63e79ce/job.log
DOCKER     : Container id '119be8a83630427c7668770b40a6e5162a3ee550f87e7c2be97f49b9c2307a61'
DOCKER     : Container name 'job-2018-11-08T13.46-63e79ce.avocado'
 (1/2) sleeptest.py:SleepTest.test: PASS: None (1.01 s)
 (2/2) test.sh: PASS: None (0.02 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 4.19 s
```

And this if I try from somewhere else:

```
(avocado27) francisco@fran-laptop:~/src/avocado_tests/alpine-avocado$ avocado run --ignore-missing-references=on --mux-inject sleep_length:5 arg1:11 arg2:22 --docker alpine-avocado -- sleeptest.py test.sh
Unable to resolve reference(s) 'sleeptest.py', 'test.sh' with plugins(s) 'file', 'yaml_testsuite', 'external', try running 'avocado list -V sleeptest.py test.sh' to see the details.

No tests found for given test references, try 'avocado list -V sleeptest.py test.sh' for details
```

It seems that locally it is still trying to find the test files.

**Comment by fj-sanchez** [comment]
I have tried again with the code from the repository directly instead of the installed from pip and it seems to work there... Anyway, I have seen how the remote runner is using a DummyLoader but the docker runner is not using anything like that. Shouldn't the docker one include this loader as well?

**Comment by fj-sanchez** [comment]
To update to my previous comment, I cannot get it working anymore, I am currently using a virtual environment without pip version of avocado, just the GIT clone with develop setup. Still no working properly.

**Comment by clebergnu** [comment]
Hi @fj-sanchez, we've decided to deprecate the docker runners, and consequently will not fix this and related issues.  See #3799.

As a heads up, a preliminary experimental container (podman) support exists in the `nrun` command via `--podman-spawner` option, and it's expected that it will evolve a lot in the upcoming releases.
