### ISSUE TITLE
Defining different docker images for different tests

### ISSUE THREAD

**Issue by fj-sanchez** [avocado-framework/avocado#2906]
Hello,

I have two use cases where having the ability to define which docker image to use would be great:

1 - Different tests with different environment requirements
I have some tests that require a number of libraries/tools available in order to work. What I would like to do is to be able to set which docker image to use with each test.
2 - One test running under different environments
For some tests where I want to run variations against different versions of a particular library. For python only requirements I could use virtualenv to fix it, but with other types of dependencies it gets more complicated. What I would like to do is to set the docker image as a variant parameter.

I haven't seen any way of doing it but I might be wrong. I wouldn't mind to work on this feature if it is not available, what would be the best way of doing it?

**Comment by willianrampazzo** [comment]
The docker runner plugin was deprecated on Release 79. A new podman implementation will be available with the N(ext)Runner. Closing this issue. If it is still needed, feel free to reopen.
