### ISSUE TITLE
Unable to install avocado on sles12sp3

### ISSUE THREAD

**Issue by parimalpp** [avocado-framework/avocado#2948]
When i did " pip install --user avocado-framework" on my sles12 box
it said : Could not find a version that satisfies the requirement avocado-framework (from versions: )
No matching distribution found for avocado-framework

Can someone please help?

**Comment by clebergnu** [comment]
@parimalpp I don't have easy access to a SLES12sp3 box, so, could you please try to gather more information on the failure?  Running `pip vvv install --user avocado-framework` should be a good start.

**Comment by parimalpp** [comment]
@clebergnu 
Thanks a lot, i did a silly mistake of not configuring the DNS properly in the system.
When i ran "pip -vvv install --user avocado-framework" i saw that my box was unable to reach the PyPi website as my dns was incorrect. After pointing my DNS to the right server i was able to install avocado.
Thank you for your help.
