### ISSUE TITLE
A possible race condition issue in avocado

### ISSUE THREAD

**Issue by rayx** [avocado-framework/avocado#2981]
I hit the issue when I ran a QEMU test. The test actually finished, but avocado process didn't exit. It just hung there for ever. 

So I took a closer look and found the main thread in the process was waiting for a worker thread. The worker thread didn't exit because it thought there was still IO but there wasn't - a symptom of race condition. 

Below was pstree output:

<pre><code>
  |   `-bash,24767
  |       `-sh,37220 run
  |           `-python,5107 ./scripts/avocado run type_specific.io-github-autotest-qemu.cgroup.cpu_share
  |               `-{python},32938
</code></pre>

main thread strace output:

<pre><code>
# strace -p 5107
strace: Process 5107 attached
futex(0x2d97ab90, FUTEX_WAIT_PRIVATE, 0, NULL
</code></pre>

and the work thread strace output contained only repeated pselect6() calls:

<pre><code>
# strace -v -p 32938 -y
strace: Process 32938 attached
pselect6(22, [21</tmp/aexpect_70Xv4tDo/outpipe-tail>], [], [], {0, 32917047}, NULL) = 0 (Timeout)
pselect6(22, [21</tmp/aexpect_70Xv4tDo/outpipe-tail>], [], [], {0, 50000000}, NULL) = 0 (Timeout)
... 
</code></pre>

It seemed that the worker thread was waiting for input from tmp/aexpect_70Xv4tDo/outpipe-tail (the file existed on the system when the process hung), but the peer was actually gone and for some reason the work thread didn't get the notification. 

I don't know the avocado internals to tell what was exactly happening, but hope the above logs are useful.

**Comment by willianrampazzo** [comment]
Hi @rayx, this issue was opened more than a year ago. Is this issue still valid?

**Comment by rayx** [comment]
See my reply in #2997

**Comment by willianrampazzo** [comment]
I'm closing this as we are planning to move to a new runner soon. If anyone reaches this problem, feel free to reopen this issue.
