### ISSUE TITLE
How can we display test data on HTML report 

### ISSUE THREAD

**Issue by pcloud2** [avocado-framework/avocado#3045]
I am using HTML result plugin to get the report, it serves my purpose to some  extent.
As of now reports are notifying, what is the status of executed test (PASS, FAIL, CANCEL .. etc). However, I would like to display statistics of each tests on the report along with test status.

Use Case
----------
My tests are mostly related to CPU benchmarking (as of now).
If test is pass, I'm able to push CPU benchmarking data in debug log. and now also on whiteboard (Thanks to Cleber's suggestion).  However I would like to display each test data on HTML report with test status. Pushing data in `whiteboard`, updating `result.json `, pretty interesting. 

How can we pull `whiteboard` data or `result.json` data on HTML report. ?

**Comment by clebergnu** [comment]
@pcloud2  a few options come to my mind when it comes to *presenting* the data:

1) Info column: it's usually only used for failures, but it could also be used to display important and short text based test result information.  If a test is about completing a task and presenting the performance, metric this could possibly be a good place. Something like: "122 mbps" would be a good candidate.
 
2) "mouse over" test title:  If you look at how test parameters are displayed on the HTML report when you put the mouse over the test's title, the same could be done for test produced data.  The whiteboard content, if it's text based information, could be shown in a similar way.  If the content is not text based, user would have to define the MIME type.

3) collapsible panel: similar to the sysinfo pre/post/profilers panels, but for each test.  I'm not sure this would be visually appealing or practical though.

Comments?

**Comment by pcloud2** [comment]
@clebergnu :  

As far as concern with benchmarking, first option looks good to me.

Another one I can think of is move under `collapsible panel` with drop down menu. So we will have litter bit more space to accommodate more params with multiple tests. (Yes, for each test we have to explicitly select the test name to see the result, not quite user friendly in my opinion)   

Also, I would like to explore the possibility of visual presentation of test data in HTML report going forward (Once we accomplished the numerical representation of test data). I believe  this can help us in performance  testing also.
To server that purpose I believe we can utilise the collapsible panel and for each test case may be we can create drop down menu. _(This info, is to explore the possibility. I am yet new to avocado, If we have better way to please suggest ! )_

`Example: ` 
For disk benchmarking, if we have separate test for 4K, 8K, 512K block. all this can be shown in drop down menu and respective visual data representation should be displayed.

**Comment by willianrampazzo** [comment]
Hi @pcloud2, this issue was opened more than a year ago. Is it still valid? Do you still need help figuring out the HTML output?

**Comment by willianrampazzo** [comment]
Closing this issue as there have not been activities for more than 2 years.
