### ISSUE TITLE
avocado/core/data_dir.py is executable. Why?

### ISSUE THREAD

**Issue by asashnov** [avocado-framework/avocado#3064]
avocado/core/data_dir.py is executable. Why?

```
alex@host [~] $ git clone git@github.com:avocado-framework/avocado.git

alex@host [~] $ cd avocado/avocado/core

alex@host [~/avocado/avocado/core] $ ls -l
total 368
-rw-rw-r-- 1 alex alex  3503 Mar 11 15:08 app.py
-rwxrwxr-x 1 alex alex  8961 Mar 11 15:08 data_dir.py    <=== why chmod +x was done???
-rw-rw-r-- 1 alex alex  2664 Mar 11 15:08 decorators.py
-rw-rw-r-- 1 alex alex   649 Mar 11 15:08 defaults.py
-rw-rw-r-- 1 alex alex  9368 Mar 11 15:08 dispatcher.py
.....

```

I see no reason for 'data_dir.py' file to be executable. 

It doesn't even contain

`#!/usr/bin/env python`

nor 
`    if __name__ == '__main__':
`

**Comment by clebergnu** [comment]
No reason at all.. thanks for reporting this.  If possible, please add your review here:

https://github.com/avocado-framework/avocado/pull/3071

Thanks!

**Comment by clebergnu** [comment]
#3071 merged, closing this.
