### ISSUE TITLE
strange Python statement: somevar = somevar

### ISSUE THREAD

**Issue by asashnov** [avocado-framework/avocado#3065]
https://github.com/avocado-framework/avocado/blob/ebce18f2a0f035b8baa0a35d4ab22a3578a7b08f/avocado/core/dispatcher.py#L31

Before I have seen this I though I know Python somehow:

```
#: Settings dispatcher is simplified and has to be available before the
#: settings object. Let's include it here for consistency
SettingsDispatcher = SettingsDispatcher
```

Need to expand the comment with explanations what is the exact effect of this statement.

Like (I don't really know) SettingsDispatcher is defined in settings. When Python interpreter tries to dereference SettingsDispatcher on the right, it throws NameError, which is handled by a handler ...(module,function name)...  which was set in .....(module,function name)...
This technic is described in ..... (link to an article, or at least a name for googling).

**Comment by clebergnu** [comment]
Hi @asashnov , the reason for the *really* strange statement, is that it makes the documentation more complete by including the `SettingsDispatcher` in the dispatcher module docs:

https://avocado-framework.readthedocs.io/en/latest/api/core/avocado.core.html#avocado.core.dispatcher.SettingsDispatcher

But, I agree that's not neat.  The original reason for that code layout was to avoid a circular import, but I'm pushing a fix that moves the `SettingsDispatcher` class to another module that can be avoid that.

**Comment by clebergnu** [comment]
#3070 merged, closing this.
