### ISSUE TITLE
azure plugin repo is deprecated

### ISSUE THREAD

**Issue by yuxisun1217** [avocado-framework/avocado#3074]
Hi,

The azure plugin repo "avocado-azure" is my own repo for testing RHEL image in Azure, and has been deprecated for a long time. Sorry for mislead you. Could someone please remove this link? thanks!

**Comment by clebergnu** [comment]
@yuxisun1217 please let me know if this PR #3075 looks good to you.  Thanks.

**Comment by yuxisun1217** [comment]
@clebergnu It's ok. Thank you so much!

**Comment by clebergnu** [comment]
#3075 merged, closing this.
