### ISSUE TITLE
How can we specify config in command line?

### ISSUE THREAD

**Issue by yuxisun1217** [avocado-framework/avocado#3080]
Hi,

I wish to run multiple test runs parallel in the same host, and need to specify a different job log dir for each run. Is there a way to specify the log dir in avocado command line? Such as: avocado run --conf xxx. Thanks!

**Comment by clebergnu** [comment]
I think you want `--job-results-dir`... but if you run two avocado jobs (`avocado run ...`) they'll automatically pick different job results directories anyway (at the same base location, though).

Does that work for you?

**Comment by yuxisun1217** [comment]
Hi @clebergnu ,

Yes it works for me. But it will be much easier if I can specify a job dir and simply get the result from the "latest" folder, so that I don't need to catch the job result dir name from the output. All these "avocado run"s are used to test different packages so that they don't need to be kept together in the same folder. Currently I modify the avocado.conf before each run but it seems a little strange I think...So just curious about if avocado provides such a parameter to specify the conf file. Thanks!

**Comment by yuxisun1217** [comment]
@clebergnu Ah yes that's what I needed. Thank you so much!
