### ISSUE TITLE
In Older Distro (RHEL7) and SLES12 avcoado failed to run due to python2 support removed 

### ISSUE THREAD

**Issue by PraveenPenguin** [avocado-framework/avocado#3088]
Hi 
We are facing issue after Drop python2 support from avocado in RHEL7 and SLES12 Distribution Series, it failed to run yaml combination as well we need to pip install package ( configparser and enum ) to avcoado library work 
1-
it failed as 
``Unable to import Avocado libraries, please verify your installation, and if necessary reinstall it.``

after installing   configparser and enum it woks (able to launch avcoado)
2- yaml input failed as unicode issue as asting.py had removed unicode support 

Traceback not available
JOB ID     : 823891ef0426a1f83cc9d82d5f2a1ac9710e96c8
JOB LOG    : /home/OpTest/avocado-fvt-wrapper/results/job-2019-03-26T14.50-823891e/job.log
Error running method “initialize” of plugin “yaml_to_mux”: ‘unicode’ object has no attribute ‘name’
(1/1) avocado-misc-tests/kernel/kernbench.py:Kernbench.test: CANCEL: libcap-ng-devel is needed for the test to be run (11.14 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 1
JOB TIME   : 11.18 s

so only one combination , now https://github.com/avocado-framework/avocado/pull/3082 after this patch goes in i think full python2 support will drop

**Comment by PraveenPenguin** [comment]
@clebergnu @ldoktor can you please help us here

**Comment by narasimhan-v** [comment]
Do we need to drop python2 support this fast, considering python2.7 will stop the support only by the end of the year ?

**Comment by sathnaga** [comment]
@clebergnu @ldoktor We are one of the major users of avocado framework for our testing and it involves the older distributions where only python2 support is available, It would be helpful if we have a conditional support for python2, at worst case we can tag a branch as lts with python2 support explicitly, and pull the relevant patches from upstream as needed...

**Comment by ldoktor** [comment]
Hello guys, I was also sad about this, some recommendations were mentioned in https://github.com/avocado-framework/avocado/pull/3060 basically I'm using LTS for py2 distros and moved to py3 on newer distros, occasionally fixing minor avocado-vt bugs but overall it works well.

**Comment by ldoktor** [comment]
I mean are there any new Avocado features missing in 69 LTS? It is really recent and will be maintained for ~1.5 year.

**Comment by PraveenPenguin** [comment]
@ldoktor thanks for reply will check in 69lts branch , it will be good if this patch also included in 69LTS https://github.com/avocado-framework/avocado/pull/3081 and https://github.com/avocado-framework/avocado/pull/3078

**Comment by sathnaga** [comment]
@ldoktor sure, Thanks, we will let know if any more missing patches.

**Comment by clebergnu** [comment]
If you're using a released version of Avocado (69.0), then you shouldn't have had any issues running it under Python 2.  If you use the latest master, you shouldn't count on anything, really - this is a development branch, and good practice suggests it should not to be used in production.

With regards to supporting only Python 3 post 69.0, it has to do with optimization of our own resources and making Avocado able to use Python 3 only features.  As an example, I've been working on some new features that, had I to worry about using Python 2 also, I'd probably be unable to get them done.

So, the short answer is please rely on 69.0 LTS not only for Python 2, but for all your production uses. 

Finally, the notice about these changes were posted to the mailing list:

https://www.redhat.com/archives/avocado-devel/2019-January/msg00018.html

So if you guys are not subscribed, I suggest you do get subscribed.

Thanks.

**Comment by clebergnu** [comment]
@PraveenPenguin please send the PRs for the same code on #3081 and #3078 to 69lts branch.

**Comment by PraveenPenguin** [comment]
@clebergnu sure i will send

**Comment by PraveenPenguin** [comment]
@clebergnu raised #3089 please have  a look

**Comment by clebergnu** [comment]
@PraveenPenguin I'm closing this issue as #3089 has been merged (for a while)
