### ISSUE TITLE
Python fabric API jump needed for F31/Rawhide

### ISSUE THREAD

**Issue by mmathesius** [avocado-framework/avocado#3125]
Remember the troubles and confusion a while back when the Python fabric package wouldn't move forward with making a Python 3 version of the package available, so someone forked it and created a new python-fabric3 package?

Well, in Fedora 31/Rawhide, the python-fabric3 package was recently retired--since the original fabric package now supports Python 3. Unfortunately, it also made the jump to the fabric2 API.

This update to fabric means avocado (particularly the remote_runner plugin) needs to adapt to the fabric2 API for F31 and beyond. The change also needs backported to the 69LTS release if it's going to build and run on F31 and beyond.

**Comment by mmathesius** [comment]
FYI, I have disabled the downstream Fedora building and packaging of the avocado "runner" sub-packages that depend upon fabric in F31/Rawhide until such time as this issue gets resolved. This impacts the `avocado:69lts` and `avocado:latest` module streams.

**Comment by mmathesius** [comment]
PR #3132 includes patches to the SPEC file so avocado will build for F31/Rawhide until this issue is resolved.

**Comment by clebergnu** [comment]
@mmathesius FIY, somewhat related to this and to PR #3132, I had to add some workarounds for Fedora 30 and later when building on COPR, see 7a962156517c56691012cd59c0b406dba02db548.

Do you have any advice on how to handle the (supposedly temporary) issue with dnf not handling build requires from packages from modules properly?

Reference: https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/V6SBSAS5TBGNORGLYW75TIRX6JDBXQ2Q/

**Comment by mmathesius** [comment]
@clebergnu I think the `dnf` problem you are referencing is a slightly different (but related) problem. Nevertheless, there's not a good solution until the general issue of getting modular packages into the non-modular buildroot is fixed.

However, in the case of avocado builds using COPR, include the `python-aexpect` package in the same COPR project with `python-avocado`. That will make aexpect available at build time, as well as making it available as a dependency in the COPR repo at avocado install time.

**Comment by clebergnu** [comment]
@mmathesius we've decided to deprecate those runners, and consequently will not fix this and related issues.  See #3799
