### ISSUE TITLE
Error running method "initialize" of plugin "varianter_cit" with Avocado 70.0

### ISSUE THREAD

**Issue by pevogam** [avocado-framework/avocado#3169]
Hi I just deployed the new Avocado 70.0 fresh out of the oven and go this:

```
Error running method "initialize" of plugin "varianter_cit": 'Namespace' object has no attribute 'cit_order_of_combinations'
```

It is nonfatal but I think it is still worth reporting.

**Comment by clebergnu** [comment]
Hi,

Thanks for reporting it. Can you please confirm if this is a fresh
environment or an upgrade?

**Comment by pevogam** [comment]
Our deployment process involves cloning the repository at the release tagged commit, then copying the spec file in the repo and manually building the RPM. From all of this I can gather that the issue should also be reproducible at the most recent master tag.

The error is nonfatal so this doesn't interrupt the run but it would be better to clean it up from the console output.

**Comment by clebergnu** [comment]
I absolutely agree with cleaning it up... the problem is that I'm not able to reproduce it so far.  I've seem similar situations, though, when a plugin, say a Varianter type is *registered* as an setuptools entrypoint, but the CLI plugin (which gives the command line options) isn't.

**Comment by pevogam** [comment]
Hmmm, the `setup.py` is completely copied from the 70.0 tarball and the only thing we modify is the spec file where we only add a small block of patches. Currently even there there is only one patch which changes a single value like so:

```diff
diff --git a/avocado/etc/avocado/avocado.conf b/avocado/etc/avocado/avocado.conf
index 7a14c6b6..29c249e4 100644
--- a/avocado/etc/avocado/avocado.conf
+++ b/avocado/etc/avocado/avocado.conf
@@ -6,7 +6,7 @@ test_dir = /usr/share/doc/avocado/tests
 # You may override the specific test auxiliary data directory with data_dir
 data_dir = /var/lib/avocado/data
 # You may override the specific job results directory with logs_dir
-logs_dir = ~/avocado/job-results
+logs_dir = /mnt/local/results
 # You can set a list of cache directories to be used by the avocado test
 # fetch_asset() with 'cache_dirs'. read-only cache directories are also
 # supported.
```

Is there some additional output that I can provide you with like `AVOCADO_LOG_DEBUG` or
`AVOCADO_LOG_EARLY`? Would that be helpful or perhaps some installation log?

**Comment by pevogam** [comment]
Here some debugging information:

```
avocado.app.debug: Reproduced traceback from: /usr/lib/python3.7/site-packages/avocado/core/dispatcher.py:154
avocado.app.debug: Traceback (most recent call last):
avocado.app.debug:   File "/usr/lib/python3.7/site-packages/avocado_varianter_cit/__init__.py", line 68, in initialize
avocado.app.debug:     order = args.cit_order_of_combinations
avocado.app.debug: AttributeError: 'Namespace' object has no attribute 'cit_order_of_combinations'
avocado.app.debug: 
Error running method "initialize" of plugin "varianter_cit": 'Namespace' object has no attribute 'cit_order_of_combinations'
```

**Comment by pevogam** [comment]
Hmmm searching for the relevant option shows only one use in `optional_plugins/varianter_cit/avocado_varianter_cit/__init__.py`:

```python
    def initialize(self, args):
        self.variants = None
        order = args.cit_order_of_combinations
```

I am not fully acquainted with the details plugin definitions but it seems there is no configuration adding this option anywhere and the only place it is used, it is expected to exist.

**Comment by pevogam** [comment]
Not sure about the source of the error but since you confirm it is not reproducible we can close this issue. On our side, we will just drop the CIT varianter and a few other dependencies that we don't really use.
