### ISSUE TITLE
Contributing guidelines link not leading to a rendered document

### ISSUE THREAD

**Issue by TheMeaningfulEngineer** [avocado-framework/avocado#3186]
From the perspective of Github, the link to the document describing how to contribute is broken.

Clicking on the link "contributing guidelines" leads to https://github.com/avocado-framework/avocado/blob/master/CONTRIBUTING.rst

![Screenshot from 2019-07-09 14-10-35](https://user-images.githubusercontent.com/1640260/60886891-5e531800-a253-11e9-88d7-707925e736a4.png)

**Comment by clebergnu** [comment]
You're right, but that's how GitHub renders symbolik links. that can also be seen with:

https://github.com/avocado-framework/avocado/blob/master/README

I wonder if we can control how GitHub renders that.

**Comment by willianrampazzo** [comment]
Closing this issue as there have not been activities for more than 2 years.
