### ISSUE TITLE
Avocado remote runner fails to get version if stderr non-empty

### ISSUE THREAD

**Issue by jallen-amd** [avocado-framework/avocado#3189]
Using the avocado remote-runner plugin, I've started getting the following error:
`Avocado job failed: JobError: Remote machine does not seem to have avocado installed`

However, the remote machine certainly _does_ have avocado installed. Digging into the remote-runner code, I find the problematic code be here (optional_plugins/runner_remote/avocado_runner_remote/\_\_init\_\_.py, line 381):
```python
        match = self.remote_version_re.findall(result.stderr + result.stdout)
        if match is None:
            return (False, None)

        try:
            return (True, tuple(int(_) for _ in match[0]))
        except IndexError:
            return (False, None)
```
Printing stdout shows "Avocado 70.0" and stderr shows "mesg: ttyname failed: Inappropriate ioctl for device"

If understand the regex properly, match will look for number + "." + number after "Avocado " at the beginning of the line. However, the match uses stderr + stdout for the string to match. So it seems that if there is anything in stderr, the regex will not match.

I don't understand why we need to concatenate stderr and stdout here. With the existing regex, it seems like we should just match on stdout. However, if we do need to concatenate the two for some reason, the problem could be resolved by removing the "^" in the regex so it looks for Avocado anywhere in the string.

**Comment by clebergnu** [comment]
@jallen-amd according to dfb6f5779bdfe59d5a4958f910d009b74d14b87f (which I had already forgot about), Python 3 will write version info to STDOUT, while Python 2 will write to STDERR.

So, given that Avocado >= 70.0 is Python 3 only, it's safe to drop the stderr from that check.

**Comment by clebergnu** [comment]
Fixed in https://github.com/avocado-framework/avocado/pull/3202
