### ISSUE TITLE
process.system_output returns bytes not string

### ISSUE THREAD

**Issue by jallen-amd** [avocado-framework/avocado#3203]
Running avocado-misc-tests/fs/fsx.py returns ERROR: a bytes-like object is required, not 'str'. This seems to be caused by the fact that process.system_output returns bytes rather than a decoded string. Reading through the code, it's unclear what the correct behavior here should be. I would assume that if avocado-misc-tests has assumed in the past that a string is returned from process.system_output, that we should keep things consistent and decode the results before returning them.

**Comment by PraveenPenguin** [comment]
@jallen-amd are you tried on python3 ? if yes we are trying to move our all test cases (https://github.com/avocado-framework-tests/avocado-misc-tests ) on python3 in meanwhile i will request you please try with python2 and corresponding  avocado you need to have 68.LTS 
`https://github.com/avocado-framework/avocado/tree/69lts` still this LTS has python2 support

**Comment by jallen-amd** [comment]
Yeah, this is with python 3 + avocado 70.0. I will be on the lookout for the python 3 support, thanks.
