### ISSUE TITLE
Re-enable codecov

### ISSUE THREAD

**Issue by clebergnu** [avocado-framework/avocado#3215]
Codecov on Travis had to be disabled in 857a1c9104646e58c98eb4a5c4e11ed7e31f7b29 due to constant job failures.  Let's attempt to reproduce the failure and re-enable it.

@ldoktor FIY.

**Comment by ldoktor** [comment]
Hello @clebergnu, I don't see any hangs on my testing repo. Wasn't it some transient issue?

**Comment by ldoktor** [comment]
The only hanged check I found is this one: https://travis-ci.org/avocado-framework/avocado/jobs/562611851 and after re-trigger it succeeded.

**Comment by clebergnu** [comment]
@ldoktor two PRs that were active at the time were constantly failing... there are two references (one from each PR) in the commit that temporarily disabled it.

I'll re-enable it and keep an eye on it.  Closing this for now.
