### ISSUE TITLE
Unable to load plugins

### ISSUE THREAD

**Issue by Resisty** [avocado-framework/avocado#3232]
Hello,

My team has been using a specially-packaged version (49) of avocado-framework for a while now but we're trying to figure out how to update it and I can't seem to get plugins to be available. I'm currently playing around with v70.0 in python 3.6.

Specifically, the yaml_to_mux plugin in optional_plugins. I've tried registering it with its setup.py script as well as just using pip to install `avocado-framework-plugin-varianter-yaml-to-mux`.

However, I can't find it under any of the modules/packages. For example:

```
>>> import avocado.plugins.varianter.yaml_to_mux
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'avocado.plugins.varianter'
>>> import avocado.plugins.varianter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'avocado.plugins.varianter'
>>>
```

Am I just looking in the wrong place? I can see avocado-framework and the plugin are both present in site-packages, but no dice.

Thanks very much for your time!

**Comment by clebergnu** [comment]
IIRC you're looking for `avocado_varianter_yaml_to_mux` which is the Python module name.

**Comment by Resisty** [comment]
@clebergnu ugh, thanks so much!
