### ISSUE TITLE
Avocado test doesn't prompt for the user input.

### ISSUE THREAD

**Issue by StorageGig** [avocado-framework/avocado#3302]
Hi @clebergnu ,
I've some code where I want the user input in between the test. In python3 we use the input() function. But it is not working with avocado test.
I've found in utils.genio there is ask function which also using the input()....Same function also I tried to execute but both marks error with "EOF when reading a line". This error is expected because it didn't prompt.
Would help me how to use input() in avocado test...Or how the genio.ask() function works.??

`from avocado import Test

class Test_UserInput(Test):

    def setUp(self):
        self.log.info("In Setup")

    def test_ask(self):
        a = input("Enter your name")
        self.log.info(a)
`

**Comment by clebergnu** [comment]
Hi,

Please refer to https://avocado-framework.readthedocs.io/en/71.0/ReferenceGuide.html#test-execution-environment for a discussion on the environment that is given to a running test.  Given that Avocado is a test *automation* framework, it's supposed to be non-interactive.  Consider passing input as parameters or external files.

Please feel free to reopen this issue if there's anything you need to know.

Thanks.
