### ISSUE TITLE
sysinfo not working when installing from pip

### ISSUE THREAD

**Issue by beraldoleal** [avocado-framework/avocado#3353]
If you install avocado from pip and run a basic test, sysinfo plugin will not collect information because of default paths on the config file.

How to reproduce?
```
$ pip3 install --user avocado-framework
$ avocado run /bin/true
$ ls -la $HOME/avocado/job-results/latest/sysinfo/pre/
```

Creating a symlink from /etc/avocado/ pointing to pip env avocado path it will fix the problem. But I think that we should improve this without the symlink.

**Comment by clebergnu** [comment]
Fixed in #3381
