### ISSUE TITLE
-p/--test-parameter not passed to remote host when using remote runner

### ISSUE THREAD

**Issue by jallen-amd** [avocado-framework/avocado#3354]
Attempting to run some remote test with the -p flag seems to fail to pass those parameters.

avocado run --remote-hostname <my_host> --remote-username <my_name> /path/to/test -p foo="bar"

Seems to give generate the following command on the remote host:

L0381 INFO | Command line: /usr/local/bin/avocado run --force-job-id <some_job_id>
 --json - --archive /path/to/test

I would expect the avocado remote runner to just run the test as if I were running it from the command line of the remote host. Is there something I'm missing here to ensure that all parameters get passed to the remote host?

**Comment by clebergnu** [comment]
Hi @fj-sanchez, we've decided to deprecate the docker runners, and consequently will not fix this and related issues.  See #3799.

As a heads up, a preliminary experimental container (podman) support exists in the `nrun` command via `--podman-spawner` option, and it's expected that it will evolve a lot in the upcoming releases.
