### ISSUE TITLE
BP001: Fix boolean command line options

### ISSUE THREAD

**Issue by beraldoleal** [avocado-framework/avocado#3440]
Related to #3427

**Comment by beraldoleal** [comment]
We need to insert a "deprecation message" before start working on this.

**Comment by pevogam** [comment]
Just writing down a note here: we have to possibly check all values that will turn into pure boolean for checks throughout the code that are aware of this and are not doing string comparisons like for instance `option != 'on'`.

**Comment by pevogam** [comment]
Hi @beraldoleal, I think you have achieved this conversion already and it remains to test for corner cases in the 82 LTS, thus you could close this if you want.

**Comment by beraldoleal** [comment]
@pevogam We still have a few options to migrate. And is one of the first things to do after lts.

**Comment by pevogam** [comment]
I see, alright then at least when it comes to the sysinfo problem I previously reported - all of it is fixed now.
