### ISSUE TITLE
Design a Requirements Resolver Blueprint

### ISSUE THREAD

**Issue by clebergnu** [avocado-framework/avocado#3455]
Tests usually depend on various types of requirements, such as:
* files to be downloaded and kept in accessible location (caching it is a common optimization)
* packages to be installed in the system (and thus a given functionality or specific files available)
* images, such as cloud operating system guest images
* O.S. level configuration, such as max number of open files or maximum size of stack 

Right now tests will handle requirements by themselves, in an ad-hoc way, usually within the `setUp()` or even `test()` methods themselves.

Avocado currently partially solves some of these use cases, but through non-uniform interfaces:
 * files can be downloaded via `avocado asset` commands or `avocado.utils.asset` APIs
 * images can be downloaded via `avocado vmimage` command or `avocado.utils.vmimage` APIs

The goal of this issue is to implement a generic and reusable mechanism based on the definition of requirement *types*, and necessary additional information (such as URLs, package names, etc) that a test can declare and whose fulfillment will be attempted by a Job-level component (to be named, such as "Requirements Fulfillment Agents").

The collection of those definitions, henceforth simply called requirements, can/should be gathered at test resolution time.  A proposal for the source of requirements follows:

```
cabort.py
cabort.py.requirements/
├── CAbort.test_2
│   └── requirements.py
└── requirements.json
```

If `requirements.json` exists in a test data directory, it will be gathered for all tests under `cabort.py`.  If an executable `requirements.*` file exists under `CAbort.test_2`, it will be gathered for that specific test.

A `requirements.json` file could look like:

```json
[
 {"type": "url", "url": "https://cabort.com/cabort.c", "hash": "deadbeefdeadbeef"},
 {"type": "vmimage", "distro": "fedora", "version": 31, "arch": "x86_64"},
 {"type": "package", "name": "lvm"}
]
```

And an executable `requirements.py` could be implemented like:

```python
#!/usr/bin/python3

import os
import json

requirements = [
 {"url": "https://cabort.com/cabort.c", "hash": "deadbeefdeadbeef"},
 {"distro": "fedora", "version": 31, "arch": os.uname()[4]},
 {"package": "lvm"}
]

print(json.dumps(requirements))
```

The Job should collect all requirements, and upon fulfillment of all of a test's requirements, should commence its execution.  If any requirement can not be fulfilled, the test should be skipped by the Job.

**Comment by willianrampazzo** [comment]
Blueprint approved and merged!
