### ISSUE TITLE
Try to reduce the scope of (manual) release test plan

### ISSUE THREAD

**Issue by beraldoleal** [avocado-framework/avocado#3456]
Right now, before every release, we're supposed to run the "manual release test plan" with:

```
python3 scripts/avocado-run-testplan -t examples/testplans/release.json
```

There has already been work to reduce the manual steps, and automate as much as possible.  The goal of this card is to look for opportunities to further reduce the manual steps and increase automation.

**Comment by beraldoleal** [comment]
More information on our (deprecated) trello card:

https://trello.com/c/hOEd6Hzz/1545-try-to-reduce-the-scope-of-manual-release-test-plan

**Comment by ana** [comment]
> More information on our (deprecated) trello card:
> 
> https://trello.com/c/hOEd6Hzz/1545-try-to-reduce-the-scope-of-manual-release-test-plan

 If it is still relevant, could you please share the information of that card here?

**Comment by willianrampazzo** [comment]
> > More information on our (deprecated) trello card:
> > https://trello.com/c/hOEd6Hzz/1545-try-to-reduce-the-scope-of-manual-release-test-plan
> 
> If it is still relevant, could you please share the information of that card here?

The information is the same as the description of this issue @ana.
