### ISSUE TITLE
Design Job API Blueprint or RFC

### ISSUE THREAD

**Issue by beraldoleal** [avocado-framework/avocado#3459]
More information, on our (deprecated) trello card:

https://trello.com/c/hRmShGIp/671-rfc-job-api

**Comment by willianrampazzo** [comment]
I think the Job API is advanced in development, and with the Release 81 objective of maturing it, I don't think this issue is needed anymore.

@beraldoleal, @clebergnu any thoughts?

**Comment by beraldoleal** [comment]
@willianrampazzo +1

**Comment by willianrampazzo** [comment]
Closing. Reopen if needed.
