### ISSUE TITLE
Move "filter-by-tag" to loaders

### ISSUE THREAD

**Issue by willianrampazzo** [avocado-framework/avocado#3465]
Currently, the "filter-by-tag" feature takes action after the discovery on the resulting suite, but after the discussion on ML, it makes sense to re-evaluate and move this to loaders instead, perhaps directly to discovery.

The benefits would be:

1. possibility to adjust the base implementation (eg. translate the filters to something the loader understands. Might allow using filters in Avocado-vt) or simply ignore them when not supported and avoid the unnecessary processing.
2. would allow to define per-variant tags when using yaml_loader or later in Job API

**Comment by willianrampazzo** [comment]
Is this issue still valid?

**Comment by clebergnu** [comment]
The loaders are not even a valid concept/component anymore, so let's close this issue.
