### ISSUE TITLE
Support as much lint checks as possible

### ISSUE THREAD

**Issue by willianrampazzo** [avocado-framework/avocado#3466]
Right now, the lint check enables a subset of message, report, category or checker ids.

It is desirable to enable as many checkers as possible.

This issue will track the enablement of lint verifications.

**Comment by willianrampazzo** [comment]
Backlog from deprecated Trello Board: https://trello.com/c/ZWd5rHkq/1550-enable-pylint-w0511-fixme-fixme-w0511

Enable W0511.

**Comment by tiagohonorato** [comment]
Hi @willianrampazzo, it seems that there are some checks that could be enabled without additional changes in the code base. Is it ok if I send a PR enabling those?

**Comment by beraldoleal** [comment]
@tiagohonorato feel free to send any PR anytime.

**Comment by tiagohonorato** [comment]
@willianrampazzo and @beraldoleal, what are your thoughts on enabling python3 checker messages? At first, I thought it would be useful to alert about python2 deprecated built-in such as `file`, `reduce`, but it might be unnecessary. Another check that could be enabled is for methods that return an iterator in python3 being used outside an iterator context (e.g. `dict.keys` returns iterator and not list as in python 2). Most of the time it should be fine, but... Just wanted to get your view on this :).

**Comment by beraldoleal** [comment]
@tiagohonorato this is something nice to have, but since we still support python2 maybe we could wait a little more. Not sure.

Did you had the chance to investigate how much work will be necessary to get away from those warnings?

**Comment by clebergnu** [comment]
> @tiagohonorato this is something nice to have, but since we still support python2 maybe we could wait a little more. Not sure.
> 

Wait, what? From `setup.py`:

```python
              "Programming Language :: Python :: 3",
              "Programming Language :: Python :: 3.5",
              "Programming Language :: Python :: 3.6",
              "Programming Language :: Python :: 3.7",
              "Programming Language :: Python :: 3.8",
...
   python_requires='>=3.4',
...
```

So Python 2 should not be an issue.

> Did you had the chance to investigate how much work will be necessary to get away from those warnings?

**Comment by beraldoleal** [comment]
@tiagohonorato my bad. I got completely confused here. Maybe too little coffee at the end of a busy day. So, please ignore my comment.

**Comment by tiagohonorato** [comment]
> @tiagohonorato my bad. I got completely confused here. For some reason (maybe too little coffee at the end of a busy day), I thought that we were still testing with python2.7. But yes, we dropped python 2 last year. So, please ignore my comment.

@beraldoleal no worries :) ! 

> Wait, what? From `setup.py`:
> 
> ```python
>               "Programming Language :: Python :: 3",
>               "Programming Language :: Python :: 3.5",
>               "Programming Language :: Python :: 3.6",
>               "Programming Language :: Python :: 3.7",
>               "Programming Language :: Python :: 3.8",
> ...
>    python_requires='>=3.4',
> ...
> ```
> 
> So Python 2 should not be an issue.

thanks @clebergnu!


> @tiagohonorato this is something nice to have, but since we still support python2 maybe we could wait a little more. Not sure.
> 
> Did you had the chance to investigate how much work will be necessary to get away from those warnings?

I have enabled some in the last PR, but I was reflecting a bit more if it would be indeed beneficial or not in the long run before going forward with others (python3 checker messages are disable by default on pylint). Regarding the amount of work, I believe it won't take too much effort for the most part. I will try to send a PR today enabling some and we can continue evaluating which would be beneficial.

**Comment by clebergnu** [comment]
Actually I noticed that the version info I posted revealed a problem with `python_requires`.  Fix in https://github.com/avocado-framework/avocado/pull/4403 .
