### ISSUE TITLE
Migrate imp lib to importlib

### ISSUE THREAD

**Issue by beraldoleal** [avocado-framework/avocado#3468]
Deprecated since version 3.4: The imp package is pending deprecation in favor of importlib.

https://docs.python.org/3.8/library/imp.html

**Comment by willianrampazzo** [comment]
As a reminder:

```
$ grep -nRw "import imp"
avocado/core/safeloader.py:22:import imp
avocado/core/loader.py:20:import imp
```

**Comment by tiagohonorato** [comment]
@beraldoleal and @willianrampazzo can I help with the migration to importlib?

**Comment by richtja** [comment]
@tiagohonorato Yes no problem, I will assign it to you.

**Comment by beraldoleal** [comment]
@tiagohonorato, thanks for helping here. Very much appreciated.

Just one side note: Looks like today we are using `imp` only inside `loader.py` and `safeloader.py`, as mentioned by @willianrampazzo . And since we are planning to remove the legacy runner, not sure if is worthed.

But, again, I'm not 100% sure here. @clebergnu can you confirm this, please?

**Comment by clebergnu** [comment]
`safeloader` will remain, it's used in the resolvers too.  So, at least that part, is definitely worth it.

**Comment by willianrampazzo** [comment]
Related PR was merged, so closing this. Thanks @tiagohonorato.
