### ISSUE TITLE
Change parameters names because of lint W0221

### ISSUE THREAD

**Issue by beraldoleal** [avocado-framework/avocado#3469]
In avocado.core.test there are functions `fail()`  `error()` and `cancel()` with disabled pylint W0221. Lets's change that before LTS release. The task is to change the parameter message to msg.

**Comment by beraldoleal** [comment]
Part of #3466 3466

**Comment by ana** [comment]
This was addressed in bbe559c24ac5adddaaed04211080e5a691517de5
