### ISSUE TITLE
Use symbolic `os.path.pardir` instead of `..`

### ISSUE THREAD

**Issue by willianrampazzo** [avocado-framework/avocado#3470]
To support future O.S. compatibility, places where the parent path is referenced as `..` needs to be changed to 'os.path.pardir`.

**Comment by nasirhm** [comment]
I would like to work on it.

**Comment by tiagohonorato** [comment]
Hi @willianrampazzo  and @nasirhm, I noticed that there are also some references to grandparent directory `...`:

```
avocado/utils/software_manager/backends/dnf.py:3:from ... import process
avocado/utils/software_manager/backends/zypper.py:4:from ... import path as utils_path
avocado/utils/software_manager/backends/zypper.py:5:from ... import process
avocado/utils/software_manager/backends/rpm.py:5:from ... import path as utils_path
avocado/utils/software_manager/backends/rpm.py:6:from ... import process
avocado/utils/software_manager/backends/yum.py:8:from ... import data_factory
avocado/utils/software_manager/backends/yum.py:9:from ... import path as utils_path
avocado/utils/software_manager/backends/yum.py:10:from ... import process
avocado/utils/software_manager/backends/dpkg.py:4:from ... import path as utils_path
avocado/utils/software_manager/backends/dpkg.py:5:from ... import process
avocado/utils/software_manager/backends/apt.py:6:from ... import path as utils_path
avocado/utils/software_manager/backends/apt.py:7:from ... import process
```
Do you think those could be an issue in the future? If so, since `os.path` does not go beyond the parent directory, changing from `...` to `....utils` would avoid future compatibility issues?

**Comment by willianrampazzo** [comment]
> Hi @willianrampazzo and @nasirhm, I noticed that there are also some references to grandparent directory `...`:
> 
> ```
> avocado/utils/software_manager/backends/dnf.py:3:from ... import process
> avocado/utils/software_manager/backends/zypper.py:4:from ... import path as utils_path
> avocado/utils/software_manager/backends/zypper.py:5:from ... import process
> avocado/utils/software_manager/backends/rpm.py:5:from ... import path as utils_path
> avocado/utils/software_manager/backends/rpm.py:6:from ... import process
> avocado/utils/software_manager/backends/yum.py:8:from ... import data_factory
> avocado/utils/software_manager/backends/yum.py:9:from ... import path as utils_path
> avocado/utils/software_manager/backends/yum.py:10:from ... import process
> avocado/utils/software_manager/backends/dpkg.py:4:from ... import path as utils_path
> avocado/utils/software_manager/backends/dpkg.py:5:from ... import process
> avocado/utils/software_manager/backends/apt.py:6:from ... import path as utils_path
> avocado/utils/software_manager/backends/apt.py:7:from ... import process
> ```
> 
> Do you think those could be an issue in the future? If so, since `os.path` does not go beyond the parent directory, changing from `...` to `....utils` would avoid future compatibility issues?

The `utils` directory should be really self-contained. The more we avoid ambiguity and future problems, the better.

Changing those you listed will not hurt. Feel free to send a PR if you are willing to. We can have further discussion on it if needed.

**Comment by tiagohonorato** [comment]
@willianrampazzo, I think I misinterpreted your proposal to use `os.path.pardir` at first. The imports would not be affected by using `os.path`. Your suggestion is to replace the references to the string `'..'`, correct?

**Comment by willianrampazzo** [comment]
@tiagohonorato this issue was part of an effort to migrate from Trello. The original card does not say much too, the link is here: https://trello.com/c/CwOBc8q2/734-use-symbolic-ospathpardir-instead-of

If I read correctly, this issue was to find places in the code where there were mentions to `..` instead of using the `os` library. I don't think this issue relates to imports.

I did some greps (`..` is not a fun string to grep) and this is the kind of occurrence we may want to change:

```
optional_plugins/varianter_yaml_to_mux/tests/test_unit.py:BASEDIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
```

Let me know if you have any thoughts on that.

**Comment by tiagohonorato** [comment]
@willianrampazzo I totally agree with you, thanks for the explanation. I did some greps as well (indeed not fun, using `\` seems to do the trick though) and found the following:
```
optional_plugins/varianter_yaml_to_mux/tests/test_unit.py:14:BASEDIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
selftests/unit/test_astring.py:74:        self.assertEqual(astring.string_to_safe_path('..'), "_.")
selftests/__init__.py:10:BASEDIR = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
avocado/utils/pci.py:390:            cfg_dic['YL'] = line.split('..')[-1].strip('.')
```
From those, at first sight, I would say that maybe the first three would be potential candidates. I can take a closer look though.

Additionally, I also have found some occurrences referencing present directory as `'.'`, for instance:

`optional_plugins/golang/avocado_golang/__init__.py:60:    if path != '.':`

Similarly, do you think it would be worth it changing those to `os.path.curdir`?

**Comment by willianrampazzo** [comment]
> @willianrampazzo I totally agree with you, thanks for the explanation. I did some greps as well (indeed not fun, using `\` seems to do the trick though) and found the following:
> 
> ```
> optional_plugins/varianter_yaml_to_mux/tests/test_unit.py:14:BASEDIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
> selftests/unit/test_astring.py:74:        self.assertEqual(astring.string_to_safe_path('..'), "_.")
> selftests/__init__.py:10:BASEDIR = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
> avocado/utils/pci.py:390:            cfg_dic['YL'] = line.split('..')[-1].strip('.')
> ```
> 
> From those, at first sight, I would say that maybe the first three would be potential candidates. I can take a closer look though.
> 

Okay, thank you, I'll leave it up to you to decide :) 

> Additionally, I also have found some occurrences referencing present directory as `'.'`, for instance:
> 
> `optional_plugins/golang/avocado_golang/__init__.py:60: if path != '.':`
> 
> Similarly, do you think it would be worth it changing those to `os.path.curdir`?

Absolutely!

**Comment by willianrampazzo** [comment]
@tiagohonorato do you want me to assign this issue to you?

**Comment by tiagohonorato** [comment]
> @tiagohonorato do you want me to assign this issue to you?

Sure, if @nasirhm is not willing to continue, I would be happy to help!

**Comment by willianrampazzo** [comment]
@tiagohonorato as it's being some time we heard from @nasirhm, I assigned it to you. This should be a simple task.

**Comment by tiagohonorato** [comment]
@willianrampazzo, would be preferable to send the alterations for `os.path.curdir` and `os.path.pardir` in the same PR (different commits) or different PRs?

**Comment by willianrampazzo** [comment]
> @willianrampazzo, would be preferable to send the alterations for `os.path.curdir` and `os.path.pardir` in the same PR (different commits) or different PRs?

You can use the same PR with different commits, no problem. Add a description to the PR explaining what you are changing and it should be good to go.

**Comment by willianrampazzo** [comment]
I think we are good here. Closing as the related PR was merged.
