### ISSUE TITLE
Create a better failure reason for SIMPLE tests

### ISSUE THREAD

**Issue by beraldoleal** [avocado-framework/avocado#3480]
This is how the Human results (the default UI) show failure for SIMPLE tests:

```
avocado run /bin/false
JOB ID     : 4d3f087f53cd75ee71fa516fa0a173b0d2548a5a
JOB LOG    : /root/avocado/job-results/job-2018-12-07T15.18-4d3f087/job.log
 (1/1) /bin/false: FAIL: Command '/bin/false' failed.\nstdout: b''\nstderr: b''\nadditional_info: None (0.02 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 0.16 s
```

It's confusing with those new lines and mixed stdout/stderr/additional_info components.  Let's see how it can be improved.

**Comment by dkarpelevich** [comment]
@beraldoleal The result of the command can be improved to:
```
$ avocado run /bin/false
/home/dkarpele/fork/avocado/avocado/plugins/run.py:287: FutureWarning: The following arguments will be changed to boolean soon: sysinfo, output-check, failfast, keep-tmp and ignore-missing-references.
  FutureWarning)
JOB ID     : 6027ad7ca2f55d29d43d8c6c2635e0e5aed8be4a
JOB LOG    : /home/dkarpele/avocado/job-results/job-2020-04-05T21.26-6027ad7/job.log
 (1/1) /bin/false: FAIL: Command '/bin/false' failed.
stdout: b''
stderr: b''
additional_info: None (0.08 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 0.16 s
JOB HTML   : /home/dkarpele/avocado/job-results/job-2020-04-05T21.26-6027ad7/results.html
```

Need to change `extra = extra.replace('\n', '\\n')` to `extra = extra.replace('\n ', '\\n')` in `avocado/plugins/human.py` line 84. Space after first `\n`.

**Comment by beraldoleal** [comment]
@dkarpelevich actually afaik, we are putting our efforts on our Next Runner (`avocado nrun`). So, maybe this could have a low priority.

@clebergnu?

**Comment by willianrampazzo** [comment]
Is this issue still valid, considering the legacy runner was deprecated?

**Comment by beraldoleal** [comment]
We are redirecting all the logs to the test's log file. Also if is part of a bigger job, at the end we print the failures. So, IMO, this is not valid for the current runner. Please, feel free to reopen.
