### ISSUE TITLE
RFE: add --dir option to avocado run (should work as path where to find tests)

### ISSUE THREAD

**Issue by jscotka** [avocado-framework/avocado#350]
Hi,
I would like to see option --dir what will meas relative path to tests:
I can imagine that situation:
You have it configured in avocado config file, where are test, where to store results, results are okay, but in case of tests it is not familiar to use some absolute paths like:
avocado run /x/y/z/a.py /x/y/z/b.sh
 it would be nice to have possibility to say, there isanother  path where to find test from cmdline like:
avocado run --dir /x/y/z a.py b.sh 

There is also second usage of that - it is good for remote and vm plugin for running tests. For example I have some shared functions for more that one script, what have to be copied to remote machine, then it could be used there. So --dir option cause that whole --dir with tests will be copied there.

     Thanks&Regards
     Honza

**Comment by clebergnu** [comment]
Hi Honza,

Thanks for opening an RFE.

Do you have another use case for `--dir`? I ask this because it looks like it can be achieved just by using a shell construct:

```
 $ avocado run /x/y/x/{a.py,b.sh}
```

So, IMHO, this use case alone is not enough to justify another option in avocado.

**Comment by jscotka** [comment]
Hi,
usecase is to append searching path for tests. In config file I have one path, and this cause to add another path. For example I have tests in /a/ location and /b/ and /c/ location and dynamically I can add dir with curretly developing tests
The most important usecase is for remote/virtual plugins -> this option cause copying whole directory structure instead of only one test.
another thing is, that it is connected with another bugs, what cause inconsintent working with shell scripts and python.

**Comment by ldoktor** [comment]
Hello @jscotka, from you description the main problem is not to find the tests, but to avoid problems solved by the 73a9bfb, am I right? If not please re-open this issue and describe the main issue.
