### ISSUE TITLE
Disable fedora-modular and fedora-updates-modular repos on deployment checks

### ISSUE THREAD

**Issue by clebergnu** [avocado-framework/avocado#3505]
Because unless those repos are disabled, the packages on the `avocado` module will be installed instead of the ones in the COPR or official repos, rendering the check useless.

This is related to https://github.com/avocado-framework/avocado/issues/3502

**Comment by mmathesius** [comment]
You may also want to disable the `rawhide-modular` repo in Rawhide, and `epel-modular` for EPEL8.
