### ISSUE TITLE
Consistent handling of python tests and shell scripts

### ISSUE THREAD

**Issue by jscotka** [avocado-framework/avocado#351]
Hi,
I've found issues with various handling for various test types:
I have tests in /usr/share/avocado/tests directory (default config for root user)
I have there two tests:
   inittest.sh - shell script
   checklogin.py - avocado framework based python

I expected to be able to run command like:
# avocado run  inittest.sh  checklogin.py

Actual situation is that I have to use absolute path for both
# avocado run  /usr/share/avocado/tests/inittest.sh  /usr/share/avocado/tests/checklogin.py
 
or absolute path for inittest and relative without suffix ".py" like
# avocado run  /usr/share/avocado/tests/inittest.sh  checklogin
It is strange and unintuitive 

      Thanks&Regards
      Honza

**Comment by lmr** [comment]
What does scripts/avocado list tell you?

**Comment by jscotka** [comment]
I've was working on that yesterday with ldoktor (I was unableto pinpoint what is wrong). Today I have no access to machine where we was playing with that. I'm reporting bugs today :-)
avocado list shows only python test not bash script like:
checklogin /usr/share/avocado/tests/checklogin.py

**Comment by adereis** [comment]
This has been fixed  either by the commit mentioned by ldoktor above, or, in the worst case, fixed in one of our changes in the handling of tests. simple and instrumented tests should be behaving the same way since long ago. Closing.
