### ISSUE TITLE
Drop Official RPM repos for packages for modular capable distros

### ISSUE THREAD

**Issue by clebergnu** [avocado-framework/avocado#3519]
With the advent of "modular repos", it's possible to have a stream with the latest packages, which is exactly what our "official" repos do.

This is related to: https://github.com/avocado-framework/avocado/issues/3502

**Comment by mmathesius** [comment]
I attempted to document the steps I use when updating the `avocado:latest` module and getting it released to the "modular repos" when a new version of `avocado` is released:

https://github.com/mmathesius/howtos/blob/master/how_to_refresh_avocado_module_for_new_upstream_release.rst

**Comment by clebergnu** [comment]
Hi @mmathesius I've sent a PR to update the latest packages to recently release 79.0.  Please let me know if it looks allright.

**Comment by clebergnu** [comment]
Documentation and release steps now reflect the official distribution repositories.
