### ISSUE TITLE
Consistent handling of python tests and shell scripts (virtual, remote plugin)

### ISSUE THREAD

**Issue by jscotka** [avocado-framework/avocado#352]
Hi,
this issue is similar to:
https://github.com/avocado-framework/avocado/issues/351

There is strange behaviour in case of virtual ar remote plugin.
I have tests in /usr/share/avocado/tests directory (default config for root user)
  inittest.sh - shell script
  checklogin.py - avocado framework based python

I've expected to use: 
 # avocado run --remote-hostname .... inittest.sh checklogin.py

Actual situation is:
usage of: # avocado run --remote-user root --remote-hostname guest ....  checklogin
works more-less well 
Strange is, that location on test by default is /usr/share/avocado/test , on remote machine this test is copied to /root/avocado/tests directory, what is inconsistent and not easy to debug why. 

usage of:
 # avocado run --remote-user root --remote-hostname guest ....  /usr/share/avocado/test/inittest.sh
does not work, because test is copied to /root/avocado/tests and thats why it is not working, but this command cause copying of test to remote machine what is expected.
I have to use
 # avocado run --remote-user root --remote-hostname guest ....  inittest.sh
but only in case test was previously copied to /root/avocado/tests directory

     Thanks&Regards
     Honza

**Comment by ldoktor** [comment]
Hi @jscotka, the locations were normalized in #397 so I'll close this issue. If you disagree with that feel free to reopen it and provide additional feedback.
