### ISSUE TITLE
utils/software_management: Add extract_from_deb and extract_from_rpm operations

### ISSUE THREAD

**Issue by wainersm** [avocado-framework/avocado#3549]
### Context ### 

The QEMU acceptance tests [1] provides some facilities for extracting files from either RPM and Deb packages. Those files are usually compiled Linux kernels that are used on 'boot an VM' kind of tests.

Those facilities are implemented in two methods in the `boot_linux_console.py` test module:
```
extract_from_deb(self, deb, path)

extract_from_rpm(self, rpm, path)
```
 

### Problem ###

Maintain that kind of facility isn't really on the scope of QEMU acceptance tests project, they would be better kept in Avocado. Also it could benefit Avocado users given that those utilities are pretty generic.

### Proposal ###

1) Move `extract_from_[rpm|deb]` to Avocado's `utils/software_management.py` module. 

The `utils/software_management.py` provides the `RpmBackend` and `DpkgBackend` implementations for, respectively, `rpm` and `dpkg` commands. Those backend seems to be good places to put those methods in. Or, alternatively, there could be created classes that represent an *rpm* or *deb* file and provides operations.   
 
2) Improve `extract_from_[rpm|deb]` method

Both methods extract a single file (passed via `path` parameter) but it could be useful to allow extract more than one file at once. Or the user could not even pass `path`, in this case it simply decompress/extract the whole package.

It needs to properly raise an exception or provides other mean to notify the user that the operation failed. 

### References ###

[1] https://github.com/qemu/qemu/tree/master/tests/acceptance

**Comment by willianrampazzo** [comment]
Technically, I see no problem, and I agree that it may benefit the Avocado project. As I know little about the Avocado+QEMU package, I don't know what impacts this change may have on it, so I'm answering just for the Avocado project side.

**Comment by wainersm** [comment]
> Technically, I see no problem, and I agree that it may benefit the Avocado project. As I know little about the Avocado+QEMU package, I don't know what impacts this change may have on it, so I'm answering just for the Avocado project side.

Avocado+QEMU already uses some Avocado utils so it will need just a little adjustment on QEMU side.

**Comment by beraldoleal** [comment]
Also, I know little about Avocado+QEMU. But I'm ok with that, unless I'm missing something.

One suggestion is to create a more generic method that will can the proper one:

```python

def extract_from_package(self, package, path):
  if is_rpm(package):
    return self.extract_from_rpm(package, path)
  elif is_deb(package):
    return self.extract_from_deb(package, path)
  elif:
    raise Exception("Not supported")
```

Not sure if it is really useful, just my two cents here.

**Comment by philmd** [comment]
> One suggestion is to create a more generic method that will call the proper one:
> 
> ```python
> def extract_from_package(self, package, path):
>   if is_rpm(package):
>     return self.extract_from_rpm(package, path)
>   elif is_deb(package):
>     return self.extract_from_deb(package, path)
>   elif:
>     raise Exception("Not supported")
> ```
Good idea!

**Comment by beraldoleal** [comment]
@wainersm, please take a look at #4673 and see if this fits your needs. Let us know if you have any further suggestions/improvements.
