### ISSUE TITLE
Use time.monotonic for timeouts

### ISSUE THREAD

**Issue by koteyur** [avocado-framework/avocado#3565]
Hi! I think it's much better to use [time.monotonic](https://docs.python.org/3/library/time.html#time.monotonic) if it's available (since python 3.3), because it guarantees that time will not decrease.

For example (actually there are a lot of other places): https://github.com/avocado-framework/avocado/blob/master/avocado/utils/wait.py#L25
```diff
-    start_time = time.time()
-    end_time = time.time() + timeout
+    start_time = time.monotonic()
+    end_time = time.monotonic() + timeout
```

**Comment by PraveenPenguin** [comment]
@koteyur seems me good idea +1 from my side

**Comment by clebergnu** [comment]
@koteyur thanks for the suggestion. I've marked this issue as epic, as one may want to do that one module or function at a time.  I've sent one to kickstart it.

**Comment by t0xic0der** [comment]
To address this, we need to find the occurrences of duration calculation and rework them with `time.monotonic()`, right? (If so, I can refer to @clebergnu's recent merge on this issue to begin with but should I make PRs per change or PR for the whole if assigned to?)

**Comment by beraldoleal** [comment]
@t0xic0der yes, we are replacing it with `time.monotonic()`. Ideally, we prefer small PR so will be easier for review and acceptance.

**Comment by t0xic0der** [comment]
Great. I think I would be able to do this. Could you assign this to me?

(By small PR, do you mean one PR per module change?)

**Comment by beraldoleal** [comment]
Yes, I do think so. Maybe you will find out that in order to change something in a specific module you need to also change in other places. Not sure.

**Comment by t0xic0der** [comment]
Alright, if I discover so (and if I have any more questions regarding such recurrent change) - I'd ask here.

**Comment by Darshnadas** [comment]
Is this issue still open? I am a newbie looking for some easy contributions to get started. I would like to work on it too!
