### ISSUE TITLE
[RFC] - Specific log collection ex: some  command execution or collect log file  when test failed 

### ISSUE THREAD

**Issue by PraveenPenguin** [avocado-framework/avocado#3567]
Hi 
  We are looking library support which enables to run the specific command when test execution Failed, One way we are thinking can be like an optional plugin like sysinfo can be configurable and used by Global Test run execution and collect The logs or
run some commands if the only test failed or error out. this can be an extension of sysinfo or a new plugin.
Like example:  In Our Test bucket if the test failed in RHEL distro we want to run sos-report and capture dmesg or can be other commands 
and logs.

If it is enabled we can enable on avocado runs and based on a fail case we can get those relevant logs so we need to not to touch test cases to have this improvement

**Comment by PraveenPenguin** [comment]
@clebergnu @ldoktor @beraldoleal  @willianrampazzo any input, please

**Comment by beraldoleal** [comment]
Hi @PraveenPenguin, did you looked into the `sysinfo.collectibles` section on configuration file?

`files` and `profilers` do not work for you, in this case?

**Comment by PraveenPenguin** [comment]
@beraldoleal thanks for the reply , yes it should what is point can we have same  kind of implementation having some extra library if needed which full fill our requirements and it can help who are looking this kind of support  if all fine we can start adding support

**Comment by narasimhan-v** [comment]
@beraldoleal What really would be helpful is, some collectibles being executed in case a test FAILs (in post only). Your thoughts ?

**Comment by beraldoleal** [comment]
@narasimhan-v @PraveenPenguin, I see and think that might be a useful collectible.

I'm just trying to thinking on a more "generic way". Yes, a plugin can be done and inspect the logs, but I'm wondering if is there any alternative solution. Maybe Avocado could generate an event/hook, like JobPre/JobPost, but also for "JobFail", so we could do this inside syslog.

But I have to confess that I don't know if is possible today or how difficult it is to implement.

@clebergnu do you have any better suggestions here?

**Comment by narasimhan-v** [comment]
> Maybe Avocado could generate an event/hook, like JobPre/JobPost, but also for "JobFail", so we could do this inside syslog.

@beraldoleal That is exactly what we would want, and what I am trying as well.
But syslog does not do anything with the context of job status as of now. So, need comments before we try to do it.

**Comment by narasimhan-v** [comment]
Raised a PR for the same https://github.com/avocado-framework/avocado/pull/3590

**Comment by narasimhan-v** [comment]
This can be closed since https://github.com/avocado-framework/avocado/pull/3923 is merged

**Comment by PraveenPenguin** [comment]
@narasimhan-v thanks for adding this utility as this much needed , @beraldoleal @sathnaga  thanks for your review
