### ISSUE TITLE
Refactoring on utils/configure_network

### ISSUE THREAD

**Issue by beraldoleal** [avocado-framework/avocado#3584]
Today, `utils/configure_network.py` has some methods to check and set network parameters.

Recently few PRs are 'open' trying to add some functionalities, because looks like this module is just a (good) starting point.

In order to avoid lack of convention on functions names and arguments, we need to do a small refactoring on this code, to support:

1. Get IP address from a interface (IPV4 and IPV6);
2. Set IP address on an interface (IPV4 and IPV6) - temporarily and with persistence;
4. Get MTU values from an interface;
5. Set MTU values on an interface (temporarily and with persistence);
6. Get interface states (UP/Down);
7. Get interface speeds;

We could use the `iproute`' `-j` option (a "new" output format) to try to get this in a clean way, in order to keep the code clean.

We should try to avoid duplicated code here.

**Comment by beraldoleal** [comment]
@anascko, @vaishnavibhat, Did I forgot something? What do you think?

**Comment by beraldoleal** [comment]
This is related to #3569 and #3580

**Comment by PraveenPenguin** [comment]
#3605 basic refactor sent as PR, later  will do other refactor  in other PR's
