### ISSUE TITLE
plugins.html: popover info doesn't work on records on pages > 1

### ISSUE THREAD

**Issue by ldoktor** [avocado-framework/avocado#359]
Hi guys, I noticed that the Info popup doesn't work only for first 10 records. The ones on following pages doesn't work. Changing the number of records per page won't help either. Only first 10 of them works.

Reproducer:

#. `./scripts/avocado run passtest passtest passtest passtest passtest passtest passtest passtest passtest passtest this_should_produce_longer_message.py`
#. click on second page
#. click on "Test this_should_produce_longer_message...."

It should display the full message but does nothing at all.

**Comment by adereis** [comment]
Can't reproduce it. Can you better explain the reproduction steps? What do you mean by "info popup"? What do you mean by "display the full message"?

**Comment by ldoktor** [comment]
The latest html plugin doesn't support popup (hover) name, instead it changes the size of the table. So this bug doesn't apply for the new version.
