### ISSUE TITLE
Avocado test gives Test died without reporting the status

### ISSUE THREAD

**Issue by redchief** [avocado-framework/avocado#3621]
`INTERRUPTED: Test died without reporting the status.\nRunner error occurred: Timeout reached\nOriginal status:`

**Comment by PraveenPenguin** [comment]
@redchief can you please elaborate more what exactly you tried as just this line not helping what is the problem

**Comment by clebergnu** [comment]
@redchief ping.

**Comment by redchief** [comment]
Hey, @clebergnu @PraveenPenguin  I'm really sorry about the late reply I was in a remote location and my apologies I can't provide you with more details I lost the logs If I come across the failure again I will update this issue with all of it.
