### ISSUE TITLE
BP001: Convert all add_argument calls to register_options on core/*

### ISSUE THREAD

**Issue by beraldoleal** [avocado-framework/avocado#3650]
With the new model used to register "configuration options" we need to finish the job that was started on `plugins/*`.

Basically, we need to replace `parser.add_argument()` calls with `settings.regiter_option()` on `core/*`.

Currently, we have 23 calls on `core/*`.

To find all calls, run:

```bash
$ grep "add_argument(" avocado/core/* -R 
```
This is part of #3443

**Comment by beraldoleal** [comment]
@clebergnu, looks like we are done here. The missing ones are:

 - `-r` and `-d` on `core/job.py`; (This will be deprecated soon);
 - `v` and `--config` (IMO, makes no sense to migrate those two;
 - core/nrunner.py (since that is a standalone runner we can keep it, right?)


Can you please double-check?

**Comment by clebergnu** [comment]
> @clebergnu, looks like we are done here. The missing ones are:
> 
> * `-r` and `-d` on `core/job.py`; (This will be deprecated soon);

The standalone feature has been deprecated, so OK.

> * `v` and `--config` (IMO, makes no sense to migrate those two;

OK.

> * core/nrunner.py (since that is a standalone runner we can keep it, right?)
> 

OK.

> Can you please double-check?

Sounds good to me.
