### ISSUE TITLE
BP001: Convert all add_argument calls to register_options on optional_plugins/*

### ISSUE THREAD

**Issue by beraldoleal** [avocado-framework/avocado#3651]
With the new model used to register "configuration options" we need to finish the job that was started on `plugins/*`.

Basically, we need to replace `parser.add_argument()` calls with `settings.regiter_option()` on `optional_plugins/*`.

Currently, we have 43 calls on `optional_plugins/*`.

To find all calls, run:

```bash
$ grep "add_argument(" optional_plugins/* -R 
```
This is part of #3443

**Comment by beraldoleal** [comment]
@clebergnu:

Just to confirm, we do have 20 old calls here on `optional_plugins/`, but are related to `runner_docker`, `runner_remote` and `runner_vm`. afaik we can close this.

Any objections to leave those calls there, since that those plugins are going to be deprecated?

**Comment by clebergnu** [comment]
> @clebergnu:
> 
> Just to double-check, we do have 20 old calls here on `optional_plugins/`, but are related to `runner_docker`, `runner_remote` and `runner_vm`. afaik we can close this.
> 
> Any objections to leaving those calls there, since that those plugins are going to be deprecated?

No objections, sounds like a plan.
