### ISSUE TITLE
BP001: Remove avocado.conf template and defaults.py

### ISSUE THREAD

**Issue by beraldoleal** [avocado-framework/avocado#3654]
This could be generated automatically with the new model. To avoid chaos, we need to remove them when all migrations are finished.

This is part of #3443

**Comment by beraldoleal** [comment]
@clebergnu About "template files": we have here some `.conf` files inside `avocado/etc/avocado/` and based on #3884 discussion, I just would like to double-check that we should delete those files. 

Since that all options have a default value during the `register_option()`, I have a feeling that there is no problem, right? It will be one less place to update "help msgs"

What do you think?

**Comment by clebergnu** [comment]
> @clebergnu About "template files": we have here some `.conf` files inside `avocado/etc/avocado/` and based on #3884 discussion, I just would like to double-check that we should delete those files.
> 
> Since that all options have a default value during the `register_option()`, I have a feeling that there is no problem, right? It will be one less place to update "help msgs"
> 
> What do you think?

Let's go ahead and remove them.
