### ISSUE TITLE
Arm64 Server with 128Gb ram cannot pass memory/numa_test.py case 3: test_thp_compare

### ISSUE THREAD

**Issue by ZYV037** [avocado-framework/avocado#3668]
memory/numa_test.py case 3: test_thp_compare

arch: arm64 
kernel: linux4.19.0-arm64-server
server with 128Gb ram cannot pass this check.

root@uos-PC:/home/uos/zhangya/avocado-misc-tests/memory/numa_test.py.data# ./bench_movepages -n 100
src node = 0 and dest node = 1
THP migration time(seconds) (Non THP = 0) = 0.008513
Base migration time(seconds) (Non THP = 1) = 0.016090
Base page migration took more time
[job-2020-03-23T23.zip](https://github.com/avocado-framework/avocado/files/4370242/job-2020-03-23T23.zip)

**Comment by willianrampazzo** [comment]
@ZYV037 is it possible to attach the logs of the test run here?

**Comment by ZYV037** [comment]
> @ZYV037 is it possible to attach the logs of the test run here?

attached.

**Comment by ZYV037** [comment]
> @ZYV037 is it possible to attach the logs of the test run here?

attached.

**Comment by clebergnu** [comment]
@ZYV037 this line seems to be the key:

```
2020-03-23 23:12:12,106 process          L0458 DEBUG| [stderr] Base page migration took more time
```

Which, as per the test logic, is an error, see:

```c
        if (bp_time >= thp_time)
                errmsg("Base page migration took more time\n");
```

Then `errmsg` exists with 1, which results in:

```
2020-03-23 23:12:12,126 process          L0714 INFO | Command './bench_movepages -n 100' finished with 1 after 2.16835999489s
```

Which is propagated as a test failure.  I don't see this is an Avocado issue.  Please open an issue with https://github.com/avocado-framework-tests/avocado-misc-tests instead.

Thanks!
