### ISSUE TITLE
N(ext) Runner: fully integrate into the Avocado Job and command line app

### ISSUE THREAD

**Issue by clebergnu** [avocado-framework/avocado#3700]
Even though the nrunner provides an integration into the Avocado job and command line application, it's currently very rough and full of limitations.  The goal of this issue is to have the nrunner completely integrated so that it can be used with all features present in the Avocado command line application such as:
 * Result formats
 * Job replay
 * Pre/Post plugins

When that is achieved, we'll consider switching the default runner to be the nrunner, and after that, removing the "legacy" runner.

**Comment by beraldoleal** [comment]
@clebergnu did you closed this but moved to "in progress". Should we reopen this?

**Comment by clebergnu** [comment]
Yes, please!

**Comment by clebergnu** [comment]
The missing items on this epic will be addressed post 82.0 LTS.

**Comment by clebergnu** [comment]
We're considering this epic to have been achieved, and the current three issues (#3877, #3870, #3867) that are open and reference this epic, are now being handled on its own.
