### ISSUE TITLE
N(ext) Runner: provide a task spawner/scheduler API

### ISSUE THREAD

**Issue by clebergnu** [avocado-framework/avocado#3701]
The current implementation of the `nrun` plugin and command spawns tasks in a very ad-hoc manner, and then leaves the responsibility of finishing the `nrun` execution to an instance of an StatusServer.

While this has been working for our own purposes inside the `nrun` command to run Avocado's own selftests, it's not mature, tested and reliable enough to be provided as a feature that to all Avocado users.

Now with the recent addition of some task "aliveness" tracking on nrunner, we can have a spawner/scheduler that knows about the tasks and works in coordination with the status/results collection.

This is part of #3700.

**Comment by beraldoleal** [comment]
I'm assuming that this is part of the Scheduler blueprint design .

**Comment by pevogam** [comment]
Hi both, I assume this is planned for release 82 as 81 focuses on the new settings module? Would you be interested in me contributing an LXC spawner either in coordination or after some progress with this issue? Finally, are accepted blueprints like 002 (the scheduler) still extendable, amendable, or possible to further comment on in any way?

**Comment by willianrampazzo** [comment]
> Hi both, I assume this is planned for release 82 as 81 focuses on the new settings module? Would you be interested in me contributing an LXC spawner either in coordination or after some progress with this issue? Finally, are accepted blueprints like 002 (the scheduler) still extendable, amendable, or possible to further comment on in any way?

BP003 is still open for comments, feel free to add your suggestions there. I still have to add mine.

**Comment by clebergnu** [comment]
With the [TaskStateMachine](https://github.com/avocado-framework/avocado/pull/4129/commits/b6284d703efc64041afd35c0f2663b55a3e5076c) part of #4129, I believe this specific issue is done.  The one about the integration of the nrunner to the job as been "revived" and put into the milestone for release 81.0.

**Comment by pevogam** [comment]
> > Hi both, I assume this is planned for release 82 as 81 focuses on the new settings module? Would you be interested in me contributing an LXC spawner either in coordination or after some progress with this issue? Finally, are accepted blueprints like 002 (the scheduler) still extendable, amendable, or possible to further comment on in any way?
> 
> BP003 is still open for comments, feel free to add your suggestions there. I still have to add mine.

Hi @willianrampazzo, can you point me to the specific open issue where we can comment? I am not sure I can easily find it and the best candidate to comment in is #3735. Is this the best choice to discuss more about the current blueprint?

**Comment by willianrampazzo** [comment]
> > > Hi both, I assume this is planned for release 82 as 81 focuses on the new settings module? Would you be interested in me contributing an LXC spawner either in coordination or after some progress with this issue? Finally, are accepted blueprints like 002 (the scheduler) still extendable, amendable, or possible to further comment on in any way?
> > 
> > 
> > BP003 is still open for comments, feel free to add your suggestions there. I still have to add mine.
> 
> Hi @willianrampazzo, can you point me to the specific open issue where we can comment? I am not sure I can easily find it and the best candidate to comment in is #3735. Is this the best choice to discuss more about the current blueprint?

Hi @pevogam, it was here: https://github.com/avocado-framework/avocado/pull/4085

**Comment by pevogam** [comment]
> > > > Hi both, I assume this is planned for release 82 as 81 focuses on the new settings module? Would you be interested in me contributing an LXC spawner either in coordination or after some progress with this issue? Finally, are accepted blueprints like 002 (the scheduler) still extendable, amendable, or possible to further comment on in any way?
> > > 
> > > 
> > > BP003 is still open for comments, feel free to add your suggestions there. I still have to add mine.
> > 
> > 
> > Hi @willianrampazzo, can you point me to the specific open issue where we can comment? I am not sure I can easily find it and the best candidate to comment in is #3735. Is this the best choice to discuss more about the current blueprint?
> 
> Hi @pevogam, it was here: #4085

Hi @willianrampazzo, I mean BP002 here and not BP003, specifically the blueprint about the requirements resolver that I think you authored. Sorry for misleading you here, I was actually thinking of finding the correct issue or place to still comment on the possibilities about the requirements resolver introduced there.

**Comment by willianrampazzo** [comment]
> > > > > Hi both, I assume this is planned for release 82 as 81 focuses on the new settings module? Would you be interested in me contributing an LXC spawner either in coordination or after some progress with this issue? Finally, are accepted blueprints like 002 (the scheduler) still extendable, amendable, or possible to further comment on in any way?
> > > > 
> > > > 
> > > > BP003 is still open for comments, feel free to add your suggestions there. I still have to add mine.
> > > 
> > > 
> > > Hi @willianrampazzo, can you point me to the specific open issue where we can comment? I am not sure I can easily find it and the best candidate to comment in is #3735. Is this the best choice to discuss more about the current blueprint?
> > 
> > 
> > Hi @pevogam, it was here: #4085
> 
> Hi @willianrampazzo, I mean BP002 here and not BP003, specifically the blueprint about the requirements resolver that I think you authored. Sorry for misleading you here, I was actually thinking of finding the correct issue or place to still comment on the possibilities about the requirements resolver introduced there.

Oh, okay, the BP002 text was approved and merged a long time ago. 

One possibility I can think for you to add your concerns is to comment on the follow on PRs when the implementation starts. Another possibility is to open an issue as an RFC for discussion on the current BP002 text.

**Comment by pevogam** [comment]
> One possibility I can think for you to add your concerns is to comment on the follow on PRs when the implementation starts. Another possibility is to open an issue as an RFC for discussion on the current BP002 text.

I don't object the BP002 text and suggestions per se, I was rather thinking of adding some additional suggestions. My intention w.r.t. this blueprint is rather to talk about extensions. Perhaps I could start an email thread about it, we will see. Thanks for the hints though!
