### ISSUE TITLE
utils/network: Many backup files are created on `sysconfig` dir

### ISSUE THREAD

**Issue by smruti77** [avocado-framework/avocado#3714]
/etc/sysconfig/network-scripts
inside this directory full of backup files.it should delete backup file while we will do remove_ipaddr().
```
ifcfg-bondtest.backup-1585819801.4519713     ifcfg-enP6p1s0f0.backup-1585889982.282879   ifcfg-enP6p1s0f0.backup-1586406687.8948472
ifcfg-bondtest.backup-1585820361.699254      ifcfg-enP6p1s0f0.backup-1585889985.271053   ifcfg-enP6p1s0f0.backup-1586406961.5345345
ifcfg-bondtest.backup-1586167871.5785477     ifcfg-enP6p1s0f0.backup-1585889988.275528   ifcfg-enP6p1s0f0.backup-1586407232.998946
ifcfg-bondtest.backup-1586170614.9093783     ifcfg-enP6p1s0f0.backup-1585890062.294873   ifcfg-enP6p1s0f0.backup-1586407365.1111474
ifcfg-bondtest.backup-1586768193.5682418     ifcfg-enP6p1s0f0.backup-1585890064.8301473  ifcfg-enP6p1s0f0.backup-1586407472.0765612
ifcfg-bondtest.backup-1586768905.8884988     ifcfg-enP6p1s0f0.backup-1585890067.3708894  ifcfg-enP6p1s0f0.backup-1586407583.1373181
ifcfg-bondtest.backup-1586770366.6917427     ifcfg-enP6p1s0f0.backup-1585891142.861402   ifcfg-enP6p1s0f0.backup-1586757628.6717095
ifcfg-bondtest.backup-1586770934.6619298     ifcfg-enP6p1s0f0.backup-1585891145.8682017  ifcfg-enP6p1s0f0.backup-1586757632.0771775
ifcfg-enP29p1s0f0                            ifcfg-enP6p1s0f0.backup-1585891148.8602374  ifcfg-enP6p1s0f0.backup-1586757635.4185843
ifcfg-enP29p1s0f0.backup-1585560215.8331306  ifcfg-enP6p1s0f0.backup-1585891179.431062   ifcfg-enP6p1s0f0.backup-1586757638.742648
ifcfg-enP29p1s0f0.backup-1585889979.2905188  ifcfg-enP6p1s0f0.backup-1585891269.5962222  ifcfg-enP6p1s0f0.backup-1586757642.001946
ifcfg-enP29p1s0f0.backup-1585889982.2978003  ifcfg-enP6p1s0f0.backup-1585891355.5022793  ifcfg-enP6p1s0f0.backup-1586757754.5175
ifcfg-enP29p1s0f0.backup-1585889985.285974   ifcfg-enP6p1s0f0.backup-1585891441.5398335  ifcfg-enP6p1s0f0.backup-1586757757.9112947
ifcfg-enP29p1s0f0.backup-1585889988.2911773  ifcfg-enP6p1s0f0.backup-1585891716.56171    ifcfg-enP6p1s0f0.backup-1586757761.2707858
ifcfg-enP29p1s0f0.backup-1585890062.3088048  ifcfg-enP6p1s0f0.backup-1585891719.5628157  ifcfg-enP6p1s0f0.backup-1586757764.6707559
ifcfg-enP29p1s0f0.backup-1585890064.843975   ifcfg-enP6p1s0f0.backup-1585892032.4383867  ifcfg-enP6p1s0f0.backup-1586757768.1042016
ifcfg-enP29p1s0f0.backup-1585890067.3845263  ifcfg-enP6p1s0f0.backup-1585892097.382283   ifcfg-enP6p1s0f0.backup-1586767528.3730009
ifcfg-enP29p1s0f0.backup-1585891142.8764522  ifcfg-enP6p1s0f0.backup-1585892184.410155   ifcfg-enP6p1s0f0.backup-1586767531.835357
ifcfg-enP29p1s0f0.backup-1585891145.8841388  ifcfg-enP6p1s0f0.backup-1585892249.4065187  ifcfg-enP6p1s0f0.backup-1586767895.0719433
ifcfg-enP29p1s0f0.backup-1585891148.8758366  ifcfg-enP6p1s0f0.backup-1585892314.5344334  ifcfg-enP6p1s0f0.backup-1586767898.2704868
ifcfg-enP29p1s0f0.backup-1585891716.5780315  ifcfg-enP6p1s0f0.backup-1585892441.9608173  ifcfg-enP6p1s0f0.backup-1586767994.1088665
ifcfg-enP29p1s0f0.backup-1585891719.578257   ifcfg-enP6p1s0f0.backup-1585892650.929472   ifcfg-enP6p1s0f0.backup-1587010218.3926716
ifcfg-enP29p1s0f0.backup-1585892032.454339   ifcfg-enP6p1s0f0.backup-1585892715.5346057  ifcfg-enP6p1s0f0.backup-1587010228.5789754
ifcfg-enP29p1s0f0.backup-1585892097.3973901  ifcfg-enP6p1s0f0.backup-1585892986.0012848  ifcfg-enP6p1s0f0.backup-1587010352.8018484
ifcfg-enP29p1s0f0.backup-1585892184.4263868  ifcfg-enP6p1s0f0.backup-1585893257.0734038  ifcfg-enP6p1s0f0.backup-1587010362.977213
ifcfg-enP29p1s0f0.backup-1585892249.4218893  ifcfg-enP6p1s0f0.backup-1585893528.046685   ifcfg-enP6p1s0f0.backup-1587011116.7922218
ifcfg-enP29p1s0f0.backup-1585892314.5497296  ifcfg-enP6p1s0f0.backup-1585893799.058233   ifcfg-enP6p1s0f0.backup-1587013445.2057853
ifcfg-enP29p1s0f0.backup-1585892441.9764616  ifcfg-enP6p1s0f0.backup-1585894070.045206   ifcfg-enP6p1s0f0.backup-1587013717.4606736
ifcfg-enP29p1s0f0.backup-1585892650.9456804  ifcfg-enP6p1s0f0.backup-1585894486.5551105  ifcfg-enP6p1s0f0.backup-1587013989.7561984
ifcfg-enP29p1s0f0.backup-1585892715.550851   ifcfg-enP6p1s0f0.backup-1585894757.2661207  ifcfg-enP6p1s0f0.backup-1587014261.9330118
ifcfg-enP29p1s0f0.backup-1585892986.016644   ifcfg-enP6p1s0f0.backup-1585895027.509222   ifcfg-enP6p1s0f0.backup-1587014534.357607
ifcfg-enP29p1s0f0.backup-1585893257.0900197  ifcfg-enP6p1s0f0.backup-1585895297.7657592  ifcfg-enP6p1s0f0.backup-1587014807.2509148
ifcfg-enP29p1s0f0.backup-1585893528.0624614  ifcfg-enP6p1s0f0.backup-1585897042.8844495  ifcfg-enP6p1s0f0.backup-1587015079.7297864
ifcfg-enP29p1s0f0.backup-1585893799.0741394  ifcfg-enP6p1s0f0.backup-1585897120.2157598  ifcfg-env10
```

**Comment by PraveenPenguin** [comment]
@smruti77 yes looks a good idea

**Comment by smruti77** [comment]
@PraveenPenguin we can do in same way, how we are doing in configure_network module.

**Comment by PraveenPenguin** [comment]
ah got it as through interface name we can  you send a patch for this

**Comment by smruti77** [comment]
ok

**Comment by beraldoleal** [comment]
@PraveenPenguin not sure if I understood, can you please provide a code example with the actual and expected scenarios?

**Comment by PraveenPenguin** [comment]
@beraldoleal this PR will solve the purpose 
https://github.com/avocado-framework/avocado/pull/3720/files

**Comment by beraldoleal** [comment]
@PraveenPenguin not exactly...

With the new logic/implementation, everything *should not be* persistent, **unless** specified by the user.

So any method call that has intentions to be persistent should be explicit. For instance, the user should call `interface.save()`

The PR #3720 is not following this logic, and instead, when removing IP address (runtime only) this change will make a move to a backup only, without the IP address changes.

I think that I understood the problem, but we need to improve this to support that. Currently, `save()` method requires an IP address, and this is not much useful when removing IP, I got it.

So maybe, we could change the `save()` to not require the `ip_address`, saving the entire interface with all the current values. The workflow would be something like that:

1. Users change the ip_address, remove, update or change MTU values in runtime only. This is not persistent;

2. *IF* the user would like to persist this, then he/she will call `interface.save()`.

I'm doing this separation, because in some cases, it makes sense to change only for a quick test, in runtime only, and if the users lost the connection to the machine, a simple reboot will bring the interface back with the "official" configuration. Makes sense to you?

**Comment by smruti77** [comment]
@beraldoleal actually when we are calling save() before that we need to call add_ipaddr() other wise its failing.
if in our interface sometime ip is their and  if we will call add_ipaddr() it will fail.so we need save() to call. 
when will run the test that time its create backup.cfg file but its not deleting,we wanted to delete the backup files,other wise its full of backup file in that directory.

**Comment by beraldoleal** [comment]
@smruti77 yes, that is expected. As mentioned bellow.

You need to change the ip address first before save. If you are having problems, or error, please post.

**Comment by beraldoleal** [comment]
@smruti77 about the backup problem, IMO this is another different problem. We could improve the backup method to save only the a few backups. Or implement a different logic. Let's separete the problems here.

**Comment by smruti77** [comment]
> @smruti77 about the backup problem, IMO this is another different problem. We could improve the backup method to save only the a few backups. Or implement a different logic. Let's separete the problems here.

ok

**Comment by smruti77** [comment]
@beraldoleal what we need to do for this problem,we need to fix this.

**Comment by beraldoleal** [comment]
@smruti77, sorry about the delay on this.

So, I was revisiting this issue and basically we have a few things to improve here:

1. With the new module, backups are adding a `time.time()` to the end of the file. This was not happening before, and I agree, maybe it is not the best solution. So a simple fix is to bring back the 'simple backup' method as before. PR #3761 will address this and is related to *this issue*.

2. We need to think of a better and complete solution for the backup system. As I described before with the new model, everything is *ephemeral*, unless users call .save() that will save a configuration file. This must be by Interface. i.e: If we have 3 interfaces and are adding IP addresses to only interface `a` when doing `a.save()`, this must shave only interface settings (and also create a backup of any previous interface file there). That's is the reason Makes sense?
