### ISSUE TITLE
bad path for results for bash scripts (html page)

### ISSUE THREAD

**Issue by jscotka** [avocado-framework/avocado#376]
Hi,
I've scheduled command:
# avocado run --vm --vm-domain $NAME --vm-clean --vm-username root --vm-hostname $IP inittest.sh checklogin.py
VM DOMAIN : checkmachine1-fedora-21-x86_64
VM LOGIN  : root@192.168.122.5
JOB ID    : 8cd8f5aa76c9d3e589ea23e6701ef35dd5d9bf5f
JOB LOG   : /root/avocado/job-results/job-2015-01-30T10.07-8cd8f5a/job.log
JOB HTML  : /root/avocado/job-results/job-2015-01-30T10.07-8cd8f5a/html/results.html
TESTS     : 2
(1/2) /root/avocado/tests/inittest.sh: PASS (87.14 s)
(2/2) checklogin.py: FAIL (10.43 s)
PASS       : 1
ERROR      : 0
NOT FOUND  : 0 
NOT A TEST : 0
FAIL       : 1
SKIP       : 0
WARN       : 0
TIME       : 97.57 s

It is working well, but there is trouble with results there are bad paths for bash scripts (and debug log for that)            links on result.html page
checklogin.py debug log path is:  file:///root/avocado/job-results/latest/test-results/checklogin.py/debug.log
inittest.sh deguh log  path is:          file:///root/avocado/tests/inittest.sh/debug.log
This path for bash (.sh) script is bad and does not exist

      Regards

**Comment by jscotka** [comment]
It is probalby caused by that there is various handling with these types, in result.html page test are shown like:
/root/avocado/tests/inittest.sh
checklogin.py

althought both of them was scheduled with relative path (mentioned in issue description)

**Comment by jscotka** [comment]
In case you would like to try my avocado tests:
https://github.com/jscotka/cockpit/tree/new_test_structure/test/tests
It is dependent on more things.
All steps including avocado run is in 
./setup.py

(You have to run it under root, or have your user under sudoers)

**Comment by adereis** [comment]
fixed a while ago, closing:

https://trello.com/c/oBod7egK/323-bug-html-report-has-broken-debug-log-link-when-using-absolute-paths-for-tests
