### ISSUE TITLE
utils/network:need to handle .backup config file should removed and reset back to original config.

### ISSUE THREAD

**Issue by smruti77** [avocado-framework/avocado#3776]
need to reset back to original config file, we can add this to remove_ipaddr()

**Comment by abdhaleegit** [comment]
I have an interface enP19p96s0f2 and I have sysfs ip configuration ifcfg-enP19p96s0f0 created with
all IP configurations

TYPE=Ethernet
BOOTPROTO=none
NAME=enP19p96s0f0
DEVICE=enP19p96s0f0
ONBOOT=yes
IPADDR=102.10.10.188
NETMASK=255.255.255.0
HWADDR=98:be:94:01:3a:68

After running some network test, the new interface.py utils is messing my config file and in some cases it is deleting my config file. making the interface down

even a Reboot is not restoring my ip config.. which blocks the CI runs

Please make sure the configurations are restored back from saved configuration, once the tests are done

**Comment by PraveenPenguin** [comment]
@smruti77 @abdhaleegit this PR will address this issue as when the test completes  you can call <interfcecallboject>.move_interface_file()

https://github.com/avocado-framework/avocado/pull/3777

**Comment by beraldoleal** [comment]
@smruti77 Thanks for reporting this.

Unfortunately, I was not able to fully understand the problem only by looking at this title and description.
But the PR sent by @PraveenPenguin help me a little bit to understand the problem. 

So please, let's try to improve our next issues title and descriptions with some use detailed descriptions and also on how to reproduce the problem.

**Comment by smruti77** [comment]
> @smruti77 Thanks for reporting this.
> 
> Unfortunately, I was not able to fully understand the problem only by looking at this title and description.
> But the PR sent by @PraveenPenguin help me a little bit to understand the problem.
> 
> So please, let's try to improve our next issues title and descriptions with some use detailed descriptions and also on how to reproduce the problem.

ok
