### ISSUE TITLE
Job API vs results files: Results file formats are only working on command-line

### ISSUE THREAD

**Issue by beraldoleal** [avocado-framework/avocado#3795]
When using the command line `avocado run`, a few results files in different outputs formats  (HTML, JSON, tap, and XML) are generated depending on the number of enabled plugins.

When using the Job API, even explicitly forcing with configuration (ex: `config['run.json.job_result'] = 'on'`) the specific results formats are not generated (I tested with JSON and TAP).

My understanding is that if the user is requesting to generate different formats, via API or via the command-line, the behavior should be the same, otherwise we are going to lost some functionalities when using the Job API.

@cleber, what is your understanding of this with the Next Runner pipeline?

**Comment by clebergnu** [comment]
Hi @beraldoleal, my understanding matches yours: the current behavior is buggy and must be fixed.

The next runner work must not have any influence here. I mean, for the `runner_nrunner` implementation to be successful, the results have to be passed to the job, but it's the job (either via the command line or job API) to generate those files.

Please let me know if my answer is clear enough.

**Comment by clebergnu** [comment]
A further question related to this, and the `future.settings` work this is described here: https://github.com/clebergnu/avocado/commit/d1abc77a5c89963d227affd2f653e610f7116c75

The commit above *forces* the behavior, and it's not intended to be a proposed solution, only a show of an alternative behavior.

The question is whether, by having a plugin *installed*, and by having it defaulting in its configuration (`register_option`) to be active (say `{'run.json.job_output': 'on'}`) if the same behavior (having the results.json generated) should happen when using the Job API, as it happens with the command line.

@beraldoleal @willianrampazzo do you guys have an opinion here?

**Comment by beraldoleal** [comment]
Hi @clebergnu:

Yes, I think that we can go with that proposal. I'm ok with that. My only concern that we should try to be more transparent. Not sure if works, just an idea, but would like to try to hide these details inside the `register_option()` method. So you don't need to do the `else` and the "duplicated code".

**Comment by beraldoleal** [comment]
Actually, IIRC, the `register_option()` was created with that in mind: If `parser` is `None`, ignore all the argparse stuff, and just register the namespace.

**Comment by clebergnu** [comment]
> Actually, IIRC, the `register_option()` was created with that in mind: If `parser` is `None`, ignore all the argparse stuff, and just register the namespace.

That's great, I wasn't expecting that.

One of my further questions and concerns has to do with the fact that, if we do register the options at the "job" layer, what happens at the "avocado run" layer? Will the option register again, this time with a parser and a long option?  This is exactly the point I raised about a week ago in our conversations.  What are your thoughts on that?

**Comment by beraldoleal** [comment]
> One of my further questions and concerns has to do with the fact that, if we do register the options at the "job" layer, what happens at the "avocado run" layer? Will the option register again, this time with a parser and a long option? This is exactly the point I raised about a week ago in our conversations. What are your thoughts on that?

Sorry if I didn't get that and missed it.

I might be wrong and haven't thought much about this, but for me when you register the option it is a "run time registration". So let's assume that we have a code like this:

```python
   parser = get_wathever_parser_here()
   settings.register_option(section='foo',
                                         key='bar',
                                         help_msg='foo help',
                                         default=0,
                                         parser=parser,
                                         long_arg='--foo-bar')
```

With this, the developer is registering the "intention" of a "complete option", but if Avocado is called from the Job API and there is no parser (`parser` will be `None`), then `parser` and `long_arg` will be ignored for this runtime. But when called by the command line, the registration process will happen again but this time using `parser` and `long_arg`.

Makes sense? What I'm missing here?

**Comment by willianrampazzo** [comment]
> > Actually, IIRC, the `register_option()` was created with that in mind: If `parser` is `None`, ignore all the argparse stuff, and just register the namespace.
> 
> That's great, I wasn't expecting that.
> 
> One of my further questions and concerns has to do with the fact that, if we do register the options at the "job" layer, what happens at the "avocado run" layer? Will the option register again, this time with a parser and a long option? This is exactly the point I raised about a week ago in our conversations. What are your thoughts on that?

I think we should definitely establish a hierarchy here to have overlapping options added. We should decide which option should remain if they are the same but from different levels.

**Comment by clebergnu** [comment]
> > One of my further questions and concerns has to do with the fact that, if we do register the options at the "job" layer, what happens at the "avocado run" layer? Will the option register again, this time with a parser and a long option? This is exactly the point I raised about a week ago in our conversations. What are your thoughts on that?
> 
> Sorry if I didn't get that and missed it, @clebergnu.
> 
> I might be wrong and haven't thought much about this, but for me when you register the option it is a "run time registration". So let's assume that we have a code like this:
> 
> ```python
>    parser = get_wathever_parser_here()
>    settings.register_option(section='foo',
>                             key='bar',
>                             help_msg='foo help',
>                             default=0,
>                             parser=parser,
>                             long_arg='--foo-bar')
> ```
> 
> With this, the developer is registering the "intention" of a "complete option", but if Avocado is called from the Job API and there is no parser (`parser` will be `None`), then `parser` and `long_arg` will be ignored for this runtime. But when called by the command line, the registration process will happen again but this time using `parser` and `long_arg`.
> 
> Makes sense? What I'm missing here?

Right now, attempting to register the same option twice will raise a `DuplicatedNamespace` exception, right?

My question are:
1. Should we require that the `job` level code contains command line option?
2. Should we allow the `job` level code to simply set its own options (without command line related arguments)?
3. Should a plugin complement or overwrite a given namespace, adding a parser and long options (for instance)?

It seems to me that the logical, layered approach, is to *not* require job level code to have to provide command line argument handling, so IMO, 1 == No.  And that drives the rest of the questions.

**Comment by clebergnu** [comment]
> > > Actually, IIRC, the `register_option()` was created with that in mind: If `parser` is `None`, ignore all the argparse stuff, and just register the namespace.
> > 
> > 
> > That's great, I wasn't expecting that.
> > One of my further questions and concerns has to do with the fact that, if we do register the options at the "job" layer, what happens at the "avocado run" layer? Will the option register again, this time with a parser and a long option? This is exactly the point I raised about a week ago in our conversations. What are your thoughts on that?
> 
> I think we should definitely establish a hierarchy here to have overlapping options added. We should decide which option should remain if they are the same but from different levels.

OK, so your idea is that the option would be overwritten completely. That seems fine to me, I just wonder if say, the `avocado run` plugin would contain a call with `settings.register_option()` looking very similar (extending) the already existing options. Or if it would share the same call, by import a specific function from the job level module.

It feels more natural to me, to have a "command line plugin" to simply add command line options to an already existing configuration, though.

**Comment by beraldoleal** [comment]
> > > One of my further questions and concerns has to do with the fact that, if we do register the options at the "job" layer, what happens at the "avocado run" layer? Will the option register again, this time with a parser and a long option? This is exactly the point I raised about a week ago in our conversations. What are your thoughts on that?
> > 
> > 
> > Sorry if I didn't get that and missed it, @clebergnu.
> > I might be wrong and haven't thought much about this, but for me when you register the option it is a "run time registration". So let's assume that we have a code like this:
> > ```python
> >    parser = get_wathever_parser_here()
> >    settings.register_option(section='foo',
> >                             key='bar',
> >                             help_msg='foo help',
> >                             default=0,
> >                             parser=parser,
> >                             long_arg='--foo-bar')
> > ```
> > 
> > 
> > With this, the developer is registering the "intention" of a "complete option", but if Avocado is called from the Job API and there is no parser (`parser` will be `None`), then `parser` and `long_arg` will be ignored for this runtime. But when called by the command line, the registration process will happen again but this time using `parser` and `long_arg`.
> > Makes sense? What I'm missing here?
> 
> Right now, attempting to register the same option twice will raise a `DuplicatedNamespace` exception, right?

My question is: where do you need to register twice? Unless I'm missing something, we shouldn't need that.

> My questions are:
> 
>     1. Should we require that the `job` level code contains command line option?

No. Don't make sense to me.
 
>     2. Should we allow the `job` level code to simply set its own options (without command line related arguments)?

I'm not sure if the "job level code", should register options. If we force the Job level code to register the own options, will be a lot of duplicated code.

>     3. Should a plugin complement or overwrite a given namespace, adding a parser and long options (for instance)?

Not sure if I understood here.

> It seems to me that the logical, layered approach, is to _not_ require job level code to have to provide command line argument handling, so IMO, 1 == No. And that drives the rest of the questions.

I guess that what we are trying to accomplish here is to avoiding passing a big config dict to the Job API. If that is the case we have to figure out one better way to register the options. Today we are registering most of them on `configure()` of `CLICmd` classes. And the problem that I can see is that those plugins are only called on the command line execution model.

So maybe create (or use) a more generic class like:

```python
MyPlugin(AvocadoPlugin, CLICmd):
   def configure(self):
      register_option here
```

This would make the registration happen not only on command-line executions. Makes sense?

**Comment by willianrampazzo** [comment]
> OK, so your idea is that the option would be overwritten completely. 

Actually, no, I told we need to decide the hierarchy. Depending on how we decide it, we will overlap, or not :)

My main point is having the layered hierarchy defined and documented to avoid the future mix of solutions.

**Comment by willianrampazzo** [comment]
> It feels more natural to me, to have a "command line plugin" to simply add command line options to an already existing configuration, though.

Yep, I agree with you.

**Comment by willianrampazzo** [comment]
> I think we should definitely establish a hierarchy here to have overlapping options added. We should decide which option should remain if they are the same but from different levels.

Sorry, I meant "considered", not "added" in the previous sentence. So we should define a hierarchy and decide what to do when similar options are added at different levels.

As mentioned before, I agree that command-line options should take precedence.

In case of the same option with added parameters, I'm in favor of considering it just like a _set_ from math set theory.

Hope it is clean now :D

**Comment by beraldoleal** [comment]
@willianrampazzo so I had a talk with cleber on irc, sorry if we didn't start on the channel.

So just to your follow up:

Yes, we concluded that: we need a method to "update" the previously registered option with the command line. So for instance: the core `job.py` (or any other component) would register the option without the "command line parameters". And if a plugin is enabled, like `run` needs to export these settings via command line, then this plugin could call this "update" method to add the command line option.

So, on job.py, for instance:

```python
 settings.register_option('job', 'spawner', 'process', 'help msg')
```

On run.py, we could have something like:

```python
settings.add_argparser_to_option('job', 'spawner', parser, '--spawner')
```

This would solve part of the problem, but we still need to figure out fix the current limitation on our plugins that are using the bsae classe `CLIcmd`. As I described on my previous comment.

What do you think?

**Comment by willianrampazzo** [comment]
> What do you think?

Cool, that is a proposal for a hierarchy and makes sense to me!

**Comment by beraldoleal** [comment]
I have created a PR based on the discussions here,

https://github.com/avocado-framework/avocado/pull/3844
