### ISSUE TITLE
job information persistency: Should we create a new file for spawners information?

### ISSUE THREAD

**Issue by beraldoleal** [avocado-framework/avocado#3796]
Today, we save the job's ID inside the `~/avocado/job-results/latest/id` file. Also, **when** the `jsonresult` plugin is enabled **and** we are using the Avocado command-line an additional  `results.json` it is also saved  (that is enabled by default).

With the things going more asynchronous and distributed using the Next Runner it is helpful to save more and more information about the job execution for further commands/operations consume.

For instance: with the introduction of the Spawners, it is important to persist the name of the spawner that executed the job. So when the user would like to download output files from tests (at any moment), we need to map the job id with the spawner that was used at the time.

One solution would be to save another file named `spawner` just with the spawner name inside the job-results directory. My only concern with this is that we will end up with a lot of small files, and even that this is the 'low level' Unix way to do things (and I really like this approach for some situations) might be a little polluted for the Avocado user.

A second solution would be to have a `job.json` file with all relevant information about the job (id, debuglog, spawner, config used, and any other future need).

A third alternative that I can think is to make `jsonresult` plugin part of the core and always have a `results.json` output file (make it available via any kind of avocado execution and always on).

For a quick fix and implementation, I'm ok with any of those alternatives, but I think that since that we have to work on this and seems that there is no much work here (maybe I'm being naive?) I would like to suggest the second alternative: Json is an easy consuming format and we will concentrate all job information in one file.

Although, I like the third too. Having the `results.json` content all the time sounds like helpful.

@clebergnu, @willianrampazzo  What do you guys think?

**Comment by clebergnu** [comment]
> Today, we save the job's ID inside the `~/avocado/job-results/latest/id` file. Also, **when** the `jsonresult` plugin is enabled **and** we are using the Avocado command-line an additional `results.json` it is also saved (that is enabled by default).
> 

A small comment (in line with the comments on issue #3795) is that the creation of `results.json` (or any other result file or feature) should be consistent across command line and Job API usage.  

> With the things going more asynchronous and distributed using the Next Runner it is helpful to save more and more information about the job execution for further commands/operations consume.
> 

Agreed.

> For instance: with the introduction of the Spawners, it is important to persist the name of the spawner that executed the job. So when the user would like to download output files from tests (at any moment), we need to map the job id with the spawner that was used at the time.
> 

OK, agreed.

> One solution would be to save another file named `spawner` just with the spawner name inside the job-results directory. My only concern with this is that we will end up with a lot of small files, and even that this is the 'low level' Unix way to do things (and I really like this approach for some situations) might be a little polluted for the Avocado user.
> 

Wouldn't that be better kept as part of the job config?  What I mean, is, right now an Avocado job will save `jobdata/config`, but, with the future settings work and config being a dictionary, IMO it makes sense to replace it (with a `JSON` file, so that it can properly represent the dict).

> A second solution would be to have a `job.json` file with all relevant information about the job (id, debuglog, spawner, config used, and any other future need).
> 

This is more in line with my previous point. We just have to understand if there's any runtime information that Avocado generates (that is, it does *not* take from the settings) and that should *also* be saved along. 

> A third alternative that I can think is to make `jsonresult` plugin part of the core and always have a `results.json` output file (make it available via any kind of avocado execution and always on).
> 
> For a quick fix and implementation, I'm ok with any of those alternatives, but I think that since that we have to work on this and seems that there is no much work here (maybe I'm being naive?) I would like to suggest the second alternative: Json is an easy consuming format and we will concentrate all job information in one file.
> 

Agreed, and this is kind of "half way" implemented. We'd just need to switch from an `ini` like config, to the resulting dict/JSON configuration (and possibly fill in a fill voids generated at run time).

> Although, I like the third too. Having the `results.json` content all the time sounds like helpful.
> 
> @clebergnu, @willianrampazzo What do you guys think?

**Comment by beraldoleal** [comment]
@clebergnu this makes complete sense to me, thanks a lot.

I'm submiting a patch to convert `--podman-spawner` to `--spawner=Podman` so we can get that information from `args`/`config` file that is already generated.

Thanks again.
