### ISSUE TITLE
[RFC] Sysinfo collectibles saving only necessary information on post

### ISSUE THREAD

**Issue by narasimhan-v** [avocado-framework/avocado#3843]
In the sysinfo collectibles, the files and commands are logged pre and post each job/test.
While it is good to have all data pre-job, wouldn't it make sense to have only the changed ones to be logged post-job ?

For example,
```
# cat commands
multipath -ll
lvdisplay
```

If multipath config is not altered, but lvm is altered, then it would be better if:
```
# cd $RESULTS/test-results/$TEST/sysinfo/
# ls pre
multipath_-ll
lvdisplay
# ls post
lvdisplay
```

This way, it will be more easier to debug and find what has changed post job/test.

Note: we should still have all the commands / files in the pre section, since it serves as a log purpose to understand the system configuration. Only post section can be optimised as above.

**Comment by harish-24** [comment]
@narasimhan-v Agree to the idea, it is advantageous. From an implementation point of view, would it be possible to detect change in the environment for commands? If we can arrive at a proper mechanism to do so, it would be really helpful.

**Comment by narasimhan-v** [comment]
Yes, since we already have a pre, we can compare it with the files / commands output, and then log only what are necessary.

For clariication: we should still have all the commands / files in the pre section, since it serves as a log purpose to understand the system configuration. Only post section can be optimised.

**Comment by sathnaga** [comment]
@narasimhan-v It is good to have one, and helps for debugging, but there are few things to notice.
1. we need to run commands anyways to know if the value changed( unless if there is any other mechanism to detect)
2. with above understanding it requires a additional process time for each command run to detect if there is change, and that will increase test time, not sure if that is acceptable.

So given that this is definitely going to be helpful, here are my thoughts
1. Test should just log the command outputs and exit
2. we can think of plugin/script that run post jobs run on a folder and eliminate the not changed ones?
3. even if we decide to add it during the job run, it should be controlled by user config, by-default disabled.

**Comment by narasimhan-v** [comment]
@sathnaga 
Config option to control - Agreed.
Config option being disabled by default - Agreed.
Time taken for analysing - How much extra time are we talking about ? These are just file diffs return codes, and deciding yes or no. But the config option kind of makes this discussion pointless.

**Comment by narasimhan-v** [comment]
One way to find if a file is changed or not, is by checking the file modified time, and comparing it against test start time (my guess that it is possible). But this is just for files, and not for commands.

**Comment by sathnaga** [comment]
> Time taken for analysing - How much extra time are we talking about ? These are just file diffs return codes, and deciding yes or no. But the config option kind of makes this discussion pointless.

Agree, config option by-default disabled will not create this issue for normal user.

In-general, considering from framework perspective this is additional event from running testcase, falls under analysis part.
let's think of a simpler testcase taking few seconds, with this enabled it can take it to few mins depends on the number of files.
so we need to be more cautious even if it with user to control via config.

in any case this is going to be useful, just that placement where, when has to be discussed, probably we can measure the time taken, and post it to get more confidence.

**Comment by willianrampazzo** [comment]
I think the idea is really interesting, but I agree with @narasimhan-v, having a plunging that runs on the post-test makes more sense as it can be disabled or enabled at any time.

**Comment by sathnaga** [comment]
> One way to find if a file is changed or not, is by checking the file modified time, and comparing it against test start time (my guess that it is possible). But this is just for files, and not for commands.

yep, that would help for files.
for commands `md5sum` would be one simple way i think of.

**Comment by narasimhan-v** [comment]
https://github.com/avocado-framework/avocado/pull/3924

**Comment by narasimhan-v** [comment]
@sathnaga In a simple test like `sleep 5`, where most files would be duplicates between pre and post, we have this:

Without this feature:
```
real	0m31.863s
user	0m25.546s
sys	0m1.458s

# du -sh /root/avocado/job-results/latest/
424K	/root/avocado/job-results/latest/
```

With this feature:
```
real	0m32.314s
user	0m25.800s
sys	0m1.303s

# du -sh /root/avocado/job-results/latest/
276K	/root/avocado/job-results/latest/
```

So we are looking at **less than 1s extra** for the processing, and a maximum of **35 % lesser space consumption**

**Comment by sathnaga** [comment]
> @sathnaga In a simple test like `sleep 5`, where most files would be duplicates between pre and post, we have this:
> 
> Without this feature:
> 
> ```
> real	0m31.863s
> user	0m25.546s
> sys	0m1.458s
> 
> # du -sh /root/avocado/job-results/latest/
> 424K	/root/avocado/job-results/latest/
> ```
> 
> With this feature:
> 
> ```
> real	0m32.314s
> user	0m25.800s
> sys	0m1.303s
> 
> # du -sh /root/avocado/job-results/latest/
> 276K	/root/avocado/job-results/latest/
> ```
> 
> So we are looking at **less than 1s extra** for the processing, and a maximum of **35 % lesser space consumption**

Yep, this will be a great saving for a long running tests, importantly, without compromising loss of logs.

Thanks for this addition :-)

**Comment by narasimhan-v** [comment]
@willianrampazzo @clebergnu @sathnaga @harish-24 @PraveenPenguin 

I also propose to remove the unchanged files from `pre` as well, so as to be even more helpful for debugging and even lesser disk usage. What say ?

**Comment by sathnaga** [comment]
@narasimhan-v sysinfo data even unaltered would be helpful in some debugging to learn more about the environment which the test was run, so it is not good idea to remove it from pre aswell.

**Comment by narasimhan-v** [comment]
Sure @sathnaga

**Comment by narasimhan-v** [comment]
Closing this, as is done via https://github.com/avocado-framework/avocado/pull/3924
