### ISSUE TITLE
sysinfo.collect.per_test not getting registered in test.py

### ISSUE THREAD

**Issue by narasimhan-v** [avocado-framework/avocado#3873]
https://github.com/avocado-framework/avocado/blob/master/avocado/core/test.py#L298-L303

**Comment by clebergnu** [comment]
@narasimhan-v do you care to explain a bit better the issue? Thanks.

**Comment by narasimhan-v** [comment]
@clebergnu 

This is my avocado.conf file.
```
# grep per_test /usr/local/lib/python3.6/site-packages/avocado_framework-79.0-py3.6.egg/avocado/etc/avocado/avocado.conf 
per_test = True
```

I was checking the per-test sysinfo, and then it did not work at all.
When I checked, it seemed that `job.config.get('sysinfo.collect.per_test')` returned None, as did `job.config.get('sysinfo.collect.enabled')`

```
# avocado run examples/tests/passtest.py examples/tests/failtest.py -S on ;  grep COLLECT /root/avocado/job-results/latest/job.log
JOB ID     : 912a9d45546f34f6ad66b122c9bfb37bbd12d438
JOB LOG    : /root/avocado/job-results/job-2020-06-02T14.40-912a9d4/job.log
 (1/2) examples/tests/passtest.py:PassTest.test: PASS (0.43 s)
 (2/2) examples/tests/failtest.py:FailTest.test: FAIL: This test is supposed to fail (0.47 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 1.60 s
2020-06-02 14:40:48,566 test             L0401 INFO | COLLECT PER TEST: None
2020-06-02 14:40:48,566 test             L0403 INFO | COLLECT ENABLED: None
```

I manually set `self.__sysinfo_enabled = True`, and then the per-test sysinfo works fine. Else, it was only per-job

**Comment by clebergnu** [comment]
@narasimhan-v please let me know if https://github.com/avocado-framework/avocado/pull/3875 works for you.
