### ISSUE TITLE
Use codeclimate test coverage?

### ISSUE THREAD

**Issue by clebergnu** [avocado-framework/avocado#3879]
Codecov has given us not so reliable results, and it requires a separate job execution on Travis. Maybe codeclimate support can be leveraged here?

**Comment by willianrampazzo** [comment]
We can enable it and see how it goes. If it performs well for us, I don't see a reason to do not use it.

**Comment by willianrampazzo** [comment]
Talking about Code Climate, what do you think if we exclude `seftests` or `selftests/unit` and `selftests/functional` from its checks? It usually complains about duplicate code in the unit and functional tests, but we know the reasons.

**Comment by clebergnu** [comment]
#3883 has been merged, and the results look good! Thanks @beraldoleal and @willianrampazzo
