### ISSUE TITLE
docs: Configuration reference has just a few options listed

### ISSUE THREAD

**Issue by beraldoleal** [avocado-framework/avocado#3947]
When running `avocado config reference` on my machine I can see 159 options:

```bash
$ avocado config reference | grep "* Default" | wc -l
159
```
But when visiting the read the docs page, I counted less than 60 options listed.

**Comment by beraldoleal** [comment]
@clebergnu do you have any thoughts here?

**Comment by clebergnu** [comment]
@beraldoleal I can reproduce it... thinking about it.

**Comment by willianrampazzo** [comment]
I'm curious as I could find only 139 `register_options` into Avocado code:

```
avocado.dev]$ grep -IR "settings.register_option" | grep -v "selftests/unit" | grep -v "examples/" | grep -v "avocado/core/settings.py" | grep -v "avocado/core/future/settings.py" | wc -l
139
```

@beraldoleal, where am I missing the 20 other registrations listed in the `avocado config reference`? No hurry, just curiosity on my side.

**Comment by beraldoleal** [comment]
@willianrampazzo maybe some of them it is inside a loop.

**Comment by willianrampazzo** [comment]
> @willianrampazzo maybe some of them are inside loops.

Há, good catch, the plugins registrations are done into a loop!

**Comment by beraldoleal** [comment]
@willianrampazzo that is the reason I'm counting with `avocado config reference` :)

**Comment by beraldoleal** [comment]
Thanks @richtja
