### ISSUE TITLE
Maybe, avocado_variants needs to be registered?

### ISSUE THREAD

**Issue by beraldoleal** [avocado-framework/avocado#3981]
Today we have config.get('avocado_variants') in some places inside avocado source code.

AFAIK, we need to register this option with `settings.register_option()`. If this is true, the challenge here is to create a way to serialize the `Varianter()` class and create a nice namespace for this.

**Comment by beraldoleal** [comment]
@clebergnu what is your understand here? Any suggestion? Comments?

**Comment by clebergnu** [comment]
Hi @beraldoleal, sorry for taking so long to answer here.  I was investigating the possible solutions, and I've already produced some work towards eliminating the need to have `avocado_variants` in the configuration.  See #4031.  I have other patches that I'm preparing to send to resolve this issue.
