### ISSUE TITLE
Unable to run scripts on LINUX platform

### ISSUE THREAD

**Issue by SumeetApigee** [avocado-framework/avocado#400]
We are running our set up on a linux server and facing the following issues while running the avocado script.

avocado --help
Traceback (most recent call last):
  File "avocado", line 25, in <module>
    from avocado.cli.app import AvocadoApp
  File "/tools/avocado/avocado-master/avocado/__init__.py", line 80, in <module>
    config.dictConfig(DEFAULT_LOGGING)
AttributeError: 'module' object has no attribute 'dictConfig'

Any ideas why this will happen ? Does Avocado runs only on Fedora and Obuntu and will not run on plain Linux OS. I tried copying the files mentioned in the error to the scripts folder but no success.

Regards
Sumeet Chawla

**Comment by clebergnu** [comment]
Sumeet, thanks for the report. Although most of the Avocado developers run Fedora, its doesn't have any hard dependecies to a particular distribution.

The error looks more like a Python issue. Can you please provide the Python version you're using?

Thanks again.

**Comment by clebergnu** [comment]
@SumeetApigee ping.

**Comment by SumeetApigee** [comment]
Sorry for replying late. Here is the version of Python

2.6.6 (r266:84292, Nov 21 2013, 10:38:03)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)]

**Comment by SumeetApigee** [comment]
Yeah seems like a python issue as config.dictConfig is available in 2.7.9 but still your inputs are valuable please let me know if you see it is because of something else.

**Comment by SumeetApigee** [comment]
Also it looks like both the errors are dependent on each other somehow as i don't see any reasons for failure for this error:

  File "avocado", line 25, in <module>
    from avocado.cli.app import AvocadoApp

**Comment by clebergnu** [comment]
Avocado is only supported on Python >= 2.7.0.

Please try to run it on that version, and if you have any issues, please report back.

Feel free to reopen this issue if you still find any issues while running on Python >= 2.7.0.

Thanks.
