### ISSUE TITLE
[BUG - Job API] 'job.run.result.tap.include_logs' is not respected into the Job API

### ISSUE THREAD

**Issue by willianrampazzo** [avocado-framework/avocado#4004]
Consider the following test as an example:

```
#!/usr/bin/env python3

import os
import sys

from avocado import Test
from avocado.core.job import Job


class PassTest(Test):
    def test_enabled(self):
        config = {'core.show': ['none'],
                  'run.references': ['/bin/true'],
                  'job.run.result.tap.include_logs': 'on'}
        with Job(config) as j:
            j.run()

    def test_disabled(self):
        config = {'core.show': ['none'],
                  'run.references': ['/bin/true'],
                  'job.run.result.tap.include_logs': 'off'}
        with Job(config) as j:
            j.run()


if __name__ == '__main__':

    config = {'run.references': [__file__],
              'core.show': ['app']}

    with Job(config) as j:
        sys.exit(j.run())
```

Test run:

```
$ avocado run /tmp/passjob_with_test.py 
/home/wrampazz/src/avocado/avocado.dev/avocado/plugins/run.py:283: FutureWarning: The following arguments will be changed to boolean soon: sysinfo, output-check, failfast and keep-tmp. 
  warnings.warn("The following arguments will be changed to boolean soon: "
JOB ID     : e63d7a235f50b1e7df06d07f3d6badf85a7478ac
JOB LOG    : /home/wrampazz/avocado/job-results/job-2020-07-17T12.42-e63d7a2/job.log
 (1/2) /tmp/passjob_with_test.py:PassTest.test_enabled:  JOB ID     : 67221ee1d3f5ac9d866c3fe77b7e3439a271ab41
JOB LOG    : /home/wrampazz/avocado/job-results/job-2020-07-17T12.42-67221ee/job.log
 (1/1) /bin/true: PASS (0.02 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/wrampazz/avocado/job-results/job-2020-07-17T12.42-67221ee/results.html
PASS (0.22 s)
 (2/2) /tmp/passjob_with_test.py:PassTest.test_disabled:  JOB ID     : 791199c9e45bfc53256df07d560b3802748d3dbc
JOB LOG    : /home/wrampazz/avocado/job-results/job-2020-07-17T12.42-791199c/job.log
 (1/1) /bin/true: PASS (0.03 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/wrampazz/avocado/job-results/job-2020-07-17T12.42-791199c/results.html
PASS (0.18 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/wrampazz/avocado/job-results/job-2020-07-17T12.42-e63d7a2/results.html
JOB TIME   : 0.51 s
```

Output of `results.tap` in both tests:

```
$ cat /home/wrampazz/avocado/job-results/job-2020-07-17T12.42-67221ee/results.tap 
1..1
# debug.log of /bin/true:
#   12:42:44 INFO | Running '/bin/true'
#   12:42:44 INFO | Command '/bin/true' finished with 0 after 0.002315521240234375s
#   12:42:44 INFO | Exit status: 0
#   12:42:44 INFO | Duration: 0.002315521240234375
#   12:42:44 DEBUG| DATA (filename=output.expected) => NOT FOUND (data sources: variant, file)
#   12:42:44 DEBUG| DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, file)
#   12:42:44 DEBUG| DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, file)
#   12:42:44 INFO | PASS 1-/bin/true
#   12:42:44 INFO |
ok 1 /bin/true

$ cat /home/wrampazz/avocado/job-results/job-2020-07-17T12.42-791199c/results.tap 
1..1
# debug.log of /bin/true:
#   12:42:44 INFO | Running '/bin/true'
#   12:42:44 INFO | Command '/bin/true' finished with 0 after 0.002328634262084961s
#   12:42:44 INFO | Exit status: 0
#   12:42:44 INFO | Duration: 0.002328634262084961
#   12:42:44 DEBUG| DATA (filename=output.expected) => NOT FOUND (data sources: variant, file)
#   12:42:44 DEBUG| DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, file)
#   12:42:44 DEBUG| DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, file)
#   12:42:44 INFO | PASS 1-/bin/true
#   12:42:44 INFO |
ok 1 /bin/true
```

Expected output of the second test with `job.run.result.tap.include_logs = 'off'`:

```
$ avocado run /bin/true
/home/wrampazz/src/avocado/avocado.dev/avocado/plugins/run.py:283: FutureWarning: The following arguments will be changed to boolean soon: sysinfo, output-check, failfast and keep-tmp. 
  warnings.warn("The following arguments will be changed to boolean soon: "
JOB ID     : bab97af951c7b73cf8770fb23ad385db509c197b
JOB LOG    : /home/wrampazz/avocado/job-results/job-2020-07-17T12.51-bab97af/job.log
 (1/1) /bin/true: PASS (0.01 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/wrampazz/avocado/job-results/job-2020-07-17T12.51-bab97af/results.html
JOB TIME   : 0.09 s

$ cat /home/wrampazz/avocado/job-results/job-2020-07-17T12.51-bab97af/results.tap 
1..1
ok 1 /bin/true
```

**Comment by beraldoleal** [comment]
@willianrampazzo: `avocado/plugins/tap.py`:175 is registering this option as `bool`. I will do some work here, to parse 'on' and 'off' as bool in this config dict too. But have you tried with Python bools (`False` and `True`)?

**Comment by willianrampazzo** [comment]
> @willianrampazzo: `avocado/plugins/tap.py`:175 is registering this option as `bool`. I will do some work here, to parse 'on' and 'off' as bool in this config dict too. But have you tried with Python bools (`False` and `True`)?

I think I tried, but if I recall correctly, it does not work.

I remember I tried to explicitly set this option to `off` or `False` in the command line and it did not work. I know the default is `False`, but how can I explicitly set it to `False` in the command line? Or we will not support this kind of setting, but only support setting to `True` when the parameter is available in the command line?

**Comment by beraldoleal** [comment]
@willianrampazzo as we discussed on the BP001, real boolean parameters dont have args. It is like -`-verbose` , or `--debug`, If the default is `False`, when you don't use the parameter will be `False`, but when you pass `--tap-include-logs` will be set to True.

I will do some tests and will comment here.

**Comment by willianrampazzo** [comment]
> @willianrampazzo as we discussed on the BP001, real boolean parameters dont have args. It is like -`-verbose` , or `--debug`, If the default is `False`, when you don't use the parameter will be `False`, but when you pass `--tap-include-logs` will be set to True.
> 
> I will do some tests and will comment here.

I remember that.

We need to check how the Job API will behave in this case.

Thanks for handling this.

**Comment by beraldoleal** [comment]
@willianrampazzo this is working with real booleans. I tried with the job API config dict and also with the command line. Working as expected.

Still, it is an open question:

We have today, 3 ways to configure things:

 1. Configuration File (ini)
 2. Command Line Arguments (bash
 3. Config objects on the Job API (python)

Each one is a different method with different syntax. The question is: Should we support on the Job API config dict the same syntax as the INI files? (allowing  'on' / 'off') ?

IMO, we shouldn't for two reasons:

 1. It is Python ;)
 2. Since we store the values in the registered type (bool) and settings.as_dict() or settings.get() will return 'bool', IMO it is confusing to set something like 'off' *here in the dict*, and when getting receive a bool.

What do you think?

**Comment by willianrampazzo** [comment]
> @willianrampazzo this is working with real booleans. I tried with the job API config dict and also with the command line. Working as expected.
> 

Good! This was impacting #3969 while using YAML files and mux to define the variants. We have switched to Python dictionaries and defining each of the variants manually, so this should not be a problem anymore.

> Still, it is an open question:
> 
> We have today, 3 ways to configure things:
> 
> 1. Configuration File (ini)
> 2. Command Line Arguments (bash
> 3. Config objects on the Job API (python)
> 
> Each one is a different method with different syntax. The question is: Should we support on the Job API config dict the same syntax as the INI files? (allowing 'on' / 'off') ?
> 
> IMO, we shouldn't for two reasons:
> 
> 1. It is Python ;)
> 2. Since we store the values in the registered type (bool) and settings.as_dict() or settings.get() will return 'bool', IMO it is confusing to set something like 'off' _here in the dict_, and when getting receive a bool.
> 
> What do you think?

I agree, and I would even extend this. If we are working to have a release ready for an LTS, in my opinion, we should get rid of all `on/off` options and make them true boolean in this release.

**Comment by beraldoleal** [comment]
I agree with you @willianrampazzo, I would leave only 'on', 'off', '0', '1', 'true', 'false' support in INI files because they are supported by default on configparser. I will close this. Please feel free to reopen.
