### ISSUE TITLE
avocado variants: Detect node with `null` value in yaml as an leaf node

### ISSUE THREAD

**Issue by harish-24** [avocado-framework/avocado#4010]
Currently the `avocado variants -c` does not treat a key with `null` value as a input.

```
# cat disk_info.yaml
dir: '/mnt'
disk: null
filesystem: !mux
    xfs:
        fs: 'xfs'
    ext4:
        fs: 'ext4'
    btrfs:
        fs: 'btrfs'

# avocado variants -c -m disk_info.yaml
Multiplex variants (3):

Variant disk-xfs-a4c9:    /run/disk, /run/filesystem/xfs
    /run/filesystem/xfs:fs => xfs
    /run:dir               => /mnt

Variant disk-ext4-a6b6:    /run/disk, /run/filesystem/ext4
    /run/filesystem/ext4:fs => ext4
    /run:dir                => /mnt

Variant disk-btrfs-c4e4:    /run/disk, /run/filesystem/btrfs
    /run/filesystem/btrfs:fs => btrfs
    /run:dir                 => /mnt
```

As `null` is a valid yaml value, expecting the mux tree with `disk` as a leaf node and not as a node path.
Variants must look like the following
```
Variant disk-xfs-a4c9:   /run/filesystem/xfs
    /run/filesystem/xfs:fs => xfs
    /run:dir               => /mnt
    /run:disk              => null
```

**Comment by harish-24** [comment]
@clebergnu @beraldoleal @willianrampazzo Any thoughts here would be helpful !

**Comment by willianrampazzo** [comment]
Hi @harish-24, what does the null represents here? If I change the null keyword by a 'null' string, your example works as desired:

```
$ cat /tmp/test.yaml 
dir: '/mnt'
disk: 'null'
filesystem: !mux
    xfs:
        fs: 'xfs'
    ext4:
        fs: 'ext4'
    btrfs:
        fs: 'btrfs'

$ avocado variants -c -m /tmp/test.yaml 
Multiplex variants (3):

Variant run-filesystem-xfs-046c:    /run/filesystem/xfs
    /run/filesystem/xfs:fs => xfs
    /run:dir               => /mnt
    /run:disk              => null

Variant run-filesystem-ext4-5e68:    /run/filesystem/ext4
    /run/filesystem/ext4:fs => ext4
    /run:dir                => /mnt
    /run:disk               => null

Variant run-filesystem-btrfs-fcd5:    /run/filesystem/btrfs
    /run/filesystem/btrfs:fs => btrfs
    /run:dir                 => /mnt
    /run:disk                => null
```

So, I think I need a bit more context here to know what you are trying to accomplish.

**Comment by harish-24** [comment]
@willianrampazzo Right, you have a good example here. The only difference is that, when reading in test using `params.get`, treats it as a string. And for example `1` would mean an integer when read in test, but as yaml already supports `None` type which can be represented using a `null`, this does not work with `avocado variants` is my point here.

So basically what I want is to define a leaf node in yaml with null type so that the test **reads** is as a `None` and not anything else.

Something like this
```
PARAMS (key=package, path=*, default=distro) => null
type(package): <class 'NoneType'>
```

So, is there a way to define a `None` in yaml as `null` is not working here?

**Comment by willianrampazzo** [comment]
> @willianrampazzo Right, you have a good example here. The only difference is that, when reading in test using `params.get`, treats it as a string. And for example `1` would mean an integer when read in test, but as yaml already supports `None` type which can be represented using a `null`, this does not work with `avocado variants` is my point here.
> 
> So basically what I want is to define a leaf node in yaml with null type so that the test **reads** is as a `None` and not anything else.
> 
> Something like this
> 
> ```
> PARAMS (key=package, path=*, default=distro) => null
> type(package): <class 'NoneType'>
> ```
> 
> So, is there a way to define a `None` in yaml as `null` is not working here?

I got your need.

I did a test here and it is a bit awkward, but it works. Here is the code I used:

```
dir: '/mnt'
disk: null
filesystem: !mux
    xfs:
        fs: 'xfs'
    ext4:
        fs: 'ext4'
    btrfs:
        fs: 'btrfs'
```

```
from avocado import Test

class PassTest(Test):

    def test(self):
        self.log.warn(type(self.params.get('disk')))
```

Although Avocado does not show the `null` like a leaf, when I look at the log, the `disk` was available for the test with the correct type:

```
2020-07-29 16:09:53,580 test             L0253 WARNI| <class 'NoneType'>
```

So, maybe it is just a matter of correctly considering the `null` value as a leaf while creating the variants.

**Comment by harish-24** [comment]
@willianrampazzo The reason for it to appear as `None` is because for two reasons.
1. the default value is not set in test like `self.params.get('disk', default="/dev/sda")`
2. the `disk: null` is not even considered as a leaf node.

So, when you have a input as `disk:''` then you can see that treated as a leaf and as a string.

**Comment by harish-24** [comment]
@willianrampazzo any update here?

**Comment by willianrampazzo** [comment]
> @willianrampazzo any update here?

I understood the use case you are referring to, and I think it is a valid use case. There may be other ways to handle this kind of use case into the test, but if you feel it is worth adding it to the mux code, I'll be happy to review your PR.

@clebergnu @beraldoleal do you have any comments here that I may not have seen?

**Comment by richtja** [comment]
After discussion in #4280, we decided that we can use null as a string and inside yaml_to_mux rewrite null strings to None.
