### ISSUE TITLE
RFE: bash helper library

### ISSUE THREAD

**Issue by jscotka** [avocado-framework/avocado#403]
Hi,
there in avocado are some helper commands solving testing phases, some command run.
It would be nice to have something similar for bash.
You can be ispired by:
https://fedorahosted.org/beakerlib/wiki/Examples
or if it is viable directly use beakerlib
     Thanks&Regards
      Honza

**Comment by ldoktor** [comment]
Hello @jscotka, we have an initial support for `logging` for bash scripts. Feel free to inspire by `libexec/*` and the `SimpleTest` body and add commands you desire.

**Comment by ldoktor** [comment]
Hello @jscotka I'm closing this issue as there is a basic tooling for bash support in avocado. Feel free to extend this library or ask for a new features, should you need some.
