### ISSUE TITLE
RFE: passing parameters to test via  avocado command line

### ISSUE THREAD

**Issue by jscotka** [avocado-framework/avocado#404]
Hi,
I somehow need to insert variables to test (set environment  variable for tests)
for example via some special param like --env
(It should setup variable for all tests)
avocado run --vm-domain $NAME --vm-username root --vm-password $PASSWD --vm-hostname $IP $AVOCADO_TEST_DIR/sources.sh --env="A=xyz" --env="B=abc" 

or another possibility, set it up for each test, like:
avocado run --vm-domain $NAME --vm-username root --vm-password $PASSWD --vm-hostname $IP "A=xyz B=abc $AVOCADO_TEST_DIR/sources.sh"

      Thanks&Regards
      Honza

**Comment by ldoktor** [comment]
Hi Jan, there are massive changes in params happening right now. Please bear with us until those change settles and I'll do whatever I can to add support for this. I also like to have the possibility to force certain value just for this run without the need to supply yaml file.

For now please use yaml file by `avocado run $tests -m file.yaml`

```yaml
key: value
key2: value2
key3: value3
```

In normal test these will be inside params and in bash test it gets injected into the environment.

**Comment by ldoktor** [comment]
This feature was already included:

```
multiplexer use on test execution:
  -m [FILE [FILE ...]], --multiplex-files [FILE [FILE ...]]
                        Location of one or more Avocado multiplex (.yaml)
                        FILE(s) (order dependent)
  --filter-only [FILTER_ONLY [FILTER_ONLY ...]]
                        Filter only path(s) from multiplexing
  --filter-out [FILTER_OUT [FILTER_OUT ...]]
                        Filter out path(s) from multiplexing
  --mux-path [MUX_PATH [MUX_PATH ...]]
                        List of paths used to determine path priority when
                        querying for parameters
  --mux-inject [MUX_INJECT [MUX_INJECT ...]]
                        Inject [path:]key:node values into the final multiplex
                        tree.
```
