### ISSUE TITLE
RFE: copy whole test directory structure to remote(virtual) machine

### ISSUE THREAD

**Issue by jscotka** [avocado-framework/avocado#405]
Hi,
Nowadays when test is running, only mentioned tests are copied to remote machine, but trouble is that I have also there some support library for some of test (contains some general part of code execution)
I have to copy also this helper lib to virt(remote) machine manually.
It is connected with issue:
https://github.com/avocado-framework/avocado/issues/350
It could be solved via some special parametr to be relative to that path like --dir or that could contain  some option like: --copy-tree what cause copying everything around mentioned test like
you run: avocado run --vm... $ABC/test.py
causes to copy $ABC to VMs
     Regards
     Honza

**Comment by ldoktor** [comment]
Hi @jscotka, I'm wondering if simple structure modification wouldn't solve your problem:

let's say you have 2 tests using the common lib:

```
share_lib/__init__.py
test1.py
test2.py
```

When you organize it like this and execute `test1.py`, avocado copies the `test1.py`'s  base directory recursively, including your `shared_lib`.

**Comment by ldoktor** [comment]
The workaround above does not work in the latest version as we only copy the test's datadir now.

**Comment by ldoktor** [comment]
Hello @jscotka, is this issue still valid? In my opinion such functionality is counterproductive as the test should fetch the dependencies itself. There is even support for `fetch_asset` if the library is available on-line.

**Comment by ldoktor** [comment]
OK I talked to @jscotka and he does not need this feature anymore and we have the datadir, which is the proper location. Let's close this as __WONTFIX__ for now.
