### ISSUE TITLE
Implement an automated test to cover Avocado features/options efficiently.

### ISSUE THREAD

**Issue by willianrampazzo** [avocado-framework/avocado#4052]
This issue tracks the implementation of an automated test to cover the Avocado features/options efficiently, as discussed here: #3969.

**Features list:**

&#128503; assets.fetch.ignore_errors
&#128503; assets.fetch.references
&#128503; config.datadir
&#9744; core.input_encoding
&#9744; core.paginator
&#9744; core.show
&#128503; core.verbose
&#9744; datadir.paths.base_dir
&#9744; datadir.paths.cache_dirs
&#9744; datadir.paths.data_dir
&#9744; datadir.paths.logs_dir
&#9744; datadir.paths.test_dir
&#9744; diff.create_reports
&#9744; diff.filter
&#9744; diff.html
&#9744; diff.jobids
&#9744; diff.open_browser
&#9744; diff.strip_id
&#9744; distro.distro_def_arch
&#9744; distro.distro_def_create
&#9744; distro.distro_def_name
&#9744; distro.distro_def_path
&#9744; distro.distro_def_release
&#9744; distro.distro_def_type
&#9744; distro.distro_def_version
&#9744; filter.by_tags.include_empty
&#9744; filter.by_tags.include_empty_key
&#9744; filter.by_tags.tags
&#128505; job.output.loglevel
&#9744; job.replay.source_job_id
&#128505; job.run.result.html.enabled
&#9744; job.run.result.html.open_browser
&#128505; job.run.result.html.output
&#128505; job.run.result.json.enabled
&#128505; job.run.result.json.output
&#128505; job.run.result.tap.enabled
&#128505; job.run.result.tap.include_logs
&#128505; job.run.result.tap.output
&#128505; job.run.result.xunit.enabled
&#128505; job.run.result.xunit.job_name
&#128505; job.run.result.xunit.max_test_log_chars
&#128505; job.run.result.xunit.output
&#128505; job.run.timeout
&#128503; jobs.get.output_files.destination
&#128503; jobs.get.output_files.job_id
&#128503; jobs.show.job_id
&#9744; json.variants.load
&#9744; list.external_runner
&#9744; list.external_runner_chdir
&#9744; list.external_runner_testdir
&#9744; list.loaders
&#9744; list.recipes.write_to_directory
&#128503; list.references
&#9744; list.resolver
&#9744; nrunner.max_parallel_tasks
&#9744; nrunner.shuffle
&#9744; nrunner.spawner
&#9744; nrunner.status_server_uri
&#9744; plugins.cli.cmd.order
&#9744; plugins.cli.order
&#128505; plugins.disable
&#9744; plugins.init.order
&#9744; plugins.job.prepost.order
&#9744; plugins.jobscripts.post
&#9744; plugins.jobscripts.pre
&#9744; plugins.jobscripts.warn_non_existing_dir
&#9744; plugins.jobscripts.warn_non_zero_status
&#9744; plugins.resolver.order
&#9744; plugins.result.order
&#9744; plugins.result_events.order
&#9744; plugins.result_upload.cmd
&#9744; plugins.result_upload.url
&#9744; plugins.resultsdb.api_url
&#9744; plugins.resultsdb.logs_url
&#9744; plugins.resultsdb.note_size_limit
&#9744; plugins.runnable.runner.order
&#9744; plugins.runner.order
&#9744; plugins.skip_broken_plugin_notification
&#9744; plugins.spawner.order
&#9744; plugins.varianter.order
&#9744; run.cit.combination_order
&#9744; run.cit.parameter_file
&#128505; run.dry_run.enabled
&#128505; run.dry_run.no_cleanup
&#9744; run.execution_order
&#9744; run.external_runner
&#9744; run.external_runner_chdir
&#9744; run.external_runner_testdir
&#128505; run.failfast
&#128505; run.ignore_missing_references
&#128505; run.job_category
&#128505; run.journal.enabled
&#128505; run.keep_tmp
&#9744; run.loaders
&#9744; run.log_test_data_directories
&#9744; run.output_check
&#9744; run.output_check_record
&#9744; run.pict_binary
&#9744; run.pict_combinations_order
&#9744; run.pict_parameter_file
&#9744; run.pict_parameter_path
&#9744; run.references
&#9744; run.replay.ignore
&#9744; run.replay.job_id
&#9744; run.replay.resume
&#9744; run.replay.test_status
&#128505; run.results.archive
&#9744; run.results_dir
&#9744; run.store_logging_stream
&#9744; run.test_parameters
&#9744; run.test_runner
&#128505; run.unique_job_id
&#9744; run.wrapper.wrappers
&#9744; runner.output.color
&#9744; runner.output.colored
&#9744; runner.output.utf8
&#9744; runner.timeout.after_interrupted
&#9744; runner.timeout.process_alive
&#9744; runner.timeout.process_died
&#9744; simpletests.status.skip_location
&#9744; simpletests.status.skip_regex
&#9744; simpletests.status.warn_location
&#9744; simpletests.status.warn_regex
&#9744; spawner.podman.bin
&#9744; spawner.podman.image
&#9744; sysinfo.collect.commands_timeout
&#128505; sysinfo.collect.enabled
&#9744; sysinfo.collect.installed_packages
&#9744; sysinfo.collect.locale
&#9744; sysinfo.collect.optimize
&#9744; sysinfo.collect.per_test
&#9744; sysinfo.collect.profiler
&#9744; sysinfo.collect.sysinfodir
&#9744; sysinfo.collectibles.commands
&#9744; sysinfo.collectibles.fail_commands
&#9744; sysinfo.collectibles.fail_files
&#9744; sysinfo.collectibles.files
&#9744; sysinfo.collectibles.profilers
&#9744; variants.cit.combination_order
&#9744; variants.cit.parameter_file
&#9744; variants.contents
&#9744; variants.debug
&#9744; variants.inherit
&#9744; variants.json_variants_dump
&#9744; variants.pict_binary
&#9744; variants.pict_combinations_order
&#9744; variants.pict_parameter_file
&#9744; variants.pict_parameter_path
&#9744; variants.summary
&#9744; variants.tree
&#9744; variants.variants
&#9744; vmimage.get.arch
&#9744; vmimage.get.distro
&#9744; vmimage.get.version
&#9744; yaml_to_mux.files
&#9744; yaml_to_mux.filter_only
&#9744; yaml_to_mux.filter_out
&#9744; yaml_to_mux.inject
&#9744; yaml_to_mux.parameter_paths

&#128505; - Already covered in the test. 
&#128503; - Plugin related, will not be tested with the Job API.
&#9744; - Still needs a test.

**Comment by willianrampazzo** [comment]
The base for the test was introduced at #4079.

**Comment by clebergnu** [comment]
Moving this to sprint 83.

**Comment by clebergnu** [comment]
While this is a worthy goal, the list of options is outdated given the age of this issue.  I'm closing this, and we can consider opening a similar one in the future.
