### ISSUE TITLE
Consolidate HTML plugin link paths for remote/vm plugins

### ISSUE THREAD

**Issue by jscotka** [avocado-framework/avocado#406]
Hi,
I've used command like:
sudo avocado run --vm-domain checkmachine1-fedora-21-x86_64 --vm-username root --vm-password testvm --vm-hostname 192.168.122.33 --vm-clean /tmp/avocado-test/tests/compiletest.sh /tmp/avocado-test/tests/checklogin.py

it generated HTML output to:
file:///root/avocado/job-results/job-2015-02-05T15.39-40f2dbc/html/results.html

but all links in page are bad, there are mixed LOCAL / REMOTE paths propably

            <table id="results" class="display" cellspacing="0" width="100%"><thead>
            <tr>
                <th>Start Time</th>
                <th>Test ID</th>
                <th>Status</th>
                <th>Time (sec)</th>
                <th>Info</th>
                <th>Debug Log</th>
            </tr>
            </thead>
                <tr class="success">
                    <td>2015-02-05 15:38:45</td>
                    <td><a href="/root/avocado/tests/tmp/avocado-test/tests/compiletest.sh">/root/avocado/tests/tmp/avocado-test/tests/compiletest.sh</a></td>
                    <td>PASS</td>
                    <td>42.99</td>
                    <td>Not supported yet</td>
                    <td><a href="/root/avocado/tests/tmp/avocado-test/tests/compiletest.sh/debug.log">debug.log</a></td>
                </tr>
                <tr class="success">
                    <td>2015-02-05 15:39:28</td>
                    <td><a href="/root/avocado/tests/tmp/avocado-test/tests/checklogin.py">/root/avocado/tests/tmp/avocado-test/tests/checklogin.py</a></td>
                    <td>PASS</td>
                    <td>9.59</td>
                    <td>Not supported yet</td>
                    <td><a href="/root/avocado/tests/tmp/avocado-test/tests/checklogin.py/debug.log">debug.log</a></td>
                </tr>
            </table>

**Comment by lmr** [comment]
I'm on it, thanks for the report.

**Comment by adereis** [comment]
Fixed a while ago, closing.

https://trello.com/c/oBod7egK/323-bug-html-report-has-broken-debug-log-link-when-using-absolute-paths-for-tests
