### ISSUE TITLE
Job Replay: write a plugin on top of the Job API

### ISSUE THREAD

**Issue by clebergnu** [avocado-framework/avocado#4062]
The current implementation of the `replay` plugin leverages the `run` command, and changes its behavior.  

With the Job API more mature, it makes more sense to have a `replay` plugin that is a standalone command, that instantiates a Job that is configured based on a given original (source job).

**Comment by beraldoleal** [comment]
If #4055 gets accepted, we need to remove a3d92cd9aa86d5af2099407f0baf083add29fa0f after we close this.

**Comment by clebergnu** [comment]
> If #4055 gets accepted, we need to remove [a3d92cd](https://github.com/avocado-framework/avocado/commit/a3d92cd9aa86d5af2099407f0baf083add29fa0f) after we close this.

I propose a different approach here now.  We already document that this combination (yaml to mux and replay) is not supported anymore, and I believe it should be kept that way:

---

https://avocado-framework.readthedocs.io/en/latest/guides/user/chapters/operations.html#job-replay

"Avocado versions 80.0 and earlier allowed replayed jobs to override the failfast configuration by setting --failfast=off in a avocado run --replay .. command line. This is no longer possible."

---

More advanced replays like this should make use of the Job API.

**Comment by beraldoleal** [comment]
I'm more than ok with that, @clebergnu . thanks. I will submit a PR to remove that test.
