### ISSUE TITLE
avocado.utils.cpu.get_version: IndexError: list index out of range

### ISSUE THREAD

**Issue by yanan-fu** [avocado-framework/avocado#4067]
This issue comes from:
https://github.com/avocado-framework/avocado/blob/9a5bb811e1c9fe5c7814fb62c91ec57fea315661/avocado/utils/cpu.py#L122

```
    for line in cpu_info:
        version_out = re.findall(version_pattern[arch], line)
        if version_out:
            break
    return version_out[0].decode('utf-8') if version_out[0] else ""
```

If can not get matched version, version_out is `[]`, `version_out[0]` will hit index error.

**Comment by yanan-fu** [comment]
@ldoktor @sathnaga  After involve the vendor variant to host-os, this issue will block the bootstrap, please help check it, thanks~

cc @luckyh

**Comment by sathnaga** [comment]
@yanan-fu two things to fix
1. handle for unknown arch/cpus yet.
2. educate the version strings for new arch/cpus as we encounter them,

for 1, will send a fix immediately

for 2, could you share `/proc/cpuinfo` output if possible, so that we can add version pattern similar to this https://github.com/avocado-framework/avocado/blob/9a5bb811e1c9fe5c7814fb62c91ec57fea315661/avocado/utils/cpu.py#L106, so that instead of none we could get valid value in your env. Thanks!

**Comment by yanan-fu** [comment]
@sathnaga  Eh~   I just send out the fix,  but without update the pattern:
https://github.com/avocado-framework/avocado/pull/4068

Here is the cpu info of my system:
```
# cat /proc/cpuinfo 
processor	: 0
vendor_id	: AuthenticAMD
cpu family	: 21
model		: 2
model name	: AMD Opteron(tm) Processor 6344
stepping	: 0
microcode	: 0x6000852
cpu MHz		: 1373.465
cache size	: 2048 KB
physical id	: 0
siblings	: 12
core id		: 0
cpu cores	: 6
apicid		: 32
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid amd_dcm aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 popcnt aes xsave avx f16c lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs xop skinit wdt fma4 tce nodeid_msr tbm topoext perfctr_core perfctr_nb cpb hw_pstate ssbd ibpb vmmcall bmi1 arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold
bugs		: fxsave_leak sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass
bogomips	: 5186.77
TLB size	: 1536 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 48 bits physical, 48 bits virtual
power management: ts ttp tm 100mhzsteps hwpstate cpb eff_freq_ro

```

**Comment by sathnaga** [comment]
> @sathnaga Eh~ I just send out the fix, but without update the pattern:
> #4068

Good, saw that, Tnx!

@yanan-fu I do not have access to AMD systems, So feel free to add send PRs for missing AMD patterns too, if you would like, let me know if you need any help :-) 

> 
> Here is the cpu info of my system:
> 
> ```
> # cat /proc/cpuinfo 
> processor	: 0
> vendor_id	: AuthenticAMD
> cpu family	: 21
> model		: 2
> model name	: AMD Opteron(tm) Processor 6344
> stepping	: 0
> microcode	: 0x6000852
> cpu MHz		: 1373.465
> cache size	: 2048 KB
> physical id	: 0
> siblings	: 12
> core id		: 0
> cpu cores	: 6
> apicid		: 32
> initial apicid	: 0
> fpu		: yes
> fpu_exception	: yes
> cpuid level	: 13
> wp		: yes
> flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid amd_dcm aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 popcnt aes xsave avx f16c lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs xop skinit wdt fma4 tce nodeid_msr tbm topoext perfctr_core perfctr_nb cpb hw_pstate ssbd ibpb vmmcall bmi1 arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold
> bugs		: fxsave_leak sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass
> bogomips	: 5186.77
> TLB size	: 1536 4K pages
> clflush size	: 64
> cache_alignment	: 64
> address sizes	: 48 bits physical, 48 bits virtual
> power management: ts ttp tm 100mhzsteps hwpstate cpb eff_freq_ro
> ```

**Comment by yanan-fu** [comment]
@sathnaga  If i understand correctly, it is aim to get the version in 'model_name' , such as `6344` for the info above, is it ?

**Comment by sathnaga** [comment]
> @sathnaga If i understand correctly, it is aim to get the version in 'model_name' , such as `6344` for the info above, is it ?

I belive, that's right for the version.

and similarly check if you can add get_family() support as well, https://github.com/avocado-framework/avocado/blob/9a5bb811e1c9fe5c7814fb62c91ec57fea315661/avocado/utils/cpu.py#L180

In this case I guess family is `Opteron` ?

Please make sure search string/place to get information is applicable more than one systems with different AMD cpus.

Thanks :+1: 

Bottomline: Idea behind this grouping is get more grarular details of environment in which the tests run, to isolate or choose right tests relevant for certain version of cpu family, version etc.

**Comment by yanan-fu** [comment]
@sathnaga  Just noticed, this issue already be closed automatically after the patch be merged.

Now, `version` is under `family`,  without implement the `get_family` for amd,  it does not make a lot of sense.
Let's track it with new issue later, thanks!
