### ISSUE TITLE
RFE: Idea of support multihost testing

### ISSUE THREAD

**Issue by jscotka** [avocado-framework/avocado#407]
Hi,
I'm not sure if this is right issue tracker (avocado-virt), I expect to  be able to do some multihost testing:

my imagination now is, that I need 
1 SERVER and 3 CLIENS and run some part of test on clients and another part on server.
It need 2 things 
 * support some sync beetween machines
 * support to script to know which part is server and which is client
 * creating X machines - could be solved for example via VMs, like (there is --vm-domain parameter given) and avocado will  clone that machine to 4 instances
for remote plugin it could be solved via more --remote-ip $IP parameters
     Thanks&Regards
     Honza

**Comment by clebergnu** [comment]
Hi Honza, this is a large work item, which we have already discussed a lot.  For now, we're tracking it here:

https://trello.com/c/AnoH6vhP/530-rfc-multiple-machine-support-for-tests

So I'll close this issue to have a central discussion point.

Thanks!

**Comment by jscotka** [comment]
Okay, tracking in trello is okay. Thanks.
