### ISSUE TITLE
future.settings is not taking into consideration runner.output.color at early stages

### ISSUE THREAD

**Issue by beraldoleal** [avocado-framework/avocado#4081]
When running Avocado with a custom config (`runner.output.color = always`) this is not being respected.

By default runner.output.color is set to 'auto' that will detect redirects and suppress color information during pipes, for instance. But with a custom config (lets say `runner.output.color = always`) the following command should produce a file with color information:

```bash
$ avocado config > some.log
```

We could change the default value to 'always' but this will not solve the real problem, that is related to the order of settings modules during Avocado bootstrap.

**Comment by beraldoleal** [comment]
@clebergnu even with this being registered at `core/__init__.py:register_core_options()` this is not working. I will do a deeper investigation but if you have a hint here, will be helpful.

**Comment by clebergnu** [comment]
Fixed by #4084
