### ISSUE TITLE
RFE: allow more fails in tests

### ISSUE THREAD

**Issue by jscotka** [avocado-framework/avocado#409]
Hi,
as we discussed, it would be nice to allow more failures in one test. to solve issue, that lots of people have to do it by own counter of fails.
It could besolved via some decorators aroound asserts in python test.
like:
   self.assertTrue(False)
   self.assertTrue(True)
   self.assertTrue(False)
should produce: 
PASS: 1
FAIL:   2
...
It would be very nice to solve it in framework instead of many own solutions for same issue.
     Thanks&Regards
     Honza

**Comment by lmr** [comment]
The plan is to make avocado tests to have the same granularity of unittests.

**Comment by clebergnu** [comment]
@jscotka some of that is already implemented. Do you mind giving it a try?

BTW: I'm closing this issue, if what we have is not enough, let us know by reopening it. Thanks!
