### ISSUE TITLE
[LTS] Functional/Integration tests with external projects

### ISSUE THREAD

**Issue by clebergnu** [avocado-framework/avocado#4103]
To make sure no regressions exist in the LTS release, and to adjust expectations, it's a good idea to test with known external plugins and/or test repositories.  Examples:

* Example tests (example/tests/)
* Avocado-VT tests
  * QEMU based
  * libvirt based
* QEMU:
  * tests/acceptance
  * unit tests ("tap" tests)
* Avocado ["misc-tests"](https://github.com/avocado-framework-tests/avocado-misc-tests)
* Avocado [I2N](https://github.com/intra2net/avocado-i2n)
* [Daos Stack](https://github.com/daos-stack/daos/blob/master/src/tests/ftest/launch.py#L749)
* [Falco](https://github.com/falcosecurity/falco/tree/master/test)

Some existing CI deployments *could* be reused, as long as its possible to pin the external project versions and keep testing Avocado's master up to the LTS release being tagged.

It's fair to *not* expect complete compatibility, but this testing should serve as input for describing migration steps from 69.x LTS to 82.x LTS.

**Comment by clebergnu** [comment]
Message sent to the DAOS community: https://daos.groups.io/g/daos/message/1126

**Comment by narasimhan-v** [comment]
@clebergnu Can you explain a bit more on what are the expectations here ? Is the expectation to tag releases of different projects to document the compatibility ?

More insights on the overall picture will help.

**Comment by pevogam** [comment]
Hi @narasimhan-v, I think the expectation is just a call for the projects to help out with LTS testing if they would like.

**Comment by narasimhan-v** [comment]
@pevogam should we also look at tagging tests which is used for validating avocado LTS build ?

**Comment by pevogam** [comment]
I am not sure if I understand what you mean. On my side for instance, what I am planning to do is simply wait for an LTS branch or signal that we will be ready for releasing 82.0, then run some local tests of our product (be it any of these) with the candidate/tested code as a dependency.

**Comment by PraveenPenguin** [comment]
@pevogam what i feel @narasimhan-v  meant as from misc test font as we have tag also available inside test so we can tag test case as well, as we already have some release but that based on major changes in the avocado library  which impact misct  test repo

**Comment by pevogam** [comment]
Hi @PraveenPenguin, alright sorry for the extra noise on my side, I just expressed how I understand the progression on this issue. I guess we will wait for the rest to provide @narasimhan-v with more information.

**Comment by clebergnu** [comment]
> I am not sure if I understand what you mean. On my side for instance, what I am planning to do is simply wait for an LTS branch or signal that we will be ready for releasing 82.0, then run some local tests of our product (be it any of these) with the candidate/tested code as a dependency.

Yes, that's  the idea.

IMO, he best timing to do (or start) the testing would be right after *81.0* is tagged/released.  Because then, functionality wise, it'll be frozen.  Then *82.0* would hopefully contain all fixes found for issues found with the external projects / tests.

**Comment by pevogam** [comment]
> IMO, he best timing to do (or start) the testing would be right after _81.0_ is tagged/released. Because then, functionality wise, it'll be frozen. Then _82.0_ would hopefully contain all fixes found for issues found with the external projects / tests.

Good to know, I was also expecting that feature development will be frozen from 81.0 to 82.0 so that we have greater stability and con provide maximum coverage with minimum reruns.

**Comment by pevogam** [comment]
Hi @clebergnu, from a two-day long large scale test run covering various corner cases so far I have only obtained one error:

![image](https://user-images.githubusercontent.com/1969979/92106977-c5d00d80-eded-11ea-9486-f5aca9572322.png)

If I however check if the option is enabled, I get positive feedback:
```
$ avocado config | grep sysinfo
    diff.filter                              ['cmdline', 'time', 'variants', 'results', 'config', 'sysinfo']
    sysinfo.collect.commands_timeout         -1
    sysinfo.collect.enabled                  True
    sysinfo.collect.installed_packages       False
    sysinfo.collect.locale                   C
    sysinfo.collect.optimize                 False
    sysinfo.collect.per_test                 False
    sysinfo.collect.profiler                 False
    sysinfo.collect.sysinfodir               None
    sysinfo.collectibles.commands            /usr/lib/python3.8/site-packages/avocado/etc/avocado/sysinfo/commands
    sysinfo.collectibles.fail_commands       /usr/lib/python3.8/site-packages/avocado/etc/avocado/sysinfo/fail_commands
    sysinfo.collectibles.fail_files          /usr/lib/python3.8/site-packages/avocado/etc/avocado/sysinfo/fail_files
    sysinfo.collectibles.files               /usr/lib/python3.8/site-packages/avocado/etc/avocado/sysinfo/files
    sysinfo.collectibles.profilers           /usr/lib/python3.8/site-packages/avocado/etc/avocado/sysinfo/profilers
```
Should I open an issue about this or do you think there is something quick I am missing?

**Comment by clebergnu** [comment]
> Hi @clebergnu, from a two-day long large scale test run covering various corner cases so far I have only obtained one error:
> 
> ![image](https://user-images.githubusercontent.com/1969979/92106977-c5d00d80-eded-11ea-9486-f5aca9572322.png)
> 
> If I however check if the option is enabled, I get positive feedback:
> 
> ```
> $ avocado config | grep sysinfo
>     diff.filter                              ['cmdline', 'time', 'variants', 'results', 'config', 'sysinfo']
>     sysinfo.collect.commands_timeout         -1
>     sysinfo.collect.enabled                  True
>     sysinfo.collect.installed_packages       False
>     sysinfo.collect.locale                   C
>     sysinfo.collect.optimize                 False
>     sysinfo.collect.per_test                 False
>     sysinfo.collect.profiler                 False
>     sysinfo.collect.sysinfodir               None
>     sysinfo.collectibles.commands            /usr/lib/python3.8/site-packages/avocado/etc/avocado/sysinfo/commands
>     sysinfo.collectibles.fail_commands       /usr/lib/python3.8/site-packages/avocado/etc/avocado/sysinfo/fail_commands
>     sysinfo.collectibles.fail_files          /usr/lib/python3.8/site-packages/avocado/etc/avocado/sysinfo/fail_files
>     sysinfo.collectibles.files               /usr/lib/python3.8/site-packages/avocado/etc/avocado/sysinfo/files
>     sysinfo.collectibles.profilers           /usr/lib/python3.8/site-packages/avocado/etc/avocado/sysinfo/profilers
> ```
> 
> Should I open an issue about this or do you think there is something quick I am missing?

Yes @pevogam, please do open an issue.  I think I know what's the cause here, but we can discuss it better in a proper issue.

**Comment by clebergnu** [comment]
All children issues are resolved, closing this epic.

**Comment by pevogam** [comment]
Hi @clebergnu, there are some current errors with Avocado VT that I just described in

https://github.com/avocado-framework/avocado-vt/pull/2758

that I am hoping we can resolve on the Avocado VT side.
