### ISSUE TITLE
 docs: Review and test examples on user's guide (sections: Avocado logging system) 

### ISSUE THREAD

**Issue by beraldoleal** [avocado-framework/avocado#4110]

**Comment by willianrampazzo** [comment]
@clebergnu is `debug` option supposed to display something?

```
$ avocado --show debug run passtest.py
$
```

The documentation says: **debug: Additional messages useful to debug Avocado (avocado.app.debug)**

I was expecting _additional_ messages if any, but I was not expecting the normal messages to be suppressed.

Anyway, I'm just looking for confirmation that the behavior is correct and I should update the documentation, or we have abnormal behavior and we need to fix Avocado.

**Comment by clebergnu** [comment]
@willianrampazzo IIRC, this means that `avocado.app.debug` logging gets enabled.  You could look if any of the Avocado code still produces messages into that logging channel to check if the *feature* is working properly.

**Comment by willianrampazzo** [comment]
> @willianrampazzo IIRC, this means that `avocado.app.debug` logging gets enabled. You could look if any of the Avocado code still produces messages into that logging channel to check if the _feature_ is working properly.

I'll check that, but I think my question was not clear.

The documentation says **additional messages**, but actually no message is displayed in the console. So, should Avocado display the normal messages plus the debug messages or the correct behavior is to show nothing and forward everything to the log files?

Knowing what is the correct behavior will drive what changes are needed.

**Comment by willianrampazzo** [comment]
There are two entries using the `avocado.app.debug` logger. One in the `extension_manager.py` and one in the `output.py`. I think it is fine for now to let this logging stream available.
