### ISSUE TITLE
[LTS] Testing Example/tests

### ISSUE THREAD

**Issue by clebergnu** [avocado-framework/avocado#4112]
Make sure no regressions exist in the LTS release with regards to example tests (`example/tests/`)

---

This is part of https://github.com/avocado-framework/avocado/issues/4103

**Comment by beraldoleal** [comment]
I tested all scripts there, and they are working properly. Only two that are not working:

 1. modify_variables.py: That was fixed by #4182 
 2. synctest.py: we have already an open issue for this (#4167)

Since, we have the pr/ssues open, I'm closing this.
