### ISSUE TITLE
[LTS] Testing Avocado's "misc-tests"

### ISSUE THREAD

**Issue by clebergnu** [avocado-framework/avocado#4117]
Make sure no regressions exist in the LTS release with regards to * Avocado ["misc-tests"](https://github.com/avocado-framework-tests/avocado-misc-tests).

---

This is part of https://github.com/avocado-framework/avocado/issues/4103

**Comment by clebergnu** [comment]
@PraveenPenguin @narasimhan-v @harish-24 (and others) could some of you own this issue?

**Comment by PraveenPenguin** [comment]
@clebergnu sure seems a good idea

**Comment by clebergnu** [comment]
@PraveenPenguin have you seen any regressions? There are no known bugs to be fixed before the LTS release, so now would be a good time to test with Avocado 2a0c9ecfca4ec962fb41d775d2d0c0c3be966bcc.

**Comment by clebergnu** [comment]
For "sport" I tried running some of the misc-tests.  Here's `memory/memcached.py`, run with `avocado --show=test run -m memcached.py.data/memcached.yaml -- memcached.py`.
[job.log](https://github.com/avocado-framework/avocado/files/5198093/job.log)

Which resulted in (TAP output):
```
1..4
ok 1 memcached.py:Memcached.test;run-setup-general-default-test_to_run-set-915a
ok 2 memcached.py:Memcached.test;run-setup-general-default-test_to_run-get-025e
ok 3 memcached.py:Memcached.test;run-setup-general-stress-test_to_run-set-39d8
ok 4 memcached.py:Memcached.test;run-setup-general-stress-test_to_run-get-03b7
```

**Comment by PraveenPenguin** [comment]
> @PraveenPenguin have you seen any regressions? There are no known bugs to be fixed before the LTS release, so now would be a good time to test with Avocado [2a0c9ec](https://github.com/avocado-framework/avocado/commit/2a0c9ecfca4ec962fb41d775d2d0c0c3be966bcc).
@clebergnu sure I will try and update in some time

**Comment by clebergnu** [comment]
@PraveenPenguin we'll be tagging Avocado 82.0 LTS tomorrow, so please let us know ASAP if you've found any blocked while running any of the misc-tests. Thanks!

**Comment by PraveenPenguin** [comment]
@clebergnu I ran major of test case expect   IO test cases seems me good, will update you more on this

**Comment by clebergnu** [comment]
Hi @PraveenPenguin thanks for your efforts here! I believe the testing done is sufficient to cover the goal of this card, so I'm closing this as a result of the successful testing.  Thanks a lot!
