### ISSUE TITLE
LTS Release Notes Document

### ISSUE THREAD

**Issue by clebergnu** [avocado-framework/avocado#4130]
We need to document the changes from the last LTS vesion (69.xLTS) to the 82.0LTS version.

Let's create two documents that contain:

1. The complete and individual changes from all releases
2. The resulting document which will contain the "squashed" version of similar entries

**Comment by beraldoleal** [comment]
I have created one big document with the merged one at the top and a copy of previous releases following this merged.

https://docs.google.com/document/d/1ggMlnHIcgsNTvx-ARz0FaatZljt40uJog71LAJWLesg/edit?usp=sharing

Please, let me know if this will work or if we should split.

**Comment by pevogam** [comment]
I have noticed the following being displayed on the GitHub page of the project:

![image](https://user-images.githubusercontent.com/1969979/92752357-8aa38080-f391-11ea-9c18-78d951f31789.png)

Does this make sure that it is updated to something more recent version there? Perhaps it could at least be updated with the latest release?

**Comment by beraldoleal** [comment]
I will guess that a simple tag will not be detected in GitHub as a release. I guess we need to create a proper release (or pre-release) with the GH interface.

**Comment by pevogam** [comment]
Alright, at the very least it is good letting you know how the GitHub web page looks at the moment for pure awareness reasons.

**Comment by clebergnu** [comment]
And both release notes document have been finalized... 82.0 is coming VERY SOON!

**Comment by pevogam** [comment]
Happy to see this on the GitHub page!:

![image](https://user-images.githubusercontent.com/1969979/93207277-6960dc80-f763-11ea-9c83-e1d8664603d7.png)
