### ISSUE TITLE
Disable missing file check in case --remote-no-copy is used

### ISSUE THREAD

**Issue by ldoktor** [avocado-framework/avocado#417]
With `--remote-no-copy` we don't copy the tests, we don't even use the files specified on cmdline, thus we should disable the check. It should happen in the remote machine.

**Comment by jscotka** [comment]
Hi,
It sounds wery good.
It would be also nice for HTML output copy (via your archive) these tests from remote machine to local result page (to be able to browse/display scheduled tests)
     Thanks&Regards
     Honza

**Comment by ldoktor** [comment]
@jscotka sure, that's clearly a bug and we will fix it. Or feel free to fix it and send a pull request :wink:

**Comment by lmr** [comment]
Closing this per #464.
