### ISSUE TITLE
Docs Contributor's Guide: Review section "Request for Comments (RFCs)"

### ISSUE THREAD

**Issue by willianrampazzo** [avocado-framework/avocado#4196]

**Comment by willianrampazzo** [comment]
This section is missing most of the content. IMHO, now is not the time to fulfill this section as it does not impact the LTS release.

I'm closing this issue. Feel free to reopen in any case.

**Comment by richtja** [comment]
@willianrampazzo I can't find the issue about fulfilling this section, maybe we should create one to not forget about it after LTS.

**Comment by willianrampazzo** [comment]
@richtja good idea, done! https://github.com/avocado-framework/avocado/issues/4205
