### ISSUE TITLE
self.params is not being populated

### ISSUE THREAD

**Issue by beraldoleal** [avocado-framework/avocado#4203]
If we have a simple test `/tmp/test.py`:
```python
from avocado import Test


class OutputTest(Test):
    def setUp(self):
        self.log.info("Setup executed")

    def test(self):
        self.log.info("PARAMS: ", self.params)
        self.assertTrue(1)
```

And execute Avocado with parameters:

```bash
$ avocado run /tmp/test.py -p foo=bar
```

foo bar parameters is not present in `self.params`:

```bash
$ cat ~/avocado/job-results/job-2020-09-04T10.01-beec5d9/job.log | grep PARAM
2020-09-04 10:01:26,593 parameters       L0143 DEBUG| PARAMS (key=timeout, path=*, default=None) => None
```

**Comment by richtja** [comment]
Hi @beraldoleal, I was looking at it and everything works well. I think that we don't have a method for printing list of all parameters so you can't test existing parameters like this.


> If we have a simple test `/tmp/test.py`:
> 
> ```python
> from avocado import Test
> 
> 
> class OutputTest(Test):
>     def setUp(self):
>         self.log.info("Setup executed")
> 
>     def test(self):
>         self.log.info("PARAMS: ", self.params)
There is a bug you should be using `self.log.info("PARAMS: %s", self.params)`
>         self.assertTrue(1)
> ```
> 
> And execute Avocado with parameters:
> 
> ```shell
> $ avocado run /tmp/test.py -p foo=bar
> ```
> 
> foo bar parameters is not present in `self.params`:
> 
> ```shell
> $ cat ~/avocado/job-results/job-2020-09-04T10.01-beec5d9/job.log | grep PARAM
> 2020-09-04 10:01:26,593 parameters       L0143 DEBUG| PARAMS (key=timeout, path=*, default=None) => None
> ```

This log message is not generated by your code

**Comment by beraldoleal** [comment]
Hi @richtja nice catch. I was using log as print. My bad. :/ Thanks , thats true.
