### ISSUE TITLE
distutils depreaction

### ISSUE THREAD

**Issue by beraldoleal** [avocado-framework/avocado#4228]
https://www.python.org/dev/peps/pep-0632/

We have one module using this: `avocado.utils.kernel`.

**Comment by t0xic0der** [comment]
Hi @beraldoleal, 

To address this issue, one has to replace `distutils` functionalities with any other viable alternatives like `sys`, `os` etc. right?

**Comment by beraldoleal** [comment]
Hi @t0xic0der, Actually we need to replace `distutils` call with `setuptools`.

**Comment by t0xic0der** [comment]
Makes sense. Small PRs for this too?

**Comment by beraldoleal** [comment]
This one will be small.

**Comment by t0xic0der** [comment]
Hi @beraldoleal, you can assign this to me. One of the issues I am working on (#3565) is halfway done as of now.

**Comment by t0xic0der** [comment]
Please look into #4248.
