### ISSUE TITLE
Create a BP000

### ISSUE THREAD

**Issue by beraldoleal** [avocado-framework/avocado#4247]
We are using Blueprints for a while but we need a BP000 that will describe the BP concept and usages and serves as a guideline for new blueprints.

**Comment by pevogam** [comment]
> We having using Blueprints for a while but we need a BP000 that will describe the BP concept and usages and serves as a guideline for new blueprints.

I think describing the concepts of blueprints is the perfect topic for a BP000. I have already had some colleagues asking me what is meant by "blueprints" in avocado. It is also useful to clarify if blueprints are supposed to propose new features, new contribution guidelines or new changes under discussion in general and this should be differentiated with a contribution guideline document.

**Comment by beraldoleal** [comment]
Yes, it was totally my fault, because we were discussing blueprint during the meetings and I introduced the BP001 without the BP000. 

The first draft is almost ready for a PR.
