### ISSUE TITLE
Show test logs on conditions

### ISSUE THREAD

**Issue by clebergnu** [avocado-framework/avocado#4266]
When running tests on certain scenarios, such as on CI environments, it's usually not a good idea to pollute the output with very verbose output.  On the other hand, when failures occurs, the only debugging aid is many times printing out the entire test log.

The proposal here is to print test logs only on certain conditions, defaulting to test failures.

A summary of the behavior can be thought of as the following command line options:

```
avocado run --show-test-logs-on=FAIL,ERROR,INTERRUPTED  -- /bin/true /bin/true /bin/false
JOB ID     : 51628e0e9aa3534d32b225db0183fc43ecd4f039
JOB LOG    : /root/avocado/job-results/job-2020-10-09T15.39-51628e0/job.log
 (1/3) /bin/true: PASS (0.03 s)
 (2/3) /bin/true: PASS (0.03 s)
 (3/3) /bin/false: FAIL: Exited with status: '1', stdout: '' stderr: '' (0.08 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
Test Log For "(3/3) /bin/false" (FAIL):
15:39:58 INFO | Running '/bin/false'
15:39:58 INFO | Command '/bin/false' finished with 1 after 0.002250194549560547s
15:39:58 INFO | Exit status: 1
15:39:58 INFO | Duration: 0.002250194549560547
15:39:58 ERROR| 
15:39:58 ERROR| Reproduced traceback from: /usr/local/lib/python3.7/site-packages/avocado/core/test.py:767
15:39:58 ERROR| Traceback (most recent call last):
15:39:58 ERROR|   File "/usr/local/lib/python3.7/site-packages/avocado/core/test.py", line 1112, in _execute_cmd
15:39:58 ERROR|     encoding=input_encoding)
15:39:58 ERROR|   File "/usr/local/lib/python3.7/site-packages/avocado/utils/process.py", line 1037, in run
15:39:58 ERROR|     raise CmdError(cmd, sp.result)
15:39:58 ERROR| avocado.utils.process.CmdError: Command '/bin/false' failed.
15:39:58 ERROR| stdout: b''
15:39:58 ERROR| stderr: b''
15:39:58 ERROR| additional_info: None
15:39:58 ERROR| 
15:39:58 ERROR| During handling of the above exception, another exception occurred:
15:39:58 ERROR| 
15:39:58 ERROR| Traceback (most recent call last):
15:39:58 ERROR|   File "/usr/local/lib/python3.7/site-packages/avocado/core/test.py", line 1156, in test
15:39:58 ERROR|     self._execute_cmd()
15:39:58 ERROR|   File "/usr/local/lib/python3.7/site-packages/avocado/core/test.py", line 1118, in _execute_cmd
15:39:58 ERROR|     raise exceptions.TestFail(test_failure)
15:39:58 ERROR| avocado.core.exceptions.TestFail: Exited with status: '1', stdout: '' stderr: ''
15:39:58 ERROR| 
15:39:58 DEBUG| Local variables:
15:39:58 DEBUG|  -> self <class 'avocado.core.test.SimpleTest'>: 3-/bin/false
15:39:58 DEBUG| DATA (filename=output.expected) => NOT FOUND (data sources: variant, file)
15:39:58 DEBUG| DATA (filename=stdout.expected) => NOT FOUND (data sources: variant, file)
15:39:58 DEBUG| DATA (filename=stderr.expected) => NOT FOUND (data sources: variant, file)
15:39:58 ERROR| FAIL 3-/bin/false -> TestFail: Exited with status: '1', stdout: '' stderr: ''
15:39:58 INFO |
JOB TIME   : 0.89 s
```

**Comment by clebergnu** [comment]
> Hmmm I am not sure I am very much for this idea. Imagine having 500 failures for instance - this will print 500 locations with such output, digging the original statuses under all sorts of details that the user has to see first before seeing the actual compact result stats like `RESULTS : PASS 2 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0` (I am imagining a case of using a terminal where the currently compact status stats are meant to be printed - a limited terminal history here could even make the statuses no longer reachable. Worse yet, in some tests the statuses could be included a long trace of nested exceptions with "during handling the previous exception, the following exception happened" and it is questionable how many lines should be shown and whether the proper error will be displayed.
> 
> I think this mimics and duplicates the function of the logs. I understand the CI is very hard to debug and I have suffered from such troubles myself but this is rather a problem to point out and solve within the CI rather than forcing this verbosity in every environment.

I think this last bit puts us on the same boat. My proposal is that the user would have to *request* such a feature to be enabled, that is, something like `--show-test-logs-on=FAIL,ERROR,INTERRUPTED` would only be set in a CI environment where there's no other way for the user to look at logs.

The location of the output (before the total final job outcome, right after each test, etc) is not something I'm sure about, though.

Sorry if it wasn't clear, but I did not intend to change the default behavior of the human UI.

**Comment by pevogam** [comment]
Definitely on the same :boat: now. I wish there was a more standard and mainstream way to deal with such CI restrictions since many projects in many different languages have the same problems of hard debugging due to lack of access to the logs. I guess such an option could help for this here but this remains a local solution to a global problem.

**Comment by clebergnu** [comment]
> Definitely on the same  now. I wish there was a more standard and mainstream way to deal with such CI restrictions since many projects in many different languages have the same problems of hard debugging due to lack of access to the logs. I guess such an option could help for this here but this remains a local solution to a global problem.

This is certainly an widespread problem.  We're starting to think and plan solutions, though.  BTW, @beraldoleal will hold a meeting next Tuesday to brainstorm around the current situation of status and result services/servers in Avocado... One of the use cases is being able to push Avocado results to servers where you can inspect the outcome, compare results, etc.  If you're interested, we can certainly extend the invitation.  If not, I'll check if we can record it and made it available.

**Comment by pevogam** [comment]
> > Definitely on the same  now. I wish there was a more standard and mainstream way to deal with such CI restrictions since many projects in many different languages have the same problems of hard debugging due to lack of access to the logs. I guess such an option could help for this here but this remains a local solution to a global problem.
> 
> This is certainly a widespread problem. We're starting to think and plan solutions, though.

It is actually a good idea that Avocado as a test framework is thinking of addressing this since it will be able to solve it for everyone using it in a CI at least to some extend.

> BTW, @beraldoleal will hold a meeting next Tuesday to brainstorm around the current situation of status and result services/servers in Avocado... One of the use cases is being able to push Avocado results to servers where you can inspect the outcome, compare results, etc. If you're interested, we can certainly extend the invitation. If not, I'll check if we can record it and made it available.

Definitely interested and this makes me wonder what happened to the usual meetings happening on each release? Some of the email discussions we started can also be clarified at least to some extend in such brainstorming meetings.
