### ISSUE TITLE
[RFC] avocado-software-manager always return 0

### ISSUE THREAD

**Issue by willianrampazzo** [avocado-framework/avocado#4273]
Opening this issue as an RFC to discuss the current behavior of `avocado-software-manager` as it may become a future item to be worked on.

When running `avocado-software-manager`, the exit code will always be `0`, independent of possible errors:

Success command:
```
[wrampazz@wrampazz ~]$ avocado-software-manager check-installed vim-common
dnf module for Python is required. Using the basic support from rpm and dnf commands
Running 'rpm -q vim-common'
Command 'rpm -q vim-common' finished with 0 after 0.01058053970336914s
Package vim-common already installed

[wrampazz@wrampazz ~]$ echo $?
0
```

Failed commands:
```
[wrampazz@wrampazz ~]$ avocado-software-manager check-installed htop
dnf module for Python is required. Using the basic support from rpm and dnf commands
Running 'rpm -q htop'
Command 'rpm -q htop' finished with 1 after 0.007279157638549805s
Package htop not installed

[wrampazz@wrampazz ~]$ echo $?
0

[wrampazz@wrampazz ~]$ avocado-software-manager install bla
dnf module for Python is required. Using the basic support from rpm and dnf commands
Running '/bin/sudo -n /bin/dnf -y install bla'
Command '/bin/sudo -n /bin/dnf -y install bla' finished with 1 after 2.611889362335205s
Failed to install bla

[wrampazz@wrampazz ~]$ echo $?
0
```

I was expecting `avocado-software-manager` to exit with the same `exitcode` as the command it internally executed, or at least something different from `0` whenever the internal command exits with something that is not `0`.

Any thoughts here?

**Comment by clebergnu** [comment]
I'd go with sharing, where applicable, the exit codes defined in `avocado.core.exit_codes`.  I don't think the underlying utilities exit codes are useful, given that this is actually supposed to be a generic interface that hides the underlying backends.

**Comment by willianrampazzo** [comment]
> I'd go with sharing, where applicable, the exit codes defined in `avocado.core.exit_codes`. I don't think the underlying utilities exit codes are useful, given that this is actually supposed to be a generic interface that hides the underlying backends.

Okay, I agree that the exit code does not need to match the utility exit code. Returning something defined on `avocado.core.exit_codes` is more than enough.

**Comment by beraldoleal** [comment]
> I'd go with sharing, where applicable, the exit codes defined in `avocado.core.exit_codes`. I don't think the underlying utilities exit codes are useful, given that this is actually supposed to be a generic interface that hides the underlying backends.

+1
