### ISSUE TITLE
We may upgrade isort to fix inspekt issue under avocado-vt project

### ISSUE THREAD

**Issue by chunfuwen** [avocado-framework/avocado#4298]
When running inspekt under avocado-vt project,  the error "module 'isort' has no attribute 'SortImports'" occurred , but I check the dependence of avocad-vt ,there is no any dependence on isort, but avocado has dependence on isort under the file requirements-selftests.txt. 
Therefore I suspend this is caused by isort under avocado.
Below are detailed logs
******************************************************************************

https://travis-ci.org/github/avocado-framework/avocado-vt/jobs/742324200

213.34s$ inspekt checkall --disable-lint W,R,C,E1002,E1101,E1103,E1120,F0401,I0011,E1003,W605 --disable-style W605,W606,E501,E265,W601,E402,E722,E741 --exclude avocado-libs,scripts/github --no-license-check
PEP8 disabled: W605,W606,E501,E265,W601,E402,E722,E741
Pylint disabled: W,R,C,E1002,E1101,E1103,E1120,F0401,I0011,E1003,W605
Pylint enabled : W0611
License check: disabled
internal error with sending report for module ['/home/travis/build/avocado-framework/avocado-vt/setup.py']
module 'isort' has no attribute 'SortImports'
internal error with sending report for module ['/home/travis/build/avocado-framework/avocado-vt/examples/tests/service.py']
module 'isort' has no attribute 'SortImports'
internal error with sending report for module ['/home/travis/build/avocado-framework/avocado-vt/examples/tests/template.py']
module 'isort' has no attribute 'SortImports'
internal error with sending report for module ['/home/travis/build/avocado-framework/avocado-vt/examples/tests/guest_hostname.py']

**Comment by beraldoleal** [comment]
Hi @chunfuwen , thanks for reporting this. I don't see any problem with updating our requirements since this is an issue with isort back compatibility. But IMO, this should be properly handled at inspector repo/project.

**Comment by clebergnu** [comment]
This is superseded by the use of https://github.com/avocado-framework/avocado-static-checks in all projects under the Avocado umbrella.
