### ISSUE TITLE
Distributed Testing Support?

### ISSUE THREAD

**Issue by rvbinder** [avocado-framework/avocado#4309]
I am looking for a test harness that will start, monitor, manage, and report concurrent test execution on multiple machines. I found Autotest, which seems to do this, but appears to be no longer supported and points to Avocado as its successor. It also appears to use Python 2.x, which would pose a problem in my environment. The Avocado documentation does not describe the orchestration of distributed tests as far as I can tell. If this understanding is not correct, please suggest how Avocado can be used for distributed testing.  If it is, please consider this as a future feature.

**Comment by willianrampazzo** [comment]
Hello @rvbinder, welcome to the Avocado Project!

Right now, Avocado Framework does not support distributed tests in the way you described. This is also a feature I would like to see in the project, and I think the community would appreciate it.

You raised this issue at the right time as we started to discuss the next steps after our last LTS release. The initial discussion is here: https://www.redhat.com/archives/avocado-devel/2020-September/msg00006.html. Feel free to reply to that and list the features that your project would benefit from.

**Comment by beraldoleal** [comment]
Hi @rvbinder, welcome!

I would like to add two more cents on top of @willianrampazzo's comment:

IIUC, today we have a new runner (`nrunner`) that it is being designed with that in mind too. 

You can execute the `nrunner`, as following:

```
$ avocado run --test-runner='nrunner' /bin/true /bin/false
```

Behind the "nrunner" we have the "spawner" concept, which will start your test inside "something". Today, we have support for "process" and "podman" spawners, that will run your tests in an isolated env. But, yes, new spawners can be implemented to run your tests remotely.

Today, the console UI report and HTML output will collect the results even when running tests on "podman" with the nrunner.

On top of that, we are also working on a better and improved "avocado-server" that will serve as a dashboard for your tests, and work with the 'nrunner' is one of the requirements.

**Comment by clebergnu** [comment]
@rvbinder there's been a slight update to this topic, with Avocado's ability to run tests on remote machines via the [remote spawner](https://avocado-framework.readthedocs.io/en/103.0/plugins/optional/spawner_remote.html).  This is the most Avocado can offer right now.

I'm closing this issue, but feel free to reopen and further contribute to the discussion (and features!).
