### ISSUE TITLE
Implement the initial architecture for a requirements resolver based on BP002 and add support for packages

### ISSUE THREAD

**Issue by willianrampazzo** [avocado-framework/avocado#4312]
This issue tracks the implementation of the initial architecture for a requirements resolver based on BP002.

The intent of this issue is also to implement the support for packages requirements.

**Comment by willianrampazzo** [comment]
I forgot to add https://github.com/avocado-framework/avocado/pull/4578 to this issue. Closing it as the PR was merged.

**Comment by beraldoleal** [comment]
@willianrampazzo would be nice to update the BP status as well. Today is "approved". Maybe "WIP" or "Implemented" ?
