### ISSUE TITLE
Assets / Cache: manually register content

### ISSUE THREAD

**Issue by clebergnu** [avocado-framework/avocado#4313]
Avocado's data cache support storing content `by_name`, in which a given file is referred to by its name, but can be found on many different places.

Let's attempt to reuse that feature, so that a user can point to an existing file, and have it copied/moved to the cache under the given name.  A sample use case is:

1) User has access to (by whatever mean) to file `custom-machine-firmware.bin`
2) While writing a test user decides that this file will be referred to as `custom-machine-firmware-foo-bar-v1.bin`
3) User runs `avocado asset register [--hash=VALUE] --by-name=custom-machine-foo-bar-v1.bin custom-machine-firmware.bin`

From this point on, it's possible to do, within a test:

```python
class Test:
   def test(self):
      boot_image = self.fetch_asset('custom-machine-firmware-foo-bar-v1.bin')
```

All options of `fetch_asset`, such as `cancel_on_missing`, should behave as expected.

---

The original request from QEMU reads:

_Not all artifacts can be easily downloadable, some are public but require the user to accept an End User License Agreement. Users would like to share their tests with the documentation about where/how
to download the requisite files (accepting the EULA) to run the tests._

**Comment by beraldoleal** [comment]
I'm not so familiar with the fetch plugin but I will give it a try here. Assigning to myself.
