### ISSUE TITLE
make not working on Fedora 33

### ISSUE THREAD

**Issue by richtja** [avocado-framework/avocado#4318]
The variable `AVOCADO_DIRNAME` in Makefile is not set properly on Fedora 33 and `make` has warning
 `/bin/sh: ${PWD\#\#*/}: bad substitution`

Because of this bug some `make commands` not work properly.

**Comment by beraldoleal** [comment]
I'm not sure what this expansion is trying to do. The closest one that I found on the reference manual was this:

> 
> ${parameter##word}
> 
>     The word is expanded to produce a pattern and matched according to the rules described below (see Pattern Matching). If the pattern matches the beginning of the expanded value of parameter, then the result of the expansion is the expanded value of parameter with the shortest matching pattern (the ‘#’ case) or the longest matching pattern (the ‘##’ case) deleted. If parameter is ‘@’ or ‘*’, the pattern removal operation is applied to each positional parameter in turn, and the expansion is the resultant list. If parameter is an array variable subscripted with ‘@’ or ‘*’, the pattern removal operation is applied to each member of the array in turn, and the expansion is the resultant list.

**Comment by beraldoleal** [comment]
IIUC, this is `basename ${PWD}`
