### ISSUE TITLE
JobAPI: all tests are being skipped when passing a 'nrunner.status_server_uri'

### ISSUE THREAD

**Issue by beraldoleal** [avocado-framework/avocado#4320]
Using the following example will make tests to fail.

```python3
#!/usr/bin/env python3

import sys
import glob
from avocado.core.job import Job
from avocado.core.suite import TestSuite
 
# Get the test binaries from the /tests/ directory
tests = glob.glob("/tmp/tests/*")
 
config = {
    'run.test_runner': 'nrunner',
    'nrunner.status_server_uri': '127.0.0.1:9999',
    # 'runner.exectest.exitcodes.skip': [77],
    'run.references': tests,
    }
 
suite = TestSuite.from_config(config)
with Job(config, [suite]) as j:
    sys.exit(j.run())

```

**Comment by willianrampazzo** [comment]
Isn't it related to https://github.com/avocado-framework/avocado/issues/4308?

**Comment by beraldoleal** [comment]
@willianrampazzo I had a look before opening this. Since this is just a preliminary investigation, I'm not 100%, maybe a different issue. I will be investigating this soon and I can mark this as duplicated if is the case.

**Comment by willianrampazzo** [comment]
> @willianrampazzo I had a look before opening this. Since this is just a preliminary investigation, I'm not 100%, maybe a different issue. I will be investigating this soon and I can mark this as duplicated if is the case.

Okay, I don't think they are exactly the same in the sense that a piece of code will fix both, but when we do a mass refactor and clean-up in the status server side, both will be gone.

**Comment by beraldoleal** [comment]
@willianrampazzo @mcondotta, I started investigating this today. Actually afaict, this is expected.
You are saying to Avocado to send results to another server that is not up. ;) By default Avocado starts a status server on 8888, if you change the port to 8888, this will work. 

So, unless I'm missing something, this is not a bug. Please, feel free to reopen if needed.
