### ISSUE TITLE
Nrunner gets stuck when running some KVM Unit Tests

### ISSUE THREAD

**Issue by mcondotta** [avocado-framework/avocado#4322]
I wrote a small Job API script, with Beraldo's help to be able to run KVM Unit Tests using Avocado Nrunner.
It is mostly working fine, however there are 2 (vmx, vmx_vmcs_shadow_test) tests for x86 that get stuck and never return.

How to Reproduce:
git clone https://gitlab.com/kvm-unit-tests/kvm-unit-tests.git
cd kvm-unit-tests
./configure ; make standalone
avocado run --test-runner='nrunner'  ./tests/vmx_vmcs_shadow_test

The test itself seems to finish, the QEMU invoked by the test exits, but the bash invokation never returns and thus the JOB and Nrunner never finish.

**Comment by clebergnu** [comment]
@mcondotta could you let me know your output for:

```avocado-runner-exec-test runnable-run -u ./tests/vmx_vmcs_shadow_test```

Thanks!

**Comment by mcondotta** [comment]
@clebergnu sure!
It keeps just repeating this:
{'status': 'running', 'time': 276874.874089401, 'result': 'fail'}
{'status': 'running', 'time': 276875.382542493, 'result': 'fail'}

I see with "ps -ef | grep vmx" that the test itself finished, however the "bash ./tests/vmx_vmcs_shadow_test" never finishes.
I'm thinking this might be a PIPE issue, both these tests dump an absurd amount of data to the stdout/stderr.
Both tests work fine with the legacy runner and when I made a change to avocado/core/nrunner.py to change stdout=subprocess.PIPE to stdout=subprocess.DEVNULL, the tests passed.

**Comment by clebergnu** [comment]
FIY #4323 is a *related* fix, but I don't think it's the only fix needed.

**Comment by beraldoleal** [comment]
@clebergnu I created issue #4321, not to fix, but to help in this case.

**Comment by beraldoleal** [comment]
I might have found the issue. Preparing a PR.

**Comment by beraldoleal** [comment]
@mcondotta can you try #4324 together with #4321, please?
