### ISSUE TITLE
Does the Avocado Project still need to support Python 3.5?

### ISSUE THREAD

**Issue by willianrampazzo** [avocado-framework/avocado#4338]
Python 3.5 last release was on Sept. 5, 2020, (https://www.python.org/dev/peps/pep-0478/) but the 3.5 branch reached the end of life and is not supported anymore (https://devguide.python.org/#status-of-python-branches).

Based on that, should the Avocado Project advertise Python 3.6 as the minimum version and drop 3.5?

**Comment by beraldoleal** [comment]
+1

**Comment by richtja** [comment]
:+1:

**Comment by clebergnu** [comment]
Because QEMU has lifted the minimum version to 3.6, I don't see why we can't bump it too.

**Comment by beraldoleal** [comment]
@clebergnu I'm doing a pr right now.
