### ISSUE TITLE
Task with default status_uri

### ISSUE THREAD

**Issue by richtja** [avocado-framework/avocado#4352]
When we're initializing a new `Task` object, we can have default `status_uri` same as default `nrunner.status_server_uri`. We are doing the same in `TestSuite.from_config()`

**Comment by beraldoleal** [comment]
@richtja I'm revisiting this, and I have doubts if this makes sense.

For instance, status server URI could be something like '0.0.0.0:8080' (to be listening in multiple interfaces). In this case, makes no sense to send messages to this address. I would also prefer to avoid corner cases (and ifs) here.

Makes sense?

If you agree, we can close this.

**Comment by richtja** [comment]
@beraldoleal AFAIK every time when we are creating the Task we are setting the `status_uri` from `nrunner.status_server_uri`. So if you set `nrunner.status_server_uri` to `0.0.0.0:8080` the `Task.status_services` will be set to `0.0.0.0:8080` this is won't be changed by this issue. My point is to not setting `status_uri` every time when we are creating `Task` as we are doing now, but have it as default.

**Comment by beraldoleal** [comment]
@richtja I got confused with the status_server_listen. Sorry for the mess. I will try to implement this.

**Comment by beraldoleal** [comment]
@richtja I did a second round of debugging here. Do you have any use case where you are creating a Task object with an empty `status_uris`?

AFAICT, today, during our runs, we are passing `status_uris` with the same value as  `nrunner.status_server_uri`.

Now, If you are creating an object Task manually, then I think that I understood the point here. IIUC, my suggestion is to remove `status_uris`  argument completely and use it as part of the configuration options/file. I will try to explain...

Today, we are passing all configuration options starting with `runner.` as runnable config. So since we are moving towards removing legacy runners, and having only one runner. We could also pass all configuration options starting with `nrunner.` to the config as well. And we have already there the `nrunner.status_server_uri`. This makes sense to me, what do you think?

**Comment by richtja** [comment]
@beraldoleal For the context, I created this issue when we had to create Task inside TestSuite creation wchich was changed in 93f93764f311ef2a988dc23bdbac80db11cfdc3f that is why I'm mentioning the `TestSuite.from_config()` here. 

I don't know any use case with the empty `status_uris`.

AFAIK right now we are using one status server, but Tasks are able to send messages to the multiple status servers and I don't know what is the expected behavior of this. If two different tasks should be able to send messages to the two different status servers than I think your solution won't work. But I am not sure what exactly is the purpose of multiple status serves. But now we have this ability.

**Comment by beraldoleal** [comment]
>If two different tasks should be able to send messages to the two different status servers than I think your solution won't work. 

My proposal is not intended to solve this problem, but only your "issue subject": Having a default status uris when creating tasks. I believe that for addressing this particular issue, we have already #4308, and we can create other issues for that.

**Comment by richtja** [comment]
Sorry but I am not understand what you mean, because I think that the #4308 is a completely different problem. It is about multiple jobs connected to one server and that is not related to this issue.

**Comment by beraldoleal** [comment]
Ok, my bad. Too little coffee at this time.

> If two different tasks should be able to send messages to the two different status servers than I think your solution won't work.

But is this issue about one task being able to connect to multiple status servers? I was only focusing on the default value here.

My proposal is only changing the place where we get the value, the argument, we get from the config. My logic was:

Today we are passing everything that starts with `runner.` as a configuration option to the `config` dict. Soon, we are going to merge `nrunner.` with `runner.` namespace, so this nrunner.foo.bar namespace will be there already and can be a list of status servers so a task can connect to multiple servers.

**Comment by beraldoleal** [comment]
Hi @richtja, since #4688 it was merged, maybe we don't need the `status_uri` on the constructor anymore, right? 

You could try to solve this using the config dict.

I will assign this to you too, but please let me know if you need any help.
