### ISSUE TITLE
Evaluate GH actions for this project

### ISSUE THREAD

**Issue by beraldoleal** [avocado-framework/avocado#4357]
Travis jobs are giving us some extra coffee time and might have available some machines to run custom runners. Let's see if GH actions can help us here.

**Comment by beraldoleal** [comment]
Initial PR is here #4475

**Comment by pevogam** [comment]
Hi @beraldoleal, do you mind clarifying what is the intended future in that regard? Is it to deprecate Travis CI completely and switch to GH actions entirely or to combine the two in some manner?

**Comment by beraldoleal** [comment]
@pevogam , we are facing some issues with Travis (multiple jobs are failing and waiting too much in order to start our jobs). Also,"travis-ci.org will be shutting down in several weeks, with all accounts migrating to travis-ci.com". 

So we are just evaluating GH actions and testing other alternatives. No decision was made yet. For now we are going to have both to evaluate and compare.

**Comment by clebergnu** [comment]
The first experiment has been committed, and we'll now monitor how well it behaves. Further actions will be tracked on other issues.

For now, we'll be keeping all the CI systems, and not dropping anyone.

**Comment by beraldoleal** [comment]
@pevogam just to give you some visibility: Travis is going from .org to .com as we noticed a few months ago, and the credits are not enough. So @ana is working migrating our CI to GH Actions.

**Comment by pevogam** [comment]
@beraldoleal It makes complete sense, we hit the same limit and also started some migrations. Very good call that you started GH actions migrations in advance.
