### ISSUE TITLE
Make a consistent setup.py with Makefile commands

### ISSUE THREAD

**Issue by beraldoleal** [avocado-framework/avocado#4372]
Today, we have a Makefile with some targets in addition to the setup.py with others. My suggestion is to make this consistent, by using setup.py targets only.

This means that the "implementation" part would be python code inside setup.py and/or utilities/modules. But we can still have a Makefile with the same targets pointing to setup.py calls.

This might help with #4357.

**Comment by ana** [comment]
https://github.com/avocado-framework/avocado/issues/4028 could be addressed as part of this.

**Comment by ana** [comment]
Folks, once https://github.com/avocado-framework/avocado/pull/4890 is merged. I consider this issue done. The Makefile could be re-worked and include https://github.com/avocado-framework/avocado/issues/4028 but this issue is about the setup.py and it's IMHO finished.
Is there anything else you're missing? @beraldoleal @clebergnu @richtja @willianrampazzo

**Comment by ana** [comment]
Folks, once https://github.com/avocado-framework/avocado/pull/4889 is merged. I consider this issue done. The Makefile could be re-order and include https://github.com/avocado-framework/avocado/issues/4028 but this issue is about the setup.py  only.
Is there anything else you're missing? @beraldoleal @clebergnu @richtja @willianrampazzo

**Comment by beraldoleal** [comment]
Hi @ana, sorry for the late reply here. 

While I think our Makefile is much better today and closer to our setup.py, I still think we do have some rooms for improvements.

> My suggestion is to make this consistent, by using setup.py targets only.

When I created this issue, the idea was not be restricted to the setup.py only. But update both so they can be consistent.

> This means that the "implementation" part would be python code inside setup.py and/or
> utilities/modules. But we can still have a Makefile with the same targets pointing to setup.py calls.

We do still have some targets on Makefile that don't have a mapping inside setup.py. i.e: source-pypi, wheel, pypi, requirements-plugins, propagte-versions, etc. While they don't need to be a 1:1 exact mapping, I have the impression that as much as closer better for maintainability and usability.

My initial ideal when created this issue it was to do a prep-work for a future Makefile purge, letting us only with the setup.py targets, to avoid having the targets in two places.

I hope this makes some sense.

**Comment by ana** [comment]
Hi @beraldoleal 

Thanks for the reply!  Almost all the targets you mentioned: `source-pypi, wheel, pypi, propagate-versions`, shouldn't be integrated in `setup.py`, because they should disappear once they're integrated in the release action (on-going at https://github.com/avocado-framework/avocado/pull/4938 ). 

The only remaining is `requirements-plugins`. This one should wait until we decide what to do with the plugins. There is also the option of removing it completely since none of the plugins under `optional_plugins` is providing a `requirements.txt` or a` Makefile`, and implement it directly when (if) becomes necessary.

**Comment by beraldoleal** [comment]
> Hi @beraldoleal
> 
> Thanks for the reply! Almost all the targets you mentioned: `source-pypi, wheel, pypi, propagate-versions`, shouldn't be integrated in `setup.py`, because they should disappear once they're integrated in the release action (on-going at #4938 ).

What about when we have a need for running those targets locally? That means that we have to look at the CI yaml file for the specific commands/steps?

Why not using the opposite direction: CI actions calling our local targets IMO? Instead of having multiple lines of code inside yaml files in our CI, it would be easier to make the CI call for our local targets (makefile/setup) instead. Removing the actual code from here and leaving only on CI would make not so trivial for running the action locally. Any reason for not going that way?
 
> The only remaining is `requirements-plugins`. This one should wait until we decide what to do with the plugins. There is also the option of removing it completely since none of the plugins under `optional_plugins` is providing a `requirements.txt` or a` Makefile`, and implement it directly when (if) becomes necessary.

I don't see as a blocker, specially if this target is doing nothing today. Also the current`setup.py` is adding `optional_plugins` path to the list of plugins when installing via `plugin` subcommand. So leaving as it is it gives me some confusion about what I should use, this Makefile target vs `setup plugin`. We could make this consistent.

**Comment by ana** [comment]
> > Hi @beraldoleal
> > Thanks for the reply! Almost all the targets you mentioned: `source-pypi, wheel, pypi, propagate-versions`, shouldn't be integrated in `setup.py`, because they should disappear once they're integrated in the release action (on-going at #4938 ).
> 
> What about when we have a need for running those targets locally? That means that we have to look at the CI yaml file for the specific commands/steps?

> Why not using the opposite direction: CI actions calling our local targets IMO? Instead of having multiple lines of code inside yaml files in our CI, it would be easier to make the CI call for our local targets (makefile/setup) instead. Removing the actual code from here and leaving only on CI would make not so trivial for running the action locally. Any reason for not going that way?

I see the opposite, why having to call for the Makefile (or setup.py!) to run an action that's only run for the release or it's basically one line command easy to remember.
Do you have any usercase where you actually need to run any of these actions outside of the release? 

 
> > The only remaining is `requirements-plugins`. This one should wait until we decide what to do with the plugins. There is also the option of removing it completely since none of the plugins under `optional_plugins` is providing a `requirements.txt` or a` Makefile`, and implement it directly when (if) becomes necessary.
> 
> I don't see as a blocker, specially if this target is doing nothing today. Also the current`setup.py` is adding `optional_plugins` path to the list of plugins when installing via `plugin` subcommand. So leaving as it is it gives me some confusion about what I should use, this Makefile target vs `setup plugin`. We could make this consistent.

Not sure to understand your reply, you're saying you're ok removing it?

**Comment by beraldoleal** [comment]
> > > Hi @beraldoleal
> > > Thanks for the reply! Almost all the targets you mentioned: `source-pypi, wheel, pypi, propagate-versions`, shouldn't be integrated in `setup.py`, because they should disappear once they're integrated in the release action (on-going at #4938 ).
> > 
> > 
> > What about when we have a need for running those targets locally? That means that we have to look at the CI yaml file for the specific commands/steps?
> 
> > Why not using the opposite direction: CI actions calling our local targets IMO? Instead of having multiple lines of code inside yaml files in our CI, it would be easier to make the CI call for our local targets (makefile/setup) instead. Removing the actual code from here and leaving only on CI would make not so trivial for running the action locally. Any reason for not going that way?
> 
> I see the opposite, why having to call for the Makefile (or setup.py!) to run an action that's only run for the release or it's basically one line command easy to remember.
> Do you have any usercase where you actually need to run any of these actions outside of the release?

The readability of a block of code inside a yaml file is not the best. Having bash for loop mixed with yaml syntax could be avoided, for instance.

Also, on top of that, third party CIs can be offline for any reason, having the ability to run during an emergency situation a target it is helpful. And it is better to have it as a simple  target instead of a block of code.

> > > The only remaining is `requirements-plugins`. This one should wait until we decide what to do with the plugins. There is also the option of removing it completely since none of the plugins under `optional_plugins` is providing a `requirements.txt` or a` Makefile`, and implement it directly when (if) becomes necessary.
> > 
> > 
> > I don't see as a blocker, specially if this target is doing nothing today. Also the current`setup.py` is adding `optional_plugins` path to the list of plugins when installing via `plugin` subcommand. So leaving as it is it gives me some confusion about what I should use, this Makefile target vs `setup plugin`. We could make this consistent.
> 
> Not sure to understand your reply, you're saying you're ok removing it?

Yes, I'm ok, specially because setup.py is already doing part of this "installation job" (and IMO makes no sense to have the installation there and the "requirements" installation in a different place.

**Comment by ana** [comment]
We are now in a much better situation with a main Makefile where most of the targets rely on a `setup.py` command.  Ancillary targets used to test packaging or by CI have been moved to secondary makefiles.
There will be changes in the future such as moving parts of  `setup.py` to `setup.cfg` but that will be part of a different epic issue.
