### ISSUE TITLE
email the report after completion of a job

### ISSUE THREAD

**Issue by sofiya07** [avocado-framework/avocado#4387]
Is there any API in avocado where an email could be sent to the user, once the job completes the run.

If yes , kindly point the link to set up the email.

Thanks

**Comment by beraldoleal** [comment]
Hi @sofiya07 , I might be wrong, but AFAICT, we don't have plugins to send emails, and that would be a nice one to have, IMO.

But, we have plugins that generate HTML output and another one that publishes the results to a server:

https://avocado-framework.readthedocs.io/en/84.0/plugins/optional/results.html#

**Comment by clebergnu** [comment]
Hi @sofiya07 

We have an example plugin at https://github.com/avocado-framework/avocado/blob/master/examples/plugins/job-pre-post/mail/avocado_job_mail.py that may serve as a starting point for you.

Bonus points if you convert it into a more usable (and official) plugin! :)

**Comment by harvey0100** [comment]
Giving this an update with a current plugin that is in development. 
https://github.com/avocado-framework/avocado/pull/5943

Further mail server support will be added soon, for the time being, this request allows emails from Gmail servers.

**Comment by clebergnu** [comment]
Closing based on the merging of #5943
