### ISSUE TITLE
Allow to easily correlate tests with their maintainers

### ISSUE THREAD

**Issue by wainersm** [avocado-framework/avocado#4430]
The intent here is to describe with my own words a requirement that came up a few times on QEMU community, which is about correlating tests with maintainers. AFAIK Philippe Mathieu-Daudé  is the person who first came up with that idea, being the last time mentioned on [1].

### Context

Let's start with a simplification of the QEMU development process.

QEMU development grew around the maintainership concept (just like Linux): a set of individuals maintain specific parts of the code base. Whenever someone contributes a patch series, it is advisable he/she seeks for reviews and approvals from those maintainers of the various parts a change can touch. In order to easily identify those individuals, the community keeps the `MAINTAINERS` file in the source's root that maps people to files/directories and record the status of those parts (supported, orphan, etc). Tools will read from that file to implement workflows, for example, the `scripts/./scripts/get_maintainer.pl` script use it to suggest who can be emailed a patch series.

### Problem

Let's talk about the avocado-based tests on QEMU, currently a very few of them have an owner. There are some pain-points to map tests in the `MAINTAINERS` file. Using the `tests/acceptance/boot_linux_console.py` file to explain the situation:
 * that files contain test methods for various target architectures (mips, x86_64, s390, etc) and machine types
 * in `MAINTAINERS` you indicate the parts in files/directories granularity
 * it is unlikely to have a single person who would take ownership of the whole  `boot_linux_console.py` file (consequently of all tests) because people are usually interested on just a subset of architectures and/or machine types

But why is important to correlate tests with maintainers? Some reasons are:

 * If a give test fails on CI then it may indicate a regression on QEMU. You might need to consult the test maintainer, that will certainly help on investigate the failure;
 * if a given test fails consistently it may indicate a bug on the test itself or the CI runtime environment. The test maintainer should be involved in any actions which could be taken: should he/she provide a fix? Should the test be disable? or possible removed from source code?
 * In case of a widely refactoring of the acceptance tests, who should be reviewing/acking the changes?
 * Unmaintained tests are likely to introduce more problems than not having them on first place
 * If we want to have gating CI then maintainers are wanted to promote (demote) tests to/from the gate keeper

### What it has to do with Avocado?

Philippe Mathieu-Daudé suggested the use of avocado tags to help on solving the problem. And if it is the direction to go forward then some improvements on Avocado side will be need.

His idea (see in [1]) is to introduce a new field on `MAINTAINERS` which value is an avocado tag. This way tests tagged with the same value can be related with an entry on the `MANTAINERS` file. That will allow to map individual test methods/classes to maintainers (or reviewers). He also suggested a use case: once a test fails on CI, it's printed the maintainers of that test.

AFAIK, Avocado doesn't provide any mean to deal with tags besides the runner being able to filter in/out tests by tag; or the `avocado list` being able to apply filters likewise. Some operations/information which might be useful for the users of Avocado to implement complex workflows:

 * Print a sorted list of all tags used so that I, a test writer, can re-use an existing tag
 * `avocado list --show-tags`  so that I, as CI admin, can see how each test is tagged so possible serving as input to create filters 
 * On job's results file (e.g. results.json) write the list of tags per job. So that I, as an CI admin, can make a script to print the owners of the tests which failed

### References

[1] https://lists.gnu.org/archive/html/qemu-devel/2021-01/msg02924.htm

**Comment by beraldoleal** [comment]
Thanks @wainersm for bringing this.

About `avocado list --show-tags` we have the `--verbose` mode that shows the tags. Isn't that enough for them?

**Comment by beraldoleal** [comment]
@wainersm please, let us know if the current --verbose plus the latest PR about this will solve QEMU's problem.

Are you still missing something else?

**Comment by pevogam** [comment]
Something like Avocado VT could greatly benefit from such mapping since it contains large areas of possibly completely unmaintained code. But I apologize if this is not relevant and I might be taking the issue beyond the scope of Qemu.

**Comment by beraldoleal** [comment]
In my understanding this is already possible today and this issue could be closed. @wainersm What I'm missing?

**Comment by clebergnu** [comment]
@wainersm did @beraldoleal answer your questions?

**Comment by wainersm** [comment]
Hi @pevogam ,

> Something like Avocado VT could greatly benefit from such mapping since it contains large areas of possibly completely unmaintained code. But I apologize if this is not relevant and I might be taking the issue beyond the scope of Qemu.

It is completely fine (and I would say welcomed) if what I suggest here could be used by many projects. Thanks for bringing a new (possible use case) here.

**Comment by wainersm** [comment]
Hi @beraldoleal ,

> In my understanding, this is already possible today and this issue could be closed. @wainersm What I'm missing?

Sorry for taking too long to reply, my github notifications aren't well tuned so I missed your question.

I think the `avocado --verbose list` plus https://github.com/avocado-framework/avocado/pull/4444 should be enough to implement all of the use cases I describe on this issue.

One improvement, though, would be to implement a machine-readable output for `avocado list` so that scripts could process it more easily (instead of parse the text output). I can open that requirement on a separate issue, then we close this one. What do you think @beraldoleal ?

**Comment by beraldoleal** [comment]
@wainersm cool. Thanks for the reply.

Yes, I agree, this could be close and we can track this new requirement as a separate issue. Please do the honors.

**Comment by wainersm** [comment]
> @wainersm cool. Thanks for the reply.
> 
> Yes, I agree, this could be close and we can track this new requirement as a separate issue. Please do the honors.

and send the PR? :D

**Comment by wainersm** [comment]
I am satisfied with the features that avocado 87.0 provides for filling up the QEMU requirements I described on this issue. Thus, I am going to close it.
