### ISSUE TITLE
lint doesn't check every file

### ISSUE THREAD

**Issue by richtja** [avocado-framework/avocado#4437]
Our lint check script doesn't check every python file inside the avocado project. This problem occurs especially in examples and selftests directories. It's happening because pylint assumes that any directory is a package, and fails if not. [[1]](https://github.com/PyCQA/pylint/issues/352) So when directory is not a package all files and subdirectories are not checked by lint.

**Comment by tiagohonorato** [comment]
A possible temporary solution (while pylint doesn't provide a solution to lint directories that are not packages) would be to use something like``git ls-files '*.py'`` to list all tracked python files and use it as input to pylint.
