### ISSUE TITLE
datadir.* with inconsist values

### ISSUE THREAD

**Issue by beraldoleal** [avocado-framework/avocado#4443]
Maybe I'm missing something, but I think we have today some inconsistent outputs:

If I would like to show my current "datadirs":
```
$ avocado config --datadir
...

Avocado Data Directories:
    base     /home/local/src/venvs/avocado-py3.7
    tests    /home/local/src/beraldo/avocado/examples/tests
    data     /home/local/src/venvs/avocado-py3.7/data
    logs     /home/local/avocado/job-results
    cache  /home/local/src/venvs/avocado-py3.7/data/cache
```

This method is getting that information from `data_dir.get_base_dir()` and some other utility methods.

But since we are using config dicts, I would expect to see those "default" values also on the following output:

```
 $ avocado config | grep datadir.paths
    datadir.paths.base_dir                   /var/lib/avocado
    datadir.paths.cache_dirs                 []
    datadir.paths.data_dir                   /var/lib/avocado/data
    datadir.paths.logs_dir                   /home/local/avocado/job-results
    datadir.paths.test_dir                   /usr/share/doc/avocado/tests
```

@clebergnu can you please, confirm if my understand is right? IMO, we should set the default values during the registration of the config option and remove the line `avocado/core/data_dir.py:208`, for instance (that is forcing a "default" value hardcoded). 

I'm already changing this, but just would like to double-check with you guys.

**Comment by clebergnu** [comment]
@beraldoleal I see your point.  The issue is that data directories (meaning those coming from `avocado/core/data_dir.py`, and being shown on `avocado config --datadir`) are more dynamic than the configuration entries.

It would be great if they could just behave like regular config indeed.  IMO we should at least try to achieve what you propose, removing the special behavior of `avocado.core.data_dir` and `avocado config --datadir`.

**Comment by beraldoleal** [comment]
> @beraldoleal I see your point. The issue is that data directories (meaning those coming from `avocado/core/data_dir.py`, and being shown on `avocado config --datadir`) are more dynamic than the configuration entries.

Not sure I agree/understood, since configurations could be manipulated dynamically as well. 

> It would be great if they could just behave like regular config indeed. IMO we should at least try to achieve what you propose, removing the special behavior of avocado.core.data_dir and avocado config --datadir.

Ok, I will see what I can do, and let you know if I hit some wall.
