### ISSUE TITLE
still troubles with run remote/vm plugin with output (not JSON) more tests

### ISSUE THREAD

**Issue by jscotka** [avocado-framework/avocado#449]
Hi,
I have version of avocado 20.0.1 and there is still some problem with remote/vm running of tests -> I know that you've repaired  partially, but it seems that there is some issue what cause traceback.
Propably it could be caused by more tests running in one avocado run command and which have various output. So it could be something like mixed more JSON output + strange text between
     Regards
     Honza

DOMAIN     : checkmachine7-fedora-21-x86_64
LOGIN      : root@192.168.122.2:22
JOB ID     : ebb596e3324213d96256264fa45b3ba57dc00612
JOB LOG    : /home/jscotka/avocado/job-results/job-2015-02-27T03.21-ebb596e/job.log
TESTS      : 3
(1/3) /root/avocado/tests/tmp/avocado-test/sources.sh: PASS (3.19 s)
(2/3) /root/avocado/tests/tmp/avocado-test/inittest.sh: PASS (3.01 s)
(3/3) /root/avocado/tests/tmp/avocado-test/compiletest.sh: PASS (133.17 s)
PASS       : 3
ERROR      : 0
FAIL       : 0
SKIP       : 0
WARN       : 0
TIME       : 139.37 s
DOMAIN     : checkmachine7-fedora-21-x86_64
LOGIN      : root@192.168.122.2:22
Avocado crashed: ValueError: Could not parse JSON from avocado remote output:
> Authentication failed
> Authentication failed
> Permission denied
> couldn't read serial dmi info: Process exited with code 1
> couldn't read serial dmi info: Process exited with code 1
Avocado crashed: TypeError: ('__init__() takes exactly 2 arguments (1 given)', <class 'testlib.Error'>, ())
Traceback (most recent call last):

  File "/usr/lib/python2.7/site-packages/avocado/job.py", line 301, in _run
    failures = self.test_runner.run_suite(test_suite)

  File "/usr/lib/python2.7/site-packages/avocado/runner.py", line 171, in run_suite
    test_state = q.get()

  File "/usr/lib64/python2.7/multiprocessing/queues.py", line 376, in get
    return recv()

TypeError: ('__init__() takes exactly 2 arguments (1 given)', <class 'testlib.Error'>, ())

Please include the traceback info and command line used on your bug report
Report bugs visiting https://github.com/avocado-framework/avocado/issues/new
Traceback (most recent call last):

  File "/usr/lib/python2.7/site-packages/avocado/job.py", line 301, in _run
    failures = self.test_runner.run_suite(test_suite)

  File "/usr/lib/python2.7/site-packages/avocado/plugins/remote.py", line 74, in run_suite
    results = self.run_test(self.result.urls)

  File "/usr/lib/python2.7/site-packages/avocado/plugins/remote.py", line 61, in run_test
    "\n%s" % result.stdout)

ValueError: Could not parse JSON from avocado remote output:
> Authentication failed
> Authentication failed
> Permission denied
> couldn't read serial dmi info: Process exited with code 1
> couldn't read serial dmi info: Process exited with code 1
Avocado crashed: TypeError: ('__init__() takes exactly 2 arguments (1 given)', <class 'testlib.Error'>, ())
Traceback (most recent call last):

  File "/usr/lib/python2.7/site-packages/avocado/job.py", line 301, in _run
    failures = self.test_runner.run_suite(test_suite)

  File "/usr/lib/python2.7/site-packages/avocado/runner.py", line 171, in run_suite
    test_state = q.get()

  File "/usr/lib64/python2.7/multiprocessing/queues.py", line 376, in get
    return recv()

TypeError: ('__init__() takes exactly 2 arguments (1 given)', <class 'testlib.Error'>, ())

Please include the traceback info and command line used on your bug report
Report bugs visiting https://github.com/avocado-framework/avocado/issues/new

Please include the traceback info and command line used on your bug report
Report bugs visiting https://github.com/avocado-framework/avocado/issues/new

**Comment by lmr** [comment]
Solved by #454.

**Comment by lmr** [comment]
@jscotka, sorry once again for the bug, and I hope you won't have more related troubles.

**Comment by jscotka** [comment]
Hi,
Nevermind :-) Thats why it has big profit for both projects.
As I said to Lukas Doktor, it would be nice to use cockpit testsuite to use as acceptance testing for Avocado :-) (It is not inportant if testsuite pass of fail, but there should not be any traceback)
    Regards
    Honza

**Comment by ldoktor** [comment]
Čau Honzo,

hopefully this should not re-occur. I put the simple reproducer in our selftests, so in some way we have part of your copilot test in our smoke test suite.

Thank you for all the feedback,
Lukáš
