### ISSUE TITLE
run avocado test on a physical machine?

### ISSUE THREAD

**Issue by omps** [avocado-framework/avocado#4499]
I have gone through the documents couldn't find how we can run tests on physical machine, the avocado-vt is creating qemu images which is not really kind of test we want to run. Unlike autotest, avocado doesn't allow for remote running of tests.

Could you please point me to the correct documentation?

**Comment by beraldoleal** [comment]
Hi @omps I'm not sure if I understood your question. Do you mean a local physical machine? Or a remote physical machine?

For both cases, you can run avocado, by just installing avocado and running your tests. Could you explain a little bit?

**Comment by omps** [comment]
Thanks. Will try

**Comment by beraldoleal** [comment]
Humm I see. Yes, the runners are removed, but with the new architecture, it is easy to add. We have for instance the "podman runner" that runs on a podman.

But you can install avocado remotely with ansible or via ssh manually and run your tests there.

**Comment by clebergnu** [comment]
Hi @omps, the [remote spawner](https://avocado-framework.readthedocs.io/en/103.0/plugins/optional/spawner_remote.html) should be a viable option to you here.
