### ISSUE TITLE
Avocado crash without output

### ISSUE THREAD

**Issue by richtja** [avocado-framework/avocado#4527]
When I run nrunner with the wrong test path avocado crashes without any information. It can be reproduced by:

`avocado run --test-runner=nrunner --ignore-missing-references -- test_utils_partition.py`

**Comment by beraldoleal** [comment]
@richtja because you are using `--ignore-missing-references`? What is the expected result?

**Comment by richtja** [comment]
Yes, I think that is happening because of usage of `--ignore-missing-references`. I think that this should be ok to do. But I am getting exit code `2` which means  `AVOCADO_JOB_FAIL`. Sorry that I didn't explain it properly at the beginning.

**Comment by beraldoleal** [comment]
Yes, so we should change the return code, but I guess that it is ok to assume no output here.
