### ISSUE TITLE
Add machine-readeable output to `avocado list`

### ISSUE THREAD

**Issue by wainersm** [avocado-framework/avocado#4538]
So that scripts could more easily use its output to implement complex workflows. Examples of workflows can be found at https://github.com/avocado-framework/avocado/issues/4430

Currently `avocado list` prints to stdout as human-readable text. If you use options like `--verbose` it will print detailed information about the tests, however, this isn't easily consumed as one would need to implement a parser. Thus, an ouput on json format would be very welcomed.

**Comment by beraldoleal** [comment]
Thank you @wainersm, Sounds good to me. I will take care of this.
