### ISSUE TITLE
Test parameters not being used by the next runner

### ISSUE THREAD

**Issue by beraldoleal** [avocado-framework/avocado#4569]
Here some basic steps to reproduce:

```python
avocado run --test-runner='nrunner'  ./examples/tests/sleeptest.py -p sleep_length=30
```

This should take 30 seconds but is passing with 1 second delay.

Maybe, with nrunner, `parameters` are deprecated since we have `args` and `kwargs`. @clebergnu can help us here.

**Comment by marioaag** [comment]
@clebergnu, is any way to work around this issue or do you have a ETA, for the fix? I'm really interested in this feature

**Comment by marioaag** [comment]
@clebergnu, I have been looking at the code and from the beginning params is empty in the test_factory variable passed to load_test in the avocado_instrumented runner.

Is this in purpose? where are the params provided via cmd going to be handle (could be done at Test class)? and also is it planed to keep the support of passing run.test_parameters as part of the runnable config parameter?

If you want I can help with this issue, just need guidance about this questions and some background about the AvocadoParams class, I did some testing hardcoding values to the test_factory variable and didn't get that value available at the test level.
```
            test_factory = [klass,
                            {'name': TestID(1, klass_method),
                             'methodName': method,
                             'config': runnable.config,
                             'modulePath': module_path,
                             'params': (TreeNode({'host_ip': 8888}), []),    <--- value hardcoded
                             'tags': runnable.tags,
                             'run.results_dir': tempfile.mkdtemp(),
                             }]

```

Not sure if the error is the way that I'm instantiating the TreeNode class or is it a real bug in AvocadoParams class

**Comment by clebergnu** [comment]
> @clebergnu, is any way to work around this issue or do you have a ETA, for the fix? I'm really interested in this feature

Hi @marioaag,

I was hoping for getting this done for 89.0, but it just won't be possible.  I did get the varianter part hooked up to the nrunner, then the passing of the parameters inside each variant (as well as the standalone parameters) would be the next problem I'd tackle.

So, long story short, the ETA should be early in the 90th sprint, and thus into the released 90.0.

**Comment by clebergnu** [comment]
> @clebergnu, I have been looking at the code and from the beginning params is empty in the test_factory variable passed to load_test in the avocado_instrumented runner.
> 
> Is this in purpose? where are the params provided via cmd going to be handle (could be done at Test class)? and also is it planed to keep the support of passing run.test_parameters as part of the runnable config parameter?
> 

Right now, with the "legacy runner", the parameters given on the command line (`-p`) will take precedence and disable the parameters from variants.  This is a limitation, of course, but we never got to the right logic of merging those standalone parameters with the varianter paramters for various reasons.  One of them is the tree-based/path capabilities of the AvocadoParams/TreeNode. 

> If you want I can help with this issue, just need guidance about this questions and some background about the AvocadoParams class, I did some testing hardcoding values to the test_factory variable and didn't get that value available at the test level.
> 
> ```
>             test_factory = [klass,
>                             {'name': TestID(1, klass_method),
>                              'methodName': method,
>                              'config': runnable.config,
>                              'modulePath': module_path,
>                              'params': (TreeNode({'host_ip': 8888}), []),    <--- value hardcoded
>                              'tags': runnable.tags,
>                              'run.results_dir': tempfile.mkdtemp(),
>                              }]
> ```
> 
> Not sure if the error is the way that I'm instantiating the TreeNode class or is it a real bug in AvocadoParams class

Hey, good to see that you've been experimenting with this.  From a quick look, it does look like you're on the right track.

Please bear with me for just another day, and I'll dive deeper (again) into this and I'll be able to give you some more precise answers.

Thanks!!!

**Comment by clebergnu** [comment]
> > @clebergnu, I have been looking at the code and from the beginning params is empty in the test_factory variable passed to load_test in the avocado_instrumented runner.
> > Is this in purpose? where are the params provided via cmd going to be handle (could be done at Test class)? and also is it planed to keep the support of passing run.test_parameters as part of the runnable config parameter?
> > If you want I can help with this issue, just need guidance about this questions and some background about the AvocadoParams class, I did some testing hardcoding values to the test_factory variable and didn't get that value available at the test level.
> > ```
> >             test_factory = [klass,
> >                             {'name': TestID(1, klass_method),
> >                              'methodName': method,
> >                              'config': runnable.config,
> >                              'modulePath': module_path,
> >                              'params': (TreeNode({'host_ip': 8888}), []),    <--- value hardcoded
> >                              'tags': runnable.tags,
> >                              'run.results_dir': tempfile.mkdtemp(),
> >                              }]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Not sure if the error is the way that I'm instantiating the TreeNode class or is it a real bug in AvocadoParams class
> 
> I was thinking about this problem yesterday. I have not looked at the code to check how params reach the tests, but could it be related to #4655? Just brainstorming here.

It is related indeed, in the sense that we have to serialize the parameters, and then made them available similarly to how the config is made available.  Then, for instrumented tests, it needs to be injected back into the `Test` class, as @marioaag was experimenting.

**Comment by willianrampazzo** [comment]
I'm reopening this bug to handle the `-p` issue in the `exec-test` here.
