### ISSUE TITLE
Automate Python package creation and publishing

### ISSUE THREAD

**Issue by clebergnu** [avocado-framework/avocado#4692]
Based on issue #4336, we came to the conclusion that using an `egg` is the way to distribute Avocado (runners) to other environments, such as containers and VMs.

But, eggs are Python version specific, and thus, we'd need to create one egg for each Python version we support.  

The "Publish Python Package" Action on GitHub, seems to be a good start to achieve this, and at the same time, eliminate one more manual step of the release process by doing the wheels package creation and distribution too.

For the eggs, the idea is to have them available either/or at:
* GitHub itself
* https://avocado-project.org/data/

**Comment by willianrampazzo** [comment]
+1 for having the packages on GitHub.

**Comment by beraldoleal** [comment]
> Based on issue #4336, we came to the conclusion that using an `egg` is the way to distribute Avocado (runners) to other environments, such as containers and VMs.
> 
> But, eggs are Python specific, and thus, we'd need to create one egg for each Python version we support.
> 
> The "Publish Python Package" Action on GitHub, seems to be a good start to achieve this, and at the same time, eliminate one more manual step of the release process by doing the wheels package creation and distribution too.
> 
> For the eggs, the idea is to have them available either/or at:
> 
>     * GitHub itself
> 
>     * https://avocado-project.org/data/

What about Pypi ? Should we add to Pypi repos too? If so, I would suggest not using /data/ for this (unless a backup is necessary).

**Comment by clebergnu** [comment]
> > Based on issue #4336, we came to the conclusion that using an `egg` is the way to distribute Avocado (runners) to other environments, such as containers and VMs.
> > But, eggs are Python specific, and thus, we'd need to create one egg for each Python version we support.
> > The "Publish Python Package" Action on GitHub, seems to be a good start to achieve this, and at the same time, eliminate one more manual step of the release process by doing the wheels package creation and distribution too.
> > For the eggs, the idea is to have them available either/or at:
> > ```
> > * GitHub itself
> > 
> > * https://avocado-project.org/data/
> > ```
> 
> What about Pypi ? Should we add to Pypi repos too? If so, I would suggest not using /data/ for this (unless a backup is necessary).

Maybe I wasn't clear enough.  I said that for the **eggs** we need to host them (and gave suggestions).  I "went without saying" about wheels (and tarballs) because IMO they will continue to go to the same place (PyPI).

**Comment by beraldoleal** [comment]
Sure, makes no sense to eggs there. Thanks for the clarification @clebergnu .

**Comment by clebergnu** [comment]
> Hi @clebergnu
> do you mind linking the github action you mentioned in the issue? I think there was a misunderstanding with the action name. At this moment GitHub doesn't provide any way of distributing packages, you can create them with github actions as we do, but not distribute it from Github. Then don't provide yet anything for Python, see:
> https://docs.github.com/en/packages/working-with-a-github-packages-registry
> 

I think I meant [this](https://github.com/actions/starter-workflows/blob/ea5c3f66f69dab31848139edf9b28bf67e88200a/ci/python-package.yml), becaus its description is "Create and test a Python package on multiple Python versions.".

But I guess I misunderstood it, as I don't see any steps to create (and keep) actual Python packages (not wheels, not eggs, etc).

> They have this planned in their roadmap, but without any implementation date: [github/roadmap#94](https://github.com/github/roadmap/issues/94)
> 

I see.

> The only solution I have found is allowing the github actions to commit the eggs in another repository...

OK, let's work with that's possible.  Are you aware of either GitHub Actions blockers or helpers to push those files elsewhere?

**Comment by ana** [comment]
> OK, let's work with that's possible. Are you aware of either GitHub Actions blockers or helpers to push those files elsewhere?

@clebergnu 
My idea was committing the eggs directly from the github action in a directory under the website repo https://github.com/avocado-framework/avocado-framework.github.io so they can be fetched directly from avocado's website.

**Comment by clebergnu** [comment]
> > OK, let's work with that's possible. Are you aware of either GitHub Actions blockers or helpers to push those files elsewhere?
> 
> @clebergnu
> My idea was committing the eggs directly from the github action in a directory under the website repo https://github.com/avocado-framework/avocado-framework.github.io so they can be fetched directly from avocado's website.

That's an **interesting** idea... But I wonder if this doesn't violate GH pages terms or even if there aren't storage size limits... hopefully it's just my paranoia :).

**Comment by ana** [comment]
> > > OK, let's work with that's possible. Are you aware of either GitHub Actions blockers or helpers to push those files elsewhere?
> > 
> > 
> > @clebergnu
> > My idea was committing the eggs directly from the github action in a directory under the website repo https://github.com/avocado-framework/avocado-framework.github.io so they can be fetched directly from avocado's website.
> 
> That's an **interesting** idea... But I wonder if this doesn't violate GH pages terms or even if there aren't storage size limits... hopefully it's just my paranoia :).

There is indeed a storage limit and bandwidth quota that will be hard to reach with python eggs. My reading of the the GH page terms doesn't forbid doing this. Are you saying this because a past experience?

**Comment by beraldoleal** [comment]
> GitHub Pages sites have a soft bandwidth limit of 100GB per month.

This is something that caught my attention. If we are planning to download .eggs for every remote test, this might be a problem to consider.

**Comment by clebergnu** [comment]
I came across this:

https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/about-releases#storage-and-bandwidth-quotas

I believe it should be our primary attempt.

**Comment by clebergnu** [comment]
> > > > OK, let's work with that's possible. Are you aware of either GitHub Actions blockers or helpers to push those files elsewhere?
> > > 
> > > 
> > > @clebergnu
> > > My idea was committing the eggs directly from the github action in a directory under the website repo https://github.com/avocado-framework/avocado-framework.github.io so they can be fetched directly from avocado's website.
> > 
> > 
> > That's an **interesting** idea... But I wonder if this doesn't violate GH pages terms or even if there aren't storage size limits... hopefully it's just my paranoia :).
> 
> There is indeed a storage limit and bandwidth quota that will be hard to reach with python eggs. My reading of the the GH page terms doesn't forbid doing this. Are you saying this because a past experience?

No, I've had no experiences with GH page terms or limits.  It was just intuition and/or paranoia :)

**Comment by clebergnu** [comment]
Another helpful resource seems to be this action: https://github.com/softprops/action-gh-release

**Comment by ana** [comment]
Looks like there was another misunderstanding more in this issue. I thought we wanted to publish the eggs for the releases *and* the eggs from the  tests - for example, for testing.
If we only want the first ones, I was planning to add as part of https://github.com/avocado-framework/avocado/issues/3456  and indeed, the idea is publishing them with the release tag in github.
For the eggs during development, I just have added them as artifact at https://github.com/avocado-framework/avocado/pull/4931 and that should do it.

**Comment by clebergnu** [comment]
> Looks like there was another misunderstanding more in this issue. I thought we wanted to publish the eggs for the releases _and_ the eggs from the tests - for example, for testing.

The first point (the eggs for the releases) is the most important one, but many orders of magnitude IMO.  One of the reasons is the need to build eggs for different Python versions.

For the second point, do you mean by "eggs from the tests", eggs generated from PRs or master?  If so, they *may* be useful indeed *when* we add tests that consume them.  For instance, we may have a "pipeline" that builds the eggs, and then runs tests out of the podman spawner, but using those eggs and not the latest released ones.

> If we only want the first ones, I was planning to add as part of #3456 and indeed, the idea is publishing them with the release tag in github.

I don't think we *only* want that, but I'd focus on that...

> For the eggs during development, I just have added them as artifact at #4931 and that should do it.

... because as you've said it yourself here, CI artifacts should be enough for the eggs built and used during CI runs.
