### ISSUE TITLE
Make the default Avocado environment variables available with the next runner

### ISSUE THREAD

**Issue by willianrampazzo** [avocado-framework/avocado#4742]
The current `runner` has support for some environment variables related to Avocado. The `nrunner` is missing support for those environment variables.

This is the `examples/tests/env_variables.sh` code:

```bash
#!/bin/sh
# This test demonstrates that shell scripts have access to avocado runtime
# information, exported through environment variables.
echo "Avocado Version: $AVOCADO_VERSION"
echo "Avocado Test basedir: $AVOCADO_TEST_BASEDIR"
echo "Avocado Test workdir: $AVOCADO_TEST_WORKDIR"
echo "Avocado Test logdir: $AVOCADO_TEST_LOGDIR"
echo "Avocado Test logfile: $AVOCADO_TEST_LOGFILE"
echo "Avocado Test outputdir: $AVOCADO_TEST_OUTPUTDIR"
echo "Custom variable: $CUSTOM_VARIABLE"

test -d "$AVOCADO_TEST_BASEDIR" -a \
     -d "$AVOCADO_TEST_WORKDIR" -a \
     -d "$AVOCADO_TEST_LOGDIR" -a \
     -f "$AVOCADO_TEST_LOGFILE" -a \
     -d "$AVOCADO_TEST_OUTPUTDIR"
```

```
$ avocado run --test-runner=nrunner examples/tests/env_variables.sh
JOB ID     : d6d0d479c1f1ece22754350d3f1938ed13a1c729
JOB LOG    : /home/wrampazz/avocado/job-results/job-2021-06-28T11.11-d6d0d47/job.log
 (1/1) examples/tests/env_variables.sh: STARTED
 (1/1) examples/tests/env_variables.sh: FAIL (0.01 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/wrampazz/avocado/job-results/job-2021-06-28T11.11-d6d0d47/results.html
JOB TIME   : 1.33 s
```

To work on a solution similar to #4734, it would be good to decide:
 - if Avocado will continue to support the current environment variables already supported ($AVOCADO_VERSION,  $AVOCADO_TEST_BASEDIR, $AVOCADO_TEST_WORKDIR, $AVOCADO_TEST_LOGDIR, $AVOCADO_TEST_LOGFILE, $AVOCADO_TEST_OUTPUTDIR, and $CUSTOM_VARIABLE).

 - If `nrunner` should support only the $CUSTOM_VARIABLE or leave it more flexible for the tester to choose which variable name to use and how many custom variables to use.

**Comment by willianrampazzo** [comment]
> To work on a solution similar to #4734, it would be good to decide:
> 

After some discussion at our scrum meeting,

> * if Avocado will continue to support the current environment variables already supported ($AVOCADO_VERSION,  $AVOCADO_TEST_BASEDIR, $AVOCADO_TEST_WORKDIR, $AVOCADO_TEST_LOGDIR, $AVOCADO_TEST_LOGFILE, $AVOCADO_TEST_OUTPUTDIR, and $CUSTOM_VARIABLE).

it was agreed that the implementation should keep compatibility with the current `runner`.

> * If `nrunner` should support only the $CUSTOM_VARIABLE or leave it more flexible for the tester to choose which variable name to use and how many custom variables to use.

The implementation on `nrunner` side should support any custom variable. I misinterpreted when I thought the `$CUSTOM_VARIABLE` was hard coded on the current `runner`.

**Comment by willianrampazzo** [comment]
I noticed there are two different issues here:
 - Avocado environment variables not available on `nrunner`.
 - The `-p` parameter not available to the `exec-test` runner.

I reopened #4569 to handle the second issue there. This issue will be about supporting the Avocado environment variables on `nrunner`. I already renamed this issue.

**Comment by willianrampazzo** [comment]
The Avocado environment variables are available to Instrumented Tests. They are set here: 

https://github.com/avocado-framework/avocado/blob/8c87bfe5e8a1895d77226064433453f158a3ce56/avocado/core/test.py#L874-L883

The same environment variables need to be set to non-instrumented tests.

**Comment by willianrampazzo** [comment]
Open discussion about this issue: https://github.com/avocado-framework/avocado/discussions/4751

**Comment by beraldoleal** [comment]
Part of #4802
