### ISSUE TITLE
Support running coroutines (AKA "async def" methods) as tests

### ISSUE THREAD

**Issue by clebergnu** [avocado-framework/avocado#4767]
Avocado currently supports regular methods as tests on `avocado-instrumented` tests.  Currently, testing coroutines involve creating regular test methods, and some boiler plate code, such [as](https://github.com/avocado-framework/avocado/blob/f0996dafefa412c77c221c2d1a6fafdcba1c97b7/selftests/unit/plugin/test_spawner.py#L17):

```python
class Process(unittest.TestCase):
    def setUp(self):
        runnable = nrunner.Runnable('noop', 'uri')
        task = nrunner.Task(runnable, '1')
        self.runtime_task = RuntimeTask(task)
        self.spawner = ProcessSpawner()

    def test_spawned(self):
        loop = asyncio.get_event_loop()
        spawned = loop.run_until_complete(self.spawner.spawn_task(self.runtime_task))
        self.assertTrue(spawned)
```

For code that is coroutine based in its majority, the loop creation/execution, along with the possible definition of a secondary coroutine that will contain the actual test code, is too much.  Avocado should be able help with that by:

1. Understanding coroutines as tests, meaning that:
1.1. The resolver should be able to find `async def test*` as "tests"
1.2. The resolver should mark that test as a special type of test. For coroutines it can "mark it" as "async"
2. Allow wrappers (callables) to be used for special types of tests
3. Have a default set of wrappers for "async" tests that will run the coroutine in a suitable environment (such as a new or default loop).

The overall experience should be that both test methods and coroutines should be executed out-of-the-box, while allowing configuration (at the test suite level) for different wrappers for different test types.

One example of possible resulting test code would look like:

```python
class Process(unittest.TestCase):
    def setUp(self):
        runnable = nrunner.Runnable('noop', 'uri')
        task = nrunner.Task(runnable, '1')
        self.runtime_task = RuntimeTask(task)
        self.spawner = ProcessSpawner()

    async def test_spawned(self):
        spawned = await self.spawner.spawn_task(self.runtime_task)
        self.assertTrue(spawned)
```

**Comment by beraldoleal** [comment]
A good think is that `ast` supports `AsyncFunctionDef`, so identify the tasks, should not be a problem here.

**Comment by jnsnow** [comment]
The only thing I'd add is that the custom wrappers should be easy to define; a common scenario might be wanting to inject async setup and teardown tasks to be executed before and after the coroutine. I think what you have laid implies that this would be possible, but "don't forget!"

Another consideration is that adding setup/teardown to coroutines might not necessarily mean we have a preference on how the coroutine gets run, but instead implies the creation of a wrapper coroutine which just gets fed to the default executor.

**Comment by jnsnow** [comment]
Oh, and a note: it may not be appropriate for any test case to have a coroutine executor run more than exactly once by default; e.g. I would not recommend doing the following:

```python
asyncio.run(TestClass._asyncSetUp())
asyncio.run(TestClass.test_case())
asyncio.run(TestClass._asyncTearDown())
```

This would create a new loop for each phase, which is ... *very probably* not what the user wants, but I can't discount the possibility that some tests may intentionally want to create multiple loops to test things breaking on purpose, but those sound like a case where you'd want to manage everything yourself and not rely on automatic machinery to do it for you.

**Comment by clebergnu** [comment]
#4924 tracks the extra features that **may** be needed wrt "coroutines as tests" support.
