### ISSUE TITLE
nrunner failfast differences

### ISSUE THREAD

**Issue by clebergnu** [avocado-framework/avocado#4814]
I've noticed two differences between the failfast behavior on the runner and nrunner implementations:

1. A message to the user about what happened `Interrupting job (failfast).`
2. The setting of the `AVOCADO_JOB_INTERRUPTED` exit code

Unless there's a very good reason for changing the behavior, we should implement the same on nrunner to allow for a smoother transition.

**Comment by beraldoleal** [comment]
@clebergnu thanks I will double check that.
