### ISSUE TITLE
website: remove duplicated sites

### ISSUE THREAD

**Issue by beraldoleal** [avocado-framework/avocado#4833]
I'm opening this issue here, to get more visibility.

Today we have two websites domains: avocado-project.org and avocado-framework.github.io (automatically provided by github).

Unless I'm missing something, we could remove the selfhosted page, but keeping the domain pointing to github pages, so we don't need cron jobs on personal servers.

Or is there anything that forces us using the custom private server?

https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site

**Comment by willianrampazzo** [comment]
+1 for one single place to store the files.

**Comment by clebergnu** [comment]
> I'm opening this issue here, to get more visibility.
> 
> Today we have two websites domains: avocado-project.org and avocado-framework.github.io (automatically provided by github).
> 
> Unless I'm missing something, we could remove the selfhosted page, but keeping the domain pointing to github pages, so we don't need cron jobs on personal servers.
> 
> Or is there anything that forces us using the custom private server?
> 
> https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site

We host data too in avocado-project.org, see [https://avocado-project.org/data/assets/](https://avocado-project.org/data/assets/).  The options I see are:

1. Add a redirect in the document root (only) of avocado-project.org, sending the user to avocado-framework.github.io
2. Creating a subdomain, such as data.avocado-project.org and having that alone on the current server.

**Comment by beraldoleal** [comment]
I vote for option 2. where we have hosted outside only the data.

**Comment by ana** [comment]
+1 with only having one site:  _remove the selfhosted page, but keeping the domain pointing to github pages_

About the data... how much space it takes? I'd like to have it in github as well. This way everybody can take care of changes/updates and  we can keep track of when and why things were changed in the git log.

**Comment by beraldoleal** [comment]
We have files with 200MB and 500MB, I guess this will hit the GH limits per file. Unless we use git lfs.

**Comment by clebergnu** [comment]
> We have files with 200MB and 500MB, I guess this will hit the GH limits per file. Unless we use git lfs.

`git lfs` won't work for GitHub pages sites according to [this](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-git-large-file-storage#pointer-file-format).

**Comment by clebergnu** [comment]
> +1 with only having one site: _remove the selfhosted page, but keeping the domain pointing to github pages_
> 
> About the data... how much space it takes? I'd like to have it in github as well. This way everybody can take care of changes/updates and we can keep track of when and why things were changed in the git log.

Like @beraldoleal explained, there are files of about 200MB and one slightly over 500MB, while GitHub limits are [much smaller](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github#file-size-limits).

LFS is also [not an option](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-git-large-file-storage#pointer-file-format) for GitHub pages.

**Comment by clebergnu** [comment]
The solution implemented is one where:

* `http(s)://avocado-project.org/data/` is served from the current server. 

* `http(s)://avocado-project.org/$(ANYTHING_BUT_DATA)` redirects to `https://avocado-framework.github.io/$(ANYTHING_BUT_DATA)`, where `$(ANYTHING_BUT_DATA)` is any URI that does not match `/data`.

I've tested the `avocado vt-bootstrap` process and it works as expected.

If anyone encounters any problems, please reopen this issue.
