### ISSUE TITLE
avocado run with vm plugin hangs bc of pager

### ISSUE THREAD

**Issue by mvollmer** [avocado-framework/avocado#486]
Our test suite stopped and hang forever, waiting for the user to quit `less` in a virtual machine.

On the host:
```
 └─avocado /usr/bin/avocado run --vm-domain checkmachine7-fedora-21-x86_64 --vm-username root --vm-password testvm --vm-hostname 192.168.123.5 ...
```

On the VM:
```
─sshd -D
  │   └─sshd    
  │       └─bash -l -c cd ~/avocado/tests; avocado list ...
  │           └─avocado /usr/bin/avocado list ...
  │               └─less -FRSX
```

**Comment by lmr** [comment]
That's some unexpected less behavior happening here.

**Comment by lmr** [comment]
@mvollmer What is the OS that your guest runs? What is the version of the less package? We never had such a problem with the versions of less in our regular development machines and VMs (they all use recent versions of Fedora). Anyway, I can patch the `list` command to not use a paginator and work around this problem.

Another possibility that just occurred to me is some sort of special terminal setting in the guest making less to paginate the list leading to this problem. A more proper solution would be to introduce a flag that disables the paginator in `avocado list`, I think I'm leaning towards it.

**Comment by mvollmer** [comment]
> That's some unexpected less behavior happening here.

Is it?  less can block on user input even with the -F option.  Maybe a new version of Avocado or the VM plugin now leaves stdin accidentally open when running "avocado list" via ssh?

**Comment by mvollmer** [comment]
> @mvollmer What is the OS that your guest runs?

It happened on a Fedora 21 guest, with

```
# rpmquery less
less-458-13.fc21.x86_64
less-471-1.fc21.x86_64
# rpmquery avocado
avocado-0.21.0-3.fc21.noarch
```

The two versions of less look very suspicious.  I'll try to find more clues...

**Comment by mvollmer** [comment]
Thanks for the fix!

**Comment by mvollmer** [comment]
> Another possibility that just occurred to me is some sort of special terminal setting in the guest making less to paginate the list leading to this problem.

I just tried and less prompts when the terminal configuration is broken, even when stdin is /dev/null:

```
$ less -F /etc/os-release
$ TERM=blah less -F /etc/os-release </dev/null
WARNING: terminal is not fully functional
/etc/os-release  (press RETURN)
```

So, yeah, I guess the only way to make sure that less doesn't block is to not use it, as you did in the fix.
