### ISSUE TITLE
TAP parser: warnings are being marked as error

### ISSUE THREAD

**Issue by beraldoleal** [avocado-framework/avocado#4865]
.avocado.hint:

```
  1 [kinds]
  2 tap = ./scripts/*/*.t
  3 
  4 [tap]
  5 uri = $testpath
  6 kwargs = PERL5LIB=./lib,LIBVIRT_TCK_CONFIG=./conf/default.yml,LIBVIRT_TCK_AUTOCLEAN=1
```

test.t:
```bash
#!/bin/bash
echo "1..4
warning: foo
ok 1 - started persistent domain object
ok 2 - dynamic domain label type is svirt_tcg_t
ok 3 - dynamic image label type is svirt_image_t
ok 4 - Domain MCS c40,c302 == Image MCS c40,c302"
```

**Comment by clebergnu** [comment]
I'm not sure I understand the problem... where is `warning` supported in TAP?  I looked [here](https://testanything.org/tap-specification.html) and saw nothing about it.

**Comment by beraldoleal** [comment]
@clebergnu, sorry if I wasn't clear. In fact revisiting the problem, seems to me that is a test issue, since they are writing to the stdout instead of stderror. And from the specification:

> A harness must only read TAP output from standard output and not from standard error. 

So probably we don't have a bug at the end.

**Comment by beraldoleal** [comment]
@clebergnu from the specs:

> A harness must only read TAP output from standard output and not from standard error. Lines written to standard output matching /^(not )?ok\b/ must be interpreted as test lines. **All other lines must not be considered test output.**

**Comment by clebergnu** [comment]
> @clebergnu from the specs:
> 
> > A harness must only read TAP output from standard output and not from standard error. Lines written to standard output matching /^(not )?ok\b/ must be interpreted as test lines. **All other lines must not be considered test output.**

Two questions:

1. Is avocado reading *TAP* content from stderr?
2. What is your interpretation of **All other lines must not be considered test output.** ?  I don't think it means that a TAP parser should silently disregard "all other lines".  I think it only means that only lines matching that pattern are about **tests**, but TAP output goes beyond test results.

**Comment by beraldoleal** [comment]
> > @clebergnu from the specs:
> > > A harness must only read TAP output from standard output and not from standard error. Lines written to standard output matching /^(not )?ok\b/ must be interpreted as test lines. **All other lines must not be considered test output.**
> 
> Two questions:
> 
>     1. Is avocado reading _TAP_ content from stderr?

No, is not. So we are safe here.

 >     2. What is your interpretation of **All other lines must not be considered test output.** ?  I don't think it means that a TAP parser should silently disregard "all other lines".  I think it only means that only lines matching that pattern are about **tests**, but TAP output goes beyond test results.

I understand and we are paying attention to bailouts, test plans, comments and others directives defined on the specs. But this sentence IMO is giving me the impression that everything else should be ignored.

I don't think that a  unknown line to stdout should mark the test as error.

**Comment by beraldoleal** [comment]
Side note: `[prove](https://perldoc.perl.org/prove)` (from Perl's `Test::Harness`) is ignoring those lines.

**Comment by clebergnu** [comment]
> Side note: [prove](https://perldoc.perl.org/prove) (from Perl's `Test::Harness`) is ignoring those lines.

I find this relaxed approach of `Test::Harness` a good enough indication that your interpretation of the standard text is correct.  And we should follow the standard the best way we can.

**Comment by beraldoleal** [comment]
Thanks @clebergnu , pr is on the way.
