### ISSUE TITLE
python setup.py test --disable-plugin-checks=html  --disable-plugin-checks ... doesn't work

### ISSUE THREAD

**Issue by ana** [avocado-framework/avocado#4904]
`python setup.py test --disable-plugin-checks=html  --disable-plugin-checks ... ` doesn't work.
I made an initial fix was c14edca0bf19b009b395bfe1973e2f15f89f3097 but it was broken. This requires more time and also `setup.yml` should be improved to check further the options of `python setup.py test` every time `setup.py` is changed.

**Comment by ana** [comment]
@beraldoleal @clebergnu @richtja @willianrampazzo 
Folks, I'm thinking what's the best way to solve this problem, there are several options:

- Fix the original bug and implement `--disable-plugins-checks=html,foo,bar`

- Remove these options entirely and if the plugin isn't at `optional_plugins/plugin_name`, automatically skip any test for this plugin. Reminder: not all test of every plugin are at `optional_plugins/plugin_name/tests/` so this will require some work.
 
- Move the tests of every plugin to their folder `optional_plugins/plugin_name/tests/*` and after running the tests of avocado itself, run the plugins for every test with a new `avocado run`. So it's a plugin failing, it'll be more clear than now.

- other? Thoughts? :)

**Comment by beraldoleal** [comment]
>     * Fix the original bug and implement `--disable-plugins-checks=html,foo,bar`

+ 1 for that.

> Remove these options entirely and if the plugin isn't at optional_plugins/plugin_name, automatically skip any test for this plugin. Reminder: not all test of every plugin are at optional_plugins/plugin_name/tests/ so this will require some work.

We might have some cases where the plugins are there and we would like to disable the checks.

**Comment by richtja** [comment]
I agree with @beraldoleal, we should move tests to their plugins folders and make mechanism for disabling them. So +1 for combinations of the first and third solutions.

**Comment by willianrampazzo** [comment]
+1 for first and thrid options too.

**Comment by ana** [comment]
I have created an issue to move the tests of each "optional_plugins" to their own folder plugin_name/tests/*   https://github.com/avocado-framework/avocado/issues/4940

**Comment by clebergnu** [comment]
> @beraldoleal @clebergnu @richtja @willianrampazzo
> Folks, I'm thinking what's the best way to solve this problem, there are several options:
> 
> * Fix the original bug and implement `--disable-plugins-checks=html,foo,bar`

Of course! :)

> * Remove these options entirely and if the plugin isn't at `optional_plugins/plugin_name`, automatically skip any test for this plugin. Reminder: not all test of every plugin are at `optional_plugins/plugin_name/tests/` so this will require some work.

I'm not so sure about this... We have been using the presence of the Python module like [here](https://github.com/avocado-framework/avocado/blob/5bdf75e10bff70d1a1a94cfb6f5301713a80c719/selftests/functional/test_basic.py#L843) and [here](https://github.com/avocado-framework/avocado/blob/5bdf75e10bff70d1a1a94cfb6f5301713a80c719/selftests/functional/test_basic.py#L1263), which is a much more robust approach.

> * Move the tests of every plugin to their folder `optional_plugins/plugin_name/tests/*` and after running the tests of avocado itself, run the plugins for every test with a new `avocado run`. So it's a plugin failing, it'll be more clear than now.

I don't think this is much of an issue... I only found 2 tests in `selftests/functional` (linked above) that reference optional plugins (`html`), and make *optional* use of them.  Of course, we can look into moving them to the html plugins directory though.

> * other? Thoughts? :)

To have a real idea of the impact of the optional plugins on tests, I removed the folder and then ran the tests, [resulting](https://cirrus-ci.com/task/5034791599865856?logs=selftests#L2045) in:

```
RESULTS    : PASS 934 | ERROR 4 | FAIL 2 | SKIP 58 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 487.04 s
Failed tests:
job-api-5-11-/tmp/cirrus-ci-build/selftests/check.py:JobAPIFeaturesTest.test_check_file_exists;job.run.result.html.enabled-True-results.html-True FAIL
job-api-6-4-/tmp/cirrus-ci-build/selftests/check.py:JobAPIFeaturesTest.test_check_output_file;job.run.result.html.output-custom.html-True FAIL
```

^ `check.py` relies on them hardcoded at the moment, but shouldn't.

```
nrunner-interface-8-selftests/functional/test_nrunner_interface.py:Interface.test_help;avocado-runner-golang ERROR
nrunner-interface-9-selftests/functional/test_nrunner_interface.py:Interface.test_help;avocado-runner-robot ERROR
nrunner-interface-17-selftests/functional/test_nrunner_interface.py:Interface.test_capabilities;avocado-runner-golang ERROR
nrunner-interface-18-selftests/functional/test_nrunner_interface.py:Interface.test_capabilities;avocado-runner-robot ERROR
```

^ `check.py` skips those if `--disable-plugin-check` is given, so these failures are expected.  One possibility of improvement here is to default to the runners queried via `pkg_resources`, similarly to the `python_module_available()` approach discussed earlier.

Final comment is `--disable-plugin-check` is needed, for instance, during RPM builds when there are not Fedora packages for `robot-framework`.  I don't see a way to do without it.

**Comment by beraldoleal** [comment]
> > * Move the tests of every plugin to their folder `optional_plugins/plugin_name/tests/*` and after running the tests of avocado itself, run the plugins for every test with a new `avocado run`. So it's a plugin failing, it'll be more clear than now.
> 
> I don't think this is much of an issue... I only found 2 tests in `selftests/functional` (linked above) that reference optional plugins (`html`), and make _optional_ use of them. Of course, we can look into moving them to the html plugins directory though.

If they are *functional* I don't see the need to change. I'm ok with keeping as it is. I was thinking/assuming that the move was more about *unit tests*. 

> > * other? Thoughts? :)
> 
> To have a real idea of the impact of the optional plugins on tests, I removed the folder and then ran the tests, [resulting](https://cirrus-ci.com/task/5034791599865856?logs=selftests#L2045) in:
> 
> ```
> RESULTS    : PASS 934 | ERROR 4 | FAIL 2 | SKIP 58 | WARN 0 | INTERRUPT 0 | CANCEL 0
> JOB TIME   : 487.04 s
> Failed tests:
> job-api-5-11-/tmp/cirrus-ci-build/selftests/check.py:JobAPIFeaturesTest.test_check_file_exists;job.run.result.html.enabled-True-results.html-True FAIL
> job-api-6-4-/tmp/cirrus-ci-build/selftests/check.py:JobAPIFeaturesTest.test_check_output_file;job.run.result.html.output-custom.html-True FAIL
> ```
> 
> ^ `check.py` relies on them hardcoded at the moment, but shouldn't.

+1
