### ISSUE TITLE
using nrunner for remote execution 

### ISSUE THREAD

**Issue by pkamam** [avocado-framework/avocado#4915]
I want to execute avocado tests remotely from jenkins server and see that the support for --remote host is removed. i.e
https://avocado-framework.readthedocs.io/en/52.1/RunningTestsRemotely.html

I saw "nrunner" concept added and it says its useful for remote execution of tests? I don't see any document on how to pass the parameters for remote execution

I created a VM and tried this,

[root@localhost functional]# avocado run --test-runner='nrunner' --nrunner-status-server-uri 192.168.x.x test_nrunner_interface.py
JOB ID     : 9cce864b30be7c5e343643a89b242dd60cc9abea
JOB LOG    : /root/avocado/job-results/job-2021-08-30T12.59-9cce864/job.log
RESULTS    : PASS 0 | ERROR 0 | FAIL 0 | SKIP 2 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 1.03 s
[root@localhost functional]#

Its not executing any tests.

Are we supposed to install avocado on the remote host and also scp the script and then execute via ssh? If so, what is the purpose of nrunner for remote execution?

**Comment by beraldoleal** [comment]
Hi @pkman, Yes, during release 81.0, the remote, vm and docker runners (which would run jobs on remote, vm and docker containers) were removed, after having being deprecated on version 78.0.

If you would like to run avocado on a remote machine, just do ssh to the machine and execute as a local execution.
 
About your error, since you are specifying a status-server, I'm assuming that you have a status server running on that IP, is that right? What is the port number? Can you specify the port as well?

**Comment by pkamam** [comment]
No. I do not have status server running on that IP. How do we create that? 
I think, I misunderstood concept of nrunner ? 
https://avocado-framework.readthedocs.io/en/latest/guides/contributor/chapters/runners.html

This has a paragraph that reads:
And these are some features which it’s believed to be more easily implemented under a different architecture and implementation:

Remote test execution

**Comment by beraldoleal** [comment]
What happen if you run just like this (using our latest release):

```bash
$ avocado run test_nrunner_interface.py
```
?

**Comment by pkamam** [comment]
That runs fine on local host. The query is for remote execution

**Comment by beraldoleal** [comment]
Hi @pkamam, based on the commit message that removed that features:

>     The remote, vm and docker runner plugins (the ones that allows users
>     to run a job on those environments), all depend on the Fabric3, which
>     in turn depends on many other Python modules.  Fabric3 is dead with
>     the Python 3 compatible releases of fabric, but it requires an API
>     overhaul, very close to rewriting those plugins.
>     
>     Maintaining those plugins is proving increasingly hard due to version
>     mismatch failures and bitrot, and the migration effort, given the
>     current plans of the Avocado project, is not really worth it.  With
>     the N(ext)Runner architecture, the goal is for *individual* tests to
>     be able to be executed in remote environments, so some of the
>     functionality may be brought back in the future, but under a very
>     different implementation, which may include even different
>     dependencies.

Because of that right now you can execute those tests remotely like that:

```bash
$ ssh -t remote_node '/path/to/your/avocado/installation/avocado run /bin/true'
```

Right now we do have only a podman spawner implementation (locally, but in an isolated podman container):

```bash
$ avocado run --nrunner-spawner='podman' run /bin/true
```

**Comment by pkamam** [comment]
$ ssh -t remote_node '/path/to/your/avocado/installation/avocado run /bin/true'
This works fine. But, first need to setup passwordless ssh to the remote host,  then copy the scripts, install avocado and setup avocado on remote server and then execute the above will work fine.

**Comment by beraldoleal** [comment]
Yes, indeed. I will open an issue so we can think/discuss about new nrunners spawners.

**Comment by pkamam** [comment]
Thanks @beraldoleal.

**Comment by clebergnu** [comment]
@pkamam Avocado 103.0 includes a [remote spawner](https://avocado-framework.readthedocs.io/en/103.0/plugins/optional/spawner_remote.html).  I'm closing this issue, but feel free to reopen in case it doesn't match your exact use case.
