### ISSUE TITLE
Merge ExecRunner and ExecTestRunner

### ISSUE THREAD

**Issue by beraldoleal** [avocado-framework/avocado#4922]
Take the following `.avocado.hint`:

```
[kinds]
exec = /tmp/external_runner.sh

[exec]
uri = $testpath
args = generate
```

And execute with this

```bash
$ avocado run /tmp/external_runner.sh
JOB ID     : 8c32c65cd764a10f53f6a7d8f7c6c9cdd735a7b2
JOB LOG    : /home/local/avocado/job-results/job-2021-08-31T14.51-8c32c65/job.log
 (1/1) /tmp/externaLrunner.sh: STARTED

Avocado crashed: AttributeError: 'NoneType' object has no attribute 'upper'
Traceback (most recent call last):

  File "/home/local/src/beraldo/avocado/avocado/core/job.py", line 636, in run_tests
    summary |= suite.run(self)

  File "/home/local/src/beraldo/avocado/avocado/core/suite.py", line 338, in run
    return self.runner.run_suite(job, self)

  File "/home/local/src/beraldo/avocado/avocado/plugins/runner_nrunner.py", line 375, in run_suite
    self.status_repo.get_result_set_for_tasks(test_ids)])

  File "/home/local/src/beraldo/avocado/avocado/plugins/runner_nrunner.py", line 374, in <listcomp>
    summary.update([status.upper() for status in

AttributeError: 'NoneType' object has no attribute 'upper'

Please include the traceback info and command line used on your bug report
Report bugs visiting https://github.com/avocado-framework/avocado/issues/new
```

**Comment by beraldoleal** [comment]
@clebergnu I was debugging this before my PTO, and I forgot to ask you. But IIUC, "ExecRunner" (exec) is just a base class and should be executed directly, for that we have the "ExecTestRunner" (exec-test). Is my understand right?

**Comment by clebergnu** [comment]
> @clebergnu I was debugging this before my PTO, and I forgot to ask you. But IIUC, "ExecRunner" (exec) is just a base class and shouldn't be executed directly, for that we have the "ExecTestRunner" (exec-test). Is my understand right?

So, `exec` (and `ExecRunner`) was kept because I believed that it'd be useful for Jobs to execute commands (using spawners) while not necessarily considering them tests.... so it never returns a `pass` or `fail` (or other test status result).

But, I don't think that belief was justified, and the `exec`/`ExecRunner` are unjustifiable at this point.  I'd be more than happy to see them gone.
