### ISSUE TITLE
Redundant [debug] tag in test's debug logs

### ISSUE THREAD

**Issue by pevogam** [avocado-framework/avocado#4925]
Hi all,

After trying out 91.0 I saw this change in the debug logs of each test:

```
[debug] 2021-09-01 16:45:21,218 utils            L0167 DEBUG|     catch_monitor = catch_monitor
[debug] 2021-09-01 16:45:21,218 utils            L0167 DEBUG|     cdrom_cd_rip = /mnt/local/isos/avocado_rip.iso
[debug] 2021-09-01 16:45:21,218 utils            L0167 DEBUG|     cdroms = 
[debug] 2021-09-01 16:45:21,218 utils            L0167 DEBUG|     check_image = yes
[debug] 2021-09-01 16:45:21,218 utils            L0167 DEBUG|     connect_uri = default
[debug] 2021-09-01 16:45:21,218 utils            L0167 DEBUG|     convert_ppm_files_to_png_on_error = yes
[debug] 2021-09-01 16:45:21,218 utils            L0167 DEBUG|     cpu_chk_cmd = grep -c processor /proc/cpuinfo
[debug] 2021-09-01 16:45:21,219 utils            L0167 DEBUG|     cpu_model = SandyBridge
[debug] 2021-09-01 16:45:21,219 utils            L0167 DEBUG|     cpu_model_flags = 
[debug] 2021-09-01 16:45:21,219 utils            L0167 DEBUG|     create_image = no
[debug] 2021-09-01 16:45:21,219 utils            L0167 DEBUG|     cyrus_user_path = /datastore/imap-mails/user/
```

This doesn't quite make sense since we already see the logging level as DEBUG (and others) and it only pushes the text to the right making all lines even longer and requiring even more scrolling, yet doesn't provide any meaningful information in addition to the previous logging.

Have you observed this too? Is it expected?

Best,
Plamen

**Comment by willianrampazzo** [comment]
This was introduced when we decided to keep everything (stderr, stdout) on `debug.log` file when using nrunner (https://github.com/avocado-framework/avocado/discussions/4816).  The changes were implemented here to reflect the overall discussion: https://github.com/avocado-framework/avocado/commit/eef0f8b404820ceac75f654ef3693b99c43e74aa

**Comment by pevogam** [comment]
Hi @willianrampazzo I guess you probably meant your links in reverse since the second one is a commit and the first one is a discussion. I also participated in the discussion there but I wasn't aware of the implementation. Thanks for the pointers though.

@richtja Regarding your commit eef0f8b, I understand now that you prepend `[stdout]` and `[stderr]` in the two other cases. However, could third and most common case at least use a better name like `[log]` or even `[stdlog]`? TBH "debug" doesn't tell me much and I easily confused it with the debug level of the log files and it seems what you are trying to differentiate there is the channel and not the logging level.

**Comment by richtja** [comment]
Hi @pevogam, thanks for bringing this topic, I think you are right, the `[debug]` might be confusing for users. I will change that to `[stdlog]`

**Comment by pevogam** [comment]
Thanks for the quick responses and fixes guys!
