### ISSUE TITLE
Improve the spawner's API, so we can categorize "Deployment Spawners" vs "Non-Deployment"

### ISSUE THREAD

**Issue by beraldoleal** [avocado-framework/avocado#4932]
Improve the spawner's API, so we can categorize "Deployment Spawners" vs "Non-Deployment"

Current Spawners API does not support the separation between the ones that need deployment and the ones that don't.

- Non-Deployment Spawners: Spawners that don't need to deploy the bootstrap artifacts (Avocado runners, tests, and test's data). i.e ProcessSpawner.
- Deployment Spawners: The ones that would be handy if does that. i.e: PodmanSpawner and any other remote spawner like a future SSHSpawner.

This could be done via entirely different class definitions, a simple attribute/flag on our base Spawner class or any other method accepted and discussed here.
 
Today, our deployment strategy is simple as copying the nrunner.py file to the container. We need to improve that, so "Deployment Spawners" would be able to trigger the deployment code and:

#### For the Avocado component:

- Deployment code would fetch matching eggs (avocado.utils.fetch_asset("http://location/avocado-$version.egg"): Here cache should be considered to avoid downloading already cached eggs. This is Blocked by:
  -  #4336
  - #4692
- Deployment code would copy the egg to the destination environment. Something like `self.deploy_egg()`

#### Other deployment artifacts:

- We need to do the same with the test references (i.e: `mytest.py` and data files (i.e `mytest.py.data`)

**Comment by clebergnu** [comment]
Closing with resolution by #5053
