### ISSUE TITLE
Update PodmanSpawner to the new deployment model

### ISSUE THREAD

**Issue by beraldoleal** [avocado-framework/avocado#4933]
After #4932, we need to update the PodmanSpawner to get the benefits from this new API, being able to deploy Avocado from eggs instead of the current standalone model (nrunner.py)

**Comment by pevogam** [comment]
I guess I am not fully aware of the type of deployment you mean here and the particularities of its implementation but want to add my 2 cents here. For instance, looking at this from the perspective of the LXC spawner but also in general I am not sure if we should always go in direction of packaging. Some systems could be very different or even impossible to do package management on and simply deploying currently used (and potentially modified) code like a standalone `nrunner.py` generalizes best over various conditions within the container environment. But I might be misunderstanding what you mean here.

**Comment by beraldoleal** [comment]
Hi @pevogam,

We are assuming that the only requirement will be Python and we are planning to use eggs for that. Where we can even run it directly from them, without installing.

I tried to create an epic issue (#4934), with all the related issues that we are working on this problem. Let me know if that makes for you and let us know about your concerns.
