### ISSUE TITLE
LTS Release Notes

### ISSUE THREAD

**Issue by clebergnu** [avocado-framework/avocado#4968]
Create a public editable document with the release notes since 82.0 LTS up to 92.0 LTS.

Given we have 10 releases, let's split the work per lots of releases.  Example:

- [x] @clebergnu 83.0, 92.0
- [x] @ana 84.0, 85.0
- [x] @beraldoleal 86.0, 87.0
- [x] @willianrampazzo 88.0, 89.0
- [x] @richtja 90.0, 91.0

**Comment by beraldoleal** [comment]
86 and 87 are done.

**Comment by richtja** [comment]
90 and 91 are done.

**Comment by clebergnu** [comment]
A few ideas that I came across while doing my part:

* I believe the "Internal changes" section can be omitted from the LTS release notes, and only present in the regular release notes.
* For the "utility libraries" section, we should further categorize the changes taking the module in consideration.  For instance, instead of 3 lines with changes related to "avocado.utils.foo", there would be one bullet point about it, and three items *under* it with the actual changes (new utility methods, etc).
* For the completely **new** utility libraries, when comparing to 82.0, a single bullet point is enough (there's no need to add, say, one bullet item for every new individual APIs added to a module in this case).

How does that sound @ana @beraldoleal @richtja @willianrampazzo ?

**Comment by clebergnu** [comment]
FIY, 83.0 notes are done, but 92.0 will of course be delayed until we finalize the sprint itself.

**Comment by ana** [comment]
> How does that sound @ana @beraldoleal @richtja @willianrampazzo ?

All sounds good to me.

**Comment by willianrampazzo** [comment]
88.0 and 89.0 done
