### ISSUE TITLE
Allow users to set a custom identifier format per runner

### ISSUE THREAD

**Issue by beraldoleal** [avocado-framework/avocado#4980]
**Is your feature request related to a problem? Please describe.**

With the new runner architecture, currently we don't have an "easy" way to change the test identifier without using some "advanced" features like "yaml2mux", for instance.

Users that have a wrapper as an entry point for the tests will always have the same wrapper as test id. For instance, imagine a Makefile with some targets ('foo', 'bar') and each target is one test. Having a single test suite with those tests will make avocado print something like this:

```
JOB ID     : b6e5bdf2c891382bbde7f24e906a168af351154a
JOB LOG    : /home/local/avocado/job-results/job-2021-09-24T17.39-b6e5bdf/job.log
 (kubernetes-CRI_CONTAINERD_K8S-1/2) make: STARTED
 (kubernetes-CRI_CONTAINERD_K8S-1/2) make: PASS (2.72 s)
 (kubernetes-CRI_CONTAINERD_K8S-2/2) make: STARTED
 (kubernetes-CRI_CONTAINERD_K8S-2/2) make: PASS (0.02 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/local/avocado/job-results/job-2021-09-24T17.39-b6e5bdf/results.html
JOB TIME   : 5.49 s
```

This is happening because avocado is using the 'uri' as identifier in our current Runners. 

(Yes, we could use a multiplexer plugin for that, but some users are not so familiar with those plugins.)

**Describe the solution you'd like**

Would be nice to have a way to configure how tests should be identifier so results could be easly distinguishable. For instance:

```
JOB ID     : b6e5bdf2c891382bbde7f24e906a168af351154a
JOB LOG    : /home/local/avocado/job-results/job-2021-09-24T17.39-b6e5bdf/job.log
 (kubernetes-CRI_CONTAINERD_K8S-1/2) /usr/bin/make-foo: STARTED
 (kubernetes-CRI_CONTAINERD_K8S-1/2) /usr/bin/make-foo: PASS (2.72 s)
 (kubernetes-CRI_CONTAINERD_K8S-2/2) /usr/bin/make-bar: STARTED
 (kubernetes-CRI_CONTAINERD_K8S-2/2) /usr/bin/make-bar: PASS (0.02 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/local/avocado/job-results/job-2021-09-24T17.39-b6e5bdf/results.html
JOB TIME   : 5.49 s
```

**Describe alternatives you've considered**

After discussing this with @clebergnu, one possible solution, would be to allow users to configure an "identifier format" per test runner. Something like:

```python
config = {'runner.exectest.identifier_format = "%u-%a"'}
```

This would allow the exectest runner use "UID-ARGS" as identifier. In this example, this would be translated to `/usr/bin/make-foo`, `/usr/bin/make-bar`.
 
**Additional information**

Most of the runners could have "%u" as default identifier.

**Comment by wainersm** [comment]
@beraldoleal first of all, thanks for working on this requirement!

Context: I'm doing some experiments to see if Avocado can solve some problems on Kata Containers project.

The tests are executed by a kind of job script and you can think of evocations to `make <target>` are conceptually equivalent to run  individual tests. The evocation of those make commands aren't unfortunately so simple: there are something like `/usr/bin/sudo -E PATH=$PATH CRI_RUNTIME=containerd bash -c 'make <target>'`. Therefore, using the `"%u-%a"` formatter doesn't help either as the result will be a bit "ugly" (assuming that avocado will concatenate the arguments somehow). Yes I can try to simplify those evocations, but still ugly.

Another issue is to distinguish two tests which have the same command and arguments but different environment variables (changing the behavior of the tests).

IMHO it needs more thoughts. :)

**Comment by beraldoleal** [comment]
@wainersm, Thanks for the reply. I missed some information in the description.

%u and %a are just examples, for sure we need a bigger table of "special variables". ENV variables could be supported as well. 

One think that we discussed it was adding support to something like this "%a[6-7]". Where, in your example would result in something like "make <target>".

**Comment by wainersm** [comment]
> @wainersm, Thanks for the reply. I missed some information in the description.
> 
> %u and %a are just examples, for sure we need a bigger table of "special variables". ENV variables could be supported as well.
> 
> One think that we discussed it was adding support to something like this "%a[6-7]". Where, in your example would result in something like "make target".

hello @beraldoleal , got it, having the flexibility to choose so specifics arguments should work out.
Thanks!
