### ISSUE TITLE
Evaluate the need for selftests/run

### ISSUE THREAD

**Issue by beraldoleal** [avocado-framework/avocado#4992]
Currently our main entry point for checks is `check.py`. However `selftests/run` is called by `selftests/run_coverage`. We need to double check if that is really needed.

IIRC @willianrampazzo was working in somehow integrate avocado using the coverage' API, so maybe after that we can remove this file.

**Comment by clebergnu** [comment]
This is indeed related to https://github.com/avocado-framework/avocado/issues/4957
