### ISSUE TITLE
subprocess output of a test not being stored in stdout file

### ISSUE THREAD

**Issue by beraldoleal** [avocado-framework/avocado#4996]
**Describe the bug**
stdout|stderr files are not storing subprocess output when using the nrunner. If you use the legacy runner the subprocess's output of a test will be stored properly. But this is not happening here with the nrunner.

Although this content can be found in the test's debug.log, the information should be consistent. 

**Steps to reproduce**
1. Create a file called `/tmp/test.py` with the following content:

```python
#!/bin/env python
import sys

from avocado import Test
from avocado.utils import process

print("top_print")
sys.stdout.write("top_stdout\n")
sys.stderr.write("top_stderr\n")

process.run("/bin/echo top_process")


class OutputTest(Test):
    def __init__(self, *args, **kwargs):
        super(OutputTest, self).__init__(*args, **kwargs)
        print("init_print")
        sys.stdout.write("init_stdout\n")
        sys.stderr.write("init_stderr\n")
        process.run("/bin/echo init_process")

    def test(self):
        print("test_print")
        sys.stdout.write("test_stdout\n")
        sys.stderr.write("test_stderr\n")
        process.run("/bin/echo -n test_process > /dev/stdout",
                    shell=True)
        process.run("/bin/echo -n __test_stderr__ > /dev/stderr",
                    shell=True)
        process.run("/bin/echo -n __test_stdout__ > /dev/stdout",
                    shell=True)

    def __del__(self):
        print("del_print")
        sys.stdout.write("del_stdout\n")
        sys.stderr.write("del_stderr\n")
        process.run("/bin/echo -n del_process")
```

2. Run with the next runner and check for the stdout file:
```
$ avocado run /tmp/test.py
$ grep test_process ~/avocado/job-results/latest/test-results/1*/stdout
```

**Expected behavior**
We should see *one line* with the "test_process" string inside this file.

**Current behavior**
Returning nothing.

**System information (please complete the following information):**
 - OS: 
```LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 33 (Thirty Three)
Release:	33
Codename:	ThirtyThree
```

 - Avocado version: `avocado -v`:
`Avocado 91.0`
 - Avocado installation method: pip, rpm, github ?
`$ python setup.py develop`

**Additional information**
I was planning to update the following test to use the nrunner when I found this issue:
```selftests/functional/test_output.py:OutputTest.test_print_to_std```

**Comment by clebergnu** [comment]
@beraldoleal just to make sure, when you say: 

---

**Expected behavior**:
We should see some lines with the "test_process" string inside this file.

---

You mean a *single* line, right?

**Comment by beraldoleal** [comment]
yes.!

**Comment by clebergnu** [comment]
I don't think the expectation or the premises here are correct.  Just to rule out Avocado (as in the runners), I wrote this sample script, attempting to exercise a way to get the output to the Python process stdout:

```python
#!/usr/bin/python3

from avocado.utils import process

process.run("/bin/echo -n test_process > /dev/stdout", shell=True)
process.run("/bin/echo -n test_process > /dev/stdout", shell=True, verbose=True)
process.run("/bin/echo -n test_process")
process.run("/bin/echo -n test_process", shell=True)
process.run("/bin/echo -n test_process", shell=True, verbose=True)
process.run("/bin/echo -n test_process", verbose=True)
process.run("/bin/echo test_process > /dev/stdout")
process.run("/bin/echo test_process > /dev/stdout", shell=True)
process.run("/bin/echo test_process > /dev/stdout", shell=True, verbose=True)
process.run("/bin/echo test_process > /dev/stdout", verbose=True)
process.run("/bin/echo test_process")
process.run("/bin/echo test_process", shell=True)
process.run("/bin/echo test_process", shell=True, verbose=True)
process.run("/bin/echo test_process", verbose=True)


process.run("/bin/uname > /dev/stdout", shell=True)
process.run("/bin/uname > /dev/stdout", shell=True, verbose=True)
process.run("/bin/uname")
process.run("/bin/uname", shell=True)
process.run("/bin/uname", shell=True, verbose=True)
process.run("/bin/uname", verbose=True)
process.run("/bin/uname > /dev/stdout", shell=True)
process.run("/bin/uname > /dev/stdout", shell=True, verbose=True)
process.run("/bin/uname")
process.run("/bin/uname", shell=True)
process.run("/bin/uname", shell=True, verbose=True)
process.run("/bin/uname", verbose=True)
```

The behavior of this script is to generate **no output**.  The `process.run()` API will read (drain) the process stdout (and stderr), but kill keep it in the result object.

When redirecting to `/dev/stdout`, executing under a shell, it means that output will go to the shell's process stdout/stderr -- and in no way to the Python interpreter stdout/stderr.

Let me know if you think I'm missing something.

**Comment by beraldoleal** [comment]
@clebergnu I think this might be a little bit strange at first to me. As Python' `subprocess.run()` user I was expecting to see results on an example like this:

```python
import subprocess
result = subprocess.run(["ls", "-l"])
```

Maybe I'm missing some important information about the Avocado's process goals.

Also, `selftests/functional/test_output.py:OutputTest:test_print_to_std` is expecting to see this as an `[output]` (Yes, it is looking inside the job.log` which IMO makes things confusing.)

If I run this with the legacy runner I'm getting the expected output.

**Comment by clebergnu** [comment]
> @clebergnu I think this might be a little bit strange at first to me. As Python' `subprocess.run()` user I was expecting to see results on an example like this:
> 
> ```python
> import subprocess
> result = subprocess.run(["ls", "-l"])
> ```
> 
> Maybe I'm missing some important information about the Avocado's process goals.
> 

I'd say it's simply a different behavior than `subprocess.run()`.  Among the *reasons* I'd list the requirement to cope with large amounts of output (`avocado.utils.process.run()` will drain internal buffers to avoid them to overrun).

> Also, `selftests/functional/test_output.py:OutputTest:test_print_to_std` is expecting to see this as an `[output]` (Yes, it is looking inside the job.log` which IMO makes things confusing.)
> 

This is confusing indeed, but it's a consequence of the next point...

> If I run this with the legacy runner I'm getting the expected output.

The legacy runner has a much weaker isolation than the nrunner.  If the `verbose` flag is set, a `stream_logger` with the FDDrainer will be used to, not only write to a given file, but also log it.  Because the test process shares a lot with the parent process (Avocado itself) it will reuse its logging configurations, which means the output will go the test log file.

But, this is IMO unintended behavior.

**Comment by beraldoleal** [comment]
> > Maybe I'm missing some important information about the Avocado's process goals.
> 
> I'd say it's simply a different behavior than `subprocess.run()`. Among the _reasons_ I'd list the requirement to cope with large amounts of output (`avocado.utils.process.run()` will drain internal buffers to avoid them to overrun).

Is this documented in any place? I could not find inside the module doc strings. IMO this is critical to avoid bad experiences.

> > Also, `selftests/functional/test_output.py:OutputTest:test_print_to_std` is expecting to see this as an `[output]` (Yes, it is looking inside the job.log` which IMO makes things confusing.)
> 
> This is confusing indeed, but it's a consequence of the next point...
> 
> > If I run this with the legacy runner I'm getting the expected output.
> 
> The legacy runner has a much weaker isolation than the nrunner. If the `verbose` flag is set, a `stream_logger` with the FDDrainer will be used to, not only write to a given file, but also log it. Because the test process shares a lot with the parent process (Avocado itself) it will reuse its logging configurations, which means the output will go the test log file.

I confess that I'm not so familiar with the drainer's concept and the isolation idea here. I'm avoiding on purpose. From the user PoV *this is still confusing* (and based on your explanation, I understood why, thanks).  But I will try to explain my main problem here (the confusion part):

Regardless our sub process should output or not, `avocado.utils.process` it is capturing this and presenting to the user inside `debug.log` like this:

```
[stdlog] 2021-09-30 17:03:17,597 avocado.test              L0461 DEBUG| [stdout] test_process
```

When I look at this file and see this together with the test output, things starts being fuzzy IMO. I understand that if we are using a test that is not using our library, this confusion will not happen.

> But, this is IMO unintended behavior.

I'm assuming that you are talking about the legacy runner usage. Probably we are on the same page here. But since this is still confusing, let's try to agree with the following action items:

 1. `selftests/functional/test_output.py:OutputTest:test_print_to_std` must be adapted (or copied) to not search for subprocess's  strings inside the stdout file. (when using the nrunner); (I will change that within #4998)
 2. `avocado.utils.process.run()` could be improved to accept an optional argument to redirect subprocess's output as well (or instead of a new argument, use the existing "verbose") (Post LTS)
 3. We need to better separate what is a "test stdout|stderr output" (avocado.test.stdout|stderr* logger namespaces) vs 'avocado.test': Today, `avocado.utils.process` is using `avocado.test.stdout` to print to the debug things that *are not a test stdout*. Regardless if the test calling or not, this namespace IMO should be `avocado.utils.process.stdout` (or something like that). If 2 is implemented we probably will capture this by the runner side. (Also post LTS).
 4. Document, document and document.


Let me know if that makes sense to you.

Thank you again @clebergnu for the explanation.

**Comment by clebergnu** [comment]
> > > Maybe I'm missing some important information about the Avocado's process goals.
> > 
> > 
> > I'd say it's simply a different behavior than `subprocess.run()`. Among the _reasons_ I'd list the requirement to cope with large amounts of output (`avocado.utils.process.run()` will drain internal buffers to avoid them to overrun).
> 
> Is this documented in any place? I could not find inside the module doc strings. IMO this is critical to avoid bad experiences.
> 

We can improve the documentation, but just to make it clear: are you expecting to find information about the "drainage" in the user visible documentation?  IMO this could be added as a note, but it doesn't impact how the users consume the `process.run()` API.

> > > Also, `selftests/functional/test_output.py:OutputTest:test_print_to_std` is expecting to see this as an `[output]` (Yes, it is looking inside the job.log` which IMO makes things confusing.)
> > 
> > 
> > This is confusing indeed, but it's a consequence of the next point...
> > > If I run this with the legacy runner I'm getting the expected output.
> > 
> > 
> > The legacy runner has a much weaker isolation than the nrunner. If the `verbose` flag is set, a `stream_logger` with the FDDrainer will be used to, not only write to a given file, but also log it. Because the test process shares a lot with the parent process (Avocado itself) it will reuse its logging configurations, which means the output will go the test log file.
> 
> I confess that I'm not so familiar with the drainer's concept and the isolation idea here. I'm avoiding on purpose. From the user PoV _this is still confusing_ (and based on your explanation, I understood why, thanks). But I will try to explain my main problem here (the confusion part):
> 
> Regardless our sub process should output or not, `avocado.utils.process` it is capturing this and presenting to the user inside `debug.log` like this:
> 
> ```
> [stdlog] 2021-09-30 17:03:17,597 avocado.test              L0461 DEBUG| [stdout] test_process
> ```
> 
> When I look at this file and see this together with the test output, things starts being fuzzy IMO. I understand that if we are using a test that is not using our library, this confusion will not happen.
> 
> > But, this is IMO unintended behavior.
> 
> I'm assuming that you are talking about the legacy runner usage. Probably we are on the same page here. But since this is still confusing, let's try to agree with the following action items:
> 
> 1. `selftests/functional/test_output.py:OutputTest:test_print_to_std` must be adapted (or copied) to not search for subprocess's  strings inside the stdout file. (when using the nrunner); (I will change that within [Improvements on logging #4998](https://github.com/avocado-framework/avocado/pull/4998))

Not `subprocess`s string, but [process.run()](https://github.com/avocado-framework/avocado/blob/65c2725a09388aacd05587f78570acd93326e035/selftests/functional/test_output.py#L65), right?

ACK, about removing that entry from the test's log.

> 2. `avocado.utils.process.run()` could be improved to accept an optional argument to redirect subprocess's output as well (or instead of a new argument, use the existing "verbose") (Post LTS)

Ditto (`s/subprocess/process.run()`), right?

ACK about that proposal.  What we need is explicit and clear common API, such as:

```python
import logging
from avocado.utils import process

LOG = logging.getLogger("my.custom.logger")

process.run("/path/to/command", log=LOG)
```

And possibly paired with higher level, test scoped, utility APIs such as:

```python
from avocado import Test

class My(Test):

   def test(self):
       # similar to process.run(..., log=self.log)
       self.run("/path/to/command")
```

> 3. We need to better separate what is a "test stdout|stderr output" (avocado.test.stdout|stderr* logger namespaces) vs 'avocado.test': Today, `avocado.utils.process` is using `avocado.test.stdout` to print to the debug things that _are not a test stdout_. Regardless if the test calling or not, this namespace IMO should be `avocado.utils.process.stdout` (or something like that). If 2 is implemented we probably will capture this by the runner side. (Also post LTS).

ACK.

> 4. Document, document and document: even though this change makes sense, users will get surprised when not find the outputs on stdout file.

Agreed.

> 
> Let me know if that makes sense to you.
> 
> Thank you again @clebergnu for the explanation.

YW!

**Comment by beraldoleal** [comment]
> > > > Maybe I'm missing some important information about the Avocado's process goals.
> > > 
> > > 
> > > I'd say it's simply a different behavior than `subprocess.run()`. Among the _reasons_ I'd list the requirement to cope with large amounts of output (`avocado.utils.process.run()` will drain internal buffers to avoid them to overrun).
> > 
> > 
> > Is this documented in any place? I could not find inside the module doc strings. IMO this is critical to avoid bad experiences.
> 
> We can improve the documentation, but just to make it clear: are you expecting to find information about the "drainage" in the user visible documentation? IMO this could be added as a note, but it doesn't impact how the users consume the `process.run()` API.

I would expect a better documentation at all levels: better doc strings for developers and better sections talking about what to expect on those files for the user guide. Not expecting to have internal module implementation on the user guide.


> > 
> > 1. `selftests/functional/test_output.py:OutputTest:test_print_to_std` must be adapted (or copied) to not search for subprocess's  strings inside the stdout file. (when using the nrunner); (I will change that within [Improvements on logging #4998](https://github.com/avocado-framework/avocado/pull/4998))
> 
> Not `subprocess`s string, but [process.run()](https://github.com/avocado-framework/avocado/blob/65c2725a09388aacd05587f78570acd93326e035/selftests/functional/test_output.py#L65), right?

Yes.

> ACK, about removing that entry from the test's log.
> 
> > 1. `avocado.utils.process.run()` could be improved to accept an optional argument to redirect subprocess's output as well (or instead of a new argument, use the existing "verbose") (Post LTS)
> 
> Ditto (`s/subprocess/process.run()`), right?

Yes.
