### ISSUE TITLE
[nrunner] PythonUnittestRunner is converting "." to "/" on paths

### ISSUE THREAD

**Issue by willianrampazzo** [avocado-framework/avocado#5017]
**Describe the bug**
While running a Python unittest using the nrunner, if the path has a dot (".") in the name, it will be replaced by a forward-slash ("/").

**Steps to reproduce**
Run the `selftests/.data/unittests.py` using the `avocado-runner-python-unittest` runner from a folder that has a dot in the name. Example:

```
avocado-runner-python-unittest runnable-run -u /home/wrampazz/src/avocado/avocado.dev/selftests/.data/unittests.py:First.test_pass
```

**Expected behavior**
The test should runs successfully, like:

```
$ avocado-runner-python-unittest runnable-run -u selftests/.data/unittests.py:First.test_pass
{'status': 'started', 'time': 138372.811405082}
{'status': 'running', 'time': 138372.821851093}
{'type': 'stdout', 'log': b'----------------------------------------------------------------------\nRan 1 test in 0.000s\n\nOK\n', 'status': 'running', 'time': 138372.8219836}
{'status': 'finished', 'result': 'pass', 'time': 138372.821998181}
```

**Current behavior**
The test fails with an error when trying to import the module. Example:

```
$ avocado-runner-python-unittest runnable-run -u /home/wrampazz/src/avocado/avocado.dev/selftests/.data/unittests.py:First.test_pass
{'status': 'started', 'time': 138043.030314055}
{'status': 'running', 'time': 138043.040851727}
{'type': 'stdout', 'log': b'======================================================================\nERROR: unittests (unittest.loader._FailedTest)\n----------------------------------------------------------------------\nImportError: Failed to import test module: unittests\nTraceback (most recent call last):\n  File "/usr/lib64/python3.9/unittest/loader.py", line 154, in loadTestsFromName\n    module = __import__(module_name)\nModuleNotFoundError: No module named \'unittests\'\n\n\n----------------------------------------------------------------------\nRan 1 test in 0.001s\n\nFAILED (errors=1)\n', 'status': 'running', 'time': 138043.041081028}
{'status': 'finished', 'result': 'error', 'time': 138043.041114521}
```

**System information (please complete the following information):**
 - OS: `lsb_release -a`:
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 34 (Thirty Four)
Release:	34
Codename:	ThirtyFour
 - Avocado version: clone at 1be5367cafb99fbbf8d7f8912e6e1b79aa94806a
 - Avocado installation method: github dev

**Additional information**
The problem is at:

https://github.com/avocado-framework/avocado/blob/a8034b99c1c9de3d4e7a41a95f33f7c64377effa/avocado/core/nrunner.py#L594

We need to define another way to resolve the module path.

**Comment by beraldoleal** [comment]
Probably is not this commit fault. However, I'm wondering how we would fix this, since pythonunittest uses 'dot' as a convention for splitting the modules.
