### ISSUE TITLE
Allow the deployment and use of development versions of Avocado

### ISSUE THREAD

**Issue by clebergnu** [avocado-framework/avocado#5072]
**Is your feature request related to a problem? Please describe.**
Epic issue https://github.com/avocado-framework/avocado/issues/4934 covers aspects such as creating and publishing (AFAICT) packages for every Avocado release, for every Python version, and how they will be deployed and installed on `DeploymentSpawner`s.

But, this doesn't address the development time needs, where unreleased code may be needed in both the job side (say running out of a GIT checkout), and on the isolated spawner environment.

**Describe the solution you'd like**
There should be a way to signal a preference for given wheels to be used, instead of the latest release ones. 

**Describe alternatives you've considered**
Building the wheels is probably going to be a separate step (such as the current `make whee`, and It will probably be necessary to refer to them by a local (non HTTP(s)) uri.   Bonus point for an all-in-one `--mirror-this-repo-as-a-wheel-and-deploy-it` kind of feature, but I think this will be too complex.

**Comment by beraldoleal** [comment]
I'm assuming here we have a `s/wheel/eggs/g`
