### ISSUE TITLE
Avocado/Spawners should be smart enough when setting/saving to the output dir

### ISSUE THREAD

**Issue by willianrampazzo** [avocado-framework/avocado#5083]
**Is your feature request related to a problem? Please describe.**
On the legacy runner, the content saved to the output dir was available in the `job-results` directory. With the nrunner architecture, we decided to leave the content in a temporary directory, which may be located in a different environment than where Avocado was started. This decision was made because the transfer of huge files could be a bottleneck to the execution of the tests. The current implementation allows the users to _get_ the content using the `avocado jobs get-output-files`.

See https://github.com/avocado-framework/avocado/pull/5059#discussion_r737291135.

**Describe the solution you'd like**
Avocado and the spawners should be smart enough to _know_ they have access to the `job-results` folder and save the test content to it.

For the `process` spawner, as it is running in the same environment where Avocado was started, there is no need to create another temporary folder to store the test files. The output dir can be inside the `job-results` dir.

For the `podman` spawner, mounting the `job-results/<test>` dir is a possibility to make it accessible to the tests.

**Describe alternatives you've considered**
The alternative is implemented today and uses a manual step to _get_ the test files saved to the output dir.

**Additional information**

**Comment by richtja** [comment]
Resolved in  #5179
