### ISSUE TITLE
Early logging for external plugins is missing in Avocado

### ISSUE THREAD

**Issue by pevogam** [avocado-framework/avocado#5120]
**Describe the bug**
Printing a simple log message before initiating any jobs is ignored and not present anywhere. As we only have a job.log and a debug.log for tests, the doesn't seem to be appropriate file for storing such messages.

**Steps to reproduce**
Create a simple plugin and perform the following:
```python
from avocado.core.output import LOG_JOB as log
from avocado.core.plugin_interfaces import CLICmd

class SimplePlugin(CLICmd):

    name = 'simple'
    description = 'reproducer'

    def run(self, config):
        log.info("Simple plugin started.")
```

**Expected behavior**
We want to see "Simple plugin started" in the job.log.

**Current behavior**
Not seen.

**System information (please complete the following information):**
 - OS: Fedora 33
 - Avocado version: 92.0 LTS
 - Avocado installation method: rpm

**Additional information**
It could be that I am missing something so feel free to disqualify this issue if your tested code works. I will be happy to see how it did though.

**Comment by beraldoleal** [comment]
Hi @pevogam thanks for reporting this.

Even with `avocado.test` (`JOB_LOG`)  not being the perfect namespace for this, I confirm that we might have an issue here.

Using the plugin's namespace is not showing either:

```python
import logging

from avocado.core.plugin_interfaces import CLICmd

LOG = logging.getLogger(__name__)


class SimplePlugin(CLICmd):

    name = 'simple'
    description = 'reproducer'

    def run(self, config):
        LOG.info("Simple plugin started.")
```

I will be investigating this. Not sure if we will be able to fix by this sprint. But I will keep this as a high priority in my tasks.

**Comment by beraldoleal** [comment]
Hi @pevogam I was investigating this yesterday and discussed this with the team during our last meeting. So, this seems to be a feature request instead of a bug.

As you pointed, our current log files are not the best place for those types of messages. AFAICT, Avocado's logging it was targeting log information per job run. With our recent changes in the architecture (not only on logging), we are needing a "global" logging file (something like `/var/log/avocado.log`, `/var/log/avocado/something.log` or `~/avocado/log`.

Based on some tests here with old versions, this is not possible either. For this feature, I have created #5177.

While this feature is not ready, and since this is a "CLI Command plugin", one possible alternative would be to log into the UI (that is file agnostic) using `LOG_UI`.

**Comment by pevogam** [comment]
Hi @beraldoleal,

> Hi @pevogam I was investigating this yesterday and discussed this with the team during our last meeting. So, this seems to be a feature request instead of a bug.
> 
> As you pointed, our current log files are not the best place for those types of messages. AFAICT, Avocado's logging it was targeting log information per job run. With our recent changes in the architecture (not only on logging), we are needing a "global" logging file (something like `/var/log/avocado.log`, `/var/log/avocado/something.log` or `~/avocado/log`.
> 
> Based on some tests here with old versions, this is not possible either. For this feature, I have created #5177.

I see, I read it and think it sounds like a better alternative. We cannot reasonably force the output of a CLI plugin or anything of a scope that is more general than a job to log within a job's logging namespace so what you say makes a lot of sense.

> While this feature is not ready, and since this is a "CLI Command plugin", one possible alternative would be to log into the UI (that is file agnostic) using `LOG_UI`.

This is true but won't work for real-life large cases where we have lots of logging output. Such output would quickly clutter the UI and make such a solution less desirable.

> If you think this makes sense, I think we can close this issue and discuss the details about the global logging on #5177.

It does, closing this.
