### ISSUE TITLE
Support of PEP 420 - implicit Namespace Packages

### ISSUE THREAD

**Issue by ana** [avocado-framework/avocado#5165]
Ticket to track support for PEP 420 https://www.python.org/dev/peps/pep-0420/

As a previous step for migrating `avocado.utils` to an external repository and with the goal of supporting libraries in external repositories in the future (e.g. `avocado.utils.project_using_avocado`), we should update avocado to support implicit namespace packages.

I'm adding it for next milestone (`#94`)  but it's quite likely it won't be ready.

**Comment by beraldoleal** [comment]
Hi @ana I took a quick look into the PEP and some examples and methods for creating a "namespace package" and looks like we could use it, for sure.

IIUC, we could have the same namespace 'avocado.utils' used by different repositories (package distributions) without the need of having a package called "avocado_utils". Or have you found any issue that needs a different package name?

Also, do you have any suggestion on the approach? "native namespace packages" vs "pkgutil-style namespace packages"?

**Comment by ana** [comment]
> IIUC, we could have the same namespace 'avocado.utils' used by different repositories (package distributions) without the need of having a package called "avocado_utils". Or have you found any issue that needs a different package name?

I mentioned that using something like `avocado_utils` would be the easiest way, but we want to keep using the same namespace 'avocado.utils' independently if the library is inside avocado or another repository, so the possibility of `avocado_utils` was discarded quite fast.

The approach is native namespace packages https://packaging.python.org/guides/packaging-namespace-packages/#native-namespace-packages

**Comment by beraldoleal** [comment]
> > IIUC, we could have the same namespace 'avocado.utils' used by different repositories (package distributions) without the need of having a package called "avocado_utils". Or have you found any issue that needs a different package name?
> 
> I mentioned that using something like `avocado_utils` would be the easiest way, but we want to keep using the same namespace `avocado.utils` independently if the library is inside avocado or another repository, so the possibility of `avocado_utils` was discarded quite fast.

Ok, I missed that. Thanks.

> The approach is native namespace packages https://packaging.python.org/guides/packaging-namespace-packages/#native-namespace-packages

Good, makes sense since `pip install` is replacing `setup.py install`.

**Comment by clebergnu** [comment]
This is part of https://github.com/avocado-framework/avocado/issues/4390.

**Comment by ana** [comment]
Hi @clebergnu @richtja @beraldoleal 

In the last week, I've been procrastinating this comment and looking for alternatives. No luck :(

PEP420 is incompatible with running avocado from eggs. You must have the `_init__.py` files inside the eggs or it won't find the modules. While we could add empty files when creating the eggs, this will break anyway having external modules under `avocado.plugins.* `and `avocado.utils.*`
It'll open a path for workaround after workaround I'm not sure we want to do this only with the goal of having external modules under `avocado.plugins.* `and `avocado.utils.*`

Besides this, `from avocado import Test` and also `from avocado import main` will stop working as discussed in the draf PR. This will mean a huge transition.

So unless we really want to make a huge refactoring of avocado, I'm not sure this is worth it and maybe using `avocado-utils.* `and `avocado-plugins `modules aren't that bad after all.

**Comment by clebergnu** [comment]
> Hi @clebergnu @richtja @beraldoleal
> 
> In the last week, I've been procrastinating this comment and looking for alternatives. No luck :(
> 

Hi @ana,

Thanks for coming up with this summary of your investigations.

> PEP420 is incompatible with running avocado from eggs. You must have the `_init__.py` files inside the eggs or it won't find the modules. While we could add empty files when creating the eggs, this will break anyway having external modules under `avocado.plugins.* `and `avocado.utils.*` It'll open a path for workaround after workaround I'm not sure we want to do this only with the goal of having external modules under `avocado.plugins.* `and `avocado.utils.*`
> 

I understand that PEP-420 compatibility was pursued because of the initial goal of maintaining the `avocado.utils` and `avocado.plugins` namespaces *after* the split, correct?

While this was one goal, it is not the ultimate objective.  The ultimate objective is to have a single and superior utilities library, instead of the multiple utilities libraries scattered around the avocado* projects.

On an old RFC sent to the mailing list, for instance, I suggested the namespace/name `greenmatter` for that utility library and project (was available on PyPI).

> Besides this, `from avocado import Test` and also `from avocado import main` will stop working as discussed in the draf PR. This will mean a huge transition.
> 

This seems like another *challenge* for implementing PEP-420 indeed.  But, if we give up PEP-420 and the goal of preserving the `avocado.utils` namespace, then I understand it becomes a non-issue.

> So unless we really want to make a huge refactoring of avocado, I'm not sure this is worth it and maybe using `avocado-utils.* `and `avocado-plugins `modules aren't that bad after all.

Sure, or any other name for that matter.  Plugins are always registered using setuptools entrypoints, and their code are seldomly (if ever) referred to by other plugins, so the name of the modules are a lot less important than with the utilities.

**Comment by ana** [comment]
As mentioned in a comment above, this idea was abandoned for several reasons:

* Removal of `avocado/avocado/__init__.py` would require some work.
* A huge change for test suites importing `from avocado import Test, main`. This would be replaced for something like` from avocado.init import Test, main`
* This change requires a setuptools version greater than 40.1.0. This would stop the support out-of-the-box in older distributions like rhel 8
* PEP420 is incompatible with running avocado from eggs
