### ISSUE TITLE
Avocado still modifying the root logger

### ISSUE THREAD

**Issue by pevogam** [avocado-framework/avocado#5166]
Earlier today @samiraguiar pointed out to me that Avocado is still modifying the root logger here:

https://github.com/avocado-framework/avocado/blob/2f52fd3531b6677c4d564e7c897f5e2558918482/avocado/core/output.py#L392

Is this supposed to really happen? I thought the point of staying away from the root logger was to leave it to the user to decide about the logging level and other properties when it comes to this logger in particular.

It could be that I am missing something important here and this is more appropriate in discussions but we can convert it if you think this is more appropriate.

**Comment by willianrampazzo** [comment]
Hi, @pevogam, this line was added six years ago. I think it is a remaining from the changes that @beraldoleal and @richtja are doing to avoid using the root logger; thanks for pointing it out!

**Comment by pevogam** [comment]
Hi @willianrampazzo, I see this sounds pretty interesting. The reasoning behind the question is that this modification resets some of our application-level logging down to DEBUG level and we have a workaround, however I am not sure if this is a desired side effect considering Avocado's transition to logging namespaces.

**Comment by beraldoleal** [comment]
@pevogam thanks for reporting. This is not expected and probably a left over.

Thanks @richtja for self assigned on this and please let me know if you need any help.

**Comment by pevogam** [comment]
Thanks all and thanks to @samiraguiar for making me aware of this.
