### ISSUE TITLE
Categorize the test results data by status

### ISSUE THREAD

**Issue by eskultety** [avocado-framework/avocado#5201]
**Is your feature request related to a problem? Please describe.**
It is not clear which tests passed and which failed by merely looking at the test results data dir. Consider a local development environment (aka not a cloud-based CI infrastructure). Now, consider a scenario where test results are exposed as some kind of artifacts which are then presented to a developer, e.g. as a tarball. Without looking at `results.tap` (or its XML/JSON equivalents) it is not possible for the developer to tell which tests actually failed by merely looking at the `test-results` directory.

**Describe the solution you'd like**
It would be great if the directory hierarchy could be enhanced by using by a `status` directory containing further subdirectories mapping to the  `FAIL`, `PASS`, `ERROR`,etc. statuses. These status directories would then contain symlinks to the actual test results data. See the example below:

```
$ ls -lR avocado/job-results/latest/
...

avocado/job-results/latest/by-status:            
total 4                                                             
drwxr-xr-x. 2 test test  4096 Dec 17 17:25 FAIL                      
                                                                        
avocado/job-results/latest/by-status/FAIL:   
total 8                                                                       
lrwxrwxrwx. 1 test test 72 Dec 17 17:25 1-_bin_false -> avocado/job-results/latest/test-results/1-_bin_false
lrwxrwxrwx. 1 test test 72 Dec 17 17:25 3-_bin_false -> avocado/job-results/latest/test-results/3-_bin_false

...

avocado/job-results/latest/test-results:
total 12
drwxr-xr-x. 2 test test 4096 Dec 17 17:05 1-_bin_false
drwxr-xr-x. 2 test test  4096 Dec 17 17:05 2-_bin_true
drwxr-xr-x. 2 test test  4096 Dec 17 17:05 3-_bin_false

...
```

**Describe alternatives you've considered**
Given the scenario above, I have not found a suitable alternative.

**Comment by beraldoleal** [comment]
@eskultety, thanks for reporting this. Just one consideration...

Although I like to browse the directories, over the last few months we've noticed that this model has some limitations and may not be as attractive for some users. For this reason, we create the `avocado show jobs` command.

So I would like to ask if you consider an extra option in this command as a valid option. Ex: `avocado jobs show latest --filter-by-status=FAIL` (or something like this).

I'm not excluding the initial ideal (or maybe both), but we need to consider if it's really necessary, as IMO accessing this through the interface can make it more attractive and also keeping two snippets of code is something we should consider.

**Comment by clebergnu** [comment]
> @eskultety, thanks for reporting this. Just one consideration...
> 
> Although I like to browse the directories, over the last few months we've noticed that this model has some limitations and may not be as attractive for some users. For this reason, we create the `avocado show jobs` command.
> 
> So I would like to ask if you consider an extra option in this command as a valid option. Ex: `avocado jobs show latest --filter-by-status=FAIL` (or something like this).
> 
> I'm not excluding the initial ideal (or maybe both), but we need to consider if it's really necessary, as IMO accessing this through the interface can make it more attractive and also keeping two snippets of code is something we should consider.

The problem is how such functionality would be consumed by non interactive systems.  Think of GitLab CI: you can not, post job execution, based on the output of a command or logic, tell it which results to keep as artifacts.  The location must be ready to be consumed based on a previous static job configuration (on the YAML file).

**Comment by beraldoleal** [comment]
Thanks @clebergnu I got the user case. Makes sense.

**Comment by eskultety** [comment]
I should have been more exact in the description, @clebergnu  described exactly the use case I had in mind.

**Comment by beraldoleal** [comment]
> I should have been more exact in the description, @clebergnu described exactly the use case I had in mind.

You were very precise. My fault for not having read it right.
