### ISSUE TITLE
Bump pylint to version 2.12.2

### ISSUE THREAD

**Issue by ana** [avocado-framework/avocado#5211]
We should bump pylint to a more recent version, latest release version is 2.12.2. Testing with this version outputs arounds ~1100 lineas of issues:

```
842 times:   C0209  Formatting a regular string which could be a f-string (consider-using-f-string)
125 times:   W1514  Using open without explicitly specifying an encoding (unspecified-encoding)
 10 times:   E0012  Bad option value 'W1620' (bad-option-value)
 37 times:   W1406  The u prefix for strings is no longer necessary in Python >=3.0 (redundant-u-string-prefix) 
 12 times:   C0206  Consider iterating with .items() (consider-using-dict-items)
  1 times:   W0402  Uses of a deprecated module 'imp' (deprecated-module)
  3 times:   W0237  Parameter 'o' has been renamed to 'config_option' in overridden 'ConfigEncoder.default' method (arguments-renamed)
  2 times:   R1709  Boolean expression may be simplified to None (simplify-boolean-expression)  
  1 times:   W0612  Unused variable 'details' (unused-variable)
  1 times:   R1735  Consider using {} instead of dict() (use-dict-literal)
  1 times:   C0207  Use str(uuid.uuid4()).split('-', maxsplit=1)[0] instead (use-maxsplit-arg)
  2 times:   E1133  Non-iterable value data.tests is used in an iterating context (not-an-iterable)
```
The goal is to fix them all before bumping the pylint version.

**Comment by ana** [comment]
@clebergnu @beraldoleal @richtja  Fixing C0209 will be a huge change, do we want to fix this pyling warning or we want to override it?

**Comment by ana** [comment]
I just got a small surprise, the stats in the top don't include the checking under `selftest`. So there are more things to fix, but nothing crazy.

**Comment by beraldoleal** [comment]
@ana, this could be something that we could be improving as we go. So adding it to .pylintrc would be acceptable, IMO.

**Comment by ana** [comment]
I filed a low-hanging-fruit issue for switching to f-strings https://github.com/avocado-framework/avocado/issues/5219

**Comment by ana** [comment]
This was done in 4 separate PR:
01  https://github.com/avocado-framework/avocado/pull/5213
02  https://github.com/avocado-framework/avocado/pull/5215
03  https://github.com/avocado-framework/avocado/pull/5216
04  https://github.com/avocado-framework/avocado/pull/5226
