### ISSUE TITLE
Remove legacy runner leftovers

### ISSUE THREAD

**Issue by beraldoleal** [avocado-framework/avocado#5246]
Currently we keep in our code, multiple references to legacy runner, in order to keep some level of compatibility. At this point, we can drop them.

I have started working on this. I'm creating this issue just to keep tracking of this job.

**Comment by clebergnu** [comment]
@beraldoleal I think we can close this issue given that https://github.com/avocado-framework/avocado/pull/5362 (which concerts itself with the legacy *runner*) has been merged, and there's https://github.com/avocado-framework/avocado/issues/5138 that covers the *loader* part.

If I'm missing something, please feel free to reopen this.
