### ISSUE TITLE
Replace avocado website

### ISSUE THREAD

**Issue by ana** [avocado-framework/avocado#5265]
Folks, I have ready a new website using jekyll that can replace the current one. You can browse it at https://ana.github.io/avocado.github.io/

If you are ok, the plan is to rename the current master branch at https://github.com/avocado-framework/avocado-framework.github.io as **old_website** and replace **master** with https://github.com/ana/avocado.github.io
Once the master branch is replaced at  https://github.com/avocado-framework/avocado-framework.github.io we can make further changes and updates  using PRs

@clebergnu @beraldoleal @richtja does this plan sound OK to you?

**Comment by beraldoleal** [comment]
Sounds good to me. The new website is much better. Thanks!

I'm just missing a "contributing" or "how to contribute" section on the right menu. By looking at the new website, the only pointer to contribute is the "Report a bug" link. But this could be improved later.

**Comment by richtja** [comment]
@ana, This is great, thanks. Yeah, we can go with this approach.

**Comment by ana** [comment]
Thanks for the replies. I'm going to add a README file and switch the branches as mentioned.

**Comment by ana** [comment]
Website updated \o/
