### ISSUE TITLE
exec-test support for warn_regex and skip_regex

### ISSUE THREAD

**Issue by clebergnu** [avocado-framework/avocado#5333]
**Is your feature request related to a problem? Please describe.**
The legacy runner, through its `avocado.core.test.SimpleTest` implementation, have a [feature](https://avocado-framework.readthedocs.io/en/96.0/guides/writer/chapters/writing.html#simple-tests-status) that allows the configuration of regular expressions that, if matched, will determine the status of a test.

This issue is about tracking the same feature for the nrunner based `exec-test`.

**Describe the solution you'd like**
The same behavior as documented [here](https://avocado-framework.readthedocs.io/en/96.0/guides/writer/chapters/writing.html#simple-tests-status) and passing the tests [here](https://github.com/avocado-framework/avocado/blob/3599d2f98b9b93dfbc0db1950f2775ff41c72190/selftests/functional/test_basic.py#L816).

**Describe alternatives you've considered**
The alternative is dropping the feature.

**Additional information**
This is part of https://github.com/avocado-framework/avocado/issues/5138

**Comment by beraldoleal** [comment]
> Describe alternatives you've considered
> The alternative is dropping the feature.

If there is no users, this is always a valid option. Do you remember any potential user? We could keep this in long term backlog for a while.

**Comment by clebergnu** [comment]
This feature has not been demanded in ~ months.  Closing it.
