### ISSUE TITLE
Netperf testing gives low throughput

### ISSUE THREAD

**Issue by pacc-314** [avocado-framework/avocado#5342]
I am running netperf test from a client server with netserver already started on peer server. I constantly see throughput percentage less than 50 %. Can you please let know if we are running test wrongly? The 

# avocado run /var/tmp/avocado/selftests/unit/utils/netperf_test.py -p peer_ip=10.x.x.x -p interface=bond0 -p peer_user=root -p TIMEOUT=720 -p NETSERVER_RUN=0 -p EXPECTED_THROUGHPUT=90 -p duration=60 -p minimum_iterations=1 -p maximum_iterations=5 -p option='TCP_STREAM --'
Fetching asset from /var/tmp/avocado/selftests/unit/utils/netperf_test.py:Netperf.test
JOB ID     : e9ea3d44bdc72d6586644ec1a3148f95cd47b34f
JOB LOG    : /root/avocado/job-results/job-2022-04-21T05.24-e9ea3d4/job.log
 (1/1) /var/tmp/avocado/selftests/unit/utils/netperf_test.py:Netperf.test: FAIL: FAIL: Throughput Actual - 43.425%, Expected - 90%, Throughput Actual value - 17370Mb/sec  (10.38 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 11.11 s

It seems to compare the throughput value with below file to get percentage throughput
# cat /sys/class/net/bond0/speed
40000

**Comment by clebergnu** [comment]
@pacc-314 is the test you run here actually [this](https://github.com/avocado-framework-tests/avocado-misc-tests/blob/master/io/net/netperf_test.py) ?  If so, do you believe there is an Avocado issue that is impacting the test results (performance)?

If not, I'll close this issue, and it should be opened on the avocado-misc-tests repo.

Thanks.

**Comment by clebergnu** [comment]
Hi @pacc-314, please let us know if you have more info on this.  If you do, please reopen this issue.

Thanks.
