### ISSUE TITLE
Issuing log.warning prior to a failed assertion results in test result as WARN instead of FAIL

### ISSUE THREAD

**Issue by on-kage** [avocado-framework/avocado#5375]
**Describe the bug**
If a test logs a warning via the log.warning command, then no matter what happens afterwards the test result will be WARN. This is the case even if there is a later failed assertion

**Steps to reproduce**
from avocado import Test

class Test_assert(Test):
        """
        :avocado: enable
        """

        def setUp(self):
            pass

        def tearDown(self):
            pass

        def test_1(self):
            self.log.warning(f'warn message')
            self.assertTrue(False, 'assertion fail')

**Expected behavior**
In the test shown in "Steps to reproduce", I would expect the test result to be FAIL based on the failed assertTrue statement. 

**Current behavior**
The test results in a WARN

**System information (please complete the following information):**
 - OS: docker image based on `python:3.10.2-slim-buster`
 - Avocado version: Avocado 96.0
 - Avocado installation method: pip

**Additional information**
Checked with Avocado 69 which is what we were previously using and the result of the test is FAIL

**Comment by richtja** [comment]
Hi @on-kage thanks for reporting this. It is definitely a problem.
