### ISSUE TITLE
Test sequence using an yaml file

### ISSUE THREAD

**Issue by celebgnu** [avocado-framework/avocado#5377]
### Discussed in https://github.com/avocado-framework/avocado/discussions/5376

<div type='discussions-op-text'>

<sup>Originally posted by **celebgnu** May 13, 2022</sup>
Hello,

We had used avocado-framework-plugin-loader-yaml plugin for creating an test sequence, where in we had used the test reference along with its parameters inside an yaml file and directly provided as an input to the runner.

As per my understanding the plugin support was discontinued in avocado version 82. 
So i was wondering if we have an alternative in the newer version where in we can provide the test reference inside an yaml file.

Best Regards.</div>

**Comment by clebergnu** [comment]
Hi @celebgnu, this is certainly possible by using the Job API.  You can create a simple Python script that reads the YAML file (say, using PyYAML) and creates a test suite from it.

Let us know if you have trouble navigating the Job API, but please consult the examples in the `examples/jobs` folder.
