### ISSUE TITLE
PyYAML compile error while installing varianter_yaml_to_mux plugin avocado 97.0

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework/avocado#5417]
**Describe the bug**
optional plugin varianter_yaml_to_mux fails to compile with below error blocking all our automation runs on the latest avocado 97.0

```
Processing avocado_framework_plugin_varianter_yaml_to_mux-97.0-py3.6.egg
Copying avocado_framework_plugin_varianter_yaml_to_mux-97.0-py3.6.egg to /usr/local/lib/python3.6/site-packages
Adding avocado-framework-plugin-varianter-yaml-to-mux 97.0 to easy-install.pth file

Installed /usr/local/lib/python3.6/site-packages/avocado_framework_plugin_varianter_yaml_to_mux-97.0-py3.6.egg
Processing dependencies for avocado-framework-plugin-varianter-yaml-to-mux==97.0
Searching for PyYAML>=4.2b2
Reading https://pypi.org/simple/PyYAML/
Downloading https://files.pythonhosted.org/packages/36/2b/61d51a2c4f25ef062ae3f74576b01638bebad5e045f747ff12643df63844/PyYAML-6.0.tar.gz#sha256=68fb519c14306fec9720a2a5b45bc9f0c8d1b9c72adf45c37baedfcd949c35a2
Best match: PyYAML 6.0
Processing PyYAML-6.0.tar.gz
Writing /tmp/easy_install-0iqmjj6n/PyYAML-6.0/setup.cfg
Running PyYAML-6.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-0iqmjj6n/PyYAML-6.0/egg-dist-tmp-5fw0nfhq
warning: no files found matching 'README'
gcc: error: yaml/_yaml.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
Error compiling module, falling back to pure Python
zip_safe flag not set; analyzing archive contents...
Moving PyYAML-6.0-py3.6-linux-ppc64le.egg to /usr/local/lib/python3.6/site-packages
Adding PyYAML 6.0 to easy-install.pth file
```

**Steps to reproduce**
git clone https://github.com/avocado-framework/avocado.git
cd avocado;python3.6 setup.py install
cd optional_plugins/varianter_yaml_to_mux; python3.6 setup.py install  

It fails to compile with error as shown

**Expected behavior**
compilation should complete and avocado should be able to proceed with test runs with yaml options

**Current behavior**
```
avocado run -nrunner-max-parallel-task=1 /bin/true
Failed to load plugin from module "avocado_varianter_yaml_to_mux.varianter_yaml_to_mux": ModuleNotFoundError("No module named 'avocado_varianter_yaml_to_mux'",) :
  File "/usr/local/lib/python3.6/site-packages/avocado_framework-97.0-py3.6.egg/avocado/core/extension_manager.py", line 94, in __init__
    plugin = ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)

usage: avocado run [-h] [-p NAME_VALUE] [--test-runner TEST_RUNNER] [-d]
```
**System information (please complete the following information):**
 - OS: All RHEL and SLES releases
 - Avocado version: Avocado 97.0
 - Avocado installation method: pip, rpm, github ? problem seen with all type of installaiton

**Additional information**
Add any other information about the problem here. Test details can be added here.
[avocado-PyYAMLcompilelogs.txt](https://github.com/avocado-framework/avocado/files/9008576/avocado-PyYAMLcompilelogs.txt)

**Comment by abdhaleegit** [comment]
@clebergnu @beraldoleal Could you please have a look into this, Thanks

**Comment by PraveenPenguin** [comment]
moved in 94.0 https://github.com/avocado-framework/avocado/commit/0eefb48fd57f9081b11af1c352b19fd7a01264f7 and it working fine trying to do bisect to get what is causing this issue

**Comment by clebergnu** [comment]
@PraveenPenguin thanks for looking into it.  Let me know if you have any more info about it.

**Comment by clebergnu** [comment]
@PraveenPenguin do you have any updates on this issue?

**Comment by narasimhan-v** [comment]
@PraveenPenguin Any update on this ?

**Comment by PraveenPenguin** [comment]
@narasimhan-v issue is fixed in master branch
