### ISSUE TITLE
The `utils.process` default int handler needs an update for newer python versions

### ISSUE THREAD

**Issue by pevogam** [avocado-framework/avocado#5460]
Hi all,

It seems this line might need an update:

https://github.com/avocado-framework/avocado/blob/5a0c5b2348da450397287a0954e4c335c0d590a9/avocado/utils/process.py#L648

In Python 3.9 this function is documented as:
```
Help on built-in function default_int_handler in module _signal:

default_int_handler(...)
    default_int_handler(...)
    
    The default handler for SIGINT installed by Python.
    It raises KeyboardInterrupt.
```
and will work with the current code but the same will have obligatory argument requirements in Python 3.10:
```
Help on built-in function default_int_handler in module _signal:

default_int_handler(signalnum, frame, /)
    The default handler for SIGINT installed by Python.
    
    It raises KeyboardInterrupt.
```
Has anyone else noticed this?

**Comment by clebergnu** [comment]
Closing because of fix in https://github.com/avocado-framework/avocado/pull/5540

**Comment by pevogam** [comment]
I was about to test this first but I guess I will do so retrogressively then.
