### ISSUE TITLE
--nrunner-status-server-uri  is not working as stated in help

### ISSUE THREAD

**Issue by nirGNU** [avocado-framework/avocado#5473]
**Describe the bug**
Help : 'URI for connecting to the status server, usually '
                    'a "HOST:PORT" string. Use this if your status server '
                    'is in another host, or different port'

--nrunner-status-server-uri option is not sending logs on different host/port. 

**Steps to reproduce**
 avocado run  test.py --nrunner-status-server-uri <IP:PORT> --nrunner-status-server-disable-auto

**Expected behavior**
Log messages to be sent to server listening on <IP:PORT> socket

**Current behavior**
By default socket is created on localhost if --nrunner-status-server-uri option is set.
 <Server sockets=[<socket.socket fd=12, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 8888)>]>

**System information (please complete the following information):**
 - OS: `CentOS 7`
 - Avocado version: `Avocado 92.0
`
 - Avocado installation method: pip

**Comment by HalloweenCoder** [comment]
Thank you so much,
I looked into runner_nrunner.py plugin and identified a crude workaround fix as well. 

if --nrunner-status-server-uri  is set and not set to default
then status_uris = test_suite.config.get('nrunner.status_server_uri') 
else status_uri = self.status_server.uri 

```

226        task = nrunner.Task(runnable,
227                           identifier=test_id,
228                            known_runners=nrunner.RUNNERS_REGISTRY_PYTHON_CLASS,
229                            status_uris=[self.status_server.uri],
230                            job_id=job_id)
```

**Comment by clebergnu** [comment]
Hi @HalloweenCoder ,

Thanks for reporting this.

@richtja thanks for reproducing it.

I've sent a draft PR (#5481) that hopefully takes care of this.  Please let me know if the fix works for you.

If it does, I'll be adding a test to make sure this regression doesn't happen anymore.

**Comment by HalloweenCoder** [comment]
Hi @clebergnu, @richtja 

Thanks for a quick fix, I have verified it and its working as expected. 
No issues found as such. 

Can you kindly provide a patch for LTS 92.0 as well please? :)

**Comment by nirGNU** [comment]
Thank you @clebergnu and @richtja for addressing this issue.
I request to please backport this fix or at least provide an official patch for 92 LTS as well.

**Comment by clebergnu** [comment]
> Thank you @clebergnu and @richtja for addressing this issue. I request to please backport this fix or at least provide an official patch for 92 LTS as well.

@nirGNU see #5485 (still a draft, letting it go through CI first).

**Comment by nirGNU** [comment]
Hi @richtja and @clebergnu 
Thanks for a fix in 92 LTS, when can I expect this to be merged?

**Comment by clebergnu** [comment]
> Hi @richtja and @clebergnu Thanks for a fix in 92 LTS, when can I expect this to be merged?

PR https://github.com/avocado-framework/avocado/pull/5485 has already been merged into 92lts.  

The next 92.x release will include it.  BTW, how are you consuming Avocado 92.x? From the GIT branch? From a PIP package?

**Comment by nirGNU** [comment]
Wow !!
I hope I will get the next release soon :) I am using it through PIP package installer.

**Comment by nirGNU** [comment]
Hi  @clebergnu,
looks like human plugin is showing incorrect status with the correct URI support, tests are marked as Skipped even if test is Failed or Passed.

**Comment by nirGNU** [comment]
Hi @richtja and @clebergnu 
When can I expect a released hotfix with this fix as my major release depends on this fix. 
Can you please help?

**Comment by clebergnu** [comment]
> Hi @richtja and @clebergnu When can I expect a released hotfix 92.x with this fix as my major release depends on this fix. Can you please help?

Hi @nirGNU ,

We'll have a new LTS release within a day or two.  Thanks for checking in!

**Comment by nirGNU** [comment]
Hi @clebergnu ,

Great, that works, thank you 🙂

**Comment by clebergnu** [comment]
Hi @nirGNU , just an update here regarding the release.  I've found a few things (release related, no actual bugs in the code) that I need to address before cutting a new release.

I don't think it will take much longer, and I'm expecting a release Tomorrow.

**Comment by clebergnu** [comment]
After quite a lot of work, we have the release jobs passing: https://github.com/avocado-framework/avocado/actions/runs/3325764602

The 92.1 release should be out Tomorrow.

**Comment by clebergnu** [comment]
@nirGNU [Avocado 92.1](https://pypi.org/project/avocado-framework/92.1/) is out! Closing this issue now.

**Comment by nirGNU** [comment]
Hi Cleber,

Can you kindly point me to the 92.1 LTS change history?


Regards,
Niranjan.
