### ISSUE TITLE
network util support for network manager and wicked way of configuration

### ISSUE THREAD

**Issue by TasmiyaNalatwad** [avocado-framework/avocado#5478]
Network util support for network manager and wicked way of configuration

Before RHEL 9
1. Network utils supports legacy ifcfg way of network configuration
2. Path of the configuration file was '/etc/sysconfig/network-scripts'
3. Naming convention of the configuration would be 'ifcfg-NetworkName'

RHEL 9
1. Rhel 9 onwards network configurations are managed by NetworkManager (NMconnections) 
2. NetworkManager offers management through different ways. One of the way is through 'nmcli'
3. Path of the NMconnection file is '/etc/NetworkManager/system-connections'
4. Naming convention of the file would be 'NetworkName.nmconnection'

SUSE supports Wicked way of network configuration
1. SUSE use to support legacy ifcfg way of configuration, Now SUSE also supports Wicked way of configuration
2. Wicked Configuration file remains same with "ifcfg-NetworkName" but has just 3 parameters
IPADDR=''
BOOTPROTO=''
STARTMODE=''
 

Plan to add support for NetworkManager in avocado/utils 
1. Adding a condition check for RHEL 9 version for new NM connection configuration and keeping old configuration as it is to support old versions
2. Adding condition check for path where file is been stored
3. generating .nmconnection file using nmcli commands 
commands used :
nmcli c mod id {Network name} ipv4.method manual ipv4.address {ipaddr}/{netmask}
nmcli connection up {Network name}

4. For SUSE Wicked configuration support planning to add a condition check for creating a cfg file with just above given parameters.

@beraldoleal Requesting your inputs on the plan for adding NetworkManager support

**Comment by abdhaleegit** [comment]
@TasmiyaNalatwad thanks for the patch https://github.com/avocado-framework/avocado/pull/5480 @clebergnu @beraldoleal  Tasmiya has tried fixing this.. Please have a look

**Comment by richtja** [comment]
Solved in  #5480
