### ISSUE TITLE
avocado list output is empty

### ISSUE THREAD

**Issue by jie2xzhou** [avocado-framework/avocado#5487]
**Describe the bug**
avocado list output is empty

**Steps to reproduce**
avocado list

**Expected behavior**
INSTRUMENTED /test/avocado/examples/tests/abort.py:AbortTest.test
INSTRUMENTED /test/avocado/examples/tests/assert.py:Assert.test_assert_raises
INSTRUMENTED /test/avocado/examples/tests/assert.py:Assert.test_fails_to_raise
INSTRUMENTED /test/avocado/examples/tests/assets.py:Hello.test_gpg_signature

**Current behavior**
output is empty

**System information (please complete the following information):**
 - OS: Fedora release 36 (Thirty Six)
 - Avocado version: `avocado -v`
Avocado 98.0
 - Avocado installation method: pip, rpm, github ?
git clone https://github.com/avocado-framework/avocado.git
pip3 install avocado-framework

**Comment by richtja** [comment]
Hi @jie2xzhou, can you please check if you are able to list tests with `avocado list /test/avocado/examples/`, thanks.

**Comment by richtja** [comment]
Hi @jie2xzhou, is this issue still valid?

**Comment by jie2xzhou** [comment]
Hi,

>Hi @jie2xzhou, can you please check if you are able to list tests with avocado list /test/avocado/examples/, thanks.
Yes, I am able to list tests with avocado list /test/avocado/examples/
Thank you very much.

best regards,

________________________________________
