### ISSUE TITLE
Asset fetch() should consider different hash algorithms

### ISSUE THREAD

**Issue by danielhb** [avocado-framework/avocado#5496]
Hello,

In QEMU we download the Fedora 31 assets before the Avocado tests beforehand via a Makefile target [1]. This target will download the files using the default 'sha1' hash algorithm, creating a -CHECKSUM file for each, e.g.:

$ cat Fedora-Cloud-Base-31-1.9.ppc64le.qcow2-CHECKSUM 
sha1 9993dc28e7c49ceb52125f9513130dfe2ace026c

Problem is that the asset will not be found if the asset() caller is trying to use a different hash algorithm - in utils/asset.py, find_asset_file() will call _has_valid_hash(), which isn't considering the current value of self.algorithm. It'll make a direct comparison between the provided hash and the hash from the -CHECKSUM file. So, at this moment, QEMU is triggering a asset re-download each time 'make check-avocado'  is executed with a clean cache because it's trying to use a 'sha256' algorithm when issuing vmimage.get().

It would be good if Avocado is able to do an extra check to check if the algorithm in the stored CHECKSUM is the same as self.algorithm. If not, recalculate the hash of the asset to match the chosen algorithm. The overhead of re-calculating the hash will usually be smaller than the overhead of re-downloading an asset that was already available but with a different hash algorithm in CHECKSUM.

[1] https://gitlab.com/qemu-project/qemu/-/blob/master/tests/Makefile.include#L132

**Comment by richtja** [comment]
Hi @danielhb thanks for your proposal. This make sense to me and I think it is a valid for avocado. Also, it shouldn't be so hard to implement. I add this to our short term backlog with proper tags, so we wouldn't lose track of it.
