### ISSUE TITLE
Latest documentation refers to `max-parallel-tasks` command line parameter while previous says `nrunner-max-parallel-tasks`

### ISSUE THREAD

**Issue by willianrampazzo** [avocado-framework/avocado#5502]
**Describe the bug**
The fail-fast documentation at https://avocado-framework.readthedocs.io/en/latest/guides/user/chapters/introduction.html?highlight=max-parallel#interrupting-the-job-on-first-fail-failfast says:

```
To replicate the same behavior as the legacy runner, use --max-parallel-tasks=1 to limit the number of tasks executed in parallel:
```

and the command shown in the documentation uses the `--max-parallel-tasks=1`, but the command line help is still referring to the old nrunner parameter `--nrunner-max-parallel-tasks` and the `--max-parallel-tasks=1` does not work:

```
$ avocado run --failfast --max-parallel-tasks=1 /bin/true /bin/false /bin/true /bin/true
...
avocado run: error: unrecognized arguments: --max-parallel-tasks=1
```

**Steps to reproduce**
Run the command as stated in the documentation:

```
$ avocado run --failfast --max-parallel-tasks=1 /bin/true /bin/false /bin/true /bin/true
```

**Expected behavior**
The command completes successfully as in the documentation.

**Current behavior**
```
avocado run: error: unrecognized arguments: --max-parallel-tasks=1
```

**Additional information**
The command line parameter needs to be updated to reflect the correct parameter `--max-parallel-tasks`.

**Comment by willianrampazzo** [comment]
> Hi @willianrampazzo I am glad to see you in avocado project blush, can you please check which version are you using, because on the master this works fine and the [documentation for the version 98](https://avocado-framework.readthedocs.io/en/98.0/guides/user/chapters/introduction.html#interrupting-the-job-on-first-fail-failfast) uses `--nrunner-max-parallel-tasks`. So IMO everything is correct.

Hello @richtja :) , I see the out-of-sync information is between the `latest` documentation and `98.0`. I was using the `latest` documentation with the Avocado 98.0 version from pip:

```
$ avocado --version
Avocado 98.0
```

So, considering you mentioned that running the command from `master` worked with `--nrunner-max-parallel-tasks`, should we say the `latest` documentation is out of sync?

**Comment by richtja** [comment]
> So, considering you mentioned that running the command from `master` worked with `--nrunner-max-parallel-tasks`, should we say the `latest` documentation is out of sync?

The  `latest` documentation is build from master. So yes, sometimes it could be out of sync with the last avocado version, especially at the end of development cycle, which is now, because version 99 will be released this week.

**Comment by willianrampazzo** [comment]
Okay, let's wait for the release and see how the documentation sync goes. What do you think?

**Comment by richtja** [comment]
Hi @willianrampazzo I close this since, I discuss this with the avocado team and building the latest documentation from master is correct behavior and won't plan to change that. If you have any comments, please feel free to reopen the issue.
