### ISSUE TITLE
nrunner doesn't show why a test is skipped

### ISSUE THREAD

**Issue by philmd** [avocado-framework/avocado#5520]
**Describe the bug**
The new runner doesn't show the reason why a test is skipped using `from avocado import skip*`.

**Steps to reproduce**
- use a Darwin host
- build QEMU (I am using *v7.2.0-rc0*)
- Run avocado manually to use the _nrunner_: `avocado --show=app,console run --test-runner=nrunner  tests/avocado/`

**Expected behavior**
When a test is skipped, display the reason why it is skipped (as in the 'old' runner).

**Current behavior**
```
 (078/198) tests/avocado/machine_arm_mps2_an385.py:Mps2Machine.test_zephyr_5: PASS (0.62 s)
 (079/198) tests/avocado/machine_arm_n8x0.py:N8x0Machine.test_n800: STARTED
 (079/198) tests/avocado/machine_arm_n8x0.py:N8x0Machine.test_n800: SKIP
 (080/198) tests/avocado/machine_arm_n8x0.py:N8x0Machine.test_n810: STARTED
 (077/198) tests/avocado/machine_arm_mps2_an385.py:Mps2Machine.test_zephyr_4: PASS (2.21 s)
 (080/198) tests/avocado/machine_arm_n8x0.py:N8x0Machine.test_n810: SKIP
 (081/198) tests/avocado/machine_aspeed.py:AST1030Machine.test_ast1030_zephyros: STARTED
```

**System information (please complete the following information):**
 - OS: `lsb_release -a`
```
-bash: lsb_release: command not found
```

 - Avocado version: `avocado -v`
```
Avocado 88.1
```

 - Avocado installation method: pip, rpm, github ?
```
pip
```

**Comment by clebergnu** [comment]
This is a valid problem indeed under 88.1.  Current versions, such as 99.0, do display the reason associated with a SKIP, ERROR, etc.  Example:

```
JOB ID     : 296ea8dea9b6fc3b715c3f3635bd553fd3770472
JOB LOG    : /builds/cleber.gnu/qemu/build/tests/results/job-2022-11-15T00.08-296ea8d/job.log
 (001/193) tests/avocado/acpi-bits.py:AcpiBitsTest.test_acpi_smbios_bits: STARTED
 (001/193) tests/avocado/acpi-bits.py:AcpiBitsTest.test_acpi_smbios_bits:  SKIP: incorrect platform or dependencies (xorriso) not installed or running on GitLab
```

From https://gitlab.com/cleber.gnu/qemu/-/jobs/3322108726#L165

**Comment by philmd** [comment]
> This is a valid problem indeed under 88.1. Current versions, such as 99.0, do display the reason associated with a SKIP, ERROR

Ah thanks, I'll wait to update from QEMU then :)
