### ISSUE TITLE
Package dependency won't be fulfilled when re-running the test

### ISSUE THREAD

**Issue by Cypresslin** [avocado-framework/avocado#5523]
**Describe the bug**
When using the dependency defined for the test, if the target package was removed after the test, re-run the test won't get it installed again.

**Steps to reproduce**
Run the example test script:

    from avocado import Test

    class PassTest(Test):
        """
        :avocado: dependency={"type": "package", "name": "hello"}
        """
        def test(self):
            """
            A success test
            """

With the following command:

    avocado run example.py; hello
    sudo apt remove --purge -y hello &> /dev/null
    avocado run example.py; hello

**Expected behavior**
The hello package can be installed again, so the test dependency can be fulfilled.

**Current behavior**

    $ avocado run example.py; hello
    JOB ID     : 37a5eaab97c49a7a7390f69caaa7ab53d49d720a
    JOB LOG    : /home/ubuntu/avocado/job-results/job-2022-11-18T09.17-37a5eaa/job.log
     (1/1) example.py:PassTest.test: STARTED
     (1/1) example.py:PassTest.test: PASS (0.02 s)
    RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
    JOB TIME   : 12.97 s
    Hello, world!
    $ sudo apt remove --purge -y hello &> /dev/null
    $ avocado run example.py; hello
    JOB ID     : 6244984c07ef81de30ec0e98fe8e19fa87978da9
    JOB LOG    : /home/ubuntu/avocado/job-results/job-2022-11-18T09.28-6244984/job.log
     (1/1) example.py:PassTest.test: STARTED
     (1/1) example.py:PassTest.test: PASS (0.02 s)
    RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
    JOB TIME   : 1.80 s
    -bash: /usr/bin/hello: No such file or directory

**System information (please complete the following information):**
 - OS: Ubuntu Jammy
 - Avocado version: Avocado 99.0
 - Avocado installation method: pip, rpm, github ? github source code (head 892342236b) with setup.py

**Comment by richtja** [comment]
Hi @Cypresslin I create #5535 to track cache disable feature. And I consider this issue solved, if you will have any questions or comments, please feel free to reopen it.
