### ISSUE TITLE
Job Timeout: sub-second granularity

### ISSUE THREAD

**Issue by clebergnu** [avocado-framework/avocado#553]
@ruda take a look at the following avocado execution:

```
./scripts/avocado run sleeptest -m examples/tests/sleeptest.py.data/sleeptest.yaml --job-timeout 1s
JOB ID     : 9b054d39ef2086b25fe194780991372b40ff4816
JOB LOG    : /home/cleber/avocado/job-results/job-2015-04-15T19.26-9b054d3/job.log
JOB HTML   : /home/cleber/avocado/job-results/job-2015-04-15T19.26-9b054d3/html/results.html
TESTS      : 4
(1/4) sleeptest.py: PASS (0.50 s)
(2/4) sleeptest.py.1: PASS (1.00 s)
(3/4) sleeptest.py.2: SKIP
(4/4) sleeptest.py.3: SKIP
PASS       : 2
ERROR      : 0
FAIL       : 0
SKIP       : 2
WARN       : 0
INTERRUPT  : 0
TIME       : 1.52 s
```

IMHO, for correctness, test 2/4 should not have finished as a `PASS`, but it should have been interrupted.

**Comment by ruda** [comment]
I would consider as a "corner case", in the sense that we should expect to use, for the job timeout, values greater than 1 for testing things that takes more than 1 second. So 1/1 is a corner case.

If we decrease the values of `first`/`step` inside `run_tests`, for the function `wait_for()` (say, first=0.01, step = 0.001), it may turn back the unstable behavior that we've had once in avocado.

So I  recommend to turn this issue into `won't fix` and document  about it in avocado (in the command line? man page?).
