### ISSUE TITLE
Avocado support for python 3.11 on macOS

### ISSUE THREAD

**Issue by richtja** [avocado-framework/avocado#5534]
**Is your feature request related to a problem? Please describe.**
Some optional plugins (resultsdb) are not able to install with easy_install on macOS with python 3.11 because of issues with package compatibility. We temporarily removed the macOS with python 3.11 from our CI to run python 3.11 checks on other systems, but we need to investigate this issue and enable the checks again.

python 3.11 support in #5510

**Comment by clebergnu** [comment]
This has been resolved in f6a5150c7de0677963650bea47bc654b7279d54b .
