### ISSUE TITLE
Test variants all have the same name in results.xml output

### ISSUE THREAD

**Issue by verdog** [avocado-framework/avocado#5589]
**Describe the bug**
When test variants are generated (I am using the yaml to mux plugin), the test names are distinct in the avocado terminal output:
```
 (19/52) tests.py:ZmqnetTest.test_SubsetCreationTest;run-debug-yes-60a2: STARTED
 (20/52) tests.py:ZmqnetTest.test_SubsetCreationTest;run-debug-no-f272: STARTED
```

But in the resulting `results.xml`, they have the same name:
```xml
<testcase classname="<unknown>" file="tests.py" name="tests.py:ZmqnetTest.test_SubsetCommandTest" time="8.702"/>
<testcase classname="<unknown>" file="tests.py" name="tests.py:ZmqnetTest.test_SubsetCommandTest" time="8.754"/>
```

**Steps to reproduce**
Generate some test variants, run tests, and check `results.xml`.

**Expected behavior**
The name field in `results.xml` should be unique.

**Current behavior**
The name fields in `results.xml` for each variant are the same.

**System information**
 - OS:
```
LSB Version:    n/a
Distributor ID: SUSE
Description:    SUSE Linux Enterprise Server 15 SP3
Release:        15.3
Codename:       n/a
```
 - Avocado version: **100.0**
 - Avocado installation method: **pip in a venv**

**Additional information**
This behavior results in confusing in some test result reporting tools. Tests are merged and the results of the duplicate tests are lost.

**Comment by richtja** [comment]
Hi @verdog, thanks for reporting this. I create a fix #5592 can you, please, test if it solves your problem, thanks.

**Comment by verdog** [comment]
Thanks for the speedy fix! I don't really know how to test a development version of avocado (I always just get it from pip). I'll trust your and @clebergnu's judgements and assume it's fixed and keep my eye out in 101. Thanks again!

**Comment by clebergnu** [comment]
> Thanks for the speedy fix! I don't really know how to test a development version of avocado (I always just get it from pip). I'll trust your and @clebergnu's judgements and assume it's fixed and keep my eye out in 101. Thanks again!

Hi @verdog, you are very welcome.  It should be easy to test the development versions of avocado.  In particular, to test the Avocado right after this issue was fixed (hopefully), you could run:

```
pip install git+https://github.com/avocado-framework/avocado@c0f5ce594bfa65c36d9c0d00d96bfa8db55446ff#egg=avocado_framework
```

You'd also need to install the plugin varianter you are using (I'm assuming it's `yaml_to_mux`):

```
pip install git+https://github.com/avocado-framework/avocado@c0f5ce594bfa65c36d9c0d00d96bfa8db55446ff#egg=avocado_framework_plugin_varianter_yaml_to_mux&subdirectory=optional_plugins/varianter_yaml_to_mux
```

It'd be helpful to get an ACK from your side too.

**Comment by verdog** [comment]
Oh, I had no idea it was that easy. Thanks for the tip.

Unfortunately all of the machines I use have Python 3.6 or less, so when I try to install the master, I get
```
ERROR: Package 'avocado-framework' requires a different Python: 3.6.8 not in '>=3.7'
```

(I don't have root on these machines so I can't change the installed version)
