### ISSUE TITLE
Avocado config settings seem to be ignored with Avocado>=100

### ISSUE THREAD

**Issue by eskultety** [avocado-framework/avocado#5603]
**Describe the bug**
Starting with Avocado 100.0 the avocado.config file seems to be ignored with executions. Here's a sample config file we use in libvirt:
```
$ cat avocado.config
[run]
test_runner=nrunner

[nrunner]
max_parallel_tasks=1
```
Given the config ^above, Avocado should ignore task parallelism completely.

**Steps to reproduce**
1. Use the config file above
2. run  `avocado --config avocado.config run  /bin/true /bin/false /bin/true`
```
JOB ID     : 1d94833cee40b55da296cbb4b79d6ac63d737762
JOB LOG    : /root/avocado/job-results/job-2023-02-07T13.12-1d94833/job.log
(2/3) /bin/false: STARTED
(2/3) /bin/false:  FAIL (0.01 s)
(3/3) /bin/true: STARTED
(1/3) /bin/true: STARTED
(3/3) /bin/true:  PASS (0.01 s)
(1/3) /bin/true:  PASS (0.01 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 1.03 s
```
3. Seems like `max_parallel_tasks=1` was ignored completely
4. Now run `avocado --config avocado.config run --max-parallel-tasks 1  /bin/true /bin/false /bin/true`
```
JOB ID     : 78998afd4c53c6264d13fbabfb61622b1cc5b495
JOB LOG    : /root/avocado/job-results/job-2023-02-07T13.21-78998af/job.log
 (1/3) /bin/true: STARTED
 (1/3) /bin/true:  PASS (0.01 s)
 (2/3) /bin/false: STARTED
 (2/3) /bin/false:  FAIL (0.01 s)
 (3/3) /bin/true: STARTED
 (3/3) /bin/true:  PASS (0.01 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 1.26 s

Test summary:
/bin/false: FAIL
```

**Expected behavior**
Unless `avocado.config` has been deprecated, it should honor the setting and run all tasks in sequence, just as if `--max-parallel-tasks 1` was passed explicitly

**System information (please complete the following information):**
- OS: fedora 37 
- Avocado version: 100.0+
 - Avocado installation method: pip

**Additional information**
The fact that the config file seems to be ignored by the runner means we cannot upgrade to v100 even with https://github.com/avocado-framework/avocado/pull/5567 in place as our current test suite isn't independent and tests impact each other and hence must be run in sequence.

**Comment by richtja** [comment]
Hi @eskultety it is because we drop `nrunner` prefix in 8db957992761c0087303224bdc0ecf798a401fb7 so the `nrunner.max_parallel_tasks` was changed to `run.max_parallel_tasks`.

config which should work for you:
```
[run]
max_parallel_tasks=1
```

Can you please check if it works for you? Thanks.

**Comment by eskultety** [comment]
> ```
> [run]
> max_parallel_tasks=1
> ```
> 
> Can you please check if it works for you? Thanks.

Running only a subset of the test suite seems to support your argument, let me run the whole thing and I'll come back whether this can be closed or not, thanks.

**Comment by eskultety** [comment]
@richtja is there a way to preserve compatibility with older Avocados in this regards, IOW, is this going to work reliably?
```
[run]
test_runner=nrunner
max_parallel_tasks=1

[nrunner]
max_parallel_tasks=1
```

**Comment by richtja** [comment]
@eskultety AFAICT this shouldn't be a problem, but we don't support it and we don't test it. Therefore, I can't ensure it.

**Comment by richtja** [comment]
Thanks, for the test. I will close this, but if you find any other problems with this, feel free to reopen it.
