### ISSUE TITLE
Add Zstandard support in avocado.utils.archive

### ISSUE THREAD

**Issue by philmd** [avocado-framework/avocado#5609]
**Is your feature request related to a problem? Please describe.**
The QEMU project uses the Avocado framework, in particular the `avocado.utils.archive` class.
This class support various compression format, but not the _Zstandard_ one.

**Describe the solution you'd like**
Native support of _Zstandard_ in `avocado.utils.archive`.

**Describe alternatives you've considered**
We call `zstd` directly:
https://lore.kernel.org/qemu-devel/20230207204433.752020-1-alex.bennee@linaro.org/

**Comment by clebergnu** [comment]
Hi @philmd,

Thanks for creating this issue about this QEMU requirement... real world use cases are my personal favorite kind of issues.

This shouldn't be hard (as long as we don't want to re-implement the standard within Avocado in pure Python), but it will require a bit of refactor in the `avocado.utils.archive` module to deal with the possibly missing tools doing the actual hard work.

Just to get things going, I've sent #5611, and I'll follow up soon with the next steps.
