### ISSUE TITLE
Avocado crashes randomly on `get_path_mount_point`

### ISSUE THREAD

**Issue by pevogam** [avocado-framework/avocado#5620]
**Describe the bug**
In some cases (so far seems to be random and a race condition) avocado (101) runs would crash with `FileNotFoundError: [Errno 2] No such file or directory`.

**Steps to reproduce**
Run Avocado VT tests is the closest I can suggest as an attempt to reproduce this.

**Expected behavior**
No crashing, the test run must complete as normal.

**Current behavior**
Some test runs complete as normal while some do not (same tests and test sets).

**System information (please complete the following information):**
 - OS: `lsb_release -a`

LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 36 (Thirty Six)
Release:	36
Codename:	ThirtySix

 - Avocado version: `avocado -v`

Avocado 101.0

 - Avocado installation method: pip, rpm, github ?
 
RPM

**Additional information**
This is the backtrace I am getting:
```
Avocado crashed: FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):

  File "/usr/lib/python3.10/site-packages/avocado/core/job.py", line 632, in run_tests
    summary |= suite.run(self)

  File "/usr/lib/python3.10/site-packages/avocado/core/suite.py", line 313, in run
    return self.runner.run_suite(job, self)

  File "/usr/lib/python3.10/site-packages/avocado_i2n/runner.py", line 379, in run_suite
    loop.run_until_complete(asyncio.wait_for(asyncio.gather(*to_traverse),

  File "/usr/lib64/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()

  File "/usr/lib64/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut

  File "/usr/lib/python3.10/site-packages/avocado_i2n/runner.py", line 301, in run_traversal
    await self._traverse_test_node(graph, next, params, slot)

  File "/usr/lib/python3.10/site-packages/avocado_i2n/runner.py", line 496, in _traverse_test_node
    status = await self.run_test_node(test_node)

  File "/usr/lib/python3.10/site-packages/avocado_i2n/runner.py", line 180, in run_test_node
    await self.run_test(self.job, node)

  File "/usr/lib/python3.10/site-packages/avocado_i2n/runner.py", line 132, in run_test
    await Worker(state_machine=TaskStateMachine([task], self.status_repo),

  File "/usr/lib/python3.10/site-packages/avocado/core/task/statemachine.py", line 415, in run
    await self.start()

  File "/usr/lib/python3.10/site-packages/avocado/core/task/statemachine.py", line 318, in start
    start_ok = await self._spawner.spawn_task(runtime_task)

  File "/usr/lib/python3.10/site-packages/avocado/plugins/spawners/lxc.py", line 97, in wrapper
    await fn(self, runtime_task)

  File "/usr/lib/python3.10/site-packages/avocado/plugins/spawners/lxc.py", line 193, in spawn_task
    self.create_task_output_dir(runtime_task)

  File "/usr/lib/python3.10/site-packages/avocado/plugins/spawners/lxc.py", line 267, in create_task_output_dir
    output_dir_path = self.task_output_dir(runtime_task)

  File "/usr/lib/python3.10/site-packages/avocado/core/spawners/common.py", line 38, in task_output_dir
    self._job.test_results_path, runtime_task.task.identifier.str_filesystem

  File "/usr/lib/python3.10/site-packages/avocado/core/test_id.py", line 73, in str_filesystem
    test_id_fs = astring.string_to_safe_path(test_id)

  File "/usr/lib/python3.10/site-packages/avocado/utils/astring.py", line 272, in string_to_safe_path
    max_length = path.get_max_file_name_length(input_str)

  File "/usr/lib/python3.10/site-packages/avocado/utils/path.py", line 256, in get_max_file_name_length
    mount_point = get_path_mount_point(path)

  File "/usr/lib/python3.10/site-packages/avocado/utils/path.py", line 240, in get_path_mount_point
    path = os.path.abspath(path)

  File "/usr/lib64/python3.10/posixpath.py", line 383, in abspath
    cwd = os.getcwd()

FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by clebergnu** [comment]
Hi @pevogam,

Thanks for reporting this.  I was able to reproduce the basic premise of this crash like this:

1. Create a directory, say /tmp/foo
2. Change into that directory
3. Run `python3 -c 'import os; os.rmdir("/tmp/foo"); os.getcwd()'`

Basically, it seems that a directory (a task output dir?) is being attempted to being created in a location that gets deleted before the creation completes.  Since I don't remember running into such race conditions on the regular spawners, do you see any possibility of the lxc/avocado-vt set up being prone to that?

**Comment by pevogam** [comment]
Hi @clebergnu and thanks for checking this.

> Thanks for reporting this. I was able to reproduce the basic premise of this crash like this:
> 
>     1. Create a directory, say /tmp/foo
> 
>     2. Change into that directory
> 
>     3. Run `python3 -c 'import os; os.rmdir("/tmp/foo"); os.getcwd()'`
> 
> 
> Basically, it seems that a directory (a task output dir?) is being attempted to being created in a location that gets deleted before the creation completes. Since I don't remember running into such race conditions on the regular spawners, do you see any possibility of the lxc/avocado-vt set up being prone to that?

Hmmm the thing is that the way the LXC spawner handles this is completely copied and outsourced to the way avocado does it in all other spawners:
```python
    async def spawn_task(self, runtime_task):
        self.create_task_output_dir(runtime_task)
        task = runtime_task.task
        #...

    def create_task_output_dir(self, runtime_task):
        output_dir_path = self.task_output_dir(runtime_task)
        runtime_task.task.setup_output_dir(output_dir_path)
```
so any potential deletions or the way the task output directory is created must be as default as it gets. I wonder if the container isolation could play some role here but (correct me if I am wrong) this task output directory is located outside of the containers and on the host machine. In any case I would suggest one of two things:

1) We wait to see if this can be reproduced in any other way and if not we can close the issue. As it happens I haven't also gotten these race conditions in the recent weeks so I suspect might already be indirectly fixed or reduced the chance of.
2) We analyze this after merging the LXC spawner branch so that you can have full reproducibility.

What do you think?

**Comment by clebergnu** [comment]
> Hi @clebergnu and thanks for checking this.
> 
> > Thanks for reporting this. I was able to reproduce the basic premise of this crash like this:
> > ```
> > 1. Create a directory, say /tmp/foo
> > 
> > 2. Change into that directory
> > 
> > 3. Run `python3 -c 'import os; os.rmdir("/tmp/foo"); os.getcwd()'`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Basically, it seems that a directory (a task output dir?) is being attempted to being created in a location that gets deleted before the creation completes. Since I don't remember running into such race conditions on the regular spawners, do you see any possibility of the lxc/avocado-vt set up being prone to that?
> 
> Hmmm the thing is that the way the LXC spawner handles this is completely copied and outsourced to the way avocado does it in all other spawners:
> 
> ```python
>     async def spawn_task(self, runtime_task):
>         self.create_task_output_dir(runtime_task)
>         task = runtime_task.task
>         #...
> 
>     def create_task_output_dir(self, runtime_task):
>         output_dir_path = self.task_output_dir(runtime_task)
>         runtime_task.task.setup_output_dir(output_dir_path)
> ```
> 
> so any potential deletions or the way the task output directory is created must be as default as it gets. I wonder if the container isolation could play some role here but (correct me if I am wrong) this task output directory is located outside of the containers and on the host machine. In any case I would suggest one of two things:
> 
> 1. We wait to see if this can be reproduced in any other way and if not we can close the issue. As it happens I haven't also gotten these race conditions in the recent weeks so I suspect might already be indirectly fixed or reduced the chance of.
> 2. We analyze this after merging the LXC spawner branch so that you can have full reproducibility.
> 
> What do you think?

I'm fine with merging this, that is, let's go with 2.  We just need to make sure CI is passing in the LXC Spawner PR.

**Comment by pevogam** [comment]
> > 2\. We analyze this after merging the LXC spawner branch so that you can have full reproducibility.
> > 
> > What do you think?
> 
> I'm fine with merging this, that is, let's go with 2. We just need to make sure CI is passing in the LXC Spawner PR.

Yes see my last comment [there](https://github.com/avocado-framework/avocado/pull/4158#issuecomment-1480675651) so that we don't kidnap this topic here from my last steps in this direction and request for some feedback.

**Comment by pevogam** [comment]
I haven't seen this issue reappear for quite a while now after merging the original LXC spawner pull request and the follow up slight fix pull request of its results directory, all while using the most recent 102.0 release, hence I suggest we close this as no longer relevant.
