### ISSUE TITLE
Ability to generate tests at runtime

### ISSUE THREAD

**Issue by verdog** [avocado-framework/avocado#5636]
We use avocado to test a command line debugger. Our current approach is to input a batch file of commands to the debugger, run them, and check the output. That makes up one avocado test.

One drawback of this approach is that if a single command in the batch file fails, the whole test case fails, and it's hard to determine exactly which command among the many in the batch file failed.

We would like to increase the granularity of our tests. We want to map each individual debugger command to a single avocado test to make it easier to pinpoint/report individual command failures.

We would also like to keep the nice aspects of the batch file approach. One nice aspect is that the input files are just text files consisting of commands and their expected results. This format is easy to create and easier to read than say, python code.

**Describe the solution you'd like**
I would like to be able to write a test suite that reads these batch files and then generates an avocado test for each individual command in the batch file. To do this, I need some way to register avocado tests at runtime after the test suite starts running.

**Comment by richtja** [comment]
Hi @verdog, this is an interesting idea. Have you thought about creating a batch file resolver which would resolve your commands into the avocado exec-tests? https://avocado-framework.readthedocs.io/en/latest/guides/contributor/chapters/runners.html#finding-tests

You can find and basic example of resolver in:
 https://github.com/avocado-framework/avocado/blob/master/examples/plugins/tests/magic/avocado_magic/resolver.py

or more complicated example for exec-tests:
https://github.com/avocado-framework/avocado/blob/master/avocado/plugins/resolvers.py#L34
