### ISSUE TITLE
Loader for avocado-instrumented can fail to load module from correct path

### ISSUE THREAD

**Issue by clebergnu** [avocado-framework/avocado#5686]
**Describe the bug**
I've experienced ERRORs when trying to run tests such as `selftests/functional/plugin/spawners/lxc.py:LXCSpawnerTest.test_slots_cache_custom` when the system has a `python3-lxc` package installed.  Without the package installed, the ERROR was not observed.

Based on my experiments, `importlib.import_module()` is returning the module from the `python3-lxc` package, even though the absolute path containing `selftests/functional/plugin/spawners` is added as the first entry into the path list.  The behavior of `importlib.import_module()` should, AFAICT, be similar to:

```
$ PYTHONPATH=/home/cleber/src/avocado/avocado/selftests/functional/plugin/spawners:$PYTHONPATH python3 -c 'import lxc; print(lxc)'
<module 'lxc' from '/home/cleber/src/avocado/avocado/selftests/functional/plugin/spawners/lxc.py'>
```

But instead, it's importing `<module 'lxc' from '/usr/lib64/python3.11/site-packages/lxc/__init__.py'>`.

**Steps to reproduce**
1. Have an avocado development environment (`make develop`)
2. Install `python3-lxc`
3. Run `avocado run selftests/functional/plugin/spawners/lxc.py:LXCSpawnerTest.test_slots_cache_custom`

**Expected behavior**

A successful load of the test module (and thus test class and method):

```
JOB ID     : 82adce520e07cdab7c890463ce66aa4339e14873
JOB LOG    : /root/avocado/job-results/job-2023-05-23T16.44-82adce5/job.log
 (1/1) selftests/functional/plugin/spawners/lxc.py:LXCSpawnerTest.test_slots_cache_custom: STARTED
 (1/1) selftests/functional/plugin/spawners/lxc.py:LXCSpawnerTest.test_slots_cache_custom: PASS (0.10 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado/job-results/job-2023-05-23T16.44-82adce5/results.html
JOB TIME   : 0.78 s
```

**Current behavior**
```
JOB ID     : f6fa9a195fb3546c702dde3f8d31c32c2c291b48
JOB LOG    : /home/cleber/avocado/job-results/job-2023-05-23T12.45-f6fa9a1/job.log
 (1/1) selftests/functional/plugin/spawners/lxc.py:LXCSpawnerTest.test_slots_cache_custom: STARTED
 (1/1) selftests/functional/plugin/spawners/lxc.py:LXCSpawnerTest.test_slots_cache_custom:  ERROR: 'str' object is not callable (0.01 s)
RESULTS    : PASS 0 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/cleber/avocado/job-results/job-2023-05-23T12.45-f6fa9a1/results.html
JOB TIME   : 2.77 s

Test summary:
selftests/functional/plugin/spawners/lxc.py:LXCSpawnerTest.test_slots_cache_custom: ERROR
```

With the traceback containing:

```
[stderr] Traceback (most recent call last):
[stderr]   File "/home/cleber/src/avocado/avocado/avocado/plugins/runners/avocado_instrumented.py", line 101, in _run_avocado
[stderr]     instance = loader.load_test(test_factory)
[stderr]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[stderr]   File "/home/cleber/src/avocado/avocado/avocado/core/utils/loader.py", line 66, in load_test
[stderr]     test_instance = test_class(**test_parameters)
[stderr]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[stderr] TypeError: 'str' object is not callable
```

**System information (please complete the following information):**
 - OS: ```LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 37 (Thirty Seven)
Release:	37
Codename:	ThirtySeven```
 - Avocado version: 77e656d11c8462c6a2c06d1092e751233c4e911c
 - Avocado installation method: `make develop`

**Comment by richtja** [comment]
Hi @clebergnu, I can confirm that I was able to reproduce it.

I also found out that this issue doesn't occur when virtual environment is used. I am using a virtual environment created by `pyenv` during my development and I wasn't able to reproduce it there.
