### ISSUE TITLE
Resolver plugins can't report hard errors

### ISSUE THREAD

**Issue by dgibson** [avocado-framework/avocado#5710]
**Describe the bug**
This is related to #5644, but I realized there's a more fundamental issue here.

Resolver plugins have no way to report "this reference looks like it belongs to me, but something went wrong".   Instead, any failure in the resolver whether it's `NOTFOUND` or `ERROR` simply results in moving onto the next resolver type.  If they all fail, we simply don't resolve, and we get the fairly cryptic message noted in #5644, which has been improved somewhat by the change there.

Except.. there's a much worse failure mode: if we resolve multiple references (including a directory) we don't get *any* error as long as some of them resolve.  That means we can have a badly damaged test file and it will silently be ignored, as long as there is some other test which resolves.  For avocado-instrumented we can't do much better, because there isn't a good way to distinguish between a Python file that's supposed to contain avocado-instrumented tests but is broken and some unrelated python file.  However, other resolvers might have the means to be confident that a file is for them, but have detected an unrecoverable error even trying to resolve.  In this case the user should get an error message, even if other tests can be resolved.
**System information (please complete the following information):**
 - Avocado version: 101.0

**Additional information**

I think what we want here is for `Resolver.resolve` not to catch and (mostly) ignore exceptions from resolver plugins.  If we get an exception here something is wrong that the user should know about: maybe it's a problem in their test file, which they definitely want to know about, or it's a bug in the resolver plugin, which should probably be reported as well.

This does mean that resolver plugins need to be careful and catch their own exceptions up until the last point they could return `NOTFOUND`.  That's a little extra work, but I think allowing resolvers to be sloppy in this way ultimately causes more problems.

**Comment by clebergnu** [comment]
Hi David,

You certainly do have some good points here especially about:
* How error reporting can be more explicit and more granular
* How the "policy" on what to do under `ERROR`/`NOTFOUND` may be influenced by Resolver plugins 

But, one thing I can not fully understand is:

_"However, other resolvers might have the means to be confident that a file is for them, but have detected an unrecoverable error even trying to resolve."_

IMO, if the resolver *has* the confidence, it should already have all the information needed to return a `SUCCESS`.  The amount of things that can go wrong between the point where the confidence level is reached and the response is returned is very low IMO.

Let me know if this matches what you're thinking about.  Let's say we have a collection of files under `tests/`, and every single file named as a three-digit incremental number (`001`, `002`, etc) MUST be a test.  The situation changes if it's assumed that each of these files must contain one or more tests.

If `tests/001` *is* a test, then there is not much else to do about its resolution.  Trying to go further, would probably get closer to actually running it, which should be discouraged.

Now if `tests/001` must *contain* one or more tests, then indeed further work must be done.

This is somehow connected with the "directory resolution". It's interesting to note the behavior of `avocado run directory-with-tests` and `avocado run directory-with-tests/*` (assuming shell globbing expansion) can be quite different.

IIUC, you're looking for a way to explicitly state that a list of paths/files MUST contain tests, and any failure to identify those tests should be handled much more explicitly.  Does that make sense?

**Comment by dgibson** [comment]
> Hi David,
> 
> You certainly do have some good points here especially about:
> 
>     * How error reporting can be more explicit and more granular
> 
>     * How the "policy" on what to do under `ERROR`/`NOTFOUND` may be influenced by Resolver plugins
> 
> 
> But, one thing I can not fully understand is:
> 
> _"However, other resolvers might have the means to be confident that a file is for them, but have detected an unrecoverable error even trying to resolve."_
> 
> IMO, if the resolver _has_ the confidence, it should already have all the information needed to return a `SUCCESS`. The amount of things that can go wrong between the point where the confidence level is reached and the response is returned is very low IMO.

That might be true for the existing resolvers, but I don't think it's true in general.  So in my draft 'avocado-classless' resolver, I use a special `#!` line to indicate that the file contains classless tests, rather than being just any Python file.  As soon as we see that `#!` line we can be confident that it should contain tests for us.  But if the module fails to load, we can't determine what those tests are.  We neither want to go onto other resolvrers - we know it's for us - nor do we want to just ignore the file and carry on without informing the user, because it's likely that we are silently ignoring tests in that case.

The problem isn't specific to that classless resolver though.  If we had runner/resolver plugins that took tests described in some structured format we can have the same issue: we can be confident early that the file is meant for us based on extension, magic numbers or the like, but if we get an error while parsing the resolver can't succeed, and it shouldn't fail silently.

> Let me know if this matches what you're thinking about. Let's say we have a collection of files under `tests/`, and every single file named as a three-digit incremental number (`001`, `002`, etc) MUST be a test. The situation changes if it's assumed that each of these files must contain one or more tests.
> 
> If `tests/001` _is_ a test, then there is not much else to do about its resolution. Trying to go further, would probably get closer to actually running it, which should be discouraged.
> 
> Now if `tests/001` must _contain_ one or more tests, then indeed further work must be done.
> 
> This is somehow connected with the "directory resolution". It's interesting to note the behavior of `avocado run directory-with-tests` and `avocado run directory-with-tests/*` (assuming shell globbing expansion) can be quite different.
> 
> IIUC, you're looking for a way to explicitly state that a list of paths/files MUST contain tests, and any failure to identify those tests should be handled much more explicitly. Does that make sense?

No, it's more than that.  I want the resolver to be able to say "this looks like it's for me, but something went wrong and I can't complete resolution".  This is a situation the user wants to know about, so they can fix their tests.
