### ISSUE TITLE
Status server is not disabled on --nrunner-status-server-disable-auto and --nrunner-status-server-uri 

### ISSUE THREAD

**Issue by nirGNU** [avocado-framework/avocado#5740]
**Describe the bug**
When --nrunner-status-server-disable-auto and --nrunner-status-server-uri <IP:PORT> is given then also Avocado starts a local status server with default values of --nrunner-status-server-listen.

This server is not getting any messages and statuses this can be disabled completely.

This issue is blocking execution of two avocado instances on the same host with status server URI because Avocado fails in binding the default --nrunner-status-server-listen even if default status server is not required.
 
**Steps to reproduce**
avocado run /bin/true  --nrunner-status-server-disable-auto --nrunner-status-server-uri 127.0.0.1:9999

**Expected behavior**
status server should not be started on default socket in nrunner.status_server_listen config  if --nrunner-status-server-disable-auto and  --nrunner-status-server-uri <IP:PORT> is given

**Current behavior**
A status server is started with default config, This server is not getting any messages and statuses this can be disabled completely.

**System information (please complete the following information):**
 - OS: `lsb_release -a`
```
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: Rocky
Description:    Rocky Linux release 8.5 (Green Obsidian)
Release:        8.5
Codename:       GreenObsidian

```
 - Avocado version: `avocado -v` : **Avocado 92.1**
 
 - Avocado installation method: pip, rpm, github : **PIP**

**Comment by richtja** [comment]
Hi @nirGNU, thank you for reporting this, and sorry for late reply. I can confirm that we have this problem even on master branch. I will prepare a fix which will be part of 103lts version.
