### ISSUE TITLE
avocado.core.exceptions.TestError: Unable to receive test's early-status in 60s, something wrong happened probably in the avocado framework.

### ISSUE THREAD

**Issue by yangzeyu8** [avocado-framework/avocado#5764]
errno=, stdout=/usr/local/lib/python3.9/site-packages/avocado_framework_plugin_varianter_yaml_to_mux-77.0-py3.9.egg/avocado_varianter_yaml_to_mux/__init__.py:168: SyntaxWarning: "is not" with a literal. Did you mean "!="?
/usr/local/lib/python3.9/site-packages/avocado_framework_plugin_varianter_yaml_to_mux-77.0-py3.9.egg/avocado_varianter_yaml_to_mux/__init__.py:168: SyntaxWarning: "is not" with a literal. Did you mean "!="?
Error running method "configure" of plugin "sysinfo": Key sysinfodir already registered in section sysinfo.collect
/usr/local/lib/python3.9/site-packages/avocado_framework-77.0-py3.9.egg/avocado/plugins/run.py:284: FutureWarning: The following arguments will be changed to boolean soon: sysinfo, output-check, failfast, keep-tmp and ignore-missing-references.
  warnings.warn("The following arguments will be changed to boolean soon: "

Avocado crashed: TestError: Unable to receive test's early-status in 60s, something wrong happened probably in the avocado framework.
Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/avocado_framework-77.0-py3.9.egg/avocado/core/job.py", line 610, in run_tests
    summary = self.test_runner.run_suite(self,

  File "/usr/local/lib/python3.9/site-packages/avocado_framework-77.0-py3.9.egg/avocado/plugins/runner.py", line 423, in run_suite
    if not self.run_test(job, result, test_factory, queue, summary,

  File "/usr/local/lib/python3.9/site-packages/avocado_framework-77.0-py3.9.egg/avocado/plugins/runner.py", line 187, in run_test
    test_status.wait_for_early_status(proc, 60)

  File "/usr/local/lib/python3.9/site-packages/avocado_framework-77.0-py3.9.egg/avocado/core/runner.py", line 148, in wait_for_early_status
    raise exceptions.TestError(msg)

avocado.core.exceptions.TestError: Unable to receive test's early-status in 60s, something wrong happened probably in the avocado framework.

**Comment by richtja** [comment]
Hi @yangzeyu8, thank you for reporting this. IIUIC you use avocado version 77.0 This has been deprecated and we no longer support it, now we are at version 102. Can you please upgrade your version and let me know if the problem persists? Thank you.

**Comment by yangzeyu8** [comment]
> 嗨 @扬泽宇8，谢谢你的报道。IIUIC您使用鳄梨版本77.0这已被弃用，我们不再支持它，现在我们的版本为102。你能升级你的版本吗，如果问题仍然存在，请告诉我？谢谢你。

Thank you. I also came to know that version 77 is a deprecated version. We will plan to upgrade to the latest version later. Where can I see the new features of the new version?

**Comment by richtja** [comment]
You can check our [release notes](https://avocado-framework.readthedocs.io/en/latest/releases/index.html), which describes changes between each version. Avocado change a lot from version 77, the biggest change is that we completely change the way how avocado resolves and run tests. This change brings many features like parallel run or higher isolation of test environment, but it might make your tests incompatible with newer avocado. More info in [here](https://avocado-framework.readthedocs.io/en/latest/guides/contributor/chapters/runners.html).

Also, if you plan to upgrade avocado to newer version, we are just working on new LTS release which should be good choice for the update, because we declare long stability support with the version. We plan to do the [LTS release](https://github.com/avocado-framework/avocado/discussions/5729) in next two months.

**Comment by yangzeyu8** [comment]
> You can check our [release notes](https://avocado-framework.readthedocs.io/en/latest/releases/index.html), which describes changes between each version. Avocado change a lot from version 77, the biggest change is that we completely change the way how avocado resolves and run tests. This change brings many features like parallel run or higher isolation of test environment, but it might make your tests incompatible with newer avocado. More info in [here](https://avocado-framework.readthedocs.io/en/latest/guides/contributor/chapters/runners.html).
> 
> Also, if you plan to upgrade avocado to newer version, we are just working on new LTS release which should be good choice for the update, because we declare long stability support with the version. We plan to do the [LTS release](https://github.com/avocado-framework/avocado/discussions/5729) in next two months.

It's really exciting. Finally, we can use the concurrent function. If we can have the concurrent function, we can greatly improve the test efficiency. I want to study it.

**Comment by richtja** [comment]
I will close this issue since it is not related to new versions of avocado. If you need any help with the update your tests to nrunner, don't hesitate to ask, in this issue or in [Discussions ](https://github.com/avocado-framework/avocado/discussions)section, we are happy to help.
