### ISSUE TITLE
avocado-runner-* crashes when status server socket closes

### ISSUE THREAD

**Issue by clebergnu** [avocado-framework/avocado#5794]
**Describe the bug**
All runners built on top of `avocado.core.nrunner.app.BaseRunnerApp` will use `TaskStatusService.post()` to send status messages to the status server.  If the socket get closed, there will be an `EPIPE` returned during `send()`, followed by a `SIGPIPE`, followed by a `BrokenPipeError` that is not handled, which results in a crash.

**Steps to reproduce**
1. `nc -l -U /tmp/socket &`
2. `avocado-runner-rogue task-run -i ID -u x-avocado-runner-rogue -s /tmp/socket &`
3. `kill %1`

**Expected behavior**
The runners should be more resilient when the status server is not operating properly.  Ignoring failures is not a good option, so maybe runners will need a way to queue and persist messages they can't initially send to status servers.

But known crashes should be prevented, and unknown crashes (with information such as backtraces) should be captured.

**Current behavior**
```
avocado-runner-rogue task-run -i ID -u x-avocado-runner-rogue -s /tmp/socket &
[1] 747815
{'status': 'started', 'time': 142105.739663621, 'output_dir': '/tmp/.avocado-task-djf9hljx', 'id': 'ID'}
{'status': 'running', 'time': 142105.739762377, 'id': 'ID'}
...
{'status': 'running', 'time': 142113.250716832, 'id': 'ID'}
Traceback (most recent call last):
  File "/home/cleber/.local/bin/avocado-runner-rogue", line 33, in <module>
    sys.exit(load_entry_point('avocado-rogue', 'console_scripts', 'avocado-runner-rogue')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cleber/src/avocado/avocado/examples/plugins/tests/rogue/avocado_rogue/runner.py", line 55, in main
    app.run()
  File "/home/cleber/src/avocado/avocado/avocado/core/nrunner/app.py", line 179, in run
    return kallable(args)
           ^^^^^^^^^^^^^^
  File "/home/cleber/src/avocado/avocado/avocado/core/nrunner/app.py", line 293, in command_task_run
    for status in task.run():
  File "/home/cleber/src/avocado/avocado/avocado/core/nrunner/task.py", line 213, in run
    status_service.post(status)
  File "/home/cleber/src/avocado/avocado/avocado/core/nrunner/task.py", line 65, in post
    self.connection.send(data.encode("ascii") + "\n".encode("ascii"))
BrokenPipeError: [Errno 32] Broken pipe
```

**System information (please complete the following information):**
 - OS: ```LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 38 (Thirty Eight)
Release:	38
Codename:	ThirtyEight```
 - Avocado version: a0388203f4aa7f0cca8b603e6c4431fad9d322a6
 - Avocado installation method: Git

**Additional information**
This was found under https://github.com/avocado-framework/avocado/pull/5788

**Comment by richtja** [comment]
Solved in #5860
