### ISSUE TITLE
Unable to install avocado on immutable OS

### ISSUE THREAD

**Issue by abdhaleegit** [avocado-framework/avocado#5809]
**Describe the bug**

The below install command fails 

**$ sudo python3 setup.py install** 

running install
/usr/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3.11/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 30] Read-only file system: '/usr/lib/python3.11/site-packages/test-easy-install-2822.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/lib/python3.11/site-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://setuptools.pypa.io/en/latest/deprecated/easy_install.html

Please make the appropriate changes for your system and try again.

**System information (please complete the following information):**
 - OS: OpenSUSE  :   6.4.0-1-default
 - Avocado version: `latest upstream`
 - Avocado installation method:  github

**Comment by abdhaleegit** [comment]
@clebergnu @richtja 

Hello, 

I was trying to install avocado on my powerpc box having latest SUSE operting system and it fails to install with above errors

Any plans to support the latest SUSE OS or is there any discussions happening on the same?

Thanks

**Comment by clebergnu** [comment]
@abdhaleegit I'm not sure how Avocado itself can help with the limitations enforced by an  immutable OS.  If certain parts of the operating system can not be modified, what can the system-wide installation of Avocado (or any Python package for that matter) do?

For reference, I've installed Avocado successfully on Fedora Silverblue by doing:

```
$ git clone https://github.com/avocado-framework/avocado
$ cd avocado
$ python3 setup.py install --user
```

*Not using* the `--user` will result in the same kind of failures you report.

Unless I'm missing something, it's not up to Avocado to do anything besides what is already doing.  I'm closing this issue, feel free to reopen if I'm missing something.
