### ISSUE TITLE
New 92.X LTS version? :-)

### ISSUE THREAD

**Issue by dnegreira** [avocado-framework/avocado#5899]
Hi there! :wave: 

We are preparing a new [sos](https://github.com/sosreport/sos/) release in Ubuntu, more specifically Ubuntu Noble 24.04 which is due to be released soon with the shiny Python3.12, we [hit an issue](https://github.com/sosreport/sos/issues/3588) with running tests with the avocado-framework because Python3.12 deprecates the `imp` module.

I was digging a bit and I see that a couple of fixes have landed for the 92lts branch, more specifically [the PR](https://github.com/avocado-framework/avocado/pull/5727) that fixes the issue with `imp`.

We have done some tests locally with the `92lts` branch of avocado and it fixes our issues, so thanks for that!

Our question is if a new 92.X LTS version be pushed to PyPI based on the 92lts branch?

Thanks in advance!

**Comment by clebergnu** [comment]
Hi @dnegreira,

The 92.x releases won't happen so often, but they can happen based on user's requests.  So, in short, we can definitely work on the 92.2 release.

I'll keep you posted of any issues, or simply notify you when the release is on PyPI.

Thanks!

**Comment by dnegreira** [comment]
Hi @clebergnu,

We are also looking into moving to a more recent version of avocado-framework and we have a workaround to install/run tests from git rather than installing the package from PyPI, so, no pressure from our side.

**Comment by clebergnu** [comment]
92.2 is released and has been published to PyPI:

https://pypi.org/project/avocado-framework/92.2/
