### ISSUE TITLE
Guest connection with multiple transports: ssh, console

### ISSUE THREAD

**Issue by richtja** [avocado-framework/avocado#5914]
Avocado with usage of other avocado tools like [avocado-vt](https://github.com/avocado-framework/avocado-vt) or [Aexpect](https://github.com/avocado-framework/aexpect) has ways how to manage and monitor guest connections. Unfortunately, those use-cases are not well documented and avocado lacks the existence of examples which could help users. 

Let's investigate the possibilities of avocado with aexpect and prepare examples.

**Comment by clebergnu** [comment]
We'll be using the Dovetail instance issue to track this: https://gitlab.com/avocado-framework/dovetail/-/issues/5
