### ISSUE TITLE
Time normalization

### ISSUE THREAD

**Issue by richtja** [avocado-framework/avocado#5915]
The reason for this is the actual-needed timeouts are dependent on the environment. It's not OK to expect the test code to be modified when the environment changes significantly for an execution of the tests (say on faster or slower CPUs or networks). 

There has been some work done on this topic in #5820 which introduces timeout factor for the whole suite. But we need to investigate it further. We need to find a way how to adjust timeouts not only for the entire suite, but also for a specific test or even part of the test.

**Comment by clebergnu** [comment]
We'll be using the Dovetail instance issue to track this: https://gitlab.com/avocado-framework/dovetail/-/issues/4
