### ISSUE TITLE
Unable to install avocado-framework-plugin-varianter-yaml-to-mux using pip3

### ISSUE THREAD

**Issue by mahi657** [avocado-framework/avocado#5975]
**Describe the bug**

Unable to install avocado-framework-plugin-varianter-yaml-to-mux plugin.

[root@fvtlpar3 ~]# pip3 install --user avocado-framework
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting avocado-framework
  Downloading https://files.pythonhosted.org/packages/e1/b1/5f0f408bdbc28a82c91267095514eb795df929e0da000da1ae649840afb5/avocado_framework-100.1-py3-none-any.whl (432kB)
    100% |████████████████████████████████| 440kB 3.1MB/s 
Requirement already satisfied: setuptools in /usr/lib/python3.6/site-packages (from avocado-framework)
Installing collected packages: avocado-framework
Successfully installed avocado-framework-100.1

[root@fvtlpar3 ~]# pip3 install avocado-framework-plugin-varianter-yaml-to-mux
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting avocado-framework-plugin-varianter-yaml-to-mux
  Downloading https://files.pythonhosted.org/packages/94/8d/58d3e25a7a042a8454d87590600aa539b3b62db330509ba31c4da8c32a5f/avocado_framework_plugin_varianter_yaml_to_mux-105.0-py3-none-any.whl
Collecting avocado-framework==105.0 (from avocado-framework-plugin-varianter-yaml-to-mux)
  Could not find a version that satisfies the requirement avocado-framework==105.0 (from avocado-framework-plugin-varianter-yaml-to-mux) (from versions: 35.0, 36.0, 36.3, 36.4, 37.0.post0, 39.0, 40.0, 41.0, 42.0, 45.0, 46.0, 47.0, 48.0, 49.0, 50.0, 51.0, 52.0, 53.0, 54.0, 55.0, 56.0, 57.0, 58.0, 59.0, 60.0, 61.0, 62.0, 63.0, 64.0, 65.0, 66.0, 67.0, 68.0, 69.0, 69.1, 69.2, 69.3, 70.0, 71.0, 72.0, 73.0, 74.0, 75.1, 76.0, 77.0, 78.0, 79.0, 80.0, 81.0, 82.0, 82.1, 82.2, 83.0, 84.0, 85.0, 86.0, 87.0, 88.0, 88.1, 89.0, 90.0, 91.0, 92.0, 92.1, 92.2, 93.0, 94.0, 95.0, 96.0, 97.0, 98.0, 99.0, 100.0, 100.1)
No matching distribution found for avocado-framework==105.0 (from avocado-framework-plugin-varianter-yaml-to-mux)

_I tried version 100.1 specifically, getting this error,_

[root@fvtlpar3 ~]# pip3 install avocado-framework-plugin-varianter-yaml-to-mux==100.1
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting avocado-framework-plugin-varianter-yaml-to-mux==100.1
  Downloading https://files.pythonhosted.org/packages/b6/63/90d33dcc1bff79d7e3a44776252f45b3b3cad0fcc6c991e5f59df08ad29e/avocado_framework_plugin_varianter_yaml_to_mux-100.1-py3-none-any.whl
Collecting PyYAML>=4.2b2 (from avocado-framework-plugin-varianter-yaml-to-mux==100.1)
  Downloading https://files.pythonhosted.org/packages/ff/08/b6768d9f2da231c1396490e91471ffebb12b299a65cb369c27ec0e2a50c6/pyyaml-6.0.2rc1.tar.gz (130kB)
    100% |████████████████████████████████| 133kB 2.6MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "<fstring>", line 1
        (self.include_dirs=)
                          ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-rz1nsh39/PyYAML/

**Steps to reproduce**

Run "pip3 install avocado-framework-plugin-varianter-yaml-to-mux"
 
**Expected behavior**

avocado-framework-plugin-varianter-yaml-to-mux should get installed .

**Current behavior**

[root@fvtlpar3 ~]# pip3 install avocado-framework-plugin-varianter-yaml-to-mux==100.1
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting avocado-framework-plugin-varianter-yaml-to-mux==100.1
  Downloading https://files.pythonhosted.org/packages/b6/63/90d33dcc1bff79d7e3a44776252f45b3b3cad0fcc6c991e5f59df08ad29e/avocado_framework_plugin_varianter_yaml_to_mux-100.1-py3-none-any.whl
Collecting PyYAML>=4.2b2 (from avocado-framework-plugin-varianter-yaml-to-mux==100.1)
  Downloading https://files.pythonhosted.org/packages/ff/08/b6768d9f2da231c1396490e91471ffebb12b299a65cb369c27ec0e2a50c6/pyyaml-6.0.2rc1.tar.gz (130kB)
    100% |████████████████████████████████| 133kB 2.6MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "<fstring>", line 1
        (self.include_dirs=)
                          ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-rz1nsh39/PyYAML/

**System information (please complete the following information):**

 - OS: `lsb_release -a`
 [root@fvtlpar3 ~]# lsb_release -a
LSB Version:	:core-4.1-noarch:core-4.1-ppc64le
Distributor ID:	RedHatEnterprise
Description:	Red Hat Enterprise Linux release 8.10 (Ootpa)
Release:	8.10
Codename:	Ootpa

 - Avocado version: `avocado -v`
[root@fvtlpar3 ~]# avocado -v
Avocado 105.0

 - Avocado installation method: pip, rpm, github ?
pip

**Additional information**
Using Python 3.6.8

**Comment by richtja** [comment]
Hi @mahi657, can you please check the configuration of your pip. I can see that it fetches only avocado_framework-100.1 instead of version 105 even tho you try to instal the latest version with `pip3 install --user avocado-framework`. If you look at the release history of avocado-framework-plugin-varianter-yaml-to-mux the 105 should be available. https://pypi.org/project/avocado-framework-plugin-varianter-yaml-to-mux/#history

**Comment by PraveenPenguin** [comment]
@richtja seems there is an issue with the latest PyYAML version `6.0.2-rc` itself broken as 6.0.1 it works well if moved this line as 

https://github.com/avocado-framework/avocado/blob/master/optional_plugins/varianter_yaml_to_mux/setup.py#L51 

`install_requires=[f"avocado-framework=={VERSION}", "PyYAML==6.0.1"]`

**Comment by clebergnu** [comment]
@PraveenPenguin the issue here is that Python 3.6(.8) is being used, and Avocado itself dropped support for it in version 101.0 (see cf587e125ef741c853590eeae0f56ac5fa50f911).  On a Python 3.6 system you could do:

```
$ python3 -m pip install 'PyYAML==5.4.1'
$ python3 -m pip install 'avocado-framework-plugin-varianter-yaml-to-mux==100.1'
```

And you will have a working installation.
