### ISSUE TITLE
sysinfo not collected when running in-tree

### ISSUE THREAD

**Issue by ldoktor** [avocado-framework/avocado#703]
Sysinfo uses absolute `/etc` path, which doesn't exists when running in-tree version (when avocado was not already installed). We should detect and use in-tree configs.

Similar problems are on other places too. How about using `settings` module to say we're using `in-tree` configuration? That should be deterministic everywhere we touch settings.

@clebergnu since you implemented the configurable sysingo, can you please have a look at this, maybe it's just on my system...

**Comment by clebergnu** [comment]
This was actually discussed during development. We could:

1) make non absolute paths relative to the `etc/avocado/sysinfo` be it in-tree or in the system wide location.
2) avoid these special situations popping up in the code base, with the reasoning that in-tree users are most probably Avocado developers who can add a new configuration file changing the paths.

What do others ( @adereis, @lmr, @ruda ) think?

**Comment by adereis** [comment]
> 2) avoid these special situations popping up in the code base, with the reasoning that in-tree
> users are most probably Avocado developers who can add a new configuration file changing
> the paths.

Agree with this reasoning. If you want your own configuration, `$ scripts/avocado -c <your-own-config-file>` is your friend.

**Comment by adereis** [comment]
> 1) make non absolute paths relative to the etc/avocado/sysinfo be it in-tree or in the system
> wide location.

This was solved in GNU autoconf by having macros in the config file "templates" that would be changed at build/installation time. I wonder if setup.py offers something similar, given that it supports `install --prefix` and `install --root`.

**Comment by clebergnu** [comment]
It will not write a `config.h` like autotools will. We can certainly come up with a hack, but that's not how it's intended to be used.

**Comment by ldoktor** [comment]
Right, I remember talking about it. OK simple setup script:

```
sed -i "s@^commands = /@commands = $AVOCADO_PATH/@g" etc/avocado/avocado.conf
sed -i "s@^files = /@files = $AVOCADO_PATH/@g" etc/avocado/avocado.conf
sed -i "s@^profilers = /@profilers = $AVOCADO_PATH/@g" etc/avocado/avocado.conf
```

is my friend :smile:

**Comment by adereis** [comment]
> It will not write a config.h like autotools will. We can certainly come up with a hack, but that's not
> how it's intended to be used.

What I'm talking about is the usage of template .in files. For example, IIRC, a foobar.1.man.in file would contain macros that configure sets, creating a foobar.1.man file. Then there's automake, which can get .am files as templates too. The config.h file is for the C files to get variables from.

Anyway, autoconf/automake are legacy tools, I imagine there are other, more modern approaches to the same problem.

Maybe hacking setup.py as suggested by ldoktor is the way to go.

**Comment by clebergnu** [comment]
@adereis still we're talking about running some kind of routine (preprocessor, setup, configure) etc. In Python land this would be indeed running setup.py (probably from pip, in a virtual environment, etc), but this is not what this issue is about. It's about running from a pristine source tree. So we've talked about this before and decided that providing a command line option with an alternative configuration file is the way to go.

So, any objections to closing this issue?
