### ISSUE TITLE
--help info on RHEL6 is broken

### ISSUE THREAD

**Issue by Andrei-Stepanov** [avocado-framework/avocado#747]
[root@astepano2 avocado]# pwd
/root/avocado
[root@astepano2 avocado]# scripts/avocado vt-bootstrap --help
Usage:
  avocado [OPTION...] - GStreamer initialization

Help Options:
  -h, --help                        Show help options
  --help-all                        Show all help options
  --help-gst                        Show GStreamer Options

[root@astepano2 avocado]# git log
commit bb2de3960549a5a994b9417b2824db73782ab8b1
Merge: d90ea78 63fef11
Author: Lucas Meneghel Rodrigues <lmr@redhat.com>
Date:   Mon Aug 3 23:47:25 2015 -0300

**Comment by lmr** [comment]
I sent a fixed in https://github.com/avocado-framework/avocado-vt/pull/48

**Comment by adereis** [comment]
Fix has been merged, closing.
