### ISSUE TITLE
python-psutil EL6 compatibility 

### ISSUE THREAD

**Issue by clebergnu** [avocado-framework/avocado#774]
One specific functional test, `selftests/all/functional/avocado/interrupt_tests.py`, fails on EL6 systems when using the `python-psutil` package, at version 0.6.1, available from EPEL.

Ideally, it would be nice to have a development environment all based on packaged versions. Currently, a newer version must be installed via `pip`.

Let's examine if `python-psutil` 0.6.1 is enough for what avocado needs.

**Comment by lmr** [comment]
Oh, right. It's good that we still don't depend on `python-psutil` inside avocado. I'd like it to moving forward, that library is pretty awesome.

**Comment by lmr** [comment]
Fixed with 119b2f7bd62b1de7c2f5899696422b96b8a1ab1d
