### ISSUE TITLE
Avocado: basic-example documentation needs an update

### ISSUE THREAD

**Issue by bssrikanth** [avocado-framework/avocado#783]
link: http://avocado-framework.readthedocs.org/en/latest/WritingTests.html#basic-example

Above link talks of an basic example which users could refer and run to get used to Avocado. Currently the .yaml contents in that page is missing '!mux' keyword, run as-is will show users below error:

14:57:33 job              L0399 INFO | Multiplex tree representation:
14:57:33 job              L0401 INFO |  \-- run
14:57:33 job              L0401 INFO |       \-- sleeptest
14:57:33 job              L0401 INFO |            |    -> type: builtin
14:57:33 job              L0401 INFO |            |-- short
14:57:33 job              L0401 INFO |            |      -> sleep_length: 0.5
14:57:33 job              L0401 INFO |            |-- medium
14:57:33 job              L0401 INFO |            |      -> sleep_length: 1
14:57:33 job              L0401 INFO |            \-- long
14:57:33 job              L0401 INFO |                   -> sleep_length: 5
14:57:33 job              L0402 INFO | 
14:57:33 job              L0406 INFO | Temporary dir: /var/tmp/avocado_RMhEVQ
14:57:33 job              L0407 INFO | 
14:57:33 job              L0414 INFO | Variant 1:    /run/sleeptest/short, /run/sleeptest/medium, /run/sleeptest/long
14:57:33 job              L0417 INFO | 
14:57:33 job              L0292 INFO | Job ID: 76915559c8f8b86a5a39f55844d5dd857124c6d8
14:57:33 job              L0293 INFO | 
14:57:33 test             L0153 INFO | START sleeptest.py:SleepTest.test
14:57:33 multiplexer      L0193 DEBUG| PARAMS (key=timeout, path=*, default=None) => None
14:57:33 stacktrace       L0036 ERROR| 
14:57:33 stacktrace       L0039 ERROR| Reproduced traceback from: /usr/lib/python2.6/site-packages/avocado-0.27.0-py2.6.egg/avocado/core/test.py:375
14:57:33 stacktrace       L0042 ERROR| Traceback (most recent call last):
14:57:33 stacktrace       L0042 ERROR|   File "/usr/share/avocado/tests/sleeptest.py", line 21, in test
14:57:33 stacktrace       L0042 ERROR|     sleep_length = self.params.get('sleep_length', default=1)
14:57:33 stacktrace       L0042 ERROR|   File "/usr/lib/python2.6/site-packages/avocado-0.27.0-py2.6.egg/avocado/core/multiplexer.py", line 265, in get
14:57:33 stacktrace       L0042 ERROR|     value = self._get(key, path, default)
14:57:33 stacktrace       L0042 ERROR|   File "/usr/lib/python2.6/site-packages/avocado-0.27.0-py2.6.egg/avocado/core/multiplexer.py", line 281, in _get
14:57:33 stacktrace       L0042 ERROR|     return param.get_or_die(path, key)
14:57:33 stacktrace       L0042 ERROR|   File "/usr/lib/python2.6/site-packages/avocado-0.27.0-py2.6.egg/avocado/core/multiplexer.py", line 372, in get_or_die
14:57:33 stacktrace       L0042 ERROR|     for _ in ret]))
14:57:33 stacktrace       L0042 ERROR| ValueError: Multiple  leaves contain the key 'sleep_length'; ['/run/sleeptest/short=>0.5', '/run/sleeptest/medium=>1', '/run/sleeptest/long=>5']
14:57:33 stacktrace       L0043 ERROR| 
14:57:33 test             L0482 ERROR| Traceback (most recent call last):

14:57:33 test             L0482 ERROR|   File "/usr/lib/python2.6/site-packages/avocado-0.27.0-py2.6.egg/avocado/core/test.py", line 424, in _run_avocado
    raise test_exception

14:57:33 test             L0482 ERROR| ValueError: Multiple  leaves contain the key 'sleep_length'; ['/run/sleeptest/short=>0.5', '/run/sleeptest/medium=>1', '/run/sleeptest/long=>5']

14:57:33 test             L0499 ERROR| ERROR sleeptest.py:SleepTest.test -> ValueError: Multiple  leaves contain the key 'sleep_length'; ['/run/sleeptest/short=>0.5', '/run/sleeptest/medium=>1', '/run/sleeptest/long=>5']
14:57:33 test             L0486 INFO | 

Needs a small update as mentioned below:

sleeptest: !mux  <<---
    type: "builtin"
    short:
        sleep_length: 0.5
    medium:
        sleep_length: 1
    long:
        sleep_length: 5

**Comment by bssrikanth** [comment]
Created PR #784 against avacado git repo

**Comment by lmr** [comment]
Closing this upon #784's merge
