### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '/var/tmp/avocado_ugU6zs/address_pool.lock'

### ISSUE THREAD

**Issue by ehabkost** [avocado-framework/avocado#818]
I don't know how to reproduce this, because the second time I tried to run the same tests, it worked as expected.

Some log messages:

    16:23:30 qemu_monitor     L0608 WARNI| Could not connect to monitor 'Could not connect to monitor socket: [Errno 2] No such file or directory'
    16:23:30 qemu_monitor     L0608 WARNI| Could not connect to monitor 'Could not connect to monitor socket: [Errno 2] No such file or directory'
    16:23:30 vt               L0456 DEBUG| Searching for test modules that match 'type = boot' and 'provider = io-github-autotest-qemu' on this cartesian dict
    16:23:30 vt               L0470 DEBUG| Found subtest module /home/ehabkost/avocado/data/avocado-vt/test-providers.d/downloads/io-github-autotest-qemu/generic/tests/boot.p
    y
    16:23:30 env_process      L0662 DEBUG| KVM version: 4.1.5-100.fc21.x86_64
    16:23:30 env_process      L0683 DEBUG| KVM userspace version: 2.4.50
    16:23:30 process          L0272 INFO | Running 'true'
    16:23:30 storage          L0415 DEBUG| Image backup /home/ehabkost/avocado/data/avocado-vt/images/jeos-21-64.qcow2.backup already exists, skipping...
    16:23:30 env_process      L0862 ERROR| [Errno 2] No such file or directory: '/var/tmp/avocado_ugU6zs/address_pool.lock'
    16:23:30 process          L0272 INFO | Running 'true'
    16:23:30 vt               L0524 ERROR| Exception raised during postprocessing: Failures occurred while postprocess:
    Postprocess: [Errno 2] No such file or directory: '/var/tmp/avocado_ugU6zs/address_pool.lock'
    16:23:30 stacktrace       L0036 ERROR| 
    16:23:30 stacktrace       L0039 ERROR| Reproduced traceback from: /home/ehabkost/rh/proj/virt/avocado/avocado/core/plugins/vt.py:575
    16:23:30 stacktrace       L0042 ERROR| Traceback (most recent call last):
    16:23:30 stacktrace       L0042 ERROR|   File "/home/ehabkost/rh/proj/virt/avocado/avocado/core/plugins/vt.py", line 361, in runTest
    16:23:30 stacktrace       L0042 ERROR|     self._runTest()
    16:23:30 stacktrace       L0042 ERROR|   File "/home/ehabkost/rh/proj/virt/avocado/avocado/core/plugins/vt.py", line 484, in _runTest
    16:23:30 stacktrace       L0042 ERROR|     params = env_process.preprocess(self, params, env)
    [...]
    16:23:30 stacktrace       L0042 ERROR|   File "/home/ehabkost/rh/proj/virt/avocado/virttest/utils_net.py", line 2531, in lock_db
    16:23:30 stacktrace       L0042 ERROR|     self.lock = utils_misc.lock_file(self.db_lockfile)
    16:23:30 stacktrace       L0042 ERROR|   File "/home/ehabkost/rh/proj/virt/avocado/virttest/utils_misc.py", line 229, in lock_file
    16:23:30 stacktrace       L0042 ERROR|     lockfile = open(filename, "w")
    16:23:30 stacktrace       L0042 ERROR| IOError: [Errno 2] No such file or directory: '/var/tmp/avocado_ugU6zs/address_pool.lock'
    16:23:30 stacktrace       L0043 ERROR| 
    16:23:30 test             L0491 ERROR| Traceback (most recent call last):
    
    16:23:30 test             L0491 ERROR|   File "/home/ehabkost/rh/proj/virt/avocado/avocado/core/plugins/vt.py", line 617, in _run_avocado
        raise test_exception
    
    16:23:30 test             L0491 ERROR| IOError: [Errno 2] No such file or directory: '/var/tmp/avocado_ugU6zs/address_pool.lock'
    
    16:23:30 test             L0508 ERROR| ERROR io-github-autotest-qemu.reboot -> IOError: [Errno 2] No such file or directory: '/var/tmp/avocado_ugU6zs/address_pool.lock'
    16:23:30 test             L0495 INFO | 

Full job result tarball available at: https://dl.dropboxusercontent.com/u/1626365/tmp/job-2015-10-02T16.23-3c858a8.tar.bz2

.

**Comment by ehabkost** [comment]
Avocado was run as:

    $ ./scripts/avocado run --vt-qemu-bin=/home/ehabkost/rh/proj/virt/qemu/x86_64-softmmu/qemu-system-x86_64 reboot
    JOB ID     : 3c858a8d5de854db6161a3a41d7dbf762096cf92
    JOB LOG    : /home/ehabkost/avocado/job-results/job-2015-10-02T16.23-3c858a8/job.log
    TESTS      : 1
     (1/1) io-github-autotest-qemu.reboot: ERROR (0.30 s)
    RESULTS    : PASS 0 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0
    JOB HTML   : /home/ehabkost/avocado/job-results/job-2015-10-02T16.23-3c858a8/html/results.html
    TIME       : 0.30 s

**Comment by lmr** [comment]
Basically due to some changes to the tmp files management, the first failure is expected, because you had an environment file that remembered an old location of a lock file. After the 2nd execution, things should not fail anymore. I'd close this one unless you are still having trouble.

**Comment by ehabkost** [comment]
If that's not going to happen again (it really happened only once), I don't mind closing it.
