### ISSUE TITLE
Compatible with python2.6

### ISSUE THREAD

**Issue by will-Do** [avocado-framework/avocado#880]
Hi folks,
The python2.6 needs packages are installed only for travis(requirements-travis-python26.txt), should we install them in Makefile to support all our tests can run on python2.6(RHEL6)?

**Comment by lmr** [comment]
I don't think so, they are necessary for testing avocado itself.

**Comment by will-Do** [comment]
In fact, it failed as missing modules, such as 'importlib'
```
$ grep -rn importlib .
./avocado.spec:21:Requires: python-argparse, python-importlib, python-logutils, python-unittest2
./avocado.spec:23:BuildRequires: python-argparse, python-importlib, python-logutils, python-unittest2
./tags:8248:importlib	avocado/core/restclient/cli/app.py	/^import importlib$/;"	i	language:Python
./tags:8249:importlib	avocado/core/restclient/cli/parser.py	/^import importlib$/;"	i	language:Python
./requirements-travis-python26.txt:4:importlib==1.0.3
Binary file ./avocado/core/plugins/builtin.pyc matches
./avocado/core/plugins/builtin.py:20:from importlib import import_module
./avocado/core/restclient/cli/parser.py:22:import importlib
./avocado/core/restclient/cli/parser.py:79:        basemod = importlib.import_module(prefix)
./avocado/core/restclient/cli/parser.py:107:        module = importlib.import_module(module_name)
./avocado/core/restclient/cli/app.py:21:import importlib
./avocado/core/restclient/cli/app.py:86:            module = importlib.import_module(module_name)
```

**Comment by will-Do** [comment]
```
5:48:47 2015-11-06 05:48:49,653     INFO|Bootstrap avocado-vt...
05:48:47 Avocado crashed unexpectedly: No module named importlib
05:48:47 You can find details in /tmp/avocado-traceback-2015-11-06_05:48:50-BKaezL.log
05:48:48 2015-11-06 05:48:50,078     INFO|--- Testing Phase ---
05:48:48 2015-11-06 05:48:50,135     INFO|Start running libvirt CI in /tmp/acceptance-autotest-6.8-x86_64-runtest-3
05:48:48 Traceback (most recent call last):
05:48:48   File "./runner", line 674, in <module>
05:48:48     exit(Runner(args=args).run())
05:48:48   File "/tmp/acceptance-autotest-6.8-x86_64-runtest-3/avocado/runner_main.py", line 26, in __init__
05:48:48     from virttest import data_dir
05:48:48   File "/tmp/acceptance-autotest-6.8-x86_64-runtest-3/avocado/virttest/data_dir.py", line 12, in <module>
05:48:48     from avocado.core import data_dir
05:48:48   File "/tmp/acceptance-autotest-6.8-x86_64-runtest-3/avocado/avocado/__init__.py", line 19, in <module>
05:48:48     from avocado.core.job import main
05:48:48   File "/tmp/acceptance-autotest-6.8-x86_64-runtest-3/avocado/avocado/core/job.py", line 44, in <module>
05:48:48     from .plugins import manager
05:48:48   File "/tmp/acceptance-autotest-6.8-x86_64-runtest-3/avocado/avocado/core/plugins/manager.py", line 19, in <module>
05:48:48     from .builtin import load_builtins
05:48:48   File "/tmp/acceptance-autotest-6.8-x86_64-runtest-3/avocado/avocado/core/plugins/builtin.py", line 20, in <module>
05:48:48     from importlib import import_module
05:48:48 ImportError: No module named importlib
```

**Comment by lmr** [comment]
These packages are handled in the spec file just fine.

**Comment by lmr** [comment]
Now if you are running avocado straight from the source then you need a plan to install the dependencies.

**Comment by lmr** [comment]
%if 0%{?el6}
    Requires: PyYAML
    Requires: python-argparse, python-importlib, python-logutils, python-unittest2
    BuildRequires: PyYAML
    BuildRequires: python-argparse, python-importlib, python-logutils, python-unittest2
    %else
    Requires: python-yaml
    BuildRequires: python-yaml, fabric
    %endif

**Comment by lmr** [comment]
Now, for us is very hard to tell exactly how the user wants to use avocado - we favor using distro native packages because it's easier to control dependencies. I'm not sure that it's correct to add 'pip install' commands before the `install` target, but that's something that could be done.

**Comment by lmr** [comment]
Well, I've sent #881 as a proposal to resolve the problem you're having. I'm curious as to why you are not using rpm packages, though.

**Comment by will-Do** [comment]
Thx @lmr 
Well, we always using avocado (autotest before) from the source in our libvirt-ci projects, so we can always run the newest codes. For now, we patched in our project to install these requirements  to solve this problem.

**Comment by ldoktor** [comment]
the proper way even when using it from source is to use `make rpm` and then `yum localinstall` :wink:

**Comment by clebergnu** [comment]
@will-Do hopefully #918 took care of this. Can you please check? If necessary, please reopen this issue.

**Comment by will-Do** [comment]
@clebergnu Sure, thanks for your effort.
