### ISSUE TITLE
avocado rpms for ppc64[le]

### ISSUE THREAD

**Issue by sathnaga** [avocado-framework/avocado#894]
Hi @lmr,
Hi @ldoktor,
 
I used to see avocado ppc64le rpms(for fedora) being maintained into your copr(https://copr.fedoraproject.org/coprs/lmr/Autotest/) repository, though those builds were failing.
Has there been any change in plans?
Anyways I can still use the direct repository and do make(with couple of dependencies resolved), let me know if any of our help needed there to bring that repo back.
Thanks in advance. 

_regards,
-Satheesh.

**Comment by ldoktor** [comment]
Hello Satheesh, the good news about the new repository (which deprecated the copr one) is, that it's properly set as `noarch` architecture and you can use it on `ppc64` and `ppc64le`.

https://repos-avocadoproject.rhcloud.com/static/avocado-el.repo

Btw if you use `PowerKVM` there is a bug in `PyYAML` (or in some dependency) and multiplexer fails to load any file. You have to "disable" the `C` version of PyYAML to make it work. See details in here: https://www.redhat.com/archives/avocado-devel/2015-November/msg00018.html

**Comment by sathnaga** [comment]
Hi Lukáš Doktor(@ldoktor),
 Sure, Thanks a lot for the info, will try and get back :-)

**Comment by sathnaga** [comment]
@ldoktor : Looks like the repo link is broken, below error is from RHEL 7.2(ppc64le)
https://repos-avocadoproject.rhcloud.com/static/epel-7Server-noarch/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found

If you can give a sample baseurl link, that would help :-)

Thanks in advance.
Regards,
-Satheesh

**Comment by ldoktor** [comment]
It's a missing symlink problem (We have https://repos-avocadoproject.rhcloud.com/static/epel-7-noarch/repodata/repomd.xml and https://repos-avocadoproject.rhcloud.com/static/epel-7Workstation-noarch/repodata/repomd.xml variants). There are so many variants that eg. epel uses different repo for 5, 6 and 7 and ignores the release. We wanted to use the release but there comes the initial troubles ...

@clebergnu: would you please add symink to Server? (Also add the Cloud and the other I mentioned by email, it seems we need them).

**Comment by clebergnu** [comment]
We now have the following links:

* epel-7Server-RT-noarch
* epel-7Server-SAPHANA-noarch
* epel-7Wokstation-noarch
* epel-7ComputeNode-noarch
* epel-7Server-noarch
* epel-7Server-SAP-noarch
* epel-7Client-noarch
* epel-7Workstation-noarch

Let me know if we're missing any other.

**Comment by ldoktor** [comment]
Great, thanks. @sathnaga, now it should work fine.

**Comment by sathnaga** [comment]
Now it works fine for RHEL72 ppc64le,

# yum install avocado
Loaded plugins: product-id, search-disabled-repos, subscription-manager
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
avocado                                                  | 2.9 kB     00:00     
avocado/7Server/primary_db                                 | 6.1 kB   00:00     
Resolving Dependencies
--> Running transaction check
---> Package avocado.noarch 0:0.30.0-0.el7.centos will be installed

**Comment by sathnaga** [comment]
@ldoktor @clebergnu  Thanks :-)
