### ISSUE TITLE
Command line arguments for tests

### ISSUE THREAD

**Issue by narasimhan14** [avocado-framework/avocado#900]
Hi,

Currently there is no way to supply command line arguments to the tests.
We either have to give through config file or multiplexer.
Can we have command line arguments, so that dynamic inputs can be given.

--
Thanks
Narasimhan V

**Comment by ldoktor** [comment]
Dear Narasimhan,

you can inject values via `--mux-inject` on the cmdline. It can also dynamically create nodes for you...

Regards,
Lukáš

**Comment by narasimhan14** [comment]
Thanks Lukas

**Comment by UnitasBrooks** [comment]
So I tried mux-inject and I can't seem to get it working here is the command I'm running: 

avocado run ./sample-test.py --mux-inject key:var

and in my test:
        self.key = self.params.get('key', default="none!")
        print "key: " + self.key

the result is: key: none! 

I am on Avocado 47.0, Centos 7.3, python 2.7.5

**Comment by ldoktor** [comment]
Hello @UnitasBrooks, short answer is use `--mux-inject /run:key:var`.

The long answer is that `--mux-inject` is a swiss-knife which simply injects the key/var pair into the specified path. When the path is not specified, it uses `/`, which is not in the default path to look for params. So to avoid this issue you can (ordered by preference):

1. use `--mux-inject $path:$key:$value` to inject it into a path, which is by default accepted (`--mux-inject /run:key:var`)
2. in test get the value from specific path by `self.params.get('key', path="/*")
3. override the default path to `/` by `--mux-path /`

Note that using the high level `--mux-yaml` the content is by default injected in `/run` which makes it available to tests in the default location. You can check it out by using `avocado multiplex --mux-inject ... --mux-yaml ... --tree`.

**Comment by UnitasBrooks** [comment]
Great thanks so much Lukáš.

**Comment by ldoktor** [comment]
No problem, I know this area is still a bit hackish due to bound to our single implementation. We are already working on standardization which should make things easier to start with...

**Comment by UnitasBrooks** [comment]
Hi I had a question about the varianter, and I wasn't sure where to go, IRC
seems very quiet and I haven't been accepted on your mailing list, hope
this reaches you!

I am using a varianter yaml file to run a test a few different ways, the
problem I'm running into is that I want it to only apply to that test in a
given job. For instance if I run this command:

avocado run -m variant.yml variant_case.py not_a_variant_case.py

the variant.yml gets applied to both variant_case.py and
not_a_variant_case.py, if the variant.yml has 5 things in it,
not_a_variant_case.py will get ran 5 times in exactly the same way.

Let me know if it's possible to configure this behavior, and thanks for
your time.

- Joe

**Comment by clebergnu** [comment]
@UnitasBrooks can you please tell me what kind of problem you're having with the mailing list?  It should defintely be open to anyone.  IRC is really quiet, and just today I tried to join oftc.net and it seemed to be down.

Anyway, back to your question:  it's not currently possible to provide variants only for some tests.  The variants are applied to every single test in a Job's test suite.  We do think it'd be nice to be more flexible here.  Any proposals?

**Comment by UnitasBrooks** [comment]
I think I just need to be accepted to it and haven't yet? I tried emailing it and it got bounced.

One way it could be handled is by having the variant file defined in the test case as opposed to the command line, other wise just parsing it differently could help like allowing commas between cases:

avocado run case_1, case_2 -m v.yml, case_3, case_4 -m v2.yml

**Comment by clebergnu** [comment]
Under the hood, we currently have some limitations.  Basically `avocado.core.job.Job.run_tests()` do not take a list of variants or tests (what we call the test suite).  That's because Avocado provides the Job abstraction, so the test suite is the job's own.

One possibility, which is by far the most clean and flexible, is to programatically make use of the `avocado.core.job.Job` class.  You'd write a script such as:

```python
from argparse import Namespace
from avocado.core.job import Job

# arguments for the first set of tests
args = Namespace(reference=["variant_case.py"])
job = Job(args)
# assuming some "default" variants are being created
job.create_test_suite()
job.run_tests()
args.avocado_variants = None
args.reference = ['not_a_variant_case.py']
job.run_tests()
```

If you try that exact code, you'll find most of the current limitations.  We've discussed what needs to be done, but due to other higher priority tasks, we haven't addressed them.

If you feel like this is worth it, your help is very much appreciated.
