### ISSUE TITLE
Support multi avocado-vt instances in a host

### ISSUE THREAD

**Issue by xutian** [avocado-framework/avocado#909]
Sometimes, many teams shared a machine to run test (special for some new platform or expensive platform like ppc). And many of our test case a automated in avocao/autotest and it will help our guys to save testing resource, so our guys like to run this kind test case in avocado/autotest. But now avocado reading configuration from  /etc/avocado, and copy test configuration to /usr/share/avocado directory,  if multi-instance running in same host, avocado configuration and avocado testing configuration will be overwrite by latest instance.

**Comment by xutian** [comment]
@clebergnu and @lmr 
Any suggestion for this issue?

Thanks,
Xu

**Comment by ldoktor** [comment]
Hello @xutian, avocado reads the configuration from various places, including home-dir and command line using `--config` argument. It works as any other programs, first it reads /etc, then the user-config, which overrides values from /etc. So once you use different paths in your new config, or if you use various users, it should work fine.

Anyway we also have in our todo-list (not on the top, but it's already in the short-term todo-list) to implement locking mechanism, to avoid corrupting other test's resources. In the first version it should simply raise an exception when 2 users/tests are trying to use the same resource, for example 2 root users executing avocado-vt test. This should make your life easier. Feel free to propagate this to increase the priority:

https://trello.com/c/VMoQ2DPU/390-provide-a-locking-api-for-shared-resources

**Comment by xutian** [comment]
@ldoktor 
Thanks for you sharing. As your said avocado still need to implement locking mechanism, and  we  lack powerpc platform in nay office and three sections guys share the hardware resource, so our test schedule impacted  because the defeat of avocado. so we hope your team can raise priority of this issue.  cc @clebergnu 
Thanks very much.

**Comment by adereis** [comment]
Just a quick note: avocado itself is multi-user and multi-job aware. The problem is in avocado-vt (a problem inherited from virt-test).

Right now if VT tests are run in different jobs at the same time, there will be unexpected results, because the tests assume full control of system-wide resources. The locking mechanism will prevent this scenario, by immediately returning an error.

**Comment by ldoktor** [comment]
@xutian as I said before, the simples solution is to modify the config file, or if you use the same user you can run `avocado --config user1.cfg ...` and change the `datadir.paths.data_dir` in each `userX.cfg` file. Most of the code is using datadir module, so it should suffice.

**Comment by xutian** [comment]
@ldoktor , thanks your suggestion.  We will used virtualenv to run multi-instance in a host and as your saied we need to update code for ready configuration file. And @suqinhuang  has a PR for it https://github.com/avocado-framework/avocado/pull/1026 , can you help review the PR, and any comments are welcomed.

Thanks,
Xu

**Comment by ldoktor** [comment]
OK, virtualenv should also work. The only problem of that pull request is the CI check and Amador already suggested the fix.

**Comment by ldoktor** [comment]
Hello @xutian, the @suqinhuang's PR was closed and there are no updates here so I guess you have a working solution. If not please re-open and update the issue so it reflects the current state.

Thank you,
Lukáš

**Comment by xutian** [comment]
Close it is OK for me.

**Comment by ldoktor** [comment]
Great, out of curiosity, could you share how you solved this issue for you? Are you using different users, or do you use `--config` for different runs? (don't feel obliged to do so, I'm only curious)

**Comment by xutian** [comment]
We use virtualenv  + '--config'

**Comment by ldoktor** [comment]
Cool, I'm wondering if you could write (some day) a section in documentation regarding this. (a paragraph or so). I think others would benefit.
