### ISSUE TITLE
Update path of core file to case log folder

### ISSUE THREAD

**Issue by suqinhuang** [avocado-framework/avocado#922]
Now core file is generated under avocado framework folder,

1. the core will be replaced while more than one core is generated during test,
2. tester could not see the core from test result.

need to put the core in the case log folder

**Comment by lmr** [comment]
@suqinhuang, avocado could, until yesterday, be run from the source code dir without any modifications, but we always had in mind rpm installs. Can you describe what's happening with examples? What was the behavior before, and what's the behavior now?

**Comment by clebergnu** [comment]
@suqinhuang can you please provide more information here?

For instance, are you using the GDB specific option to enable the core dump generation? Can you explain where your coredumps are being saved and where you want them to be with a real `run` example?

**Comment by suqinhuang** [comment]
Hi @lmr @clebergnu 
 
I simulate core file generating during test with "touch qemu.core" cmd
the core file is generated in current path
# pwd
/root/Autotest/staf-kvm-devel 
# ls
qemu.222.core
qemu.test.core

once I run a test loop, and more than one case generate core file,
1. not sure which case the core file belong to
2. maybe covered by the following test (although pid is diff)
3. Tester could not find the core file from test result.

What's behaviour before?
core file is generate in the case log
 # pwd
/root/autotest/client/results/default/virt.qemu.smp_1.4096m.repeat1.run_test.Host_RHEL.7.2.qcow2.virtio_blk.up.virtio_net.Win7.x86_64.sp1.io-github-autotest-qemu.boot

**Comment by ldoktor** [comment]
Hello @suqinhuang, it was the autotest's work to set `core_pattern` and avocado is not doing it now, which results in default (usually the binary location). I'm adding trello card to work on it.

Well actually I'll add 2 cards, one to port the autotest's version and other to try to come up with a way to make this work in multi-instance environment (I mean multiple avocado executions at the same time). There are few possibilities how to solve it, but discussions about this should not block the basic support.

**Comment by suqinhuang** [comment]
hi @ldoktor thanks a lot, could I know when will be the patch ready?

**Comment by ldoktor** [comment]
Nobody started working on it yet, but it's the first item on the current sprint TODO list. I'm finishing the logging refactor and working on multi-host experiment, which should keep me busy for ~ a week, then I can take a look at this, unless @apahim or @clebergnu takes care of it earlier.

Alternatively feel free to pick the card: https://trello.com/c/ijJFFbpI/140-bug-save-core-dump-file-in-test-results-via-proc-sys-kernel-core-pattern yourself, it describes the idea, but is related to the  simple solution, which can be copied from `autotest.client.test.py`.

**Comment by clebergnu** [comment]
@suqinhuang can you and/or your team take a look at:

https://github.com/avocado-framework/avocado/pull/1210

It's based on job scripts, a feature of Avocado (not related to Avocado-VT), but developmented targeted Avocado-VT.  On my development sessions, I ran Avocado-VT tests and sent SIGSEGV signals to qemu, resulting in core files generated at the job level, but linked on to the specific test directories where the failures occurred.

We're really interested in knowing if this is something that would actually be used by your team or, if not, what are the shortcomings.  Thanks!

**Comment by clebergnu** [comment]
@suqinhuang we have a v2:

https://github.com/avocado-framework/avocado/pull/1211

**Comment by suqinhuang** [comment]
Sorry for late reply as it's Weekend in Beijing, the design meet our requirement, will have a test.

Thanks

**Comment by suqinhuang** [comment]
Hi it there something wrong in my testing? didn't get the core file in case result folder 
 pwd
/etc/avocado/scripts/job/pre.d
[root@dhcp-10-214 pre.d]# ls
001-set-core-pattern  README

[root@dhcp-10-214 post.d]# pwd
/etc/avocado/scripts/job/post.d
[root@dhcp-10-214 post.d]# ls
001-restore-core-pattern  002-link-core-to-tests  README

core file is generated with "gcore pid"
core.18756

but I didn't find the core in the test result
[root@dhcp-10-214 latest]# pwd
/root/avocado/job-results/latest
 # find -name core.18756 (no output)

**Comment by ldoktor** [comment]
Hello @suqinhuang,

do you have the `coredumps` directories created in `$RESULTDIR/coredumps/` and the `$RESULTDIR/test-results/*/coredumps/`? And what was the output of avocado when executing it? Are there any pre/post exceptions? Also are the `00*` files set as executable?

**Comment by suqinhuang** [comment]
1. 
-rwxr-xr-x 1 root root  896 May 16 17:15 001-restore-core-pattern
-rwxr-xr-x 1 root root 2453 May 16 17:15 002-link-core-to-tests
-rwxr-xr-x 1 root root 1113 May 16 17:15 001-set-core-pattern

2. There is coredumps directory created in $RESULTDIR/coredumps/
3. no directory $RESULTDIR/test-result/*/coredumps/
4. I didn't find the info of post.d/00*
2016-05-17 13:53:02,778 process          L0331 INFO | Running '/etc/avocado/scripts/job/pre.d/001-set-core-pattern'
2016-05-17 13:53:02,797 sysinfo          L0338 INFO | Commands configured by file: /etc/avocado/sysinfo/commands

**Comment by suqinhuang** [comment]
Thanks @ldoktor for you help, the fix works for me.

Thanks 
Suqin

**Comment by ldoktor** [comment]
Glad to hear that. Please file a new issue for possible RFEs.
