### ISSUE TITLE
worngly detected testcases in one file

### ISSUE THREAD

**Issue by jscotka** [avocado-framework/avocado#952]
Hi,
I done some test with mistake, that all test methods have same name:
```
#!/usr/bin/python

from avocado import Test
from avocado import main
from avocado.utils import process

class BasicTestSuite(Test):

    def test1(self):
        self.assertTrue(False)

    def test1(self):
        raise Exception("Ahoj")

    def test1(self):
        self.assertTrue(True)

if __name__ == '__main__':
    main()
'''
causes that avcado do:
```
$ avocado run test.py
JOB ID     : 9eb6ad4c22eab5b1df947abc15059041c98a7dbc
JOB LOG    : /home/jscotka/avocado/job-results/job-2016-01-12T12.12-9eb6ad4/job.log
TESTS      : 3
 (1/3) test.py:BasicTestSuite.test1: PASS (0.00 s)
 (2/3) test.py:BasicTestSuite.test1.1: PASS (0.00 s)
 (3/3) test.py:BasicTestSuite.test1.2: PASS (0.00 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0
TIME       : 0.01 s
'''

Expected result is, that avcado detect that there is only one test (last one (it is okay)), or do all 3 tests, no 3-times same.

**Comment by ldoktor** [comment]
@jscotka well it seems odd, but there is a good reason why it works like this and we can't do much about it (well we can detect the same name within a single class and raise error with explanation, but IMO that's a bit overhead).

The reason it detects all 3 subtests is that we use static analysis. That means the code is not executed and avocado detects all possible targets.

The reason 3 identical tests are executed is the way python defines the attributes/methods. It's not a failure to override existing method, so what happens on import is that the `BasicTestSuite` first adds method `test1`, then it overrides this attribute with the second `test1` method and in the end it overrides it with the last `test1` method. This means in the end you can only reach to the last method defined.

My feeling is that detecting this corner cases is wasting of resources and users should check their code with pylint/pep8 to avoid such problems. But @adereis, @clebergnu can have different opinions, so let's invite them to this communication.

**Comment by clebergnu** [comment]
A short and effective fix we can have is to make test methods unique in `avocado.core.loader.TestLoader._find_avocado_tests()`.

That way, the static analysis can mimic what Python evaluation would do: have only a single `test1` method after the class is instantiated.

I'm trying that right now.

**Comment by ldoktor** [comment]
Btw there is another similar problem we have due to static analysis is:

```python
from avocado import main
from avocado import Test

class MyClass(Test):
    def __init__(self, *args, **kwargs):
        super(MyClass, self).__init__(*args, **kwargs)
        for _ in xrange(10):
            setattr(self, "test%s" % _, lambda: None)

    def test1():
        raise Exception()

if __name__ == '__main__':
    main()
```

which executes one test (without the `def test1` it's not even recognized as test) even though if you import it the class contains 10 tests.

It was decided that safety is more important than flexibility. There are ways to say certain test is an avocado test (or that it's not) using docstring.

**Comment by ldoktor** [comment]
@clebergnu yep, that's what I mentioned in the first post. Anyway I'd prefer failing the suit in such case, because it's clearly a big problem for the tester.

**Comment by clebergnu** [comment]
@ldoktor if you try to defeat the static parser, you'll surely win. `list` should be kept as is, using static parsing. If user wants the real stuff, he should use `--dry-run`.

**Comment by ldoktor** [comment]
Yep, I know, the post was for @jscotka to let him know why we do it the way we do it and why it's _the only correct_ way :smile:

**Comment by jscotka** [comment]
ye. thanks for discussion, all possibilities are okay, also traceback. But in case it is pythonish correct, I prefer, to use that list(set(...))

Or you can change static analysis to dynamic one based on object inspection, like:
from inspect import getmembers
import test
print [o[0] for o in getmembers(test.BasicTestSuite) if o[0].startswith("test")]

**Comment by clebergnu** [comment]
@jscotka dynamic means Avocado runs code. That means Avocado can run **unintended** code while looking for tests. That means Avocado can trash your system, so no! :smile:
