### ISSUE TITLE
Failure to identify/run executable Python scripts as SIMPLE tests

### ISSUE THREAD

**Issue by clebergnu** [avocado-framework/avocado#973]
Avocado fails to identify/run executable Python scripts as `SIMPLE` tests, even when "forced" to do so. Example:

```
$ ./scripts/avocado list -V examples/tests/passtest.py --loaders file.SIMPLE

Type    Test
MISSING examples/tests/passtest.py

ACCESS_DENIED: 0
BROKEN_SYMLINK: 0
FILTERED: 0
INSTRUMENTED: 0
MISSING: 1
NOT_A_TEST: 0
SIMPLE: 0
```

And consequently:

```
/scripts/avocado run examples/tests/passtest.py --loaders file.SIMPLE 

Unable to discover url(s) 'examples/tests/passtest.py' with loader plugins(s) 'file', try running 'avocado list -V examples/tests/passtest.py' to see the details.
```

The condition for being a simple test should be: an executable file exists on the system. This simple condition check is not being met.

Currently, the only resort is to use the docstring tag `:avocado: disable`, which seems wrong.

**Comment by ldoktor** [comment]
Yep, this was a simplification in file loader I wanted to deal with later... The way it works now is it detects as file loader and then filter the results for disabled test types...

**Comment by ldoktor** [comment]
This is fixed in https://github.com/avocado-framework/avocado/pull/988
